# Generated by Django 3.1 on 2020-09-29 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('app_name', models.TextField()),
                ('name', models.TextField()),
                ('details', models.TextField(null=True)),
                ('severity', models.CharField(choices=[('D', 'DEBUG'), ('I', 'INFO'), ('W', 'WARNING'), ('E', 'ERROR')], default='I', max_length=1)),
                ('filename', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
