# Generated by Django 4.0.2 on 2022-02-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0002_viewevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewevent',
            name='referer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
