# Generated by Django 6.1 on 2026-08-24 08:00

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventlog", "0003_viewevent_referer"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("key", models.TextField(unique=True)),
                ("name", models.TextField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("I", "Inbound"), ("O", "Outbound")],
                        default="I",
                        max_length=1,
                    ),
                ),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("last_change", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True, null=True)),
                ("attempt_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Integration activity",
            },
        ),
    ]
