# Generated by Django 6.1 on 2026-08-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0004_integrationactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationactivity',
            name='last_error_acknowledged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
