# Generated by Django 3.1 on 2020-11-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0003_transcript_version_json_del_gene_name'),
        ('pathtests', '0002_auto_20201124_2152'),  # Deleted FK to PanelApp
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelapppanelrelevantdisorders',
            name='panel_app_panel',
        ),
        migrations.DeleteModel(
            name='PanelAppPanel',
        ),
        migrations.DeleteModel(
            name='PanelAppPanelRelevantDisorders',
        ),
    ]
