# Generated by Django 3.1 on 2020-11-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_delete_columnvcfinfo'),
        ('genes', '0004_auto_20201124_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelAppPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_id', models.IntegerField()),
                ('disease_group', models.TextField()),
                ('disease_sub_group', models.TextField()),
                ('name', models.TextField()),
                ('current_version', models.TextField()),
                ('cached_web_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.cachedwebresource')),
            ],
        ),
        migrations.CreateModel(
            name='PanelAppServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('url', models.TextField(unique=True)),
                ('icon_css_class', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PanelAppPanelRelevantDisorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('panel_app_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.panelapppanel')),
            ],
        ),
        migrations.AddField(
            model_name='panelapppanel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.panelappserver'),
        ),
        migrations.AlterUniqueTogether(
            name='panelapppanel',
            unique_together={('server', 'panel_id')},
        ),
    ]
