# Generated by Django 3.1 on 2020-11-30 00:45

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0009_remove_settingsoverride_variant_tag_group_by_variant'),
        ('genes', '0006_panel_app_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleGeneList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visible', models.BooleanField(default=True)),
                ('gene_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.genelist')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.sample')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('sample', 'gene_list')},
            },
        ),
        migrations.CreateModel(
            name='ActiveSampleGeneList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.sample')),
                ('sample_gene_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.samplegenelist')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
