# Generated by Django 3.1.3 on 2020-12-11 00:40

from django.db import migrations

def _qc_gene_list_lock_and_rename(apps, schema_editor):
    BATCH_SIZE = 2000
    GeneList = apps.get_model("genes", "GeneList")
    QCGeneList = apps.get_model("seqauto", "QCGeneList")

    gene_lists = []
    qs = QCGeneList.objects.filter(custom_text_gene_list__isnull=False)
    for qcgl in qs.select_related("qc__bam_file__unaligned_reads__sequencing_sample"):
        gene_list = qcgl.custom_text_gene_list.gene_list
        ss = qcgl.qc.bam_file.unaligned_reads.sequencing_sample
        gene_list.name = f"QC GeneList for {ss.sample_name}"
        gene_list.locked = True
        gene_lists.append(gene_list)

    GeneList.objects.bulk_update(gene_lists, fields=["name", "locked"], batch_size=BATCH_SIZE)


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0007_activesamplegenelist_samplegenelist'),
    ]

    operations = [
        migrations.RunPython(_qc_gene_list_lock_and_rename)
    ]
