# Generated by Django 3.1.3 on 2020-12-14 03:16

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def test_fake_genes(apps):
    Gene = apps.get_model("genes", "Gene")
    FAKE_GENE_ID_PREFIX = "unknown_"  # Legacy from when we allowed inserting GenePred w/o GFF3
    return Gene.objects.filter(pk__startswith=FAKE_GENE_ID_PREFIX).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0008_qc_gene_list_lock_and_rename'),
        ('manual', '0002_deployment'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_fake_genes"]), test=test_fake_genes)
    ]
