# Generated by Django 3.1.3 on 2021-01-14 23:13

from django.db import migrations
from django.db.models import Max


def _remove_dupes(apps, schema_editor):
    PanelAppPanelRelevantDisorders = apps.get_model("genes", "PanelAppPanelRelevantDisorders")

    newest_rds = PanelAppPanelRelevantDisorders.objects.values("panel_app_panel", "name").annotate(latest_id=Max('id'))
    PanelAppPanelRelevantDisorders.objects.exclude(pk__in=newest_rds.values_list("latest_id")).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('genes', '0010_auto_20210114_1530'),
    ]

    operations = [
        migrations.RunPython(_remove_dupes),
        migrations.AlterModelOptions(
            name='panelapppanellocalcachegenelist',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='panelapppanellocalcachegenelist',
            unique_together={('panel_app_panel', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='panelapppanelrelevantdisorders',
            unique_together={('panel_app_panel', 'name')},
        ),
    ]
