# Generated by Django 3.1.3 on 2021-01-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0010_auto_20210114_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panelapppanellocalcachegenelist',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='panelapppanellocalcachegenelist',
            unique_together={('panel_app_panel', 'version')},
        ),
    ]
