# Generated by Django 3.1.3 on 2021-01-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0011_auto_20210115_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hgncgenenames',
            old_name='synonyms',
            new_name='alias_symbols',
        ),
        migrations.AddField(
            model_name='hgncgenenames',
            name='gene_symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol'),
        ),
    ]
