# Generated by Django 3.1.3 on 2021-01-20 06:30

from django.db import migrations
from django.db.models import F


def _hgnc_fk_to_gene_symbol(apps, schema_editor):
    HGNCGeneNames = apps.get_model("genes", "HGNCGeneNames")
    HGNCGeneNames.objects.update(gene_symbol_id=F("approved_symbol"))


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0012_auto_20210120_1700'),
    ]

    operations = [
        migrations.RunPython(_hgnc_fk_to_gene_symbol)
    ]
