# Generated by Django 3.1.3 on 2021-01-20 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0013_hgnc_fk_to_gene_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hgncgenenames',
            name='approved_symbol',
        ),
        migrations.AlterField(
            model_name='hgncgenenames',
            name='gene_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol'),
        ),
    ]
