# Generated by Django 3.1 on 2021-01-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0015_one_off_fix_hgnc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HGNCGeneNames',
            new_name='HGNC',
        ),
    ]
