# Generated by Django 3.1 on 2021-02-01 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0018_auto_20210127_1257'),
        ('genes', '0016_auto_20210129_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HGNCGeneNamesImport',
            new_name='HGNCImport',
        ),
        migrations.AddField(
            model_name='gene',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hgnc',
            name='ccds_ids',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hgnc',
            name='ensembl_gene_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hgnc',
            name='gene_group_ids',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hgnc',
            name='gene_groups',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hgnc',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hgnc',
            name='mgd_ids',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hgnc',
            name='omim_ids',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hgnc',
            name='rgd_ids',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hgnc',
            name='ucsc_ids',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hgnc',
            name='previous_symbols',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hgnc',
            name='refseq_ids',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='UniProt',
            fields=[
                ('accession', models.TextField(primary_key=True, serialize=False)),
                ('function', models.TextField(null=True)),
                ('pathway', models.TextField(null=True)),
                ('pathway_interaction_db', models.TextField(null=True)),
                ('reactome', models.TextField(null=True)),
                ('tissue_specificity', models.TextField(null=True)),
                ('cached_web_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.cachedwebresource')),
            ],
        ),
        migrations.CreateModel(
            name='RVIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oe_ratio_percentile', models.FloatField()),
                ('cached_web_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.cachedwebresource')),
                ('gene_symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol')),
            ],
        ),
    ]
