# Generated by Django 3.1 on 2021-02-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0017_auto_20210201_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='hgnc',
            name='uniprot_ids',
            field=models.TextField(null=True),
        ),
    ]
