# Generated by Django 3.1 on 2021-02-04 07:14
"""
HGNC used to mangle their gene symbols ie "AACT~withdrawn"

We inserted this which caused us to make a lot of garbage gene names - that would never link to anything - ie you wouldn't be able to see from the AACT gene symbol page that it was once a withdrawn HGNC entry

HGNC data files have stopped doing this, ie:

HGNC:13792	AACT	symbol withdrawn, see [HGNC:16](/data/gene-symbol-report/#!/hgnc_id/HGNC:16)	Symbol Withdrawn

We don't use these anyway, as they always turn up as an alias in the proper HGNC entry, and we use that

There is no way to pull down "Symbol withdrawn" via REST (only approved/Entry withdrawn)
"""

from django.db import migrations


def _delete_hgnc_withdrawn(apps, _schema_editor):
    GeneVersion = apps.get_model("genes", "GeneVersion")
    GeneSymbol = apps.get_model("genes", "GeneSymbol")
    OntologyTerm = apps.get_model("ontology", "OntologyTerm")

    withdrawn = GeneSymbol.objects.filter(symbol__icontains='~withdrawn')
    if GeneVersion.objects.filter(gene_symbol__in=withdrawn).exists():
        # Care about GeneVersions - don't let this happen...
        raise ValueError("GeneVersion exists with ~withdrawn!")

    withdrawn.delete()  # Will cascade delete HGNC
    OntologyTerm.objects.filter(ontology_service="HGNC", name__icontains='~withdrawn').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0018_hgnc_uniprot_ids'),
    ]

    operations = [
        migrations.RunPython(_delete_hgnc_withdrawn)
    ]
