# Generated by Django 3.1 on 2021-02-05 00:13

import numpy as np
from django.db import migrations, models


def _one_off_rvis_gnomad_gene_constraint_np_to_none(apps, _schema_editor):
    """ One off patch of exisitng environments """
    RVIS = apps.get_model("genes", "RVIS")
    GnomADGeneConstraint = apps.get_model("genes", "GnomADGeneConstraint")

    RVIS.objects.filter(oe_ratio_percentile=np.NaN).update(oe_ratio_percentile=None)

    g_qs = GnomADGeneConstraint.objects.all()
    g_qs.filter(oe_lof=np.NaN).update(oe_lof=None)
    g_qs.filter(oe_lof_lower=np.NaN).update(oe_lof_lower=None)
    g_qs.filter(oe_lof_upper=np.NaN).update(oe_lof_upper=None)


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0019_delete_hgnc_withdrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvis',
            name='oe_ratio_percentile',
            field=models.FloatField(null=True),
        ),
        migrations.RunPython(_one_off_rvis_gnomad_gene_constraint_np_to_none)
    ]
