# Generated by Django 3.1.3 on 2021-02-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0020_auto_20210205_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RVIS',
        ),
    ]
