# Generated by Django 3.1.3 on 2021-03-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0024_one_off_gene_coverage_model_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genecoverage',
            name='percent_0x',
        ),
        migrations.RemoveField(
            model_name='genecoveragecanonicaltranscript',
            name='percent_0x',
        ),
    ]
