# Generated by Django 3.1.3 on 2021-04-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0025_auto_20210330_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canonicaltranscript',
            old_name='original_transcript_id',
            new_name='original_transcript',
        ),
        migrations.AddField(
            model_name='canonicaltranscript',
            name='transcript_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.transcriptversion'),
        ),
    ]
