# Generated by Django 3.1 on 2021-05-03 03:58

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_has_panel_app_gene_lists(apps):
    PanelAppPanelLocalCacheGeneList = apps.get_model("genes", "PanelAppPanelLocalCacheGeneList")
    return PanelAppPanelLocalCacheGeneList.objects.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0026_auto_20210406_1718'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_panel_app_gene_list_permissions"]),
                        test=_test_has_panel_app_gene_lists),
    ]
