# Generated by Django 3.1 on 2021-05-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0026_auto_20210406_1718'),
    ]

    # Neutralised: this used to register a manual 'fix_panel_app_gene_list_permissions' task, but that
    # command was deleted in #690 when the "public-read on PanelApp gene lists" feature was removed
    # (genes/panel_app.py no longer grants it). The manual step is obsolete, so it no longer registers.
    # Any orphaned task rows in existing DBs are cleared by manual/0004_complete_obsolete_manual_tasks.
    operations = []
