# Generated by Django 3.2.1 on 2021-05-05 08:13

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


def _citext_message(apps, schema_editor):
    print("--------")
    print("If this migration fails, you need to install the Postgres 'citex' extension")
    print("sudo su postgres")
    print("echo 'CREATE EXTENSION IF NOT EXISTS citext;' | psql")
    print("exit # leave 'postgres' user shell")
    print("sudo service postgresql restart")
    print("--------")


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0028_one_off_fix_lowercase_gene_symbols'),
    ]

    operations = [
        migrations.RunPython(_citext_message),
        migrations.AlterField(
            model_name='genesymbol',
            name='symbol',
            field=django.contrib.postgres.fields.citext.CITextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genesymbolalias',
            name='alias',
            field=django.contrib.postgres.fields.citext.CITextField(unique=True),
        ),
    ]
