# Generated by Django 3.2.1 on 2021-05-17 03:42

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0029_auto_20210505_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genesymbolalias',
            options={},
        ),
        migrations.AlterField(
            model_name='genesymbolalias',
            name='alias',
            field=django.contrib.postgres.fields.citext.CITextField(),
        ),
        migrations.AlterUniqueTogether(
            name='genesymbolalias',
            unique_together={('alias', 'gene_symbol')},
        ),
    ]
