# Generated by Django 3.2.1 on 2021-05-17 04:17

from django.db import migrations
from django.db.models import F
from django.db.models.functions import Upper

from manual.operations.manual_operations import ManualOperation


def one_off_delete_case_sensitive_aliases(apps, schema_editor):
    GeneSymbolAlias = apps.get_model("genes", "GeneSymbolAlias")

    # Now that we're case insensitive - these do nothing
    r = GeneSymbolAlias.objects.all().annotate(uc_symbol=Upper("gene_symbol_id")).filter(alias=F("uc_symbol")).delete()
    if r:
        print("Deleted GeneSymbolAlias with case sensitive aliases: ", r)


def _test_has_gene_aliases(apps):
    GeneSymbolAlias = apps.get_model("genes", "GeneSymbolAlias")
    return GeneSymbolAlias.objects.all().exists()


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0030_auto_20210517_1312'),
    ]

    operations = [
        migrations.RunPython(one_off_delete_case_sensitive_aliases),
        ManualOperation.operation_other(args=["Update HGNC - click 'update from web' button on annotation page"],
                                        test=_test_has_gene_aliases),
    ]
