# Generated by Django 3.2.4 on 2021-08-09 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0042_auto_20210730_0855'),
        ('genes', '0032_alter_geneannotationrelease_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptversion',
            name='contig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.contig'),
        ),
    ]
