# Generated by Django 3.2.1 on 2021-08-26 01:32

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_has_gene_annotations(apps):
    GeneAnnotationImport = apps.get_model("genes", "GeneAnnotationImport")
    return GeneAnnotationImport.objects.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0033_alter_geneversion_gene_symbol'),
    ]

    operations = [
        ManualOperation.operation_other(args=["Update gene annotations, see https://github.com/SACGF/variantgrid/issues/459#issuecomment-905203754"],
                                        test=_test_has_gene_annotations),
    ]
