# Generated by Django 3.2.1 on 2021-08-26 01:32

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0033_alter_geneversion_gene_symbol'),
    ]

    operations = [
        # This has been deleted
    ]
