# Generated by Django 3.2.1 on 2021-08-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0034_one_off_remind_install_new_gene_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptversion',
            name='alignment_gap',
            field=models.BooleanField(default=False),
        ),
    ]
