# Generated by Django 3.2.1 on 2021-08-27 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('genes', '0035_transcriptversion_alignment_gap'),
    ]

    operations = [
        # This has been deleted
    ]
