# Generated by Django 3.2.4 on 2021-09-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0036_one_off_set_transcript_version_alignment_gap'),
    ]

    operations = [
        # This has been left blank - we have a later test for required PyHGVS versions
    ]
