# Generated by Django 3.2.4 on 2021-09-07 01:29

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_has_nr_transcripts(apps):
    """ Only give this warning for existing installations that have NR transcripts """
    Transcript = apps.get_model("genes", "Transcript")
    return Transcript.objects.filter(identifier__startswith='NR_').exists()


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0036_one_off_set_transcript_version_alignment_gap'),
    ]

    operations = [
        ManualOperation.operation_other(args=[
            "Update pyHGVS library - sudo python3 -m pip install --force --upgrade git+https://github.com/SACGF/hgvs#egg=pyhgvs"],
                                        test=_test_has_nr_transcripts),
    ]
