# Generated by Django 3.2.4 on 2021-09-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0034_auto_20210622_1459'),
        ('genes', '0037_one_off_upgrade_pyhgvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='LRGRefSeqGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrg', models.TextField()),
                ('rna', models.TextField()),
                ('t', models.TextField(null=True)),
                ('category', models.CharField(choices=[('N', 'NCBI'), ('U', 'UCSC'), ('H', 'HGNC'), ('M', 'Manual')], max_length=1)),
                ('cached_web_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.cachedwebresource')),
            ],
            options={
                'unique_together': {('lrg', 't')},
            },
        ),
    ]
