# Generated by Django 3.2.4 on 2021-09-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0040_one_off_transcript_version_sequence_info_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptversion',
            name='alignment_gap',
        ),
        migrations.AddField(
            model_name='geneannotationimport',
            name='file_md5sum',
            field=models.TextField(default='fake_md5sum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geneannotationimport',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
