# Generated by Django 3.2.6 on 2021-09-30 12:51

from django.db import migrations


def _one_off_refseq_gene_version_zero(apps, _schema_editor):
    # Make RefSeq gene versions 0 instead of 1, so we know they're not real
    GeneVersion = apps.get_model("genes", "GeneVersion")
    GeneVersion.objects.filter(gene__annotation_consortium='R').update(version=0)


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0041_auto_20210930_1415'),
    ]

    operations = [
        migrations.RunPython(_one_off_refseq_gene_version_zero)
    ]
