# Generated by Django 3.2.4 on 2021-10-18 06:01

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_has_gene_annotations_without_url(apps):
    GeneAnnotationImport = apps.get_model("genes", "GeneAnnotationImport")
    old_imports = GeneAnnotationImport.objects.filter(url__isnull=True)
    new_imports = GeneAnnotationImport.objects.filter(url__isnull=False)
    return old_imports.exists() and not new_imports.exists()


def _test_has_classifications(apps):
    Classification = apps.get_model("classification", "Classification")
    return Classification.objects.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0042_one_off_refseq_gene_version_zero'),
    ]

    operations = [
        # Install new annotations
        ManualOperation.operation_other(args=[
            "** Before fix_legacy_classification_alignment_gap_hgvs_matching ** - Import gene annotation - see https://github.com/SACGF/variantgrid/issues/494#issuecomment-943977004"],
            test=_test_has_gene_annotations_without_url),
        # Once that's done,
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_legacy_classification_alignment_gap_hgvs_matching"]),
                        test=_test_has_classifications),

    ]
