# Generated by Django 3.2.4 on 2021-10-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0042_one_off_refseq_gene_version_zero'),
    ]

    # Neutralised: this used to register the 'Import gene annotation' reminder plus a manual
    # 'fix_legacy_classification_alignment_gap_hgvs_matching' task (#494). That command matched against the
    # pre-cdot transcript JSON schema and rematched via the pre-ImportedAlleleInfo API, so it has been
    # deleted - classification/0167_one_off_rematch_alignment_gap_allele_infos registers its replacement,
    # fix_legacy_imported_allele_info_alignment_gap, and clears the orphaned task row.
    operations = []
