# Generated by Django 3.2.4 on 2021-10-18 06:33

from django.db import migrations


def _change_gene_symbol_case(apps):
    GeneSymbol = apps.get_model("genes", "GeneSymbol")
    if not GeneSymbol.objects.exists():
        return  # New install

    # I got these from HGNC download, where symbol != symbol.upper()
    LC_SYMBOLS = """C10orf105,C10orf120,C10orf126,C10orf143,C10orf53,C10orf55,C10orf62,C10orf67,C10orf67-AS1,C10orf71,
    C10orf71-AS1,C10orf82,C10orf88,C10orf88B,C10orf90,C10orf95,C10orf95-AS1,C10orf99,C11orf1,C11orf16,C11orf21,C11orf24,
    C11orf40,C11orf42,C11orf49,C11orf52,C11orf53,C11orf54,C11orf58,C11orf65,C11orf68,C11orf71,C11orf80,C11orf86,
    C11orf87,C11orf91,C11orf94,C11orf96,C11orf97,C11orf98,C11orf98P1,C12orf29,C12orf4,C12orf40,C12orf42,C12orf43,
    C12orf50,C12orf54,C12orf56,C12orf57,C12orf60,C12orf71,C12orf73,C12orf75,C12orf76,C13orf42,C13orf46,C14orf119,
    C14orf132,C14orf178,C14orf180,C14orf28,C14orf39,C14orf93,C15orf32,C15orf39,C15orf40,C15orf48,C15orf61,C15orf62,
    C15orf65,C16orf46,C16orf54,C16orf72,C16orf74,C16orf78,C16orf82,C16orf86,C16orf87,C16orf89,C16orf90,C16orf91,
    C16orf92,C16orf95,C16orf95-DT,C16orf96,C17orf100,C17orf107,C17orf113,C17orf114,C17orf49,C17orf50,C17orf58,C17orf64,
    C17orf67,C17orf75,C17orf78,C17orf80,C17orf97,C17orf98,C17orf99,C18orf15,C18orf21,C18orf25,C18orf32,C18orf54,
    C18orf63,C19orf12,C19orf18,C19orf25,C19orf33,C19orf38,C19orf44,C19orf47,C19orf48,C19orf53,C19orf54,C19orf67,
    C19orf71,C19orf73,C19orf81,C19orf84,C19orf85,C1orf100,C1orf105,C1orf109,C1orf112,C1orf115,C1orf116,C1orf122,
    C1orf127,C1orf131,C1orf141,C1orf146,C1orf147,C1orf159,C1orf162,C1orf167,C1orf167-AS1,C1orf174,C1orf185,C1orf198,
    C1orf21,C1orf21-DT,C1orf210,C1orf216,C1orf220,C1orf226,C1orf232,C1orf35,C1orf43,C1orf50,C1orf52,C1orf53,C1orf54,
    C1orf56,C1orf68,C1orf74,C1orf87,C1orf94,C20orf141,C20orf144,C20orf173,C20orf181,C20orf202,C20orf203,C20orf204,
    C20orf27,C20orf85,C20orf96,C21orf140,C21orf58,C21orf62,C21orf62-AS1,C21orf91,C21orf91-OT1,C22orf15,C22orf23,
    C22orf31,C22orf39,C22orf42,C22orf46,C2orf15,C2orf16,C2orf27A,C2orf42,C2orf49,C2orf49-DT,C2orf50,C2orf66,C2orf68,
    C2orf69,C2orf69P1,C2orf69P2,C2orf69P3,C2orf69P4,C2orf69P5,C2orf72,C2orf73,C2orf74,C2orf74-DT,C2orf76,C2orf78,
    C2orf80,C2orf81,C2orf83,C2orf88,C2orf92,C3orf14,C3orf18,C3orf20,C3orf22,C3orf33,C3orf36,C3orf38,C3orf49,C3orf49P1,
    C3orf52,C3orf56,C3orf62,C3orf70,C3orf80,C3orf84,C3orf85,C3orf86,C4o4rf46P1,C4orf17,C4orf19,C4orf3,C4orf33,C4orf36,
    C4orf45,C4orf46,C4orf46P2,C4orf46P3,C4orf46P4,C4orf47,C4orf48,C4orf50,C4orf51,C4orf54,C5orf15,C5orf22,C5orf24,
    C5orf34,C5orf34-AS1,C5orf38,C5orf46,C5orf47,C5orf49,C5orf52,C5orf58,C5orf60,C5orf63,C5orf64,C5orf64-AS1,C5orf67,
    C6orf118,C6orf120,C6orf132,C6orf136,C6orf141,C6orf15,C6orf163,C6orf201,C6orf223,C6orf226,C6orf47,C6orf47-AS1,
    C6orf52,C6orf58,C6orf62,C6orf89,C7orf25,C7orf26,C7orf31,C7orf33,C7orf50,C7orf57,C7orf61,C7orf77,C8orf17,C8orf33,
    C8orf34,C8orf34-AS1,C8orf44,C8orf44-SGK3,C8orf48,C8orf58,C8orf74,C8orf76,C8orf82,C8orf86,C8orf88,C8orf89,C9orf116,
    C9orf129,C9orf131,C9orf152,C9orf153,C9orf163,C9orf24,C9orf40,C9orf43,C9orf50,C9orf57,C9orf64,C9orf72,C9orf78,
    C9orf85,C9orf92,CXorf38,CXorf49,CXorf49B,CXorf51A,CXorf51B,CXorf58,CXorf65,CXorf66,HSPB2-C11orf52,RNASEK-C17orf49,
    RPL17-C18orf32,ZHX1-C8orf76'
    """

    for symbol in LC_SYMBOLS:
        symbol = symbol.strip()
        # FKs still work even if case changes, so we don't have to worry about them
        GeneSymbol.objects.filter(pk=symbol).update(symbol=symbol)


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0043_one_off_hgvs_gap'),
    ]

    operations = [
        migrations.RunPython(_change_gene_symbol_case)
    ]
