# Generated by Django 3.2.4 on 2021-10-22 05:58

from django.db import migrations


def _one_off_gene_annotation_import_move_to_url(apps, schema_editor):
    GeneAnnotationImport = apps.get_model("genes", "GeneAnnotationImport")
    for gai in GeneAnnotationImport.objects.filter(url__isnull=True):
        gai.url = f"File: {gai.filename}"
        if gai.file_md5sum != "fake_md5sum":
            gai.url += f" (md5sum: {gai.file_md5sum})"
        gai.save()


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0044_one_off_fix_gene_symbol_case'),
    ]

    operations = [
        migrations.RunPython(_one_off_gene_annotation_import_move_to_url),
    ]
