# Generated by Django 3.2.4 on 2021-10-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0045_one_off_gene_annotation_import_move_to_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geneannotationimport',
            name='file_md5sum',
        ),
        migrations.RemoveField(
            model_name='geneannotationimport',
            name='filename',
        ),
        migrations.AlterField(
            model_name='geneannotationimport',
            name='url',
            field=models.TextField(),
        ),
    ]
