# Generated by Django 3.2.6 on 2021-11-24 06:56

from importlib import metadata
from importlib.metadata import PackageNotFoundError

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_old_version(apps):
    needs_upgrade = False
    try:
        required_version = (0, 12, 0)  # Bumped version on 24 Nov 2021 - has mito and cDNA_match fixes
        versions = [int(v) for v in metadata.version("pyhgvs").split(".")]
        for req_v, v in zip(versions, required_version):
            needs_upgrade |= req_v < v
    except PackageNotFoundError:
        needs_upgrade = True

    return needs_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0047_one_off_flag_uta_transcripts_with_gaps'),
    ]

    operations = [
        ManualOperation.operation_other(args=[
            "Update pyHGVS library - sudo python3 -m pip install --force --upgrade git+https://github.com/SACGF/hgvs#egg=pyhgvs"],
            test=_test_old_version),
    ]
