# Generated by Django 3.2.6 on 2021-11-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0047_one_off_flag_uta_transcripts_with_gaps'),
    ]

    operations = [
        # This has been left blank - we have a later test for required PyHGVS versions
    ]
