# Generated by Django 3.2.4 on 2021-12-12 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0054_auto_20211122_1407'),
        ('genes', '0048_one_off_upgrade_pyhgvs'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptversion',
            name='contig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.contig'),
        ),
    ]
