# Generated by Django 3.2.4 on 2021-12-12 23:00

from django.db import migrations
from django.db.models import CASCADE, SET_NULL

# At this point in the migration history, GeneCoverage.transcript_version and
# GeneCoverageCanonicalTranscript.transcript_version are still on_delete=CASCADE (set in
# genes.0023, relaxed to SET_NULL only in genes.0053, three migrations later). Those two models
# are Postgres inheritance parents with 44,234 children each - plain tables, not partitions, so
# there is no pruning. A Django .delete() resolves the cascade in Python and issues
# "WHERE transcript_version_id IN (...)" against each parent, which the planner then expands
# over all 88,468 children. That is enough to exhaust the machine's memory (see snpdb.0045,
# which took the box down exactly this way).
#
# Note that moving genes.0053 earlier would NOT help: SET_NULL just turns the cascade into
# "UPDATE ... SET transcript_version_id = NULL WHERE transcript_version_id IN (...)", which
# recurses into every child identically.
#
# So delete with raw SQL against named tables, and check the inheritance children ourselves
# first. This check is deliberately inline rather than shared with snpdb.0045 - migrations are
# frozen historical artifacts, and a shared helper could change under them later.
INHERITANCE_PARENTS_REFERENCING_TRANSCRIPT_VERSION = [
    "genes_genecoverage",
    "genes_genecoveragecanonicaltranscript",
    "annotation_variantannotation",
    "annotation_varianttranscriptannotation",
]


def _assert_no_inheritance_child_references(cursor, bad_ids):
    """ These FKs are NO ACTION and Postgres checks those with ONLY, so a DELETE will not notice
        rows sitting in the children and would leave them dangling. Every other table
        referencing TranscriptVersion is a plain table that Postgres does check, and will raise
        on violation, so these are the only ones we have to police ourselves. """
    referencing = []
    for parent in INHERITANCE_PARENTS_REFERENCING_TRANSCRIPT_VERSION:
        cursor.execute("""
            SELECT c.relname
            FROM pg_inherits i
            JOIN pg_class p ON p.oid = i.inhparent
            JOIN pg_class c ON c.oid = i.inhrelid
            WHERE p.relname = %s
        """, [parent])
        children = [row[0] for row in cursor.fetchall()]
        for child in children:
            # Child names come from pg_catalog, so they are safe to interpolate. transcript_version_id
            # is indexed on these children, so each probe is a cheap index lookup.
            cursor.execute(f'SELECT 1 FROM ONLY "{child}" WHERE transcript_version_id = ANY(%s) LIMIT 1',
                           [bad_ids])
            if cursor.fetchone() is not None:
                referencing.append(f"{parent}.{child}")

    if referencing:
        raise ValueError(f"Bad TranscriptVersion records are referenced by inheritance children, "
                         f"so deleting them would leave dangling rows: {referencing}")


def _clear_referencing_rows(cursor, TranscriptVersion, bad_ids):
    """ on_delete is applied by Django's collector, in Python, so bypassing the collector means
        honouring it ourselves. Postgres sees all of these FKs as NO ACTION: it refuses the
        delete rather than cascading or nulling, and because Django creates FKs as DEFERRABLE
        INITIALLY DEFERRED that refusal only lands at COMMIT.

        At this point in history every FK to TranscriptVersion is CASCADE (genes.0053 relaxes
        several to SET_NULL later, which is why reading the *current* models here would be
        misleading). Both dispositions are handled so this stays correct either way.

        The two coverage parents are skipped deliberately: a DELETE or UPDATE against an
        inheritance parent recurses into all 44,234 children, which is precisely the fan-out
        this migration exists to avoid, and _assert_no_inheritance_child_references has already
        proven no child holds a matching row.

        Nothing references these tables in turn, so one level is enough - a second level would
        surface as a foreign key violation rather than passing silently. """
    cleared = []
    for rel in TranscriptVersion._meta.related_objects:
        field = rel.field
        table = field.model._meta.db_table
        column = field.column
        if table in INHERITANCE_PARENTS_REFERENCING_TRANSCRIPT_VERSION:
            continue
        on_delete = field.remote_field.on_delete
        if on_delete is CASCADE:
            cursor.execute(f'DELETE FROM "{table}" WHERE "{column}" = ANY(%s)', [bad_ids])
            verb = "deleted"
        elif on_delete is SET_NULL:
            cursor.execute(f'UPDATE "{table}" SET "{column}" = NULL WHERE "{column}" = ANY(%s)',
                           [bad_ids])
            verb = "nulled"
        else:
            continue  # PROTECT / DO_NOTHING - leave Postgres to enforce
        if cursor.rowcount:
            cleared.append(f"{table}.{column} ({cursor.rowcount} {verb})")
    if cleared:
        print(f"Cleared references to bad TranscriptVersions: {', '.join(cleared)}")
    return cleared


def _delete_bad_transcript_versions(cursor, TranscriptVersion):
    """ Delete TranscriptVersions whose data has no 'chrom' entry. Returns the number deleted. """
    cursor.execute("SELECT id FROM genes_transcriptversion WHERE data->>'chrom' IS NULL")
    bad_ids = [row[0] for row in cursor.fetchall()]
    if not bad_ids:
        return 0

    print(f"Deleting {len(bad_ids)} legacy TranscriptVersion records missing 'chrom' entries")
    _assert_no_inheritance_child_references(cursor, bad_ids)
    _clear_referencing_rows(cursor, TranscriptVersion, bad_ids)
    # Any other table still referencing these raises a foreign key violation here, which is the
    # same guarantee the old "unexpected CASCADE deletion" check gave us
    cursor.execute("DELETE FROM genes_transcriptversion WHERE id = ANY(%s)", [bad_ids])
    return cursor.rowcount


def _get_chrom_contig_mappings(contigs) -> dict[str, 'Contig']:
    # Copied from GenomeBuild as we can't use models in migrations
    chrom_contig_mappings = {}
    for contig in contigs:
        chrom_contig_mappings[contig.name] = contig
        chrom_contig_mappings[contig.ucsc_name] = contig
        chrom_contig_mappings[contig.genbank_accession] = contig
        chrom_contig_mappings[contig.refseq_accession] = contig
    # Map lowercase "mt" -> "MT"
    chrom_contig_mappings["mt"] = chrom_contig_mappings["MT"]
    return chrom_contig_mappings


def _one_off_transcript_version_contig(apps, schema_editor):
    GenomeBuild = apps.get_model("snpdb", "GenomeBuild")
    Contig = apps.get_model("snpdb", "Contig")
    TranscriptVersion = apps.get_model("genes", "TranscriptVersion")

    with schema_editor.connection.cursor() as cursor:
        _delete_bad_transcript_versions(cursor, TranscriptVersion)

    for genome_build in GenomeBuild.objects.all():
        contigs = Contig.objects.filter(genomebuildcontig__genome_build=genome_build)
        chrom_contig_mappings = _get_chrom_contig_mappings(contigs)
        transcript_versions = []
        for tv in TranscriptVersion.objects.filter(genome_build=genome_build):
            if chrom := tv.data.get("chrom"):
                tv.contig = chrom_contig_mappings[chrom]
                transcript_versions.append(tv)

        if num_update := len(transcript_versions):
            print(f"Setting contig on {num_update} {genome_build.name} transcript versions")
            TranscriptVersion.objects.bulk_update(transcript_versions, fields=["contig"], batch_size=2000)


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0049_transcriptversion_contig'),
    ]

    operations = [
        migrations.RunPython(_one_off_transcript_version_contig),
    ]
