# Generated by Django 3.2.4 on 2021-12-12 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0054_auto_20211122_1407'),
        ('genes', '0050_one_off_transcript_version_contig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptversion',
            name='contig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.contig'),
        ),
    ]
