# Generated by Django 4.0.3 on 2022-04-13 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0052_geneversion_hgnc_identifier_alter_geneversion_hgnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonicaltranscript',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.transcript'),
        ),
        migrations.AlterField(
            model_name='canonicaltranscript',
            name='transcript_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.transcriptversion'),
        ),
        migrations.AlterField(
            model_name='genecoverage',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.transcript'),
        ),
        migrations.AlterField(
            model_name='genecoverage',
            name='transcript_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.transcriptversion'),
        ),
        migrations.AlterField(
            model_name='genecoveragecanonicaltranscript',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.transcript'),
        ),
        migrations.AlterField(
            model_name='genecoveragecanonicaltranscript',
            name='transcript_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.transcriptversion'),
        ),
        migrations.AlterField(
            model_name='pfamsequenceidentifier',
            name='transcript_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.transcriptversion'),
        ),
    ]
