# Generated by Django 4.0.3 on 2022-04-13 04:27

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0053_alter_canonicaltranscript_transcript_and_more'),
    ]

    operations = [
        ManualOperation(ManualOperation.operation_other([
            "Download cdot data and run import_gene_annotation. " +
            "See https://github.com/SACGF/variantgrid/issues/566#issuecomment-1097543081",
            ])),
    ]
