# Generated by Django 4.0.3 on 2022-04-22 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0054_one_off_import_gene_annotation_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='hgnc',
            name='uniprot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.uniprot'),
        ),
    ]
