# Generated by Django 4.0.6 on 2022-08-01 06:19

from importlib import metadata
from importlib.metadata import PackageNotFoundError

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_old_version(apps):
    needs_upgrade = False
    try:
        required_version = (0, 12, 2)  # Bumped version on 1 Aug 2022 - dup matches reference fix
        versions = [int(v) for v in metadata.version("pyhgvs").split(".")]
        for req_v, v in zip(versions, required_version):
            needs_upgrade |= req_v < v
    except PackageNotFoundError:
        needs_upgrade = True

    return needs_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0056_one_off_link_hgnc_and_uniprot'),
    ]

    operations = [
        ManualOperation.operation_other(args=[
            "Update pyHGVS library - sudo python3 -m pip install --force --upgrade git+https://github.com/SACGF/hgvs#egg=pyhgvs"],
            test=_test_old_version),
    ]
