# Generated by Django 4.0.6 on 2022-08-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0056_one_off_link_hgnc_and_uniprot'),
    ]

    operations = [
        # This has been left blank - we have a later test for required PyHGVS versions
    ]
