# Generated by Django 4.1.3 on 2022-12-06 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0057_one_off_upgrade_pyhgvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MANE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('M', 'MANE Select'), ('C', 'MANE Plus Clinical')], max_length=1)),
                ('ensembl_gene_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mane_ensembl', to='genes.geneversion')),
                ('ensembl_transcript_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mane_ensembl', to='genes.transcriptversion')),
                ('hgnc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.hgnc')),
                ('ncbi_gene_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mane_ncbi', to='genes.geneversion')),
                ('refseq_transcript_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mane_refseq', to='genes.transcriptversion')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol')),
            ],
        ),
    ]
