# Generated by Django 4.1.3 on 2022-12-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0058_mane'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfamsequenceidentifier',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
