# Generated by Django 4.1.3 on 2022-12-12 04:11

from django.db import migrations
from django.db.models import OuterRef, Subquery


def _one_off_pfamsequenceidentifier_alter_transcript_version(apps, _schema_editor):
    TranscriptVersion = apps.get_model("genes", "TranscriptVersion")
    PfamSequenceIdentifier = apps.get_model("genes", "PfamSequenceIdentifier")

    version_query = TranscriptVersion.objects.filter(
        id=OuterRef('transcript_version_id')
    ).values_list(
        'version'
    )[:1]
    PfamSequenceIdentifier.objects.update(version=Subquery(version_query))


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0059_pfamsequenceidentifier_version'),
    ]

    operations = [
        migrations.RunPython(_one_off_pfamsequenceidentifier_alter_transcript_version)
    ]
