# Generated by Django 4.1.3 on 2022-12-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0060_one_off_pfamsequenceidentifier_alter_transcript_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfamsequenceidentifier',
            name='transcript_version',
        ),
    ]
