# Generated by Django 4.1.3 on 2022-12-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0061_remove_pfamsequenceidentifier_transcript_version'),
    ]

    operations = [
        # Left blank - replaced by genes 0068
    ]
