# Generated by Django 4.1.3 on 2023-01-04 00:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        # Have analysis run first to remove field, so that deleting the model doesn't cascade delete analysis node
        ('analysis', '0069_remove_genelistnodepanelapppanel_panel_app_panel_local_cache_gene_list_and_more'),
        ('genes', '0062_one_off_cdot_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelAppPanelLocalCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('version', models.TextField()),
                ('panel_app_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.panelapppanel')),
            ],
            options={
                'unique_together': {('panel_app_panel', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PanelAppPanelLocalCacheGeneSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('gene_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol')),
                ('panel_app_local_cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.panelapppanellocalcache')),
            ],
        ),
        migrations.DeleteModel(
            name='PanelAppPanelLocalCacheGeneList',
        ),
    ]
