# Generated by Django 4.1.3 on 2023-01-04 00:06

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Have analysis run first to remove field, so that deleting the model doesn't cascade delete analysis node
        ('analysis', '0069_remove_genelistnodepanelapppanel_panel_app_panel_local_cache_gene_list_and_more'),
        ('genes', '0062_one_off_cdot_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelAppPanelLocalCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('version', models.TextField()),
                ('panel_app_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.panelapppanel')),
            ],
            options={
                'unique_together': {('panel_app_panel', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PanelAppPanelLocalCacheGeneSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('panel_app_local_cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.panelapppanellocalcache')),
            ],
        ),
        # gene_symbol pulled out of the CreateModel above: Django 6 emits CITextField as `text`,
        # but genes_genesymbol.symbol is still `citext` here (genes.0078 converts the graph to
        # text later), so a `text` FK cannot reference the citext PK. Create the column as citext;
        # the table is otherwise Django-created and empty, so NOT NULL is safe.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
                        ALTER TABLE "genes_panelapppanellocalcachegenesymbol"
                            ADD COLUMN "gene_symbol_id" citext NOT NULL;
                        ALTER TABLE "genes_panelapppanellocalcachegenesymbol"
                            ADD FOREIGN KEY ("gene_symbol_id")
                            REFERENCES "genes_genesymbol" ("symbol") DEFERRABLE INITIALLY DEFERRED;
                        CREATE INDEX ON "genes_panelapppanellocalcachegenesymbol" ("gene_symbol_id");
                    ''',
                    reverse_sql='ALTER TABLE "genes_panelapppanellocalcachegenesymbol" '
                                'DROP COLUMN "gene_symbol_id";',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='panelapppanellocalcachegenesymbol',
                    name='gene_symbol',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol'),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='PanelAppPanelLocalCacheGeneList',
        ),
    ]
