# Generated by Django 4.1.3 on 2023-02-23 06:37
from importlib import metadata
from importlib.metadata import PackageNotFoundError

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_old_cdot_version(apps):
    needs_upgrade = False
    try:
        required_version = (0, 2, 13)  # Need PyHGVS fixes
        versions = [int(v) for v in metadata.version("cdot").split(".")]
        for req_v, v in zip(versions, required_version):
            needs_upgrade |= req_v < v
    except PackageNotFoundError:
        needs_upgrade = True

    return needs_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0063_panelapppanellocalcache_and_more'),
    ]

    operations = [
        ManualOperation.operation_other(args=[
            "Update cdot library - sudo python3 -m pip install --upgrade cdot"],
            test=_test_old_cdot_version),
    ]
