# Generated by Django 4.1.3 on 2023-03-03 04:03

from django.db import migrations

from annotation.management.commands.gene_annotation import bad_gene_annotation
from manual.operations.manual_operations import ManualOperation


def _check_has_panel_app_gene_lists(apps):
    GeneList = apps.get_model("genes", "GeneList")
    return GeneList.objects.filter(category__name='PanelAppCache').exists()


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0064_one_off_upgrade_cdot'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_make_panel_app_gene_lists_public"]),
                        test=_check_has_panel_app_gene_lists)
    ]
