# Generated by Django 4.1.3 on 2023-03-10 04:20

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0065_one_off_fix_make_panel_app_gene_lists_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genelist',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='genelist',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genelist',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
