# Generated by Django 4.1.5 on 2023-04-12 03:08
from importlib import metadata
from importlib.metadata import PackageNotFoundError

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_old_version(apps):
    needs_upgrade = False
    try:
        required_version = (0, 12, 3)  # Bumped version on 12 Aug 2023 - allow spans to have = (match ref)
        versions = [int(v) for v in metadata.version("pyhgvs").split(".")]
        for req_v, v in zip(versions, required_version):
            needs_upgrade |= req_v < v
    except PackageNotFoundError:
        needs_upgrade = True

    return needs_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0066_alter_genelist_options_genelist_created_and_more'),
    ]

    operations = [
        ManualOperation.operation_other(args=[
            "Update pyHGVS library - sudo python3 -m pip install --force --upgrade git+https://github.com/SACGF/hgvs#egg=pyhgvs"],
            test=_test_old_version),
    ]
