# Generated by Django 4.1.5 on 2023-04-12 03:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0066_alter_genelist_options_genelist_created_and_more'),
    ]

    operations = [
        # This has been left blank - we have a later test for required PyHGVS versions
    ]
