# Generated by Django 4.1.5 on 2023-04-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0067_one_off_upgrade_pyhgvs'),
    ]

    operations = [
        # This is intentionally blank, replaced with 0069 (needed to bump version again)
    ]
