# Generated by Django 4.1.3 on 2023-05-18 07:14

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_old_cdot(apps):
    TranscriptVersion = apps.get_model("genes", "TranscriptVersion")

    if not TranscriptVersion.objects.exists():
        return False  # No transcripts, new install

    if cdot_transcript := TranscriptVersion.objects.filter(data__cdot__isnull=False).first():
        cdot_version = tuple(int(i) for i in cdot_transcript.data["cdot"].split("."))
        return cdot_version < (0, 2, 17)  # 0.2.16 had chrom names instead of contigs
    return True  # ancient version of transcript annotations (no cdot version entry)


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0068_one_off_upgrade_cdot_data'),
    ]

    operations = [
        ManualOperation.operation_other(args=["Update cdot - import_gene_annotation with cdot transcript DATA >= 0.2.17"
                                              " You can do this by running: "
                                              "./annotation/annotation_data/cdot_update.sh or manually, see "
                                              "https://github.com/SACGF/cdot/releases"
                                              "Data only - no need to update the library code for this change"],
                                        test=_test_old_cdot),
    ]
