# Generated by Django 4.1.3 on 2023-05-18 07:14
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0068_one_off_upgrade_cdot_data'),
    ]

    operations = [
        # Old pyhgvs/cdot versions etc now covered in deployment_check
    ]
