# Generated by Django 4.2.2 on 2023-09-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0069_nice_one_off_upgrade_cdot_cdot_data_pyhgvs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genesymbol',
            options={'base_manager_name': 'objects'},
        ),
    ]
