# Generated by Django 4.2.2 on 2023-12-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0070_alter_genesymbol_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gnomadgeneconstraint',
            old_name='oe_lof',
            new_name='lof_oe',
        ),
        migrations.RenameField(
            model_name='gnomadgeneconstraint',
            old_name='oe_lof_lower',
            new_name='lof_oe_ci_lower',
        ),
        migrations.RenameField(
            model_name='gnomadgeneconstraint',
            old_name='oe_lof_upper',
            new_name='lof_oe_ci_upper',
        ),
        migrations.RemoveField(
            model_name='gnomadgeneconstraint',
            name='gene',
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='constraint_flags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_exp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_hc_lc_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_hc_lc_mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_hc_lc_obs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_hc_lc_oe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_hc_lc_pli',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_hc_lc_pnull',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_hc_lc_possible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_hc_lc_prec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_obs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_pli',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_pnull',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_possible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_prec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_z_raw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='lof_z_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mane_select',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_exp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_obs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_oe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_oe_ci_lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_oe_ci_upper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_possible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_pphen_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_pphen_obs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_pphen_oe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_pphen_possible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_z_raw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='mis_z_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='syn_exp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='syn_mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='syn_obs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='syn_oe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='syn_oe_ci_lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='syn_oe_ci_upper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='syn_possible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='syn_z_raw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='syn_z_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnomadgeneconstraint',
            name='transcript_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.transcriptversion'),
        ),
    ]
