# Generated by Django 4.2.10 on 2024-06-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0071_rename_oe_lof_gnomadgeneconstraint_lof_oe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicaltranscriptcollection',
            name='file_sha256sum',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customtextgenelist',
            name='sha256_hash',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transcriptversionsequenceinfofastafileimport',
            name='sha256_hash',
            field=models.TextField(null=True, unique=True),
        ),
    ]
