# Generated by Django 4.2.10 on 2024-06-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0073_md5_to_sha256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canonicaltranscriptcollection',
            name='file_md5sum',
        ),
        migrations.RemoveField(
            model_name='customtextgenelist',
            name='md5_hash',
        ),
        migrations.RemoveField(
            model_name='transcriptversionsequenceinfofastafileimport',
            name='md5_hash',
        ),
        migrations.AlterField(
            model_name='canonicaltranscriptcollection',
            name='file_sha256sum',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customtextgenelist',
            name='sha256_hash',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transcriptversionsequenceinfofastafileimport',
            name='sha256_hash',
            field=models.TextField(unique=True),
        ),
    ]
