# Generated by Django 4.2.11 on 2024-08-01 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genes", "0074_remove_canonicaltranscriptcollection_file_md5sum_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genesymbol",
            old_name="symbol",
            new_name="old_symbol",
        ),
        migrations.RenameField(
            model_name="genesymbolalias",
            old_name="alias",
            new_name="old_alias",
        ),
        migrations.AlterUniqueTogether(
            name="genesymbolalias",
            unique_together={("old_alias", "gene_symbol")},
        ),
    ]
