# Generated by Django 4.2.11 on 2024-08-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genes", "0075_rename_symbol_genesymbol_old_symbol_and_more"),
        ("snpdb", "0140_case_insensitive_collation"),  # Defines db_collation 'case_insensitive'
    ]

    operations = [
        migrations.AddField(
            model_name="genesymbol",
            name="symbol",
            field=models.TextField(db_collation="case_insensitive", null=True),
        ),
        migrations.AddField(
            model_name="genesymbolalias",
            name="alias",
            field=models.TextField(db_collation="case_insensitive", null=True),
        ),
    ]
