# Generated by Django 4.2.11 on 2024-08-01 04:06

from django.db import migrations
from django.db.models import F


def _one_off_copy_citext_to_textfield(apps, _schema_editor):
    GeneSymbol = apps.get_model('genes', 'GeneSymbol')
    GeneSymbolAlias = apps.get_model('genes', 'GeneSymbolAlias')

    GeneSymbol.objects.all().update(symbol=F("old_symbol"))
    GeneSymbolAlias.objects.all().update(alias=F("old_alias"))


class Migration(migrations.Migration):
    dependencies = [
        ("genes", "0076_genesymbol_symbol_genesymbolalias_alias"),
    ]

    operations = [
        migrations.RunPython(_one_off_copy_citext_to_textfield)
    ]
