# Generated by Django 4.2.11 on 2024-08-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genes", "0077_one_off_copy_citext_to_textfield"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="genesymbolalias",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="genesymbol",
            name="old_symbol",
        ),
        migrations.AlterField(
            model_name="genesymbol",
            name="symbol",
            field=models.TextField(
                db_collation="case_insensitive", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="genesymbolalias",
            name="alias",
            field=models.TextField(db_collation="case_insensitive"),
        ),
        migrations.AlterUniqueTogether(
            name="genesymbolalias",
            unique_together={("alias", "gene_symbol")},
        ),
        migrations.RemoveField(
            model_name="genesymbolalias",
            name="old_alias",
        ),
    ]
