# Generated by Django 4.2.17 on 2025-02-28 04:54

from django.db import migrations

def _panel_app_aus_url_change(apps, _schema_editor):
    PanelAppServer = apps.get_model("genes", "PanelAppServer")

    PanelAppServer.objects.filter(name="PanelApp Australia").update(url="https://panelapp-aus.org")


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0078_alter_genesymbolalias_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(_panel_app_aus_url_change),
    ]
