# Generated by Django 6.0.3 on 2026-05-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genes", "0080_genecoveragecollection_data_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="panelapppanel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
