# Generated by Django 6.0.6 on 2026-08-12 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genes", "0085_delete_geneinfo"),
        ("snpdb", "0207_gene_level_contig"),
    ]

    operations = [
        migrations.CreateModel(
            name="FusionGeneId",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol_str",
                    models.TextField(db_collation="case_insensitive", unique=True),
                ),
                (
                    "gene_symbol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="genes.genesymbol",
                    ),
                ),
                (
                    "hgnc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="genes.hgnc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneFusion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_ordered", models.BooleanField(default=False)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fusions_as_anchor",
                        to="genes.fusiongeneid",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fusions_as_partner",
                        to="genes.fusiongeneid",
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="snpdb.variant"
                    ),
                ),
            ],
        ),
    ]
