# Generated by Django 6.1 on 2026-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0086_fusion_gene_id_and_gene_fusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfamsequence',
            name='domains_imported',
            field=models.DateTimeField(null=True),
        ),
    ]
