# Generated by Django 6.1 on 2026-08-27

from django.db import migrations
from django.db.models import Exists, OuterRef
from django.utils import timezone


def _stamp_sequences_with_existing_domains(apps, _schema_editor):
    """ Domains are now fetched lazily per gene from InterPro (#1554) - deployments that ran the old bulk
        ingest before the upstream file disappeared keep what they have, rather than re-fetching 90k proteins """
    PfamSequence = apps.get_model("genes", "PfamSequence")
    PfamDomains = apps.get_model("genes", "PfamDomains")

    has_domains = PfamDomains.objects.filter(pfam_sequence=OuterRef("pk"))
    PfamSequence.objects.annotate(has_domains=Exists(has_domains)).filter(
        has_domains=True, domains_imported__isnull=True).update(domains_imported=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ("genes", "0087_pfamsequence_domains_imported"),
    ]

    operations = [
        migrations.RunPython(_stamp_sequences_with_existing_domains, migrations.RunPython.noop),
    ]
