# Generated by Django 6.1.1 on 2026-09-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0089_one_off_resync_release_gene_symbol_genes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fusiongeneid',
            name='genes',
            field=models.ManyToManyField(blank=True, to='genes.gene'),
        ),
    ]
