# Generated by Django 6.1.1 on 2026-09-09 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0090_fusiongeneid_genes'),
        ('snpdb', '0260_annotsv_acmg_class_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FusionGeneId',
            new_name='GeneLevelId',
        ),
        migrations.CreateModel(
            name='GeneCopyNumberEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('G', 'Gain'), ('L', 'Loss')], max_length=1)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                           related_name='copy_number_events', to='genes.genelevelid')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.variant')),
            ],
        ),
    ]
