# Generated by Django 6.1.1 on 2026-09-16 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0091_gene_level_id_and_copy_number_event'),
        ('snpdb', '0263_mandatory_columns_all_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpliceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('display', models.TextField()),
                ('donor', models.IntegerField()),
                ('acceptor', models.IntegerField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.contig')),
                ('gene_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol')),
                ('genome_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.genomebuild')),
            ],
            options={
                'unique_together': {('gene_symbol', 'label', 'genome_build'), ('genome_build', 'contig', 'donor', 'acceptor')},
            },
        ),
    ]
