# Generated by Django 6.1.1 on 2026-09-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0093_seed_splice_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spliceevent',
            name='label',
            field=models.TextField(db_collation='case_insensitive'),
        ),
    ]
