# Generated by Django 6.1.1 on 2026-09-18 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0095_canonical_splice_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genecoverage',
            name='gene_coverage_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genes.genecoveragecollection'),
        ),
        migrations.AlterField(
            model_name='genecoveragecanonicaltranscript',
            name='gene_coverage_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genes.genecoveragecollection'),
        ),
    ]
