# Generated by Django 6.1.1 on 2026-10-01 05:11

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genes", "0096_alter_genecoverage_gene_coverage_collection_and_more"),
        ("snpdb", "0277_delete_vcfbedintersection"),
    ]

    operations = [
        migrations.CreateModel(
            name="CdotDataVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "annotation_consortium",
                    models.CharField(
                        choices=[("R", "RefSeq"), ("E", "Ensembl")], max_length=1
                    ),
                ),
                ("cdot_version", models.TextField()),
                (
                    "genome_build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.genomebuild",
                    ),
                ),
            ],
            options={
                "unique_together": {("genome_build", "annotation_consortium")},
            },
        ),
    ]
