# Generated by Django 6.1.1 on 2026-10-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genes", "0098_one_off_cdot_data_version_from_transcripts"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptversion",
            name="modified_cdot_version",
            field=models.TextField(blank=True, null=True),
        ),
    ]
