# Generated by Django 3.1 on 2020-09-29 05:30

import django.utils.timezone
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models

import library.django_utils.guardian_permissions_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_private', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlagResolution',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('description', models.TextField()),
                ('status', models.TextField(choices=[('O', 'Open'), ('C', 'Closed'), ('R', 'REJECTED')], default='O', max_length=1)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(models.Model, library.utils.ModelUtilsMixin),
        ),
        migrations.CreateModel(
            name='FlagTypeContext',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
            ],
            bases=(models.Model, library.utils.ModelUtilsMixin),
        ),
        migrations.CreateModel(
            name='FlagType',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('description', models.TextField()),
                ('help_text', models.TextField(default='')),
                ('raise_permission', models.TextField(choices=[('0', 'NO_PERM'), ('U', 'USERS'), ('O', 'OWNER'), ('A', 'ADMIN')], default='A', max_length=1)),
                ('permission', models.TextField(choices=[('0', 'NO_PERM'), ('U', 'USERS'), ('O', 'OWNER'), ('A', 'ADMIN')], max_length=1)),
                ('only_one', models.BooleanField(default=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('importance', models.IntegerField(default=0)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.flagtypecontext')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(models.Model, library.utils.ModelUtilsMixin),
        ),
        migrations.CreateModel(
            name='FlagComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('text', models.TextField()),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.flag')),
                ('resolution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flags.flagresolution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlagCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flags.flagtypecontext')),
            ],
            options={
                'permissions': (('admin_flagcollection', 'FlagCollection Admin'),),
            },
            bases=(models.Model, library.django_utils.guardian_permissions_mixin.GuardianPermissionsMixin),
        ),
        migrations.AddField(
            model_name='flag',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.flagcollection'),
        ),
        migrations.AddField(
            model_name='flag',
            name='flag_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.flagtype'),
        ),
        migrations.AddField(
            model_name='flag',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flags.flagresolution'),
        ),
        migrations.AddField(
            model_name='flag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FlagWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
                ('flag_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.flagcollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('flag_collection', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FlagTypeResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('flag_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.flagtype')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.flagresolution')),
            ],
            options={
                'unique_together': {('flag_type', 'resolution')},
            },
        ),
    ]
