# Generated by Django 4.0.4 on 2022-05-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0006_alter_flagcomment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagtype',
            name='permission',
            field=models.TextField(choices=[('0', 'NO_PERM'), ('U', 'USERS'), ('O', 'OWNER'), ('X', 'ADMIN'), ('A', 'SYSTEM')], max_length=1),
        ),
        migrations.AlterField(
            model_name='flagtype',
            name='raise_permission',
            field=models.TextField(choices=[('0', 'NO_PERM'), ('U', 'USERS'), ('O', 'OWNER'), ('X', 'ADMIN'), ('A', 'SYSTEM')], default='A', max_length=1),
        ),
        migrations.DeleteModel(
            name='FlagWatch',
        ),
    ]
