# Generated by Django 4.2.2 on 2023-09-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0009_condition_resolution_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flagtype',
            options={'base_manager_name': 'objects'},
        ),
    ]
