from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView
from django.urls import include
from django.urls.conf import path as path_standard
from django.views.generic import RedirectView

from library.preview_request import preview_view
from snpdb.grids import (
    AlleleLiftoverFailureColumns,
    CohortListColumns,
    CohortSampleListColumns,
    CustomColumnsCollectionColumns,
    DuosListColumns,
    GenomicIntervalsListColumns,
    LiftoverRunAlleleLiftoverColumns,
    LiftoverRunColumns,
    ManualVariantEntryCollectionColumns,
    QuadsListColumns,
    SampleColumns,
    SampleSkippedAnnotationColumns,
    SamplesListColumns,
    TagColorsCollectionColumns,
    TriosListColumns,
    VCFListColumns,
    VCFSkippedAnnotationColumns,
)
from snpdb.views import (
    views,
    views_autocomplete,
    views_cohort,
    views_data,
    views_graphs,
    views_json,
    views_lab,
    views_liftover,
    views_permissions,
    views_rest,
    views_sample_gene_matrix,
    views_tag,
    views_user_settings,
)
from snpdb.views.datatable_view import DatabaseTableView
from variantgrid.perm_path import path

urlpatterns = [
    # public pages
    path('public_global_sample_gene_matrix', views_sample_gene_matrix.public_global_sample_gene_matrix, name='public_global_sample_gene_matrix'),

    path('data', views_data.data, name='data'),
    path('vcfs', views_data.vcfs, name='vcfs'),
    path('samples', views_data.samples, name='samples'),
    path('bed_files', views_data.bed_files, name='bed_files'),
    path('job_status/<job_id>', views_json.job_status, name='job_state'),
    path('cached_generated_file/check/<cgf_id>', views_json.cached_generated_file_check, name='cached_generated_file_check'),
    path('cached_generated_file/delete', views.cached_generated_file_delete, name='cached_generated_file_delete'),
    path('cohort/create_cohort_genotype/<int:cohort_id>', views_json.create_cohort_genotype, name='create_cohort_genotype'),
    path('cohort/create_sub_cohort/<int:cohort_id>', views_json.create_sub_cohort, name='create_sub_cohort'),
    path('cohorts', views_cohort.cohorts, name='cohorts'),
    path('view_vcf/<int:vcf_id>', views_data.view_vcf, name='view_vcf'),
    path('vcf/<int:vcf_id>/archive', views_data.archive_vcf_view, name='archive_vcf'),
    path('vcf/<int:vcf_id>/restore', views_data.restore_vcf_view, name='restore_vcf'),
    path('vcf/<int:vcf_id>/populate_clingen_alleles', views_json.vcf_populate_clingen_alleles, name='vcf_populate_clingen_alleles'),
    path('vcf/<int:vcf_id>/change_zygosity_count/<int:vzcc_id>/<operation>', views_json.vcf_change_zygosity_count, name='vcf_change_zygosity_count'),
    path('get_patient_upload_csv_for_vcf/<int:pk>', views_data.get_patient_upload_csv_for_vcf, name='get_patient_upload_csv_for_vcf'),

    path('view_sample/<int:sample_id>', views_data.view_sample, name='view_sample'),
    path('view_genomic_intervals/<int:genomic_intervals_collection_id>', views_data.view_genomic_intervals, name='view_genomic_intervals'),
    path('genomic_intervals_graphs_tab/<int:genomic_intervals_collection_id>', views_data.genomic_intervals_graphs_tab, name='genomic_intervals_graphs_tab'),
    path('view_cohort/<int:cohort_id>', views_cohort.view_cohort, name='view_cohort'),
    path('cohort/hotspot/<int:cohort_id>', views_cohort.cohort_hotspot, name='cohort_hotspot'),
    path('cohort/gene_counts/<int:cohort_id>', views_cohort.cohort_gene_counts, name='cohort_gene_counts'),
    path('cohort/gene_counts/matrix/<int:cohort_id>/<gene_count_type_id>/<int:gene_list_id>', views_cohort.cohort_gene_counts_matrix, name='cohort_gene_counts_matrix'),
    path('cohort/sample_count/<int:cohort_id>', views_json.cohort_sample_count, name='cohort_sample_count'),
    path('cohort/sample_rows/<int:cohort_id>', views_cohort.cohort_sample_rows, name='cohort_sample_rows'),
    path('cohort_sample_edit/<int:cohort_id>', views_cohort.cohort_sample_edit, name='cohort_sample_edit'),
    path('trios', views_cohort.trios, name='trios'),
    path('view_trio/<int:pk>', views_cohort.view_trio, name='view_trio'),
    path('quads', views_cohort.quads, name='quads'),
    path('view_quad/<int:pk>', views_cohort.view_quad, name='view_quad'),
    path('duos', views_cohort.duos, name='duos'),
    path('view_duo/<int:pk>', views_cohort.view_duo, name='view_duo'),
    path('sample_files_tab/<int:sample_id>', views_data.sample_files_tab, name='sample_files_tab'),
    path('sample_variants_tab/<int:sample_id>', views_data.sample_variants_tab, name='sample_variants_tab'),
    path('sample_variants_gene_detail/<int:sample_id>/<gene_symbol>', views_data.sample_variants_gene_detail, name='sample_variants_gene_detail'),
    path('sample_graphs_tab/<int:sample_id>', views_data.sample_graphs_tab, name='sample_graphs_tab'),
    path('sample_permissions_tab/<int:sample_id>', views_data.sample_permissions_tab, name='sample_permissions_tab'),
    path('messages_bulk_delete', views.messages_bulk_delete, name='messages_bulk_delete'),
    path('manual_variant_entry', views_data.manual_variant_entry, name='manual_variant_entry'),
    path('watch_manual_variant_entry/<int:pk>', views_data.watch_manual_variant_entry, name='watch_manual_variant_entry'),
    path('group_permissions/<class_name>/<int:primary_key>', views_permissions.group_permissions, name='group_permissions'),
    path('group_permissions_object_delete/<class_name>/<int:primary_key>', views_permissions.group_permissions_object_delete, name='group_permissions_object_delete'),
    path('group_permissions/bulk/<class_name>', views_permissions.bulk_group_permissions, name='bulk_group_permissions'),
    path('settings/custom_columns/', views_user_settings.custom_columns, name='custom_columns'),
    path('settings/custom_columns/view/<int:custom_columns_collection_id>', views_user_settings.view_custom_columns, name='view_custom_columns'),
    path('settings/custom_columns/clone/<int:custom_columns_collection_id>', views_json.clone_custom_columns, name='clone_custom_columns'),
    path('settings/set_user_row_config', views_user_settings.set_user_row_config, name='set_user_row_config'),
    path('settings/set_user_data_grid_config', views_user_settings.set_user_data_grid_config, name='set_user_data_grid_config'),
    path('settings/set_show_tips', views_user_settings.set_show_tips, name='set_show_tips'),
    path('settings/set_all_variants_filter/<genome_build_name>', views_user_settings.set_all_variants_filter,
         name='set_all_variants_filter'),
    path('settings/tags', views_tag.tag_settings, name='tag_settings'),
    path('settings/tags/merge/<tag_id>', views_tag.tag_merge, name='tag_merge'),
    path('settings/tags/retire/<tag_id>', views_tag.tag_retire, name='tag_retire'),
    path('settings/tags/reinstate/<tag_id>', views_tag.tag_reinstate, name='tag_reinstate'),
    path('settings/tags/allele_origin/<tag_id>', views_tag.tag_set_allele_origin, name='tag_set_allele_origin'),
    path('settings/tags/collection/datatable', DatabaseTableView.as_view(column_class=TagColorsCollectionColumns),
         name='tag_color_collections_datatable'),
    path('settings/tags/collection/view/<int:tag_colors_collection_id>', views_tag.view_tag_colors_collection,
         name='view_tag_colors_collection'),
    path('settings/tags/collection/clone/<int:tag_colors_collection_id>', views_json.clone_tag_colors_collection,
         name='clone_tag_colors_collection'),
    path('settings/tags/collection/set_tag_color/<int:tag_colors_collection_id>', views_tag.set_tag_color, name='set_tag_color'),
    path('settings/igv_integration', views_user_settings.igv_integration, name='igv_integration'),
    path('settings/password/password_change', PasswordChangeView.as_view(
        template_name='snpdb/settings/password_change.html',
    ), name='change_password'),
    path('settings/password/password_change_done', PasswordChangeDoneView.as_view(template_name='snpdb/settings/password_change_done.html'), name='password_change_done'),
    path('settings/user', views_user_settings.view_user_settings, name='view_user_settings'),
    path('settings/node_counts_tab/user', views_user_settings.user_settings_node_counts_tab, name='user_settings_node_counts_tab'),
    path('settings/node_counts_tab/lab/<int:pk>', views_user_settings.lab_settings_node_counts_tab, name='lab_settings_node_counts_tab'),
    path('settings/node_counts_tab/organization/<int:pk>', views_user_settings.organization_settings_node_counts_tab, name='organization_settings_node_counts_tab'),

    path('user/<pk>', views_user_settings.view_user, name='view_user'),
    path('group/<pk>', views_user_settings.view_group, name='view_group'),
    path('lab/<int:lab_id>', views_lab.view_lab, name='view_lab'),
    path('lab/members_tab/<int:pk>', views_lab.lab_members_tab, name='lab_members_tab'),
    path('lab/members/add/<int:pk>', views_lab.lab_add_member, name='lab_add_member'),
    path('lab/members/remove/<int:pk>', views_lab.lab_remove_member, name='lab_remove_member'),
    path('clinvar_key/<str:pk>', views_lab.view_clinvar_key, name='clinvar_key'),
    path('organization/<int:organization_id>', views_lab.view_organization, name='view_organization'),
    path('help_static_page/<path:page_name>', views.help_static_page, name='help_static_page'),
    path('genomic_intervals_graph/<int:genomic_intervals_collection_id>', views_graphs.genomic_intervals_graph, name='genomic_intervals_graph'),
    path('chrom_density_graph/<int:sample_id>/<slug:cmap>', views_graphs.chrom_density_graph, name='chrom_density_graph'),
    path('homozygosity_graph/<int:sample_id>/<slug:cmap>', views_graphs.homozygosity_graph, name='homozygosity_graph'),
    path('sample_allele_frequency_histogram_graph/<int:sample_id>/<int:min_read_depth>', views_graphs.sample_allele_frequency_histogram_graph, name='sample_allele_frequency_histogram_graph'),
    path('staff_only', views.staff_only, name='staff_only'),
    path('tag_autocomplete_form', views_tag.tag_autocomplete_form, name='tag_autocomplete_form'),
    path('celery/wait_for_task/<celery_task>/<int:sleep_ms>/<path:redirect_url>', views.wait_for_task, name='wait_for_task'),
    path('wiki_save/<class_name>/<unique_keyword>/<unique_value>', views.wiki_save, name='wiki_save'),
    path('labs', views_lab.labs, name='labs'),
    path('labs_graph_detail', views_lab.labs_graph_detail, name='labs_graph_detail'),
    path('liftover', views_liftover.liftover_runs, name='liftover_runs'),
    path('liftover/view_liftover_run/<liftover_run_id>', views_liftover.view_liftover_run, name='view_liftover_run'),
    path('maps', views.maps, name='maps'),
    path('index', views.index, name='index'),
    path('user_global_sample_gene_matrix', views_sample_gene_matrix.user_global_sample_gene_matrix, name='user_global_sample_gene_matrix'),

    path('view_genome_build/<genome_build_name>', views.view_genome_build, name='view_genome_build'),
    path('view_contig/<contig_accession>', views.view_contig, name='view_contig'),

    path('manual_variant_entry_collections/detail/<int:pk>', views_data.manual_variant_entry_collection_detail,
         name='manual_variant_entry_collection_detail'),

    # Grids
    path('cohort/datatable/', DatabaseTableView.as_view(column_class=CohortListColumns), name='cohort_datatable'),
    path('cohort_sample/datatable/<int:cohort_id>/', DatabaseTableView.as_view(column_class=CohortSampleListColumns), name='cohort_sample_datatable'),
    path('sample/list/datatable/', DatabaseTableView.as_view(column_class=SamplesListColumns),
         name='samples_list_datatable'),
    path('sample/skipped_annotation/datatable/<int:sample_id>/',
         DatabaseTableView.as_view(column_class=SampleSkippedAnnotationColumns),
         name='sample_skipped_annotation_datatable'),
    path('genomic_intervals/datatable/', DatabaseTableView.as_view(column_class=GenomicIntervalsListColumns), name='genomic_intervals_datatable'),
    path('liftover/liftover_runs/datatable', DatabaseTableView.as_view(column_class=LiftoverRunColumns),
         name='liftover_runs_datatable'),
    path('liftover/allele_liftover/datatable', DatabaseTableView.as_view(column_class=LiftoverRunAlleleLiftoverColumns),
         name='allele_liftover_datatable'),
    path('liftover/allele_liftover_failures/datatable',
         DatabaseTableView.as_view(column_class=AlleleLiftoverFailureColumns),
         name='allele_liftover_failures_datatable'),
    path('manual_variant_entry_collections/datatable',
         DatabaseTableView.as_view(column_class=ManualVariantEntryCollectionColumns),
         name='manual_variant_entry_collections_datatable'),
    path('settings/custom_columns/collection/datatable',
         DatabaseTableView.as_view(column_class=CustomColumnsCollectionColumns),
         name='custom_columns_collections_datatable'),
    path('samples/datatable/',
         DatabaseTableView.as_view(column_class=SampleColumns),
         name='samples_datatable'),
    path('trio/datatable/', DatabaseTableView.as_view(column_class=TriosListColumns), name='trio_datatable'),
    path('quad/datatable/', DatabaseTableView.as_view(column_class=QuadsListColumns), name='quad_datatable'),
    path('duo/datatable/', DatabaseTableView.as_view(column_class=DuosListColumns), name='duo_datatable'),
    path('vcfs/datatable/', DatabaseTableView.as_view(column_class=VCFListColumns), name='vcfs_datatable'),
    path('vcf/skipped_annotation/datatable/<int:vcf_id>/',
         DatabaseTableView.as_view(column_class=VCFSkippedAnnotationColumns),
         name='vcf_skipped_annotation_datatable'),

    # Autocompletes
    path('autocomplete/Cohort/', views_autocomplete.CohortAutocompleteView.as_view(), name='cohort_autocomplete'),
    path('autocomplete/Contig/', views_autocomplete.ContigAutocompleteView.as_view(), name='contig_autocomplete'),
    path('autocomplete/CustomColumn/', views_autocomplete.CustomColumnAutocompleteView.as_view(), name='custom_column_autocomplete'),
    path('autocomplete/GenomicIntervalsCollection/', views_autocomplete.GenomicIntervalsCollectionAutocompleteView.as_view(), name='genomic_intervals_collection_autocomplete'),
    path('autocomplete/Project/', views_autocomplete.ProjectAutocompleteView.as_view(), name='project_autocomplete'),
    path('autocomplete/Sample/', views_autocomplete.SampleAutocompleteView.as_view(), name='sample_autocomplete'),
    path('autocomplete/Tag/', views_autocomplete.TagAutocompleteView.as_view(), name='tag_autocomplete'),
    path('autocomplete/Trio/', views_autocomplete.TrioAutocompleteView.as_view(), name='trio_autocomplete'),
    path('autocomplete/Quad/', views_autocomplete.QuadAutocompleteView.as_view(), name='quad_autocomplete'),
    path('autocomplete/Duo/', views_autocomplete.DuoAutocompleteView.as_view(), name='duo_autocomplete'),
    path('autocomplete/User/', views_autocomplete.UserAutocompleteView.as_view(), name='user_autocomplete'),
    path('autocomplete/Username/', views_autocomplete.UsernameAutocompleteView.as_view(), name='username_autocomplete'),
    path('autocomplete/Lab/', views_autocomplete.LabAutocompleteView.as_view(), name='lab_autocomplete'),
    path('autocomplete/LabAddMember/', views_autocomplete.LabAddMemberAutocompleteView.as_view(),
         name='lab_add_member_autocomplete'),
    path('autocomplete/VCF/', views_autocomplete.VCFAutocompleteView.as_view(), name='vcf_autocomplete'),

    # Previews
    path('preview/<str:db>/<str:idx>', preview_view, name='preview_data'),

    # For Uptime Robot
    path('uptime_check', views.view_uptime, name='uptime_check'),

    path_standard('api-auth/', include('rest_framework.urls')),
    path('api/sample_variant_zygosity/<int:sample_id>/<int:variant_id>', views_rest.VariantZygosityForSampleView.as_view(), name='variant_zygosity_for_sample'),
    path('api/trio/<pk>', views_rest.TrioView.as_view(), name='api_view_trio'),
    path('api/quad/<pk>', views_rest.QuadView.as_view(), name='api_view_quad'),
    path('api/duo/<pk>', views_rest.DuoView.as_view(), name='api_view_duo'),
    path('api/variant_allele_for_variant/<int:variant_id>/<genome_build_name>',
         views_rest.VariantAlleleForVariantView.as_view(), name='variant_allele_for_variant'),
    path('api/variant_sample_genotypes/<int:variant_id>',
         views_rest.VariantSampleGenotypesView.as_view(), name='variant_sample_genotypes'),
    path('api/project/create', views_rest.ProjectViewSet.as_view({"post": "create"}), name='api_project_create'),
    # Schema/docs moved to drf-spectacular at /api/schema and /api/docs (see variantgrid/urls.py)
    path_standard("docs/", RedirectView.as_view(pattern_name="api-docs", permanent=True)),
]
