from dataclasses import dataclass
from typing import Optional

from snpdb.models.models_enums import VCFInfoTypes


@dataclass(frozen=True)
class VCFInfoColumnDef:
    """ VCF INFO-field metadata for a VariantGridColumn, used by the analysis-grid VCF export.
        `column` is the VariantGridColumn.grid_column_name (its primary key). """
    info_id: str
    column: str
    type: VCFInfoTypes
    description: str
    number: Optional[int] = None


COLUMN_VCF_INFO: tuple[VCFInfoColumnDef, ...] = (
    VCFInfoColumnDef('1KG_AF', 'af_1kg', VCFInfoTypes.FLOAT, 'Estimated allele frequency in the range (0,1), based on AC/AN', number=1),
    VCFInfoColumnDef('ALLELEID', 'clinvar_allele_id', VCFInfoTypes.INTEGER, 'the ClinVar Allele ID'),
    VCFInfoColumnDef('AlphaMissense_pred', 'alphamissense_pred', VCFInfoTypes.STRING, 'AlphaMissense categorical prediction', number=1),
    VCFInfoColumnDef('ALPHAMISSENSE_rankscore', 'alphamissense_rankscore', VCFInfoTypes.FLOAT, 'AlphaMissense pathogenicity rank score', number=1),
    VCFInfoColumnDef('AlphaMissense_score', 'alphamissense_score', VCFInfoTypes.FLOAT, 'AlphaMissense raw pathogenicity score', number=1),
    VCFInfoColumnDef('BayesDel_noAF_score', 'bayesdel_noaf_score', VCFInfoTypes.FLOAT, 'BayesDel score (no allele frequency)', number=1),
    VCFInfoColumnDef('CADD_phred', 'cadd_phred', VCFInfoTypes.FLOAT, 'Combined Annotation Dependent Depletion raw scores', number=1),
    VCFInfoColumnDef('CADD_raw', 'cadd_raw', VCFInfoTypes.FLOAT, 'CADD raw (uncalibrated) C-score', number=1),
    VCFInfoColumnDef('ClinPred_pred', 'clinpred_pred', VCFInfoTypes.STRING, 'ClinPred categorical prediction (D/T)', number=1),
    VCFInfoColumnDef('ClinPred_score', 'clinpred_score', VCFInfoTypes.FLOAT, 'ClinPred raw score', number=1),
    VCFInfoColumnDef('CLNDISDB', 'clinvar_disease_database_name', VCFInfoTypes.STRING, 'Tag-value pairs of disease database name and identifier, e.g. OMIM:NNNNNN'),
    VCFInfoColumnDef('CLNDN', 'clinvar_preferred_disease_name', VCFInfoTypes.STRING, "ClinVar's preferred disease name for the concept specified by disease identifiers in CLNDISDB"),
    VCFInfoColumnDef('CLNREVSTAT', 'clinvar_review_status', VCFInfoTypes.STRING, 'ClinVar review status for the Variation ID'),
    VCFInfoColumnDef('CLNSIG', 'clinical_significance', VCFInfoTypes.STRING, 'ClinVar Variant Clinical Significance, 0 - Uncertain significance, 1 - not provided, 2 - Benign, 3 - Likely benign, 4 - Likely pathogenic, 5 - Pathogenic, 6 - drug response, 7 - histocompatibility, 255 - other'),
    VCFInfoColumnDef('CLNSIGCONF', 'conflicting_clinical_significance', VCFInfoTypes.STRING, 'Conflicting clinical significance for this single variant'),
    VCFInfoColumnDef('CLNSIG_MAX', 'clinvar_highest_pathogenicity', VCFInfoTypes.STRING, 'ClinVar Highest Pathogenicty'),
    VCFInfoColumnDef('CLNVI', 'clinvar_clinical_sources', VCFInfoTypes.STRING, "the variant's clinical sources reported as tag-value pairs of database and variant identifier"),
    VCFInfoColumnDef('CLNVID', 'clinvar_variation_id', VCFInfoTypes.INTEGER, 'ClinVar Variant Accession'),
    VCFInfoColumnDef('CONSEQUENCE', 'consequence', VCFInfoTypes.STRING, 'Molecular Consequence'),
    VCFInfoColumnDef('COSMIC_CNT', 'cosmic_count', VCFInfoTypes.INTEGER, 'Number of COSMIC samples with mutation', number=1),
    VCFInfoColumnDef('COSMIC_ID', 'cosmic_id', VCFInfoTypes.STRING, 'COSMIC_ID'),
    VCFInfoColumnDef('COSMIC_LEGACY_ID', 'cosmic_legacy_id', VCFInfoTypes.STRING, 'COSMIC Legacy ID', number=1),
    VCFInfoColumnDef('DBSCSNV_ADA', 'dbscsnv_ada_score', VCFInfoTypes.FLOAT, 'dbSCSNV Ada Score'),
    VCFInfoColumnDef('DBSCSNV_RF', 'dbscsnv_rf_score', VCFInfoTypes.FLOAT, 'dbSCSNV RF Score'),
    VCFInfoColumnDef('DBSNP_RS_ID', 'dbsnp_rs_id', VCFInfoTypes.STRING, 'dbSNP ID'),
    VCFInfoColumnDef('denovo_db_case_count', 'denovo_db_case_count', VCFInfoTypes.INTEGER, 'denovo-db case count (non-control)', number=1),
    VCFInfoColumnDef('denovo_db_control_count', 'denovo_db_control_count', VCFInfoTypes.INTEGER, 'denovo-db control count', number=1),
    VCFInfoColumnDef('denovo_db_primary_phenotypes', 'denovo_db_primary_phenotypes', VCFInfoTypes.STRING, 'denovo-db primary phenotypes (&-separated)'),
    VCFInfoColumnDef('denovo_db_pubmed_ids', 'denovo_db_pubmed_ids', VCFInfoTypes.STRING, 'denovo-db PubMed IDs (&-separated)'),
    VCFInfoColumnDef('denovo_db_studies', 'denovo_db_studies', VCFInfoTypes.STRING, 'denovo-db contributing studies (&-separated)'),
    VCFInfoColumnDef('DOMAINS', 'domains', VCFInfoTypes.STRING, 'Protein domains'),
    VCFInfoColumnDef('ENSEMBL_PROTEIN', 'ensembl_protein', VCFInfoTypes.STRING, 'Ensembl Protein ID'),
    VCFInfoColumnDef('FATHMM_MAX', 'fathmm_pred_most_damaging', VCFInfoTypes.STRING, 'FATHMM Prediction (most damaging)'),
    VCFInfoColumnDef('FLAGS', 'flags', VCFInfoTypes.STRING, 'Flags'),
    VCFInfoColumnDef('GENE_BAND', 'band', VCFInfoTypes.STRING, 'Cytogenetic band'),
    VCFInfoColumnDef('GENE_BIOTYPE', 'gene_biotype', VCFInfoTypes.STRING, 'Gene Biotype'),
    VCFInfoColumnDef('GENE_ccds_ids', 'ccds_ids', VCFInfoTypes.STRING, 'Consensus Coding Sequence Project Ids'),
    VCFInfoColumnDef('GENE_DISEASE_MODERATE_OR_ABOVE', 'gene_disease_moderate_or_above', VCFInfoTypes.STRING, 'GenCC gene/disease classifications >= Moderate. Joined with |'),
    VCFInfoColumnDef('GENE_DISEASE_SUPPORTIVE_OR_BELOW', 'gene_disease_supportive_or_below', VCFInfoTypes.STRING, 'GenCC gene/disease classifications of Supportive/Limited. Joined with |'),
    VCFInfoColumnDef('GENE_family_description', 'gene_family_description', VCFInfoTypes.STRING, 'From HGNC database.'),
    VCFInfoColumnDef('GENE_family_tag', 'gene_family_tag', VCFInfoTypes.STRING, 'From HGNC database.'),
    VCFInfoColumnDef('GENE_function_from_uniprotkb', 'function_from_uniprotkb', VCFInfoTypes.STRING, 'Function from <a href="http://www.uniprot.org">Universal Protein Knowledgebase.</a> The Swiss-Prot section is used, and it is manually annotated and reviewed and is of high-quality.'),
    VCFInfoColumnDef('GENE_hgnc_id', 'hgnc_id', VCFInfoTypes.STRING, 'HGNC Id'),
    VCFInfoColumnDef('GENE_hgnc_name', 'hgnc_name', VCFInfoTypes.STRING, 'HGNC Name'),
    VCFInfoColumnDef('GENE_hgnc_symbol', 'hgnc_symbol', VCFInfoTypes.STRING, 'Gene symbol/name from HGNC. The HUGO Gene Nomenclature Committee (HGNC) is the only worldwide authority that assigns standardised nomenclature to human genes.'),
    VCFInfoColumnDef('GENE_mgi_id', 'mgi_id', VCFInfoTypes.STRING, 'Mouse Genome Informatics ID'),
    VCFInfoColumnDef('GENE_omim_id', 'omim_id', VCFInfoTypes.STRING, 'Online Mendelian Inheritance in Man Id'),
    VCFInfoColumnDef('GENE_pathway_from_uniprotkb', 'pathway_from_uniprotkb', VCFInfoTypes.STRING, 'From Universal Protein Knowledgebase'),
    VCFInfoColumnDef('GENE_previous_symbols', 'previous_symbols', VCFInfoTypes.STRING, 'Previous Gene Names'),
    VCFInfoColumnDef('GENE_refseq_gene_summary', 'refseq_gene_summary', VCFInfoTypes.STRING, 'RefSeq Gene Summary'),
    VCFInfoColumnDef('GENE_rgd_id', 'rgd_id', VCFInfoTypes.STRING, 'Rat Genome Database ID'),
    VCFInfoColumnDef('GENE_symbol', 'gene_symbol', VCFInfoTypes.STRING, 'Gene Symbol (most recent name associated with assigned transcript)'),
    VCFInfoColumnDef('GENE_synonyms', 'synonyms', VCFInfoTypes.STRING, 'Synonyms (From the HGNC)'),
    VCFInfoColumnDef('GENE_tissue_specificity_from_uniprotkb', 'tissue_specificity_from_uniprotkb', VCFInfoTypes.STRING, 'From Universal Protein Knowledgebase'),
    VCFInfoColumnDef('GENE_ucsc_id', 'ucsc_id', VCFInfoTypes.STRING, 'UCSC ID'),
    VCFInfoColumnDef('GENE_uniprot_id', 'uniprot_id', VCFInfoTypes.STRING, 'Universal Protein Knowledgebase. The Swiss-Prot section is used, and it is manually annotated and reviewed and is of high-quality. Official website is www.uniprot.org'),
    VCFInfoColumnDef('GERP_PP_RS', 'gerp_pp_rs', VCFInfoTypes.STRING, 'GERP++ RS'),
    VCFInfoColumnDef('GNOMAD2_LIFTOVER_AF', 'gnomad2_liftover_af', VCFInfoTypes.FLOAT, 'gnomAD: Allele Frequency from gnomAD2 liftover (GRCh38 only)'),
    VCFInfoColumnDef('GNOMAD3_AC', 'gnomad_ac', VCFInfoTypes.FLOAT, 'gnomAD: Alternate Allele Count  (GRCh38 only)'),
    VCFInfoColumnDef('GNOMAD3_AN', 'gnomad_an', VCFInfoTypes.INTEGER, 'gnomAD: Total number of alleles  (GRCh38 only)'),
    VCFInfoColumnDef('GNOMAD3_POPMAX_AC', 'gnomad_popmax_ac', VCFInfoTypes.INTEGER, 'gnomAD: Allele count in the population with the maximum AF  (GRCh38 only)'),
    VCFInfoColumnDef('GNOMAD3_POPMAX_AN', 'gnomad_popmax_an', VCFInfoTypes.INTEGER, 'gnomAD: Total number of alleles in the population with the maximum AF  (GRCh38 only)'),
    VCFInfoColumnDef('GNOMAD3_POPMAX_HOM_ALT', 'gnomad_popmax_hom_alt', VCFInfoTypes.INTEGER, 'gnomAD: Count of homozygous individuals in the population with the maximum allele frequency (GRCh38 only)'),
    VCFInfoColumnDef('GNOMAD_AC_XY', 'gnomad_xy_ac', VCFInfoTypes.INTEGER, 'Allele Count in XY', number=1),
    VCFInfoColumnDef('GNOMAD_AF', 'gnomad_af', VCFInfoTypes.FLOAT, 'gnomAD AF'),
    VCFInfoColumnDef('GNOMAD_AF_mid', 'gnomad_mid_af', VCFInfoTypes.FLOAT, 'Allele Frequency (0-1) among Middle Eastern genotypes (exome+genome) (GRCh38/gnomad4 only)', number=1),
    VCFInfoColumnDef('GNOMAD_AF_XY', 'gnomad_xy_af', VCFInfoTypes.FLOAT, 'Allele Frequency in XY', number=1),
    VCFInfoColumnDef('GNOMAD_AN_XY', 'gnomad_xy_an', VCFInfoTypes.INTEGER, 'Allele Number in XY', number=1),
    VCFInfoColumnDef('GNOMAD_faf95', 'gnomad_faf95', VCFInfoTypes.FLOAT, 'Filtering allele frequency (using Poisson 95% CI) (max of exomes/genomes) (GRCh38/gnomad4 only)', number=1),
    VCFInfoColumnDef('GNOMAD_faf99', 'gnomad_faf99', VCFInfoTypes.FLOAT, 'Filtering allele frequency (using Poisson 99% CI) (max of exomes/genomes) (GRCh38/gnomad4 only)', number=1),
    VCFInfoColumnDef('GNOMAD_fafmax_faf95_max', 'gnomad_fafmax_faf95_max', VCFInfoTypes.FLOAT, 'Maximum filtering allele frequency (using Poisson 95% CI) across genetic_ancestry groups (max of exomes/genomes) (GRCh38/gnomad4 only)', number=1),
    VCFInfoColumnDef('GNOMAD_fafmax_faf99_max', 'gnomad_fafmax_faf99_max', VCFInfoTypes.FLOAT, 'Maximum filtering allele frequency (using Poisson 99% CI) across genetic_ancestry groups (max of exomes/genomes) (GRCh38/gnomad4 only)', number=1),
    VCFInfoColumnDef('GNOMAD_FILTERED', 'gnomad_filtered', VCFInfoTypes.FLAG, 'gnomAD Filtered', number=0),
    VCFInfoColumnDef('GNOMAD_GENE_OE_LOF', 'gnomad_oe_lof', VCFInfoTypes.FLOAT, 'gnomAD Gene Constraint LoF (OE)'),
    VCFInfoColumnDef('GNOMAD_HEMI_COUNT', 'gnomad_hemi_count', VCFInfoTypes.INTEGER, 'XY count (in non-PAR regions) - only on chrX', number=1),
    VCFInfoColumnDef('gnomAD_HOM_ALT', 'gnomad_hom_alt', VCFInfoTypes.INTEGER, 'Count of homozygous individuals'),
    VCFInfoColumnDef('GNOMAD_non_par', 'gnomad_non_par', VCFInfoTypes.FLOAT, 'non_par in genomes or exomes', number=1),
    VCFInfoColumnDef('GNOMAD_POPMAX', 'gnomad_popmax', VCFInfoTypes.STRING, 'gnomAD PopMax population'),
    VCFInfoColumnDef('GNOMAD_POPMAX_AF', 'gnomad_popmax_af', VCFInfoTypes.FLOAT, 'gnomAD PopMax AF'),
    VCFInfoColumnDef('GRANTHAM', 'grantham', VCFInfoTypes.INTEGER, 'Grantham', number=1),
    VCFInfoColumnDef('HGVS_C', 'hgvs_c', VCFInfoTypes.STRING, 'c.HGVS'),
    VCFInfoColumnDef('HGVS_G', 'hgvs_g', VCFInfoTypes.STRING, 'Genomic HGVS coordinate', number=1),
    VCFInfoColumnDef('HGVS_P', 'hgvs_p', VCFInfoTypes.STRING, 'p.HGVS'),
    VCFInfoColumnDef('HPO_TERMS', 'hpo_terms', VCFInfoTypes.STRING, 'Human Phenotype Ontology terms associated with gene'),
    VCFInfoColumnDef('IMPACT', 'impact', VCFInfoTypes.STRING, 'Impact'),
    VCFInfoColumnDef('INTERNAL_CLINSIG', 'internally_classified', VCFInfoTypes.STRING, 'Internally Classified'),
    VCFInfoColumnDef('INTERNAL_CLINSIG_MAX', 'max_internal_classification', VCFInfoTypes.STRING, 'Max Internal Classification'),
    VCFInfoColumnDef('INTERPRO_DOMAIN', 'interpro_domain', VCFInfoTypes.STRING, 'InterPro domain'),
    VCFInfoColumnDef('LOF_TOOL', 'loftool', VCFInfoTypes.FLOAT, 'LOF Tool'),
    VCFInfoColumnDef('Mastermind_MMCNT1', 'mastermind_count_1_cdna', VCFInfoTypes.INTEGER, "Count of <a href='https://www.genomenon.com/cvr/'>Mastermind</a> articles with cDNA matches for this specific variant", number=1),
    VCFInfoColumnDef('Mastermind_MMCNT2', 'mastermind_count_2_cdna_prot', VCFInfoTypes.INTEGER, "Count of <a href='https://www.genomenon.com/cvr/'>Mastermind</a> articles with variants either explicitly matching at the cDNA level or given only at protein level", number=1),
    VCFInfoColumnDef('Mastermind_MMCNT3', 'mastermind_count_3_aa_change', VCFInfoTypes.INTEGER, "Count of <a href='https://www.genomenon.com/cvr/'>Mastermind</a> articles including other DNA-level variants resulting in the same amino acid change.", number=1),
    VCFInfoColumnDef('Mastermind_MMID3', 'mastermind_mmid3', VCFInfoTypes.STRING, 'Mastermind MMID3 variant identifier(s), as gene:key', number=1),
    VCFInfoColumnDef('MaveDB_score', 'mavedb_score', VCFInfoTypes.FLOAT, 'MaveDB score - see MaveDB for interpretation of scores', number=1),
    VCFInfoColumnDef('MaveDB_urn', 'mavedb_urn', VCFInfoTypes.STRING, 'MaveDB database identifier', number=1),
    VCFInfoColumnDef('MAX_ENT_SCAN_ALT', 'maxentscan_alt', VCFInfoTypes.STRING, 'MaxEntScan Alt'),
    VCFInfoColumnDef('MAX_ENT_SCAN_DIFF', 'maxentscan_diff', VCFInfoTypes.STRING, 'MaxEntScan Diff'),
    VCFInfoColumnDef('MAXENTSCAN_PERCENT_DIFF', 'maxentscan_percent_diff_ref', VCFInfoTypes.FLOAT, 'Combined Annotation Dependent Depletion raw scores', number=1),
    VCFInfoColumnDef('MAX_ENT_SCAN_REF', 'maxentscan_ref', VCFInfoTypes.STRING, 'MaxEntScan Ref'),
    VCFInfoColumnDef('MetaRNN_pred', 'metarnn_pred', VCFInfoTypes.STRING, 'MetaRNN categorical prediction (D/T)', number=1),
    VCFInfoColumnDef('MetaRNN_score', 'metarnn_score', VCFInfoTypes.FLOAT, 'MetaRNN raw score', number=1),
    VCFInfoColumnDef('MONDO_TERMS', 'mondo_terms', VCFInfoTypes.STRING, 'MONDO terms associated with gene'),
    VCFInfoColumnDef('MPC_score', 'mpc_score', VCFInfoTypes.FLOAT, 'MPC (Missense badness, PolyPhen-2, Constraint) score', number=1),
    VCFInfoColumnDef('MUTATION_ASSESSOR_MAX', 'mutation_assessor_pred_most_damaging', VCFInfoTypes.STRING, 'Mutation Assessor (Most damaging)'),
    VCFInfoColumnDef('MUTATION_TASTER_MAX', 'mutation_taster_pred_most_damaging', VCFInfoTypes.STRING, 'Mutation Taster (Most damaging)'),
    VCFInfoColumnDef('MutPred2_score', 'mutpred2_score', VCFInfoTypes.FLOAT, 'MutPred2 general score', number=1),
    VCFInfoColumnDef('MutPred2_top5_mechanisms', 'mutpred2_top5_mechanisms', VCFInfoTypes.STRING, 'MutPred2 top 5 predicted molecular mechanisms'),
    VCFInfoColumnDef('NUM_DB_HET', 'total_db_het', VCFInfoTypes.INTEGER, 'Total Het in DB'),
    VCFInfoColumnDef('NUM_DB_HOM', 'total_db_hom', VCFInfoTypes.INTEGER, 'Total Hom in DB'),
    VCFInfoColumnDef('OMIM_TERMS', 'omim_terms', VCFInfoTypes.STRING, 'Online Mendelian Inheritance in Man terms associated with gene'),
    VCFInfoColumnDef('ORIGIN', 'clinvar_origin', VCFInfoTypes.STRING, 'Allele origin. One or more of the following values may be added: 0 - unknown; 1 - germline; 2 - somatic; 4 - inherited; 8 - paternal; 16 - maternal; 32 - de-novo; 64 - biparental; 128 - uniparental; 256 - not-tested; 512 - tested-inconclusive; 1073741824 - other'),
    VCFInfoColumnDef('OVERLAPPING_SYMBOLS', 'overlapping_symbols', VCFInfoTypes.STRING, 'MaxEntScan percent diff/ref', number=1),
    VCFInfoColumnDef('PATHOGENICITY_PREDICTIONS_NUM_BENIGN', 'predictions_num_benign', VCFInfoTypes.INTEGER, 'No. Pathogenic prediction tools that are benign', number=1),
    VCFInfoColumnDef('PATHOGENICITY_PREDICTIONS_NUM_PATHOGENIC', 'predictions_num_pathogenic', VCFInfoTypes.INTEGER, 'No. Pathogenic prediction tools that are pathogenic', number=1),
    VCFInfoColumnDef('POLYPHEN_HVAR_MAX', 'polyphen2_hvar_pred_most_damaging', VCFInfoTypes.STRING, 'Poplyphen2 HVAR (Most damaging)'),
    VCFInfoColumnDef('PrimateAI_pred', 'primateai_pred', VCFInfoTypes.STRING, 'PrimateAI categorical prediction (D/T)', number=1),
    VCFInfoColumnDef('PrimateAI_score', 'primateai_score', VCFInfoTypes.FLOAT, 'PrimateAI raw score', number=1),
    VCFInfoColumnDef('PUBMED', 'pubmed', VCFInfoTypes.STRING, 'PubMed'),
    VCFInfoColumnDef('REPEAT_MASKER', 'repeat_masker', VCFInfoTypes.STRING, 'Repeat masker'),
    VCFInfoColumnDef('REVEL_SCORE', 'revel_score', VCFInfoTypes.STRING, 'REVEL'),
    VCFInfoColumnDef('SIFT', 'sift', VCFInfoTypes.STRING, 'Effect prediction of single amino acid substitution by SIFT', number=1),
    VCFInfoColumnDef('SpliceAI_pred_DP_AG', 'spliceai_pred_dp_ag', VCFInfoTypes.INTEGER, "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta position for Acceptor Gain", number=1),
    VCFInfoColumnDef('SpliceAI_pred_DP_AL', 'spliceai_pred_dp_al', VCFInfoTypes.INTEGER, "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta position for Acceptor Loss", number=1),
    VCFInfoColumnDef('SpliceAI_pred_DP_DG', 'spliceai_pred_dp_dg', VCFInfoTypes.INTEGER, "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta position for Donor Gain", number=1),
    VCFInfoColumnDef('SpliceAI_pred_DP_DL', 'spliceai_pred_dp_dl', VCFInfoTypes.INTEGER, "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta position for Donor Loss", number=1),
    VCFInfoColumnDef('SpliceAI_pred_DS_AG', 'spliceai_pred_ds_ag', VCFInfoTypes.FLOAT, "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta score for Acceptor Gain", number=1),
    VCFInfoColumnDef('SpliceAI_pred_DS_AL', 'spliceai_pred_ds_al', VCFInfoTypes.FLOAT, "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta score for Acceptor Loss", number=1),
    VCFInfoColumnDef('SpliceAI_pred_DS_DG', 'spliceai_pred_ds_dg', VCFInfoTypes.FLOAT, "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta score for Donor Gain", number=1),
    VCFInfoColumnDef('SpliceAI_pred_DS_DL', 'spliceai_pred_ds_dl', VCFInfoTypes.FLOAT, "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta score for Donor Loss", number=1),
    VCFInfoColumnDef('SpliceAI_pred_SYMBOL', 'spliceai_gene_symbol', VCFInfoTypes.STRING, 'SpliceAI Gene Symbol'),
    VCFInfoColumnDef('SPLICE_REGION', 'splice_region', VCFInfoTypes.STRING, 'Splice Region'),
    VCFInfoColumnDef('SVLEN', 'svlen', VCFInfoTypes.INTEGER, 'Structural Variant Length', number=1),
    VCFInfoColumnDef('SV_overlap_AF', 'gnomad_sv_overlap_af', VCFInfoTypes.STRING, 'gnomAD SV (StructuralVariantOverlap): frequency of overlapping SV', number=1),
    VCFInfoColumnDef('SV_overlap_coords', 'gnomad_sv_overlap_coords', VCFInfoTypes.STRING, 'gnomAD SV (StructuralVariantOverlap): coordinates', number=1),
    VCFInfoColumnDef('SV_overlap_name', 'gnomad_sv_overlap_name', VCFInfoTypes.STRING, 'gnomAD SV (StructuralVariantOverlap): name of overlapping SV', number=1),
    VCFInfoColumnDef('SV_overlap_PC', 'gnomad_sv_overlap_percent', VCFInfoTypes.STRING, 'gnomAD SV (StructuralVariantOverlap): percent of input SV covered by reference SV', number=1),
    VCFInfoColumnDef('TAGS', 'tags', VCFInfoTypes.STRING, 'Tags'),
    VCFInfoColumnDef('TAGS_GLOBAL', 'tags_global', VCFInfoTypes.STRING, 'Global Tags'),
    VCFInfoColumnDef('TOPMED_AF', 'topmed_af', VCFInfoTypes.FLOAT, 'TOPMed'),
    VCFInfoColumnDef('TOTAL_DB_REF', 'total_db_ref', VCFInfoTypes.INTEGER, 'Total number of variants in database with HOM REF zygosity call', number=1),
    VCFInfoColumnDef('TOTAL_DB_UNK', 'total_db_unk', VCFInfoTypes.INTEGER, 'Total number of variants in database with HOM REF zygosity call', number=1),
    VCFInfoColumnDef('TRANSCRIPT_BIOTYPE', 'transcript_biotype', VCFInfoTypes.STRING, 'Transcript Biotype'),
    VCFInfoColumnDef('UK10K_AF', 'af_uk10k', VCFInfoTypes.FLOAT, 'Allele frequency in called genotypes, from UK10 project'),
    VCFInfoColumnDef('UNIPROT_REACTOME', 'uniprot_reactome', VCFInfoTypes.STRING, 'UniProt reactome'),
    VCFInfoColumnDef('VARIANT_CLASS', 'variant_class', VCFInfoTypes.STRING, 'Variant Class'),
    VCFInfoColumnDef('VARIANT_GRID_ID', 'variant', VCFInfoTypes.STRING, 'VariantGrid ID', number=1),
    VCFInfoColumnDef('VARITY_ER_score', 'varity_er_score', VCFInfoTypes.FLOAT, 'VARITY_ER score (rare exomes set)', number=1),
    VCFInfoColumnDef('VARITY_R_score', 'varity_r_score', VCFInfoTypes.FLOAT, 'VARITY_R score (rare set)', number=1),
    VCFInfoColumnDef('VEST4_score', 'vest4_score', VCFInfoTypes.FLOAT, 'VEST4 score', number=1),
)
