# note if you're running macOS M1 - miniconda doesn't have direct support for that, but using x64 with a translation layer should work fine
# to enable run
# conda config --env --set subdir osx-64
name: vgconda
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - py-bgzip
  - setuptools=68.0
  - more-itertools=9.1  # was 8.12.0
  - beautifulsoup4=4.12  # was 4.10.0
  - biopython=1.81
  - celery=5.2
  - configargparse=1.5
  - coreapi=2.3
  - cyvcf2==0.30.16
  - htseq=2.0
  - ijson=3.1
  - ipython=8.15
  - kombu=5.3  # was kombu==5.2.3
  - levenshtein==0.21  # was levenshtein==0.20.9
  - markdown=3.2  # was 3.1
  - matplotlib=3.5
  - networkx=2.4
  - nltk=3.8  # was 3.7
  - numpy=1.25 # was 1.22
  - oauthlib=3.1
  - pandas=1.4
  - psycopg2=2.9
  - pypdf2=2.11  # was 2.6
  - pysam==0.21  # was 0.18
  - python-dateutil=2.8
  - pyvcf3=1.0
  - redis=3.5 # was redis==3.5.3
  - reportlab=3.6 # increased patch version from requirements.txt
  - requests=2.31
  - requests-oauthlib=1.3
  - scipy=1.11  # was scipy==1.8.0
  - sqlparse=0.4
  - toposort=1.10  # was toposort==1.7
  - Unidecode=1.3
  - boto3=1.26
  - pyspellchecker=0.6
  - pydantic=2.3.0
  - deepdiff=6.5.0
  - gdal=3.7  # needed for geo
  - pip:
      - cdot==0.2.21
      - stream-zip==0.0.47
      # - bgzip==0.4.0
      - Django==4.2.5
      - django-amazon-ses==4.0.1
      - django-storages==1.12.3
      - django_autocomplete_light==3.9.1
      - django-avatar==7.1.1
      - django_cache_memoize==0.1.10
      - django-compressor==4.3.1
      - django_crispy_forms==2.0
      - django_dag==1.4.3
      - django_datetime_utc==1.0.3
      - django_debug_toolbar==4.2.0
      - django_downloadview==2.3.0
      - django-extensions==3.1.5
      - django-geojson==3.2.0
      - django_glrm==1.1.3
      - django-guardian==2.4.0
      - django_htmlmin==0.11.0
      - django-leaflet==0.28.2
      - django_model_utils==4.2.0
      - django-postgres-extra==2.0.5
      - django_recaptcha==3.0.0
      - django-registration-redux==2.9
      - django_termsandconditions==2.0.12
      - django-reversion-compare==0.15.0
      - django_threadlocals==0.10
      - djangorestframework==3.14.0
      - crispy-bootstrap4==2022.1
      - mozilla_django_oidc==2.0.0
      - easy_thumbnails==2.8.5
      - fontawesomefree==6.4.0
      - git+https://github.com/davmlaw/django-json-widget#egg=django_json_widget
      - git+https://github.com/davmlaw/django-jfu#egg=django-jfu
      - git+https://github.com/davmlaw/django-messages/#egg=django-messages
      - git+https://github.com/davmlaw/django-starfield#egg=django_starfield
      - git+https://github.com/davmlaw/django-js-reverse#egg=django-js-reverse
      - git+https://github.com/SACGF/hgvs#egg=pyhgvs
      - git+https://github.com/davmlaw/hgvs@f3701a44b389ebad3f4cc7da8dbe672d9ae4e6cb#egg=hgvs
      - nameparser==1.1.1 # nameparser hasn't been updated in conda since 1.0.5
      - rollbar==0.16.3
      - frozendict==2.3.4
      - pronto==2.4.7  # pronto causes a lot of dependancy issues that we're going to sweep under pip's rug