name: vg5
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - pip
  - beautifulsoup4=4.9.0
  - biopython=1.76
  - celery=4.4.2
  - Cython=0.29.17
  - cyvcf2=0.20.0
  - Faker=4.0.3
  - gunicorn=20.0.4
#  - HTSeq=0.12.4
  - ijson=3.0.3
  - ipython=7.14.0
  - kombu=4.6.8
  - lazy=1.4
  - lxml=4.5.0
  - markdown=3.2.1
  - matplotlib=3.2.1
  - networkx=2.4
  - numpy=1.18.4
  - oauthlib=3.1.0
  - pandas=1.0.3
#  - pronto=2.1.0
  - psycopg2=2.7.7 # had --no-binary in requirements.txt seeing if not a worry with conda
  - PyPDF2=1.26.0
#  - pysam=0.15.4
  - python-dateutil=2.7.3
  - python-Levenshtein=0.12.0
  - PyVCF=0.6.8
  - reportlab=3.5.42 # increased patch version from requirements.txt
  - requests=2.22.0
  - requests-oauthlib=1.3.0
  - rollbar=0.15.0
  - scipy=1.4.1
  - toposort=1.5
  - Unidecode=1.1.1
  - xlrd=1.2.0
  - six=1.14.0
  - pip:
      - pysam==0.15.4
#      - cyvcf2==0.20.0
      - HTSeq==0.12.4
      - pronto==2.1.0
      - coreapi==2.3.3
      - Django==2.2.10
      - django-admin-json-editor==0.2.0
      - django-amazon-ses==3.0.2
      - git+https://github.com/SACGF/django-autocomplete-light
      - django-avatar==5.0.0
      - django-compressor==2.4
      - git+https://github.com/davmlaw/django-dag#egg=django-dag
      - django-datetime-utc==1.0.2
      - django-debug-toolbar==2.2
      - django-downloadview==2.1.1
      - django-extensions==2.2.9
      - django-geojson==3.0.0
      - django-glrm==1.1.3
      - django-guardian==2.2.0
      - django-htmlmin==0.11.0
      - git+https://github.com/davmlaw/django-jfu#egg=django-jfu
      - django-js-reverse==0.9.1
      - django-leaflet==0.26.0
      - django-messages==0.6.0
      - django-model-utils==4.0.0
      - django-redis-cache==2.1.1
      - django-registration-redux==2.7
      - djangorestframework==3.11.0
      - django-starfield==1.0.post1
      - django-termsandconditions==2.0.6
      - easy-thumbnails==2.7
      - illuminate==0.6.5 # has conda but at 0.6.3
      - mozilla-django-oidc==1.2.3
      - nameparser==1.0.6 # has conda but at 1.0.5
      - nanoset==0.1.4
      - nltk==3.5 # has conda but at 2.4
      - git+https://github.com/SACGF/hgvs#egg=pyhgvs
      - redis==3.5.0 # only versions 4 and 5 are in conda
      - fastobo==0.7.2 # only linux version in conda