# Generated by Django 6.0.6 on 2026-07-23 06:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("snpdb", "0196_lab_mme_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeaconInboundQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("request_json", models.JSONField()),
                ("granularity", models.CharField(max_length=8)),
                ("authenticated", models.BooleanField(default=False)),
                ("observations_exists", models.BooleanField(default=False)),
                ("observations_count", models.IntegerField(default=0)),
                ("classifications_exists", models.BooleanField(default=False)),
                ("classifications_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="BeaconQueryCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=64)),
                ("exists", models.BooleanField(default=False)),
                ("count", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="snpdb.variant"
                    ),
                ),
            ],
            options={
                "unique_together": {("variant", "node_id")},
            },
        ),
    ]
