# Generated by Django 6.0.6 on 2026-07-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beaconquerycache",
            name="exists",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
