# Generated by Django 3.1 on 2020-09-29 05:35

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import library.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variantclassification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('config', models.JSONField(blank=True, default=library.utils.empty_dict)),
            ],
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('P', 'P'), ('S', 'S'), ('F', 'F'), ('N', 'N')], max_length=1)),
                ('meta', models.JSONField(blank=True, default=None, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.syncdestination')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariantClassificationModificationSyncRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('success', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=None, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.syncrun')),
                ('variant_classification_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variantclassification.variantclassificationmodification')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
