# Generated by Django 3.1 on 2020-10-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_auto_20201001_1635'),
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariantClassificationModificationSyncRecord',
            new_name='ClassificationModificationSyncRecord',
        ),
    ]
