# Generated by Django 3.1 on 2020-10-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_auto_20201001_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classificationmodificationsyncrecord',
            old_name='variant_classification_modification',
            new_name='classification_modification',
        ),
    ]
