# Generated by Django 3.1.3 on 2021-01-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20201001_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrun',
            name='status',
            field=models.CharField(choices=[('P', 'In Progress'), ('S', 'Success'), ('N', 'No Records'), ('F', 'Failed')], max_length=1),
        ),
    ]
