# Generated by Django 3.1 on 2021-01-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_auto_20210104_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncdestination',
            name='enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
