# Generated by Django 4.0.7 on 2023-06-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_one_off_manual_modify_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='full_sync',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='max_rows',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
