# Generated by Django 3.1 on 2020-10-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0002_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='variant_classification_config',
            new_name='classification_config',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='variant_classification_config',
            new_name='classification_config',
        ),
    ]
