# Generated by Django 3.1 on 2020-10-15 05:34

from django.db import migrations, models


def one_off_set_cohort_genotype_collection_num_samples(apps, _schema_editor):
    CohortGenotypeCollection = apps.get_model("snpdb", "CohortGenotypeCollection")

    for cg_collection in CohortGenotypeCollection.objects.all():
        if cg := cg_collection.cohortgenotype_set.first():
            num_samples = len(cg.samples_zygosity)
        else:
            num_samples = 0
        cg_collection.num_samples = num_samples
        cg_collection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0003_auto_20201001_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortgenotypecollection',
            name='num_samples',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(one_off_set_cohort_genotype_collection_num_samples),
    ]
