# Generated by Django 3.1 on 2020-10-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0004_cohortgenotypecollection_num_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortgenotypecollection',
            name='num_samples',
            field=models.IntegerField(),
        ),
    ]
