# Generated by Django 3.1 on 2020-11-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0005_auto_20201015_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsoverride',
            old_name='node_sql_tab',
            new_name='node_debug_tab',
        ),
        migrations.AddField(
            model_name='settingsoverride',
            name='variant_tag_group_by_variant',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
