# Generated by Django 3.1 on 2020-11-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0008_populate_column_vcf_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsoverride',
            name='variant_tag_group_by_variant',
        ),
    ]
