# Generated by Django 3.1.3 on 2020-12-15 05:19

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0009_remove_settingsoverride_variant_tag_group_by_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomalierVCFExtract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('vcf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.vcf')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomalierTrioRelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField()),
                ('trio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.trio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomalierCohortRelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField()),
                ('cohort_version', models.IntegerField()),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.cohort')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomalierAncestryRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('vcf_extract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.somaliervcfextract')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomalierAncestry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('predicted_ancestry', models.CharField(choices=[('A', 'African'), ('M', 'Ad Mixed American'), ('E', 'East Asian'), ('U', 'European'), ('S', 'South Asian')], max_length=1)),
                ('EAS_prob', models.FloatField()),
                ('AFR_prob', models.FloatField()),
                ('AMR_prob', models.FloatField()),
                ('SAS_prob', models.FloatField()),
                ('EUR_prob', models.FloatField()),
                ('ancestry_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.somalierancestryrun')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.sample')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
