# Generated by Django 3.1.3 on 2020-12-23 05:23

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models

from manual.operations.manual_operations import ManualOperation


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_deployment'),
        ('snpdb', '0009_remove_settingsoverride_variant_tag_group_by_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomalierAllSamplesRelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('C', 'Created'), ('P', 'Processing'), ('E', 'Error'), ('S', 'Success'), ('K', 'Skipped'), ('T', 'Terminated Early'), ('Z', 'Timed Out')], default='C', max_length=1)),
                ('error_exception', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomalierVCFExtract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('C', 'Created'), ('P', 'Processing'), ('E', 'Error'), ('S', 'Success'), ('K', 'Skipped'), ('T', 'Terminated Early'), ('Z', 'Timed Out')], default='C', max_length=1)),
                ('error_exception', models.TextField(blank=True, null=True)),
                ('vcf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.vcf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomalierTrioRelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('C', 'Created'), ('P', 'Processing'), ('E', 'Error'), ('S', 'Success'), ('K', 'Skipped'), ('T', 'Terminated Early'), ('Z', 'Timed Out')], default='C', max_length=1)),
                ('error_exception', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('trio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.trio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomalierSampleExtract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_count', models.IntegerField(default=0)),
                ('het_count', models.IntegerField(default=0)),
                ('hom_count', models.IntegerField(default=0)),
                ('unk_count', models.IntegerField(default=0)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.sample')),
                ('vcf_extract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.somaliervcfextract')),
            ],
        ),
        migrations.CreateModel(
            name='SomalierCohortRelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('C', 'Created'), ('P', 'Processing'), ('E', 'Error'), ('S', 'Success'), ('K', 'Skipped'), ('T', 'Terminated Early'), ('Z', 'Timed Out')], default='C', max_length=1)),
                ('error_exception', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cohort_version', models.IntegerField()),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.cohort')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomalierAncestryRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('C', 'Created'), ('P', 'Processing'), ('E', 'Error'), ('S', 'Success'), ('K', 'Skipped'), ('T', 'Terminated Early'), ('Z', 'Timed Out')], default='C', max_length=1)),
                ('error_exception', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('vcf_extract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.somaliervcfextract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomalierAncestry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('predicted_ancestry', models.CharField(choices=[('A', 'African'), ('M', 'Ad Mixed American'), ('E', 'East Asian'), ('U', 'European'), ('S', 'South Asian')], max_length=1)),
                ('EAS_prob', models.FloatField()),
                ('AFR_prob', models.FloatField()),
                ('AMR_prob', models.FloatField()),
                ('SAS_prob', models.FloatField()),
                ('EUR_prob', models.FloatField()),
                ('ancestry_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.somalierancestryrun')),
                ('sample_extract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.somaliersampleextract')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomalierRelatePairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatedness', models.FloatField()),
                ('ibs0', models.IntegerField()),
                ('ibs2', models.IntegerField()),
                ('hom_concordance', models.FloatField()),
                ('hets_a', models.IntegerField()),
                ('hets_b', models.IntegerField()),
                ('hets_ab', models.IntegerField()),
                ('shared_hets', models.IntegerField()),
                ('hom_alts_a', models.IntegerField()),
                ('hom_alts_b', models.IntegerField()),
                ('shared_hom_alts', models.IntegerField()),
                ('n', models.IntegerField()),
                ('x_ibs0', models.IntegerField()),
                ('x_ibs2', models.IntegerField()),
                ('relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.somalierallsamplesrelate')),
                ('sample_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='somalierrelatepairs_a', to='snpdb.sample')),
                ('sample_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='somalierrelatepairs_b', to='snpdb.sample')),
            ],
            options={
                'unique_together': {('sample_a', 'sample_b')},
            },
        ),
        ManualOperation(task_id=ManualOperation.task_id_manage(["somalier_existing_vcfs"]))
    ]
