# Generated by Django 3.1.3 on 2021-01-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0010_somalierallsamplesrelate_somalierancestry_somalierancestryrun_somaliercohortrelate_somalierrelatepai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingsGenomeBuild',
        ),
    ]
