# Generated by Django 3.1 on 2021-08-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0012_remove_organization_classification_report_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clingenallele',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
