# Generated by Django 3.1.3 on 2021-01-18 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0014_one_off_clingen_allele_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAlleleSource',
            fields=[
                ('allelesource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snpdb.allelesource')),
                ('variant_allele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.variantallele')),
            ],
            bases=('snpdb.allelesource',),
        ),
    ]
