# Generated by Django 3.1 on 2021-02-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0015_variantallelesource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantgridcolumn',
            name='annotation_level',
            field=models.CharField(choices=[('C', 'ClinVar'), ('D', 'Database'), ('G', 'Gene'), ('H', 'HGNC'), ('S', 'Sample'), ('T', 'Transcript'), ('U', 'UniProt'), ('V', 'Variant')], max_length=1, null=True),
        ),
    ]
