# Generated by Django 3.1.3 on 2021-02-11 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0017_new_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAlleleCollectionSource',
            fields=[
                ('allelesource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snpdb.allelesource')),
                ('genome_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.genomebuild')),
            ],
            bases=('snpdb.allelesource',),
        ),
        migrations.CreateModel(
            name='VariantAlleleCollectionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.variantallelecollectionsource')),
                ('variant_allele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.variantallele')),
            ],
        ),
    ]
