# Generated by Django 3.1.3 on 2021-02-19 03:15

from django.db import migrations


def _gnomad3_label_fix_remove_rvis(apps, schema_editor):
    VariantGridColumn = apps.get_model("snpdb", "VariantGridColumn")

    LABELS = {
        'gnomad_an': 'gnomAD AN',
        'gnomad_popmax_ac': 'gnomAD PopMax AC',
        'gnomad_popmax_an': 'gnomAD PopMax AN',
        'gnomad_popmax_hom_alt': 'gnomAD PopMax Hom Alt',
    }
    for c, label in LABELS.items():
        VariantGridColumn.objects.filter(grid_column_name=c).update(label=label)

    DESCRIPTION = {
        'gnomad_popmax_af': 'Allele Frequency (0-1) in outbred population with highest AF (excludes Ashkenazi, Finnish, and other) (exome+genome)',
        'gnomad_popmax': 'Outbred population (excludes Ashkenazi, Finnish, and other) with highest allele frequency (value in gnomad_popmax_af',
        'gnomad_popmax_ac': 'gnomAD: Allele count in outbred population (excludes Ashkenazi, Finnish, and other) with the maximum AF  (GRCh38 only)',
        'gnomad_popmax_an': 'gnomAD: Total number of alleles in the outbred population (excludes Ashkenazi, Finnish, and other) with the maximum AF  (GRCh38 only)',
        'gnomad_popmax_hom_alt': 'gnomAD: Count of homozygous individuals in the outbred population (excludes Ashkenazi, Finnish, and other) with the maximum allele frequency (GRCh38 only)',
    }
    for c, description in DESCRIPTION.items():
        VariantGridColumn.objects.filter(grid_column_name=c).update(description=description)

    VariantGridColumn.objects.filter(grid_column_name="rvis_percentile").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0019_new_columns_gnomad3'),
    ]

    operations = [
        migrations.RunPython(_gnomad3_label_fix_remove_rvis)
    ]
