# Generated by Django 3.1.3 on 2021-02-25 04:19

from django.db import migrations


def _change_variant_grid_column_from_foreignkey_to_fields(apps, _schema_editor):
    VariantGridColumn = apps.get_model("snpdb", "VariantGridColumn")

    # We originally pointed to ForeignKeys (ie "__gene_symbol") but this can cause filters to fail with:
    # Related Field got invalid lookup: contains. Fix is to make sure you specify path to final column
    VARIANT_GRID_COLUMNS = {
        'gene_symbol': 'variantannotation__transcript_version__gene_version__gene_symbol__symbol',
        'hgnc_symbol': 'variantannotation__transcript_version__gene_version__hgnc__gene_symbol__symbol',
    }
    for pk, variant_column in VARIANT_GRID_COLUMNS.items():
        VariantGridColumn.objects.filter(pk=pk).update(variant_column=variant_column)


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0020_gnomad3_label_fix_remove_rvis'),
    ]

    operations = [
        migrations.RunPython(_change_variant_grid_column_from_foreignkey_to_fields)
    ]
