# Generated by Django 3.1.3 on 2021-03-03 07:35

from django.db import migrations
from django.db.models import F

from library.django_utils import bulk_insert_class_data


def _new_columns_clinvar_conflicting_clinical_significance(apps, _schema_editor):
    CustomColumn = apps.get_model("snpdb", "CustomColumn")
    NEW_VARIANT_GRID_COLUMNS = [
        {'grid_column_name': 'conflicting_clinical_significance',
         'variant_column': 'clinvar__conflicting_clinical_significance',
         'annotation_level': 'C',
         'width': None,
         'label': 'ClinVar Conflicting Clin Sig',
         'description': 'Conflicting clinical significance for this single variant',
         'model_field': True,
         'queryset_field': True},
    ]

    NEW_COLUMN_VCF_INFO = [
        {'info_id': ' CLNSIGCONF',
         'column_id': 'conflicting_clinical_significance',
         'number': None,
         'type': 'S',
         'description': "Conflicting clinical significance for this single variant"},
    ]

    bulk_insert_class_data(apps, "snpdb", [("VariantGridColumn", NEW_VARIANT_GRID_COLUMNS)])
    bulk_insert_class_data(apps, "snpdb", [("ColumnVCFInfo", NEW_COLUMN_VCF_INFO)])

    # Add it to every custom columns just after "clinical_significance"
    for cc in CustomColumn.objects.filter(column='clinical_significance'):
        ccc = cc.custom_columns_collection
        # Shift everything after up 1
        ccc.customcolumn_set.filter(sort_order__gt=cc.sort_order).update(sort_order=F("sort_order") + 1)
        ccc.customcolumn_set.create(column_id='conflicting_clinical_significance', sort_order=cc.sort_order + 1)


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0021_change_variant_grid_column_from_foreignkey_to_fields'),
    ]

    operations = [
        migrations.RunPython(_new_columns_clinvar_conflicting_clinical_significance)
    ]
