# Generated by Django 3.1.3 on 2021-03-09 04:25

from django.db import migrations

from library.django_utils import bulk_insert_class_data


def _new_column_spliceai_gene(apps, schema_editor):
    NEW_VARIANT_GRID_COLUMNS = [
        {'grid_column_name': 'spliceai_gene_symbol',
         'variant_column': 'variantannotation__spliceai_gene_symbol',
         'annotation_level': 'V',
         'width': None,
         'label': 'SpliceAI Gene',
         'description': "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> Gene Symbol",
         'model_field': True,
         'queryset_field': True},
    ]

    NEW_COLUMN_VCF_INFO = [
        {'info_id': ' SpliceAI_pred_SYMBOL',
         'column_id': 'spliceai_gene_symbol',
         'number': None,
         'type': 'S',
         'description': "SpliceAI Gene Symbol"},
    ]

    bulk_insert_class_data(apps, "snpdb", [("VariantGridColumn", NEW_VARIANT_GRID_COLUMNS)])
    bulk_insert_class_data(apps, "snpdb", [("ColumnVCFInfo", NEW_COLUMN_VCF_INFO)])


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0022_new_column_clinvar_conflicting_clinical_significance'),
    ]

    operations = [
        migrations.RunPython(_new_column_spliceai_gene)
    ]
