# Generated by Django 3.1.3 on 2021-03-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0023_new_column_spliaceai_gene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcfsourcesettings',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='vcfsourcesettings',
            name='value',
        ),
        migrations.AddField(
            model_name='vcf',
            name='allele_frequency_field',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vcf',
            name='allele_frequency_source',
            field=models.CharField(choices=[('C', 'calculated'), ('F', 'field')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='vcf',
            name='variant_zygosity_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vcfsourcesettings',
            name='sample_variants_type',
            field=models.CharField(choices=[('U', 'Unknown'), ('G', 'Germline'), ('M', 'Mixed (Single Sample)'), ('S', 'Somatic only (Tumor minus normal)')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='vcfsourcesettings',
            name='variant_zygosity_count',
            field=models.BooleanField(default=True),
        ),
    ]
