# Generated by Django 3.1.3 on 2021-03-09 06:07

from django.db import migrations


def _default_vcf_source_settings(apps, schema_editor):
    MIXED = 'M'
    SOMATIC_ONLY = 'S'  # Eg Tumor/Normal subtraction
    VCFSourceSettings = apps.get_model("snpdb", "VCFSourceSettings")

    VCFSourceSettings.objects.all().delete()  # Delete previous
    VCFSourceSettings.objects.create(source_regex="^freeBayes", sample_variants_type=MIXED)
    VCFSourceSettings.objects.create(source_regex="combine_caller_data", sample_variants_type=SOMATIC_ONLY)


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0024_auto_20210309_1637'),
    ]

    operations = [
        migrations.RunPython(_default_vcf_source_settings)
    ]
