# Generated by Django 3.1.3 on 2021-03-18 04:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0025_default_vcf_source_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortgenotype',
            name='samples_filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='cohortgenotype',
            name='unk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variantzygositycount',
            name='unk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vcf',
            name='sample_filters',
            field=models.BooleanField(default=False),
        ),
    ]
