# Generated by Django 3.1.3 on 2021-03-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0026_auto_20210319_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantallele',
            options={},
        ),
        migrations.AlterField(
            model_name='allelemergelog',
            name='conversion_tool',
            field=models.CharField(choices=[('SC', 'Identical Contig/Version'), ('CA', 'ClinGen Allele Registry'), ('DB', 'dbSNP API'), ('NR', 'NCBI Remap')], max_length=2),
        ),
        migrations.AlterField(
            model_name='liftover',
            name='conversion_tool',
            field=models.CharField(choices=[('SC', 'Identical Contig/Version'), ('CA', 'ClinGen Allele Registry'), ('DB', 'dbSNP API'), ('NR', 'NCBI Remap')], max_length=2),
        ),
        migrations.AlterField(
            model_name='variantallele',
            name='conversion_tool',
            field=models.CharField(choices=[('SC', 'Identical Contig/Version'), ('CA', 'ClinGen Allele Registry'), ('DB', 'dbSNP API'), ('NR', 'NCBI Remap')], max_length=2),
        ),
        migrations.AlterField(
            model_name='variantallele',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.variant'),
        ),
        migrations.AlterUniqueTogether(
            name='variantallele',
            unique_together={('variant', 'genome_build', 'allele')},
        ),
    ]
