# Generated by Django 3.1.3 on 2021-03-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0027_auto_20210326_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcf',
            name='allele_frequency_percent',
            field=models.BooleanField(default=False),
        ),
    ]
