# Generated by Django 3.1.3 on 2021-03-30 06:43

from django.db import migrations


def _one_off_legacy_vcf_allele_frequency_percent(apps, schema_editor):
    VCF = apps.get_model("snpdb", "VCF")
    VCF.objects.filter(allele_frequency_field__isnull=True).update(allele_frequency_percent=True)


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0028_vcf_allele_frequency_percent'),
    ]

    operations = [
        migrations.RunPython(_one_off_legacy_vcf_allele_frequency_percent)
    ]
