# Generated by Django 3.1 on 2021-05-04 00:18

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0030_one_off_fix_cohort_sample_order'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["set_custom_columns_permissions"])),
    ]
