# Generated by Django 3.1.6 on 2021-04-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0030_one_off_fix_cohort_sample_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='slack_webhook',
            field=models.TextField(blank=True),
        ),
    ]
