# Generated by Django 3.1 on 2021-05-04 01:03

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0031_custom_columns_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcolumnscollection',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='customcolumnscollection',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
