# Generated by Django 3.1.6 on 2021-05-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0031_auto_20210430_1232'),
        ('snpdb', '0032_auto_20210504_1033'),
    ]

    operations = [
    ]
