# Generated by Django 3.2.1 on 2021-05-19 04:20

from django.db import migrations


def _one_off_fix_drug_response_typo(apps, schema_editor):
    VariantGridColumn = apps.get_model("snpdb", "VariantGridColumn")

    VariantGridColumn.objects.filter(grid_column_name='drug_response').update(label='ClinVar Drug Response')


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0032_auto_20210504_1033'),
    ]

    operations = [
        migrations.RunPython(_one_off_fix_drug_response_typo)
    ]
