# Generated by Django 3.1.6 on 2021-05-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0033_merge_20210505_1258'),
        ('snpdb', '0034_alter_nodecountsettings_built_in_filter'),
    ]

    operations = [
    ]
