# Generated by Django 3.1 on 2021-08-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0035_merge_20210520_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clingenallele',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
