# Generated by Django 3.1.6 on 2021-07-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0037_auto_20210715_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarkey',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
