# Generated by Django 3.1.6 on 2021-07-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0038_clinvarkey_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarkey',
            name='behalf_org_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
