# Generated by Django 3.1.6 on 2021-07-29 06:57

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0039_clinvarkey_behalf_org_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinVarKeyAssertionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('assertion_method', models.TextField(blank=True, default='')),
                ('clinvar_json', models.JSONField()),
                ('clinvar_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.clinvarkey')),
            ],
            options={
                'verbose_name': 'ClinVar key assertion method',
                'unique_together': {('clinvar_key', 'assertion_method')},
            },
        ),
    ]
