# Generated by Django 3.1.6 on 2021-07-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0040_one_off_vcf_reload_af_percent'),
        ('snpdb', '0040_clinvarkeyassertionmethod'),
    ]

    operations = [
    ]
