# Generated by Django 3.2.4 on 2021-08-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0042_auto_20210730_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clingenallele',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
