# Generated by Django 3.1.6 on 2021-08-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0043_alter_clingenallele_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarkey',
            name='inject_acmg_description',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
