# Generated by Django 3.2.6 on 2021-09-20 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0046_lab_upload_auto_pattern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinvarkey',
            old_name='behalf_org_id',
            new_name='org_id',
        ),
    ]
