# Generated by Django 3.2.6 on 2021-11-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0053_australian_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='old_country',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='old_state',
        ),
    ]
