# Generated by Django 3.2.4 on 2021-12-20 06:40
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0055_auto_20211214_1428'),
    ]

    operations = [
        # Intentionally empty - this has been replaced by library_version_checks
    ]
