# Generated by Django 3.2.4 on 2021-12-20 06:40
from importlib import metadata
from importlib.metadata import PackageNotFoundError

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_old_version(apps):
    needs_upgrade = False
    try:
        required_version = (0, 30, 14)  # Ploidy fixes
        versions = [int(v) for v in metadata.version("cyvcf2").split(".")]
        for req_v, v in zip(versions, required_version):
            needs_upgrade |= req_v < v
    except PackageNotFoundError:
        needs_upgrade = True

    return needs_upgrade

class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0055_auto_20211214_1428'),
    ]

    operations = [
        ManualOperation.operation_other(args=[
            'Update cyvcf2 library - sudo python3 -m pip install --force --upgrade numpy "cyvcf2>=0.30.14"'],
            test=_test_old_version),
    ]
