# Generated by Django 4.0.2 on 2022-02-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0057_new_gene_annotation_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedWikiCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_column_name', models.TextField()),
                ('genome_build', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.genomebuild')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedWiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_column_value', models.TextField()),
                ('markdown', models.TextField()),
                ('username', models.TextField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.importedwikicollection')),
                ('matched_wiki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.wiki')),
            ],
        ),
    ]
