# Generated by Django 4.0.2 on 2022-02-18 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0058_importedwikicollection_importedwiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortgenotypecollection',
            name='common_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.cohortgenotypecollection'),
        ),
    ]
