# Generated by Django 4.0.2 on 2022-02-21 04:19

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0059_cohortgenotypecollection_common_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortgenotypecollection',
            name='common_checked',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cohortgenotypecollection',
            name='common_collection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.cohortgenotypecollection'),
        ),
        migrations.CreateModel(
            name='CohortGenotypeCommonFilterVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('gnomad_version', models.TextField()),
                ('gnomad_af_min', models.FloatField()),
                ('clinical_significance_max', models.CharField(max_length=1, null=True)),
                ('genome_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.genomebuild')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cohortgenotypecollection',
            name='common_filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='snpdb.cohortgenotypecommonfilterversion'),
        ),
    ]
