# Generated by Django 4.0.2 on 2022-02-28 21:45

from django.db import migrations
from django.db.models import Max


def _one_off_rm_dupes_vcf_filter(apps, _schema_editor):
    VCFFilter = apps.get_model("snpdb", "VCFFilter")
    newest_qs = VCFFilter.objects.values("vcf", "filter_id").annotate(latest_id=Max('id'))
    VCFFilter.objects.exclude(pk__in=newest_qs.values_list("latest_id")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0059_cohortgenotypecommonfilterversion_and_more'),
    ]

    operations = [
        migrations.RunPython(_one_off_rm_dupes_vcf_filter)
    ]
