# Generated by Django 4.0.2 on 2022-02-22 03:32

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0060_cohortgenotypecollection_common_checked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonVariantClassified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('common_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.cohortgenotypecommonfilterversion')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.variant')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
