# Generated by Django 4.0.2 on 2022-02-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0060_one_off_rm_dupes_vcf_filter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vcffilter',
            unique_together={('vcf', 'filter_code'), ('vcf', 'filter_id')},
        ),
    ]
