# Generated by Django 4.0.2 on 2022-03-02 05:53

from django.db import migrations


def _change_hgnc_id(apps, _schema_editor):
    """ We deleted hgnc_id from variant annotation - go through gene now """
    VariantGridColumn = apps.get_model("snpdb", "VariantGridColumn")
    variant_column = "variantannotation__transcript_version__gene_version__hgnc__id"
    VariantGridColumn.objects.filter(pk='hgnc_id').update(variant_column=variant_column)


def _one_off_delete_some_columns(apps, _schema_editor):
    """ This can be removed if/when we squish migrations """
    VariantGridColumn = apps.get_model("snpdb", "VariantGridColumn")
    DELETE_COLUMNS = [
        "cadd_raw",
        "fathmm_pred",
        "mutation_assessor_pred",
        "mutation_taster_pred",
        "polyphen2_hvar_pred",
        "swissprot",
        "symbol_source",
        "trembl",
        "uniparc",
    ]
    VariantGridColumn.objects.filter(pk__in=DELETE_COLUMNS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0041_remove_variantannotation_cadd_raw_and_more'),  # Need ColumnVEPField cascade delete
        ('snpdb', '0061_alter_vcffilter_unique_together'),
    ]

    operations = [
        migrations.RunPython(_change_hgnc_id),
        migrations.RunPython(_one_off_delete_some_columns)
    ]
