# Generated by Django 4.0.2 on 2022-02-22 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0061_commonvariantclassified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonvariantclassified',
            options={},
        ),
        migrations.AlterField(
            model_name='cohortgenotypecollection',
            name='common_collection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uncommon', to='snpdb.cohortgenotypecollection'),
        ),
        migrations.AlterUniqueTogether(
            name='commonvariantclassified',
            unique_together={('variant', 'common_filter')},
        ),
    ]
