# Generated by Django 4.0.2 on 2022-03-07 03:11

from django.db import migrations


def _one_off_fix_s3_locations(apps, schema_editor):
    """ This can be removed if/when we squish migrations """
    Lab = apps.get_model("snpdb", "Lab")
    for lab in Lab.objects.filter(upload_location__isnull=False):
        if upload_location := lab.upload_location:
            if upload_location.startswith('s3:') and not upload_location.startswith('s3://'):
                lab.upload_location = "s3://" + upload_location[3:]
                lab.save()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0062_columns_change_and_delete'),
    ]

    operations = [
        migrations.RunPython(_one_off_fix_s3_locations)
    ]
