# Generated by Django 4.0.3 on 2022-04-22 07:15

from django.db import migrations


def _update_uniprot(apps, _schema_editor):
    VariantGridColumn = apps.get_model("snpdb", "VariantGridColumn")

    for vgc in VariantGridColumn.objects.filter(variant_column__startswith='variantannotation__uniprot__'):
        new_col = vgc.variant_column.replace("variantannotation__uniprot__",
                                             "variantannotation__transcript_version__gene_version__hgnc__uniprot__")
        vgc.variant_column = new_col
        vgc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0067_lab_upload_automatic_lab_upload_instructions'),
    ]

    operations = [
        migrations.RunPython(_update_uniprot),
    ]
