# Generated by Django 4.0.3 on 2022-05-04 01:09

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0069_clinvarkey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplestats',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplestats',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='samplestatspassingfilter',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplestatspassingfilter',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='SampleStatsCodeVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.TextField()),
                ('version', models.IntegerField()),
                ('code_git_hash', models.TextField()),
            ],
            options={
                'unique_together': {('name', 'version', 'code_git_hash')},
            },
        ),
        migrations.AddField(
            model_name='samplestats',
            name='code_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AddField(
            model_name='samplestatspassingfilter',
            name='code_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
    ]
