# Generated by Django 4.0.2 on 2022-05-09 01:43

from django.db import migrations
from django.db.models import F


def _variant_wiki_column(apps, _schema_editor):
    # This may have been patched back into some environments manually, so needs to be able to be re-run
    VariantGridColumn = apps.get_model("snpdb", "VariantGridColumn")
    CustomColumnsCollection = apps.get_model("snpdb", "CustomColumnsCollection")

    DATABASE_LEVEL = 'D'
    vw_column, created = VariantGridColumn.objects.get_or_create(grid_column_name='variant_wiki',
                                                                 variant_column='variantwiki__markdown',
                                                                 annotation_level=DATABASE_LEVEL,
                                                                 label='Variant Wiki',
                                                                 description='Internal Variant Wiki, edit on variant page.')

    gw_column, created = VariantGridColumn.objects.get_or_create(grid_column_name='gene_symbol_wiki',
                                                                 variant_column='variantannotation__transcript_version__gene_version__gene_symbol__genesymbolwiki__markdown',
                                                                 annotation_level='D',
                                                                 label='Gene Wiki',
                                                                 description='Internal Gene Symbol Wiki, edit on gene symbol page.')

    all_columns = CustomColumnsCollection.objects.get(name="All columns")
    if not all_columns.customcolumn_set.contains(vw_column):
        total_db_het = all_columns.customcolumn_set.get(column='total_db_het')
        after_qs = all_columns.customcolumn_set.filter(sort_order__gt=total_db_het.sort_order)
        after_qs.update(sort_order=F("sort_order") + 2)
        all_columns.customcolumn_set.create(column=vw_column,
                                            sort_order=total_db_het.sort_order+1)

    if not all_columns.customcolumn_set.contains(gw_column):
        gene_description = all_columns.customcolumn_set.get(column='gene_description')
        after_qs = all_columns.customcolumn_set.filter(sort_order__gt=gene_description.sort_order)
        after_qs.update(sort_order=F("sort_order") + 2)
        all_columns.customcolumn_set.create(column=gw_column,
                                            sort_order=gene_description.sort_order+1)


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0071_alter_samplestats_code_version_and_more'),
    ]

    operations = [
        migrations.RunPython(_variant_wiki_column)
    ]
