# Generated by Django 4.0.2 on 2022-07-18 06:34

from django.db import migrations


def _one_off_move_bam_files_to_own_model(apps, _schema_editor):
    Sample = apps.get_model("snpdb", "Sample")
    SampleFilePath = apps.get_model("snpdb", "SampleFilePath")

    BAM_FILE = 'B'
    records = []
    sample_qs = Sample.objects.filter(bam_file_path__isnull=False).exclude(bam_file_path='')
    for sample_id, bam_file_path in sample_qs.values_list("pk", "bam_file_path"):
        sfp = SampleFilePath(sample_id=sample_id, file_path=bam_file_path, file_type=BAM_FILE)
        records.append(sfp)

    if records:
        SampleFilePath.objects.bulk_create(records, batch_size=2000)


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0075_samplefilepath'),
    ]

    operations = [
        migrations.RunPython(_one_off_move_bam_files_to_own_model),
    ]
