# Generated by Django 4.0.2 on 2022-07-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0076_one_off_move_bam_files_to_own_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='bam_file_path',
        ),
        migrations.AlterField(
            model_name='samplefilepath',
            name='file_path',
            field=models.TextField(),
        ),
    ]
