# Generated by Django 4.0.4 on 2022-07-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0077_remove_sample_bam_file_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcf',
            options={'verbose_name': 'VCF', 'verbose_name_plural': 'VCFs'},
        ),
    ]
