# Generated by Django 4.0.7 on 2022-09-02 07:16

from django.db import migrations


def _grid_column_descriptions_update(apps, schema_editor):
    VariantGridColumn = apps.get_model("snpdb", "VariantGridColumn")

    NEW_DESCRIPTIONS = {
        'dbsnp_rs_id': '<a href="https://www.ncbi.nlm.nih.gov/snp/">dbSNP</a> ID',
        'phylop_30_way_mammalian': 'phyloP (phylogenetic p-values) conservation score based on the multiple alignments of 30 mammalian genomes (including human). The larger the score, the more conserved the site. Scores range from -20 to 1.312.',
        'gene_indispensability_score': 'Probability prediction of the gene being essential. From doi:10.1371/journal.pcbi.1002886',
        'gene_indispensability_pred': 'From Gene Indispensability Score, True = Essential, False = LoF tolerant. From doi:10.1371/journal.pcbi.1002886',
        'go_biological_process': 'Gene Ontology terms for biological process',
        'go_cellular_component': 'Gene Ontology terms for cellular component',
        'go_molecular_function': 'Gene Ontology terms for molecular function',
    }

    records = []
    for vgc in VariantGridColumn.objects.filter(pk__in=NEW_DESCRIPTIONS.keys()):
        vgc.description = NEW_DESCRIPTIONS[vgc.pk]
        records.append(vgc)

    if records:
        VariantGridColumn.objects.bulk_update(records, ["description"])


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0081_new_dbnsfp_gene_columns'),
    ]

    operations = [
        migrations.RunPython(_grid_column_descriptions_update),
    ]
