# Generated by Django 4.0.7 on 2022-10-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0082_grid_column_descriptions_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarkey',
            name='citations_mode',
            field=models.TextField(choices=[('all', 'All'), ('interpret', 'Interpretation Summary Only')], default='all'),
        ),
    ]
