# Generated by Django 4.0.7 on 2022-10-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0083_clinvarkey_citations_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsoverride',
            name='timezone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
