# Generated by Django 4.0.7 on 2022-11-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0084_settingsoverride_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='consolidates_variant_classifications',
            field=models.BooleanField(default=False),
        ),
    ]
