# Generated by Django 4.1.3 on 2022-11-29 05:12

from django.db import migrations

def _update_spliceai_columns(apps, _schema_editor):
    VariantGridColumn = apps.get_model("snpdb", "VariantGridColumn")
    COLUMN_DESCRIPTIONS = {
        'variantannotation__spliceai_pred_dp_ag': "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta position for Acceptor Gain. Data includes all possible substitutions (snv), 1 base insertions and 1-4 base deletions (indel) within genes. <b>Warning: Larger indels that may affect splicing are not reported</b>",
        'variantannotation__spliceai_pred_dp_al': "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta position for Acceptor Loss. Data includes all possible substitutions (snv), 1 base insertions and 1-4 base deletions (indel) within genes. <b>Warning: Larger indels that may affect splicing are not reported</b>",
        'variantannotation__spliceai_pred_dp_dg': "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta position for Donor Gain. Data includes all possible substitutions (snv), 1 base insertions and 1-4 base deletions (indel) within genes. <b>Warning: Larger indels that may affect splicing are not reported</b>",
        'variantannotation__spliceai_pred_dp_dl': "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta position for Donor Loss. Data includes all possible substitutions (snv), 1 base insertions and 1-4 base deletions (indel) within genes. <b>Warning: Larger indels that may affect splicing are not reported</b>",
        'variantannotation__spliceai_pred_ds_ag': "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta score for Acceptor Gain. Data includes all possible substitutions (snv), 1 base insertions and 1-4 base deletions (indel) within genes. <b>Warning: Larger indels that may affect splicing are not reported</b>",
        'variantannotation__spliceai_pred_ds_al': "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta score for Acceptor Loss. Data includes all possible substitutions (snv), 1 base insertions and 1-4 base deletions (indel) within genes. <b>Warning: Larger indels that may affect splicing are not reported</b>",
        'variantannotation__spliceai_pred_ds_dg': "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta score for Donor Gain. Data includes all possible substitutions (snv), 1 base insertions and 1-4 base deletions (indel) within genes. <b>Warning: Larger indels that may affect splicing are not reported</b>",
        'variantannotation__spliceai_pred_ds_dl': "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> delta score for Donor Loss. Data includes all possible substitutions (snv), 1 base insertions and 1-4 base deletions (indel) within genes. <b>Warning: Larger indels that may affect splicing are not reported</b>",
        'variantannotation__spliceai_gene_symbol': "<a href='https://pubmed.ncbi.nlm.nih.gov/30661751/'>SpliceAI</a> Gene Symbol. Data includes all possible substitutions (snv), 1 base insertions and 1-4 base deletions (indel) within genes. <b>Warning: Larger indels that may affect splicing are not reported</b>",
    }
    records = []
    for vgc in VariantGridColumn.objects.filter(variant_column__in=COLUMN_DESCRIPTIONS.keys()):
        vgc.description = COLUMN_DESCRIPTIONS[vgc.variant_column]
        records.append(vgc)
    if records:
        print(f"SpliceAI columns: Updating description for {len(records)} columns")
        VariantGridColumn.objects.bulk_update(records, ["description"])


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0085_lab_consolidates_variant_classifications'),
    ]

    operations = [
        migrations.RunPython(_update_spliceai_columns)
    ]
