# Generated by Django 4.0.7 on 2022-11-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0085_lab_consolidates_variant_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarkey',
            name='assertion_method_resolution',
            field=models.JSONField(default=dict),
        ),
    ]
