# Generated by Django 4.0.7 on 2022-12-15 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0086_update_spliceai_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeBuildPatchVersion',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('patch_version', models.IntegerField(blank=True, null=True)),
                ('genome_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.genomebuild')),
            ],
            options={
                'unique_together': {('genome_build', 'patch_version')},
            },
        ),
    ]
