# Generated by Django 4.1.3 on 2022-12-20 23:53

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models

import library.django_utils.guardian_permissions_mixin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snpdb', '0087_genomebuildpatchversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsoverride',
            name='default_genome_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.genomebuild'),
        ),
        migrations.CreateModel(
            name='TagColorsCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.TextField()),
                ('version_id', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(library.django_utils.guardian_permissions_mixin.GuardianPermissionsAutoInitialSaveMixin, models.Model),
        ),
        migrations.AddField(
            model_name='settingsoverride',
            name='tag_colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.tagcolorscollection'),
        ),
        migrations.AddField(
            model_name='usertagcolors',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.tagcolorscollection'),
        ),
    ]
