# Generated by Django 4.1.3 on 2022-12-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0089_one_off_user_tag_colors_to_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertagcolors',
            name='user',
        ),
    ]
