# Generated by Django 4.1.3 on 2022-12-21 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0090_remove_usertagcolors_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTagColors',
            new_name='TagColor',
        ),
    ]
