# Generated by Django 4.1.3 on 2022-12-21 04:40

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0091_rename_usertagcolors_tagcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcolor',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagcolor',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterUniqueTogether(
            name='tagcolor',
            unique_together={('collection', 'tag')},
        ),
    ]
