# Generated by Django 4.1.5 on 2023-02-14 05:52

from django.db import migrations


def _change_omim_id_label(apps, _schema_editor):
    VariantGridColumn = apps.get_model("snpdb", "VariantGridColumn")
    vgc_qs = VariantGridColumn.objects.filter(pk='omim_id')
    vgc_qs.update(label="OMIM gene IDs")


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0092_tagcolor_created_tagcolor_modified_and_more'),
    ]

    operations = [
        migrations.RunPython(_change_omim_id_label),
    ]
