# Generated by Django 4.1.3 on 2023-03-30 00:55
import logging

from django.db import migrations, ProgrammingError
from django.db.models import Max

from library.utils.database_utils import run_sql


def _one_off_remove_duplicate_cohort_genotype_collections(apps, _schema_editor):
    CohortGenotypeCollection = apps.get_model("snpdb", "CohortGenotypeCollection")
    newest_qs = CohortGenotypeCollection.objects.values("cohort", "cohort_version").annotate(latest_id=Max('id'))
    for cgc in CohortGenotypeCollection.objects.exclude(pk__in=newest_qs.values_list("latest_id")):
        print(f"Removing dupe CGC for : {cgc.cohort}/{cgc.cohort_version}")
        try:
            sql = f"DROP TABLE snpdb_cohortgenotype_collection_{cgc.pk}"
            run_sql(sql)
            cgc.delete()
        except ProgrammingError as pe:
            logging.warning(pe)


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0094_change_variantgridcolumn_annotation_levels'),
    ]

    operations = [
        migrations.RunPython(_one_off_remove_duplicate_cohort_genotype_collections)
    ]
