# Generated by Django 4.1.3 on 2023-03-30 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0095_one_off_remove_duplicate_cohort_genotype_collections'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cohortgenotypecollection',
            unique_together={('cohort', 'cohort_version')},
        ),
    ]
