# Generated by Django 4.1.3 on 2023-04-03 06:54

from django.db import migrations
from django.db.models import F

from library.django_utils import bulk_insert_class_data


def _new_column_internally_classified_labs(apps, _schema_editor):
    VARIANT_GRID_COLUMN = [
        {'grid_column_name': 'internally_classified_labs',
         'variant_column': 'internally_classified_labs',
         'annotation_level': 'D',
         'width': None,
         'label': 'Internal classification Labs',
         'description': "Internal classification Labs, joined by '|'",
         'model_field': False,
         'queryset_field': False},
    ]
    bulk_insert_class_data(apps, "snpdb", [("VariantGridColumn", VARIANT_GRID_COLUMN)])


def _custom_columns_for_new_internally_classified_labs(apps, _schema_editor):
    CustomColumnsCollection = apps.get_model("snpdb", "CustomColumnsCollection")
    CustomColumn = apps.get_model("snpdb", "CustomColumn")

    all_columns = CustomColumnsCollection.objects.get(name='All columns')
    internally_classified_col = all_columns.customcolumn_set.get(column_id='internally_classified')
    after_qs = all_columns.customcolumn_set.filter(sort_order__gt=internally_classified_col.sort_order)
    after_qs.update(sort_order=F("sort_order") + 1)
    CustomColumn.objects.create(custom_columns_collection=all_columns,
                                sort_order=internally_classified_col.sort_order + 1,
                                column_id='internally_classified_labs')

    # This was forgotten for some reason



class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0096_alter_cohortgenotypecollection_unique_together'),
    ]

    operations = [
        migrations.RunPython(_new_column_internally_classified_labs),
        migrations.RunPython(_custom_columns_for_new_internally_classified_labs),
    ]
