# Generated by Django 4.1.4 on 2023-04-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0097_new_column_internally_classified_labs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortgenotype',
            name='format',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cohortgenotype',
            name='info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='variant',
            name='end',
            field=models.IntegerField(null=True),
        ),
    ]
