# Generated by Django 4.2.2 on 2023-07-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0098_columns_collections_add_internally_classified_labs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cohortgenotype',
            name='format',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cohortgenotype',
            name='info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='variant',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vcf',
            name='genotype_field',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('locus', 'alt', 'end')},
        ),
    ]
