# Generated by Django 4.1.4 on 2023-04-26 01:23

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _variants_missing_end(apps):
    Variant = apps.get_model("snpdb", "Variant")
    return Variant.objects.filter(end__isnull=True).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0098_cohortgenotype_format_cohortgenotype_info_and_more'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["one_off_calc_variant_end"]),
                        test=_variants_missing_end),
    ]
