# Generated by Django 4.2.2 on 2023-08-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0099_alter_variant_unique_together_cohortgenotype_format_and_more'),
    ]

    # Variant.end is populated by 'one_off_fix_variant_end' (surfaced in 0118/0141, once svlen
    # exists) and enforced NOT NULL in 0198_alter_variant_end_not_null after it has been calculated.
    operations = []
