# Generated by Django 4.2.2 on 2023-07-28 01:18

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _variants_missing_end(apps):
    Variant = apps.get_model("snpdb", "Variant")
    return Variant.objects.filter(end__isnull=True).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0099_alter_variant_unique_together_cohortgenotype_format_and_more'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["one_off_calc_variant_end"]),
                        test=_variants_missing_end),
    ]
