# Generated by Django 4.1.4 on 2023-04-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0099_one_off_calc_variant_start_end'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('locus', 'alt', 'end')},
        ),
    ]
