# Generated by Django 4.1.3 on 2023-05-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0100_alter_variant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcf',
            name='genotype_field',
            field=models.TextField(null=True),
        ),
    ]
