# Generated by Django 4.1.4 on 2023-09-12 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0099_alter_genomebuild_options"),
        ("snpdb", "0100_one_off_calc_variant_end"),
    ]

    operations = []
