# Generated by Django 4.2.2 on 2023-09-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0101_merge_20230912_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allele',
            options={'base_manager_name': 'objects'},
        ),
    ]
