# Generated by Django 4.2.2 on 2023-09-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0102_alter_allele_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'default_manager_name': 'objects', 'ordering': ['name'], 'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
    ]
