# Generated by Django 4.1.4 on 2023-10-02 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0104_alter_settingsoverride_columns_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settingsoverride",
            name="default_genome_build",
            field=models.ForeignKey(
                blank=True,
                help_text="Used for search (jump to result if that is the only one for this build) and populating defaults everywhere",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="snpdb.genomebuild",
            ),
        ),
        migrations.AlterField(
            model_name="settingsoverride",
            name="default_sort_by_column",
            field=models.ForeignKey(
                blank=True,
                help_text="Default value to sort analysis grids (can be changed per analysis)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="snpdb.customcolumn",
            ),
        ),
        migrations.AlterField(
            model_name="settingsoverride",
            name="tag_colors",
            field=models.ForeignKey(
                blank=True,
                help_text="Set of colors assigned to tags (modify/create these in 'Tag settings')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="snpdb.tagcolorscollection",
            ),
        ),
        migrations.AlterField(
            model_name="settingsoverride",
            name="variant_link_in_analysis_opens_new_tab",
            field=models.BooleanField(
                help_text="Whether left click by default opens up variant details in new tab. No is to open details in the node editor location. It's always possible to right click and select 'open in new tab'",
                null=True,
            ),
        ),
    ]
