# Generated by Django 4.2.5 on 2023-10-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0105_alter_settingsoverride_default_genome_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsoverride',
            name='default_allele_origin',
            field=models.CharField(blank=True, choices=[('A', 'All'), ('G', 'Germline'), ('S', 'Somatic')], help_text='Automatically filters most pages to default filter to germline or somatic if either of those options are chosen', max_length=1, null=True),
        ),
    ]
