# Generated by Django 4.2.2 on 2023-11-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0105_alter_settingsoverride_default_genome_build_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allelemergelog',
            name='allele_linking_tool',
            field=models.CharField(choices=[('SC', 'Identical Contig/Version'), ('CA', 'ClinGen Allele Registry'), ('DB', 'dbSNP API'), ('NR', 'NCBI Remap'), ('PC', 'Picard LiftoverVCF'), ('CM', 'CrossMap')], max_length=2),
        ),
        migrations.AlterField(
            model_name='liftover',
            name='conversion_tool',
            field=models.CharField(choices=[('SC', 'Identical Contig/Version'), ('CA', 'ClinGen Allele Registry'), ('DB', 'dbSNP API'), ('NR', 'NCBI Remap'), ('PC', 'Picard LiftoverVCF'), ('CM', 'CrossMap')], max_length=2),
        ),
        migrations.AlterField(
            model_name='variantallele',
            name='allele_linking_tool',
            field=models.CharField(choices=[('SC', 'Identical Contig/Version'), ('CA', 'ClinGen Allele Registry'), ('DB', 'dbSNP API'), ('NR', 'NCBI Remap'), ('PC', 'Picard LiftoverVCF'), ('CM', 'CrossMap')], max_length=2),
        ),
    ]
