# Generated by Django 4.2.5 on 2023-11-08 02:53

from django.db import migrations

def _set_global_default(apps, schema):
    GlobalSettings = apps.get_model("snpdb", "GlobalSettings")
    global_settings = GlobalSettings.objects.get()
    global_settings.default_allele_origin = "A"
    global_settings.save()


def _reverse(apps, schema):
    GlobalSettings = apps.get_model("snpdb", "GlobalSettings")
    global_settings = GlobalSettings.objects.get()
    global_settings.default_allele_origin = None
    global_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0106_settingsoverride_default_allele_origin'),
    ]

    operations = [
        migrations.RunPython(_set_global_default, _reverse)
    ]
