# Generated by Django 4.2.2 on 2023-12-05 05:55

from django.db import migrations


def _one_off_move_alphamissense_dbnsfp(apps, _schema_editor):
    # Getting rid of alphamissense_pathogenicity to replace with alphamissense_rankscore

    ANNOTATION_LEVEL = 'A'

    VariantGridColumn = apps.get_model("snpdb", "VariantGridColumn")
    ColumnVCFInfo = apps.get_model("snpdb", "ColumnVCFInfo")

    VariantGridColumn.objects.filter(pk__in=['alphamissense_pathogenicity', 'alphamissense_class']).delete()

    alphamissense_rankscore = VariantGridColumn.objects.create(grid_column_name='alphamissense_rankscore',
                                                               variant_column='variantannotation__alphamissense_rankscore',
                                                               annotation_level=ANNOTATION_LEVEL,
                                                               width=None,
                                                               label='AlphaMissense RankScore',
                                                               model_field=True,
                                                               queryset_field=True)

    ColumnVCFInfo.objects.create(info_id='ALPHAMISSENSE_rankscore',
                                 column=alphamissense_rankscore,
                                 number=1,
                                 type='F',
                                 description='AlphaMissense pathogenicity rank score')


class Migration(migrations.Migration):
    dependencies = [
        ('annotation', '0082_new_vep_110_columns_v3'),
        ('snpdb', '0107_new_vep_110_columns_v3'),
    ]

    operations = [
        migrations.RunPython(_one_off_move_alphamissense_dbnsfp)
    ]
