# Generated by Django 4.2.5 on 2023-12-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0108_one_off_move_alphamissense_dbnsfp'),
        ('snpdb', '0109_useraward_award_level'),
    ]

    operations = [
    ]
