# Generated by Django 4.2.5 on 2024-01-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0110_merge_20231212_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsoverride',
            name='default_allele_origin',
        ),
        migrations.AddField(
            model_name='settingsoverride',
            name='allele_origin_exclude_filter',
            field=models.BooleanField(blank=True, help_text='Should records not for your allele origin focus be excluded out by default', null=True),
        ),
        migrations.AddField(
            model_name='settingsoverride',
            name='allele_origin_focus',
            field=models.CharField(blank=True, choices=[('G', 'Germline'), ('S', 'Somatic')], help_text='Your primary focus when it comes to allele origin', max_length=1, null=True),
        ),
    ]
