# Generated by Django 4.2.5 on 2024-01-16 05:28

from django.db import migrations


def _set_global_default(apps, _schema):
    GlobalSettings = apps.get_model("snpdb", "GlobalSettings")
    global_settings = GlobalSettings.objects.get()
    global_settings.allele_origin_focus = "G"
    global_settings.allele_origin_exclude_filter = False
    global_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0111_remove_settingsoverride_default_allele_origin_and_more'),
    ]

    operations = [
        migrations.RunPython(_set_global_default)
    ]
