# Generated by Django 4.2.5 on 2024-01-23 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0109_custom_columns_for_new_vep_110_columns_v3'),
        ('snpdb', '0112_settingsoverride_default_allele_origin_germline'),
    ]

    operations = [
    ]
