# Generated by Django 4.2.9 on 2024-02-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0113_merge_20240124_0956'),
    ]

    # Variant.end stays nullable here - it is calculated later by 'one_off_fix_variant_end' and
    # enforced NOT NULL in 0198_alter_variant_end_not_null (once svlen exists so end computes correctly).
    operations = []
