# Generated by Django 4.2.9 on 2024-02-12 05:27

from django.db import migrations, models


def _variant_end_message(apps, _schema_editor):
    print("If this migration fails, you need to have run 'one_off_calc_variant_end' - this existed in the commit before this migration/schema change 6a0b1f112f338fe4aa96fa2775bcb5e9f933c883")



class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0113_merge_20240124_0956'),
    ]

    operations = [
        migrations.RunPython(_variant_end_message),
        migrations.AlterField(
            model_name='variant',
            name='end',
            field=models.IntegerField(),
        ),
    ]
