# Generated by Django 4.2.9 on 2024-02-19 02:55

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _existing_deploy_has_variants(apps):
    Variant = apps.get_model("snpdb", "Variant")
    return Variant.objects.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0117_one_off_inv_symbolic'),
    ]

    operations = [
        ManualOperation.operation_other(args=["Run 'python3 manage.py one_off_fix_variant_end' - this can be done outside of migrations (use screen)"],
                                        test=_existing_deploy_has_variants),
    ]
