# Generated by Django 4.2.9 on 2024-02-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0117_one_off_inv_symbolic'),
    ]

    # The free text reminder registered here was retired in manual/0004_complete_obsolete_manual_tasks -
    # one_off_fix_variant_end is a real manage task in 0141_one_off_fix_variant_end2.
    operations = []
