# Generated by Django 4.2.9 on 2024-02-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0118_reminder_one_off_fix_variant_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='length',
        ),
    ]
