# Generated by Django 4.2.9 on 2024-03-05 23:02

from django.conf import settings
from django.db import migrations
from django.db.models import Q
from django.db.models.functions import Length

from manual.operations.manual_operations import ManualOperation

# The command pre-filters on 1000bp, then only converts what as_internal_symbolic() (which uses
# VARIANT_SYMBOLIC_ALT_SIZE) makes symbolic - so it only does anything at the larger of the two
_MIN_CONVERTED_SIZE = max(1000, settings.VARIANT_SYMBOLIC_ALT_SIZE)


def _test_for_unconverted_long_explicit_variants(apps):
    """ Long variants still stored explicitly - a legacy deployment upgrading to symbolic alts has these,
        but has never had a symbolic <DEL>/<DUP> so the corruption checks below don't fire """
    if not settings.VARIANT_SYMBOLIC_ALT_ENABLED:
        return False

    Sequence = apps.get_model("snpdb", "Sequence")
    Variant = apps.get_model("snpdb", "Variant")

    long_sequences = Sequence.objects.annotate(seq_length=Length("seq")).filter(seq_length__gte=_MIN_CONVERTED_SIZE)
    qs = Variant.objects.filter(Q(locus__ref__in=long_sequences) | Q(alt__in=long_sequences), svlen__isnull=True)
    return qs.exists()


def _test_needs_symbolic_variant_fix(apps):
    Variant = apps.get_model("snpdb", "Variant")
    ClinVar = apps.get_model("annotation", "ClinVar")

    qs = Variant.objects.filter(alt__seq__startswith='<').annotate(rlen=Length("locus__ref__seq")).filter(rlen__gt=1)
    if qs.exists():
        return True

    genome_build_name = 'GRCh37'
    alt_seq = '<DUP>'

    qs = ClinVar.objects.filter(version__genome_build__name=genome_build_name, variant__alt__seq=alt_seq)
    clinvar_variation_del = list(qs.values_list("clinvar_variation_id", flat=True))
    diff_representation = ClinVar.objects.filter(version__genome_build__name=genome_build_name,
                                                 clinvar_variation_id__in=clinvar_variation_del).exclude(variant__alt__seq=alt_seq)
    if diff_representation.exists():
        return True

    return _test_for_unconverted_long_explicit_variants(apps)  # Last as it scans Sequence/Variant


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0119_remove_sequence_length'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["one_off_fix_symbolic_variants"]),
                        test=_test_needs_symbolic_variant_fix),
    ]
