# Generated by Django 4.2.9 on 2024-03-05 23:02

from django.conf import settings
from django.db import migrations
from django.db.models import Q
from django.db.models.functions import Length

from manual.operations.manual_operations import ManualOperation

# one_off_fix_symbolic_variants pre-filters candidates on sequences >= 1000bp, then only converts the
# ones as_internal_symbolic() makes symbolic - which applies settings.VARIANT_SYMBOLIC_ALT_SIZE. So the
# size at which the command actually does something is the larger of the two.
_MIN_CONVERTED_SIZE = max(1000, settings.VARIANT_SYMBOLIC_ALT_SIZE)


def _test_for_unconverted_long_explicit_variants(apps):
    """ Long variants still stored explicitly (ref or alt sequence long enough that as_internal_symbolic
        would make them <DEL>/<DUP>/<INV>). Mirrors the command's own long_variants query.

        This is the case a legacy deployment upgrading straight to symbolic-alt support lands in: it has
        never held a symbolic <DEL>/<DUP>, so neither corruption check below fires, yet every long variant
        it holds needs converting. """
    if not settings.VARIANT_SYMBOLIC_ALT_ENABLED:
        # Symbolic storage is off - converting would be wrong, and VariantCoordinate rejects a set svlen
        return False

    Sequence = apps.get_model("snpdb", "Sequence")
    Variant = apps.get_model("snpdb", "Variant")

    long_sequences = Sequence.objects.annotate(seq_length=Length("seq")).filter(seq_length__gte=_MIN_CONVERTED_SIZE)
    # svlen__isnull=True -> already-symbolic variants are the other checks' business, not this one
    qs = Variant.objects.filter(Q(locus__ref__in=long_sequences) | Q(alt__in=long_sequences), svlen__isnull=True)
    return qs.exists()


def _test_needs_symbolic_variant_fix(apps):
    Variant = apps.get_model("snpdb", "Variant")
    ClinVar = apps.get_model("annotation", "ClinVar")

    qs = Variant.objects.filter(alt__seq__startswith='<').annotate(rlen=Length("locus__ref__seq")).filter(rlen__gt=1)
    if qs.exists():
        return True

    genome_build_name = 'GRCh37'
    alt_seq = '<DUP>'

    qs = ClinVar.objects.filter(version__genome_build__name=genome_build_name, variant__alt__seq=alt_seq)
    clinvar_variation_del = list(qs.values_list("clinvar_variation_id", flat=True))
    diff_representation = ClinVar.objects.filter(version__genome_build__name=genome_build_name,
                                                 clinvar_variation_id__in=clinvar_variation_del).exclude(variant__alt__seq=alt_seq)
    if diff_representation.exists():
        return True

    # Last as it scans Sequence/Variant - the cheap corruption checks above short-circuit it
    return _test_for_unconverted_long_explicit_variants(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0119_remove_sequence_length'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["one_off_fix_symbolic_variants"]),
                        test=_test_needs_symbolic_variant_fix),
    ]
