# Generated by Django 4.2.5 on 2024-04-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0122_new_gnomad_sv_overlap_column_vep_fields2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsoverride',
            name='allele_origin_exclude_filter',
            field=models.BooleanField(blank=True, help_text='Would you like to automatically filter classifications based on your selected Allele Origin focus?', null=True),
        ),
        migrations.AlterField(
            model_name='settingsoverride',
            name='allele_origin_focus',
            field=models.CharField(blank=True, choices=[('A', 'All'), ('G', 'Germline'), ('S', 'Somatic')], help_text='Your primary focus when it comes to allele origin', max_length=1, null=True),
        ),
    ]
