# Generated by Django 4.2.5 on 2024-04-04 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0123_alter_settingsoverride_allele_origin_exclude_filter_and_more'),
        ('snpdb', '0124_alter_variant_svlen'),
    ]

    operations = [
    ]
