# Generated by Django 4.2.10 on 2024-04-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0125_merge_20240404_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allelemergelog',
            name='allele_linking_tool',
            field=models.CharField(choices=[('SC', 'Identical Contig/Version'), ('CA', 'ClinGen Allele Registry'), ('DB', 'dbSNP API'), ('NR', 'NCBI Remap'), ('PC', 'Picard LiftoverVCF'), ('CM', 'CrossMap'), ('BL', 'BCFtools/liftover')], max_length=2),
        ),
        migrations.AlterField(
            model_name='liftover',
            name='conversion_tool',
            field=models.CharField(choices=[('SC', 'Identical Contig/Version'), ('CA', 'ClinGen Allele Registry'), ('DB', 'dbSNP API'), ('NR', 'NCBI Remap'), ('PC', 'Picard LiftoverVCF'), ('CM', 'CrossMap'), ('BL', 'BCFtools/liftover')], max_length=2),
        ),
        migrations.AlterField(
            model_name='variantallele',
            name='allele_linking_tool',
            field=models.CharField(choices=[('SC', 'Identical Contig/Version'), ('CA', 'ClinGen Allele Registry'), ('DB', 'dbSNP API'), ('NR', 'NCBI Remap'), ('PC', 'Picard LiftoverVCF'), ('CM', 'CrossMap'), ('BL', 'BCFtools/liftover')], max_length=2),
        ),
    ]
