# Generated by Django 4.2.2 on 2024-04-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0126_alter_allelemergelog_allele_linking_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarkey',
            name='include_interpretation_summary',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
