# Generated by Django 4.2.10 on 2024-04-18 01:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("upload", "0017_alter_uploadedclinvarversion_clinvar_version"),
        ("snpdb", "0127_clinvarkey_include_interpretation_summary"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LiftoverError",
            new_name="AlleleLiftover",
        ),
        migrations.RenameModel(
            old_name="Liftover",
            new_name="LiftoverRun",
        ),
    ]
