# Generated by Django 4.2.10 on 2024-04-18 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0128_rename_liftovererror_alleleliftover_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variantallele",
            old_name="error",
            new_name="clingen_error",
        ),
        migrations.RemoveField(
            model_name="alleleliftover",
            name="variant",
        ),
        migrations.AddField(
            model_name="alleleliftover",
            name="error",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="alleleliftover",
            name="status",
            field=models.CharField(
                choices=[
                    ("C", "Created"),
                    ("P", "Processing"),
                    ("E", "Error"),
                    ("S", "Success"),
                    ("K", "Skipped"),
                    ("T", "Terminated Early"),
                    ("Z", "Timed Out"),
                ],
                default="C",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="alleleliftover",
            name="variant_allele",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="snpdb.variantallele",
            ),
        ),
        migrations.AlterField(
            model_name="liftoverrun",
            name="allele_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="snpdb.allelesource",
            ),
        ),
    ]
