# Generated by Django 4.2.10 on 2024-04-18 03:42

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _one_off_allele_liftover(apps, schema_editor):
    AlleleLiftover = apps.get_model("snpdb", "AlleleLiftover")
    VariantAllele = apps.get_model("snpdb", "VariantAllele")

    records = []
    for al in AlleleLiftover.objects.filter(error_message__isnull=False):
        al.error = {"message": al.error_message}
        records.append(al)

    PROCESSING_STATUS_ERROR = 'E'

    AlleleLiftover.objects.bulk_update(records, fields=["error"], batch_size=1024)
    # Any existing ones were once error, so set to be error
    AlleleLiftover.objects.all().update(status=PROCESSING_STATUS_ERROR)

    # We need to represent a "failed clingen" LiftoverRun - just make 1 and link all fails we don't actually run
    # To that

    # Or should we create a new FailedClinGen liftover run all the time? But we don't want to run it...

    clingen_failures = []
    for va in VariantAllele.objects.filter(clingen_error__isnull=False):
        try:
            other_va = VariantAllele.objects.filter(allele=va.allele).exclude(pk=va.pk).get()
            al = AlleleLiftover()
        except VariantAllele.DoesNotExist:
            pass


    # For every VariantAllele that has a clingen error - we couldn't use that for liftover to another build



def _has_allele_and_liftover(apps):
    Allele = apps.get_model("snpdb", "Allele")
    Liftover = apps.get_model("snpdb", "Liftover")
    return Allele.objects.exists() and Liftover.objects.exists()


class Migration(migrations.Migration):
    """ AlleleLiftover (formerly LiftoverError) - move text field to JSON """
    dependencies = [
        ("snpdb", "0129_rename_error_variantallele_clingen_error_and_more"),
    ]

    operations = [
        migrations.RunPython(_one_off_allele_liftover),
        ManualOperation(task_id=ManualOperation.task_id_manage(["one_off_legacy_populate_allele_liftover"]),
                        test=_has_allele_and_liftover),

    ]
