# Generated by Django 4.2.10 on 2024-05-08 01:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0130_one_off_legacy_populate_allele_liftover'),
    ]

    operations = [
        # This has been replaced by annotation_files_check
    ]
