# Generated by Django 4.2.10 on 2024-05-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0131_download_liftover_chain_files'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cohortgenotypecollection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cohortgenotypecollection',
            name='collection_type',
            field=models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon')], default='U', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='cohortgenotypecollection',
            unique_together={('cohort', 'cohort_version', 'collection_type')},
        ),
    ]
