# Generated by Django 4.2.10 on 2024-05-20 01:39

from django.db import migrations
from django.db.models import Subquery, OuterRef


def _one_off_set_cgc_common(apps, _schema_editor):
    CohortGenotypeCollection = apps.get_model("snpdb", "CohortGenotypeCollection")
    Cohort = apps.get_model("snpdb", "Cohort")

    CGC_COMMON = "C"

    # To avoid the unique_together (cohort/version) the common ones were left as 0
    cgc_qs = CohortGenotypeCollection.objects.filter(common_filter__isnull=False, cohort_version=0)
    cohort_version_subquery = Subquery(Cohort.objects.filter(id=OuterRef('cohort_id')).values('version')[:1])
    cgc_qs.update(collection_type=CGC_COMMON, cohort_version=cohort_version_subquery)


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0132_alter_cohortgenotypecollection_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(_one_off_set_cgc_common, reverse_code=lambda _, __: None),
    ]
