# Generated by Django 4.2.11 on 2024-06-19 07:24
import logging
import os

from django.db import migrations


def _delete_cached_generated_graphs(apps, _schema_editor):
    CachedGeneratedFile = apps.get_model("snpdb", "CachedGeneratedFile")

    num_deleted_files = 0
    num_deleted_records = 0
    for cgg in CachedGeneratedFile.objects.all():
        if cgg.filename and os.path.exists(cgg.filename):
            num_deleted_files += 1
            os.remove(cgg.filename)
        cgg.delete()
        num_deleted_records += 1

    if num_deleted_records:
        logging.info("CachedGeneratedFile - obsolete due to hash change: deleted %d records (%d files)",
                     num_deleted_records, num_deleted_files)


class Migration(migrations.Migration):
    """ We're changing the hash on these to use sha256 sum so old ones will no longer be retrieved,
        so may as well delete them """

    dependencies = [
        ("snpdb", "0134_one_off_delete_bad_post_success_allele_liftovers"),
    ]

    operations = [
        migrations.RunPython(_delete_cached_generated_graphs)
    ]
