# Generated by Django 4.2.10 on 2024-06-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0135_delete_cached_generated_graphs'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomefasta',
            name='index_sha256sum',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='seq_sha256_hash',
            field=models.TextField(null=True, unique=True),
        ),
    ]
