# Generated by Django 4.2.10 on 2024-06-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0137_md5_to_sha256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genomefasta',
            name='index_md5sum',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='seq_md5_hash',
        ),
        migrations.AlterField(
            model_name='genomefasta',
            name='index_sha256sum',
            field=models.TextField(),
        ),
    ]
