# Generated by Django 4.2.10 on 2024-07-04 03:52
import logging

from django.db import migrations

def _one_off_look_for_bcftools_norm_symbolic_del_issue_1014(apps, schema_editor):
    Variant = apps.get_model("snpdb", "Variant")

    bad_norm = Variant.objects.filter(modifiedimportedvariant__isnull=False, locus__position=1, svlen__isnull=False)
    if bad_norm.exists():
        logging.warning("You have some badly normalized symbolic del variants. Please delete them, see issue #1014")


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0138_remove_genomefasta_index_md5sum_and_more'),
    ]

    operations = [
        migrations.RunPython(_one_off_look_for_bcftools_norm_symbolic_del_issue_1014)
    ]
