# Generated by Django 4.2.11 on 2024-08-01 02:40
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0139_one_off_look_for_bcftools_norm_symbolic_del_issue_1014"),
    ]

    operations = [
        # Example from:
        # https://docs.djangoproject.com/en/4.2/ref/contrib/postgres/operations/#managing-collations-using-migrations
        CreateCollation(
            name="case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
    ]
