# Generated by Django 4.2.11 on 2024-08-06 10:59

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _existing_deploy_has_variants(apps):
    Variant = apps.get_model("snpdb", "Variant")
    return Variant.objects.exists()


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0140_case_insensitive_collation"),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["one_off_fix_variant_end"]),
                        test=_existing_deploy_has_variants),

    ]
