# Generated by Django 4.2.11 on 2024-08-06 10:59

from django.db import migrations
from django.db.models import F, Q
from django.db.models.functions import Abs, Length

from manual.operations.manual_operations import ManualOperation


def _variants_have_wrong_end(apps):
    """ Only surface the one_off_fix_variant_end task when a variant's end doesn't match the
        formula the command applies: non-symbolic end = position + len(ref) - 1, symbolic
        end = position + abs(svlen). Earlier migrations backfill end directly, so on a deploy
        where that already produced a correct end this is a no-op and the task is skipped. """
    Variant = apps.get_model("snpdb", "Variant")

    non_symbolic_end = F("locus__position") + Length("locus__ref__seq") - 1
    non_symbolic_wrong = Q(svlen__isnull=True) & (Q(end__isnull=True) | ~Q(end=non_symbolic_end))
    if Variant.objects.filter(non_symbolic_wrong).exists():
        return True

    symbolic_end = F("locus__position") + Abs("svlen")
    symbolic_wrong = Q(svlen__isnull=False) & (Q(end__isnull=True) | ~Q(end=symbolic_end))
    return Variant.objects.filter(symbolic_wrong).exists()


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0140_case_insensitive_collation"),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["one_off_fix_variant_end"]),
                        test=_variants_have_wrong_end),
    ]
