# Generated by Django 4.2.9 on 2024-08-07 04:05

from django.db import migrations
from django.db.models import Q

from manual.operations.manual_operations import ManualOperation


def _has_clingen_indels(apps):
    Variant = apps.get_model("snpdb", "Variant")
    variants_with_clingen = Variant.objects.filter(variantallele__allele__clingen_allele__isnull=False)
    bases = "GATC"
    q_snp = Q(locus__ref__seq__in=bases) & Q(alt__seq__in=bases)
    indel_qs = variants_with_clingen.exclude(q_snp)
    return indel_qs.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0141_one_off_fix_variant_end2'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["clingen_allele_linked_variants_reference_base_check"]),
                        test=_has_clingen_indels),
    ]
