# Generated by Django 4.2.11 on 2024-08-09 11:18

from django.db import migrations


def _one_off_rename_clinvar_variantgridcolum(apps, _schema_editor):
    VariantGridColumn = apps.get_model('snpdb', 'VariantGridColumn')

    NEW_VARIANT_COLUMNS = {
        'clinvar_preferred_disease_name': 'clinvar__preferred_disease_name',
        'clinvar_disease_database_name': 'clinvar__disease_database_name',
        'clinvar_review_status': 'clinvar__review_status',
        'clinvar_clinical_sources': 'clinvar__clinical_sources',
        'clinvar_origin': 'clinvar__origin'
    }

    for pk, variant_column in NEW_VARIANT_COLUMNS.items():
        VariantGridColumn.objects.filter(pk=pk).update(variant_column=variant_column)


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0142_one_off_clingen_allele_linked_variants_reference_base_check"),
    ]

    operations = [
        migrations.RunPython(_one_off_rename_clinvar_variantgridcolum),
    ]
