# Generated by Django 4.2.11 on 2024-09-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0145_one_off_handle_renamed_table_inherited_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedgeneratedfile",
            name="progress",
            field=models.FloatField(null=True),
        ),
    ]
