# Generated by Django 4.2.11 on 2024-09-19 04:02

import uuid

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0146_cachedgeneratedfile_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedGeneratedFile2",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.TextField(null=True)),
                ("exception", models.TextField(null=True)),
                ("generator", models.TextField()),
                ("params_hash", models.TextField()),
                ("task_id", models.CharField(max_length=36, null=True)),
                ("task_status", models.TextField(null=True)),
                ("generate_start", models.DateTimeField(null=True)),
                ("generate_end", models.DateTimeField(null=True)),
                ("progress", models.FloatField(null=True)),
            ],
            options={
                "unique_together": {("generator", "params_hash")},
            },
        ),
    ]
