# Generated by Django 4.2.11 on 2024-09-19 04:03

from django.db import migrations


def _one_off_move_cached_generated_files_to_uuid(apps, _schema_editor):
    CachedGeneratedFile = apps.get_model("snpdb", "CachedGeneratedFile")
    CachedGeneratedFile2 = apps.get_model("snpdb", "CachedGeneratedFile2")

    records = []
    for values in CachedGeneratedFile.objects.all().values():
        values.pop("id")  # Want UUID
        cgf2 = CachedGeneratedFile2(**values)
        records.append(cgf2)

    # Don't care about losing some as just a cache anyway.
    CachedGeneratedFile2.objects.bulk_create(records, batch_size=1000, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0147_cachedgeneratedfile2"),
    ]

    operations = [
        migrations.RunPython(_one_off_move_cached_generated_files_to_uuid)
    ]
