# Generated by Django 4.2.11 on 2024-09-19 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0149_delete_cachedgeneratedfile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CachedGeneratedFile2",
            new_name="CachedGeneratedFile",
        ),
    ]
