# Generated by Django 4.2.9 on 2024-11-08 03:57

from django.db import migrations

def _one_off_rename_column_vcf_info(apps, _schema_editor):
    ColumnVCFInfo = apps.get_model('snpdb', 'ColumnVCFInfo')
    # We want to strip out ones that started with ' '
    qs = ColumnVCFInfo.objects.filter(pk__startswith=' ')
    data = list(qs)
    qs.delete()
    for cvi in data:
        cvi.info_id = cvi.info_id.strip()
        cvi.save()


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0152_one_off_bcftools_liftover_bad_ref"),
    ]

    operations = [
        migrations.RunPython(_one_off_rename_column_vcf_info)
    ]
