# Generated by Django 4.2.9 on 2024-12-02 04:46

from django.db import migrations


def _one_off_legacy_mt_contig_ucsc_name(apps, _schema_editor):
    Contig = apps.get_model("snpdb", "Contig")
    Contig.objects.filter(refseq_accession='NC_012920.1').update(ucsc_name='chrM')


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0153_one_off_rename_column_vcf_info"),
    ]

    operations = [
        migrations.RunPython(_one_off_legacy_mt_contig_ucsc_name)
    ]
