# Generated by Django 4.2.9 on 2024-12-03 23:44
from functools import partial

from django.db import migrations

from snpdb.genome.reference_contigs import create_build_and_contigs


def _create_t2t_genome_build_and_contigs(apps, _schema_editor):
    get_model = partial(apps.get_model, "snpdb")
    create_build_and_contigs(get_model, "T2T-CHM13v2.0", alias="T2Tv2", igv_genome="hs1")


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0154_one_off_legacy_mt_contig_ucsc_name"),
    ]

    operations = [
        migrations.RunPython(_create_t2t_genome_build_and_contigs)
    ]
