# Generated by Django 4.2.15 on 2024-12-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0155_create_t2t_genome_build_and_contigs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomebuild',
            name='accession',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genomebuild',
            name='alias',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genomebuild',
            name='enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
