# Generated by Django 4.2.17 on 2025-01-17 04:11

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _check_locus_ref_n(apps):
    Locus = apps.get_model("snpdb", "Locus")
    return Locus.objects.filter(ref__seq='N').exists()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0156_alter_genomebuild_accession_alter_genomebuild_alias_and_more'),
    ]

    operations = [
        # ManualOperation(task_id=ManualOperation.task_id_manage(["fix_locus_ref_n"]),
        #                 test=_check_locus_ref_n)
    ]
