# Generated by Django 4.2.17 on 2025-01-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0157_one_off_fix_locus_ref_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCFInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('number', models.CharField(max_length=10)),
                ('data_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('vcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.vcf')),
            ],
            options={
                'abstract': False,
                'unique_together': {('vcf', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='VCFFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('number', models.CharField(max_length=10)),
                ('data_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('vcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.vcf')),
            ],
            options={
                'abstract': False,
                'unique_together': {('vcf', 'identifier')},
            },
        ),
    ]
