# Generated by Django 4.2.17 on 2025-01-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0158_vcfinfo_vcfformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcfformat',
            name='data_type',
            field=models.CharField(choices=[('I', 'Integer'), ('F', 'Float'), ('B', 'Flag'), ('C', 'Character'), ('S', 'String')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vcfformat',
            name='identifier',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vcfformat',
            name='number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vcfinfo',
            name='data_type',
            field=models.CharField(choices=[('I', 'Integer'), ('F', 'Float'), ('B', 'Flag'), ('C', 'Character'), ('S', 'String')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vcfinfo',
            name='identifier',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vcfinfo',
            name='number',
            field=models.TextField(),
        ),
    ]
