# Generated by Django 4.2.17 on 2025-01-24 04:25

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _check_old_vcf_info_and_format_models(apps):
    from upload.management.commands.fix_vcf_info_and_format_models import Command
    VCF = apps.get_model("snpdb", "VCF")
    _qs_old_version, not_updated_qs = Command.get_historical_vcf_qs_total_and_not_updated(VCF)
    return not_updated_qs.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0159_alter_vcfformat_data_type_alter_vcfformat_identifier_and_more'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_vcf_info_and_format_models"]),
                        test=_check_old_vcf_info_and_format_models)
    ]
