# Generated by Django 4.2.18 on 2025-01-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0160_one_off_fix_vcf_info_and_format_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cohortgenotype',
            unique_together={('collection', 'variant')},
        ),
    ]
