# Generated by Django 4.2.18 on 2025-02-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0162_vcflengthstatscollection_vcflengthstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomebuild',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
