# Generated by Django 4.2.18 on 2025-02-04 05:02

from django.db import migrations
from django.utils.text import slugify


def _one_off_add_genome_build_slug(apps, _schema_editor):
    GenomeBuild = apps.get_model("snpdb", "GenomeBuild")
    for genome_build in GenomeBuild.objects.filter(slug__isnull=True):
        genome_build.slug = slugify(genome_build.name)
        genome_build.save()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0163_genomebuild_slug'),
    ]

    operations = [
        migrations.RunPython(_one_off_add_genome_build_slug)
    ]
