# Generated by Django 4.2.20 on 2025-04-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0165_one_off_allele_liftover_error_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alleleliftover',
            name='error_message',
        ),
        migrations.AddField(
            model_name='alleleliftover',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
