# Generated by Django 4.2.17 on 2025-04-10 02:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0165_one_off_allele_liftover_error_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinVarExportAssertionMethod',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('pattern', models.TextField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('reference_db', models.TextField(blank=True, choices=[('PUBMED', 'PubMed'), ('NCBI_BOOKSHELF', 'BookShelf'), ('PMC', 'pmc')], max_length=20, null=True)),
                ('reference_id', models.TextField(blank=True, null=True)),
                ('reference_url', models.TextField(blank=True, null=True)),
                ('export_type', models.TextField(choices=[('G', 'Germline'), ('O', 'Oncogenic'), ('C', 'Clinical Impact')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinVarExportAssertionMethodMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('order', models.IntegerField(help_text='Lower order is more important')),
                ('pattern', models.TextField()),
                ('assertion_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.clinvarexportassertionmethod')),
                ('clinvar_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.clinvarkey')),
            ],
            options={
                'unique_together': {('clinvar_key', 'order'), ('clinvar_key', 'pattern')},
            },
        ),
    ]
