# Generated by Django 4.2.17 on 2025-04-14 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0166_clinvarexportassertionmethod_and_more'),
        ('snpdb', '0166_remove_alleleliftover_error_message_and_more'),
    ]

    operations = [
    ]
