# Generated by Django 4.2.20 on 2025-07-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0167_one_off_delete_historical_bcftools_liftover_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsoverride',
            name='grid_sample_label_template',
            field=models.TextField(blank=True, help_text="Python string template, eg: '%(patient)s (%(sample)s)'. Variables: sample_id, sample (name), patient_id, patient_code, patient (full name), specimen_id, specimen (name). Falls back on 'sample' if blank or any error", null=True),
        ),
    ]
