# Generated by Django 4.2.17 on 2025-04-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0167_merge_20250414_1138'),
        ('classification', '0167_once_off_migrate_assertion_method_matches')
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinvarkey',
            name='assertion_method_lookup',
        ),
    ]
