# Generated by Django 4.2.15 on 2025-07-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0168_settingsoverride_grid_sample_label_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settingsoverride",
            name="grid_sample_label_template",
            field=models.TextField(
                blank=True,
                help_text="Python string template, eg: '%(patient)s (%(sample)s/%(specimen_id)s)||%(patient)s (%(sample)s)||%(sample)s'. Multiple values separated by '||', the first one to succeed will be used. Variables: sample_id, sample (name), patient_id, patient_code, patient (full name), specimen_id, specimen (name).",
                null=True,
            ),
        ),
    ]
