# Generated by Django 4.2.17 on 2025-05-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0167_one_off_delete_historical_bcftools_liftover_swap'),
        ('snpdb', '0168_remove_clinvarkey_assertion_method_lookup'),
    ]

    operations = [
    ]
