# Generated by Django 5.2.8 on 2025-11-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0169_alter_settingsoverride_grid_sample_label_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsoverride",
            name="analysis_horizontal_mode",
            field=models.BooleanField(
                blank=True,
                help_text="Analysis nodes connect left/right, and grid on bottom. Default=False - connect vertically top/bottom, grid in editor",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="settingsoverride",
            name="show_candidates_classification_evidence_update",
            field=models.BooleanField(
                blank=True,
                help_text="Show candidates on sample / classification pages (You can always explicitly go to the candidate pages)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="settingsoverride",
            name="show_candidates_cross_sample_classification",
            field=models.BooleanField(
                blank=True,
                help_text="Show candidates on sample / classification pages (You can always explicitly go to the candidate pages)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="settingsoverride",
            name="show_candidates_reanalysis_new_annotation",
            field=models.BooleanField(
                blank=True,
                help_text="Show candidates in analysis pages (You can always explicitly go to the candidate pages)",
                null=True,
            ),
        ),
    ]
