# Generated by Django 4.2.17 on 2025-09-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0169_alter_settingsoverride_grid_sample_label_template'),
        ('snpdb', '0169_merge_20250505_1251'),
    ]

    operations = [
    ]
