# Generated by Django 5.2.8 on 2025-11-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0170_settingsoverride_analysis_horizontal_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="research_consent",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
