# Generated by Django 4.2.15 on 2025-11-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0170_merge_20250924_1038'),
        ('snpdb', '0171_sample_research_consent'),
    ]

    operations = [
    ]
