# Generated by Django 5.2.8 on 2026-03-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0171_sample_research_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="variants_type",
            field=models.CharField(
                choices=[
                    ("U", "Unknown"),
                    ("G", "Germline"),
                    ("M", "Mixed (Single Sample)"),
                    ("S", "Somatic only (Tumour minus normal)"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="settingsoverride",
            name="tag_colors",
            field=models.ForeignKey(
                blank=True,
                help_text="Set of colours assigned to tags (modify/create these in 'Tag settings')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="snpdb.tagcolorscollection",
            ),
        ),
        migrations.AlterField(
            model_name="variantallele",
            name="origin",
            field=models.CharField(
                choices=[
                    ("D", "Imported as this build"),
                    ("N", "Imported (normalised)"),
                    ("L", "Liftover"),
                    ("M", "Liftover (normalised)"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="vcfsourcesettings",
            name="sample_variants_type",
            field=models.CharField(
                choices=[
                    ("U", "Unknown"),
                    ("G", "Germline"),
                    ("M", "Mixed (Single Sample)"),
                    ("S", "Somatic only (Tumour minus normal)"),
                ],
                default="U",
                max_length=1,
            ),
        ),
    ]
