# Generated by Django 6.0.3 on 2026-03-30 02:17

import django.db.models.deletion
import django_extensions.db.fields
import library.django_utils
import library.django_utils.guardian_permissions_mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0173_one_off_grch37_igv_genome_hg19"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("mother_affected", models.BooleanField(default=False)),
                ("father_affected", models.BooleanField(default=False)),
                ("sibling_affected", models.BooleanField(default=False)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="snpdb.cohort"
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quad_father",
                        to="snpdb.cohortsample",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quad_mother",
                        to="snpdb.cohortsample",
                    ),
                ),
                (
                    "proband",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quad_proband",
                        to="snpdb.cohortsample",
                    ),
                ),
                (
                    "sibling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quad_sibling",
                        to="snpdb.cohortsample",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
            bases=(
                library.django_utils.guardian_permissions_mixin.GuardianPermissionsAutoInitialSaveMixin,
                library.django_utils.SortByPKMixin,
                models.Model,
            ),
        ),
    ]
