# Generated by Django 6.0 on 2026-03-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0174_add_quad'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsoverride',
            name='initially_show_zygosity_table',
            field=models.BooleanField(blank=True, help_text='Initially expand the zygosity requirements table in Trio/Quad node editors', null=True),
        ),
    ]
