# Generated by Django 6.0.3 on 2026-04-30 07:03

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0177_denovo_db_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortGenotypeStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("filter_key", models.TextField(null=True)),
                ("passing_filter", models.BooleanField(default=False)),
                (
                    "import_status",
                    models.CharField(
                        choices=[
                            ("C", "created"),
                            ("I", "importing"),
                            ("R", "Requires user input"),
                            ("E", "error"),
                            ("S", "success"),
                            ("M", "Marked For Deletion"),
                            ("D", "Deleting"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("variant_count", models.IntegerField(default=0)),
                ("snp_count", models.IntegerField(default=0)),
                ("insertions_count", models.IntegerField(default=0)),
                ("deletions_count", models.IntegerField(default=0)),
                ("ref_count", models.IntegerField(default=0)),
                ("het_count", models.IntegerField(default=0)),
                ("hom_count", models.IntegerField(default=0)),
                ("unk_count", models.IntegerField(default=0)),
                ("x_hom_count", models.IntegerField(default=0)),
                ("x_het_count", models.IntegerField(default=0)),
                ("x_unk_count", models.IntegerField(default=0)),
                (
                    "code_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.samplestatscodeversion",
                    ),
                ),
                (
                    "cohort_genotype_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genotype_stats",
                        to="snpdb.cohortgenotypecollection",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.sample",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sample", "passing_filter"],
                        name="snpdb_cohor_sample__6f6a54_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", False), ("filter_key__isnull", True)
                        ),
                        fields=(
                            "cohort_genotype_collection",
                            "sample",
                            "passing_filter",
                        ),
                        name="cohort_genotype_stats_per_sample_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", True), ("filter_key__isnull", True)
                        ),
                        fields=("cohort_genotype_collection", "passing_filter"),
                        name="cohort_genotype_stats_aggregate_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", True), ("filter_key__isnull", False)
                        ),
                        fields=(
                            "cohort_genotype_collection",
                            "filter_key",
                            "passing_filter",
                        ),
                        name="cohort_genotype_stats_aggregate_filter_uniq",
                    ),
                ],
            },
        ),
    ]
