# Generated by Django 6.0.3 on 2026-05-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0180_new_annotsv_variantgrid_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vcf",
            name="data_archive_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vcf",
            name="data_archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vcf",
            name="data_archived_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vcf",
            name="data_restorable_from",
            field=models.TextField(blank=True, null=True),
        ),
    ]
