# Generated by Django 6.0.3 on 2026-05-04 05:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0181_vcf_data_archive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cohortgenotypecollection",
            name="data_archive_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cohortgenotypecollection",
            name="data_archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cohortgenotypecollection",
            name="data_archived_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cohortgenotypecollection",
            name="data_restorable_from",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantcollection",
            name="data_archive_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantcollection",
            name="data_archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="variantcollection",
            name="data_archived_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantcollection",
            name="data_restorable_from",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantzygositycountcollection",
            name="data_archive_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantzygositycountcollection",
            name="data_archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="variantzygositycountcollection",
            name="data_archived_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantzygositycountcollection",
            name="data_restorable_from",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PartitionArchive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archive_name", models.TextField(unique=True)),
                ("dump_path", models.TextField()),
                ("sha256", models.TextField(blank=True, null=True)),
                ("source_app_label", models.TextField()),
                ("source_model", models.TextField()),
                ("source_pk", models.TextField()),
                (
                    "source_table_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField()
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("dumped_date", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cleared_date", models.DateTimeField(blank=True, null=True)),
                ("restored_date", models.DateTimeField(blank=True, null=True)),
                (
                    "cleared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleared_partition_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dumped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dumped_partition_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_partition_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-dumped_date",),
            },
        ),
    ]
