# Generated by Django 6.0.3 on 2026-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0182_cohortgenotypecollection_data_archive_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="research",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
