# Generated by Django 6.0.5 on 2026-05-29 01:25

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


def _backfill_cohort_versions(apps, schema_editor):
    """ Create a CohortVersion row for every existing Cohort's current version so version-keyed
        caches have a row to FK to post-deploy. @see issue #1551 """
    Cohort = apps.get_model("snpdb", "Cohort")
    CohortVersion = apps.get_model("snpdb", "CohortVersion")
    cohort_versions = [
        CohortVersion(cohort_id=pk, version=version)
        for pk, version in Cohort.objects.values_list("pk", "version")
    ]
    CohortVersion.objects.bulk_create(cohort_versions, batch_size=2000, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0183_lab_research"),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("version", models.IntegerField()),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="snpdb.cohort"
                    ),
                ),
            ],
            options={
                "unique_together": {("cohort", "version")},
            },
        ),
        migrations.RunPython(_backfill_cohort_versions, migrations.RunPython.noop),
        migrations.CreateModel(
            name="SubCohortVariantCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cohort_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_cohort_variant_collection",
                        to="snpdb.cohortversion",
                    ),
                ),
                (
                    "parent_cohort_genotype_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.cohortgenotypecollection",
                    ),
                ),
                (
                    "variant_collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.variantcollection",
                    ),
                ),
            ],
        ),
    ]
