# Generated by Django 6.0.3 on 2026-06-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0184_cohortversion_subcohortvariantcollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="vcf",
            name="data_archive_started_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
