# Generated by Django 6.0.3 on 2026-06-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0185_vcf_data_archive_started_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="vcf",
            name="data_archive_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
