# Generated by Django 6.0.5 on 2026-06-11 07:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0186_vcf_data_archive_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohortgenotypecommonfilterversion",
            name="additional_gnomad_versions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list
            ),
        ),
    ]
