# Generated by Django 6.0.5 on 2026-06-11

from django.db import migrations

from manual.operations.manual_operations import ManualOperation

GNOMAD_4_VERSIONS = {"4.0", "4.1"}


def _has_common_collections_needing_gnomad4_migration(apps):
    """ Existing GRCh38 'common' partitions built against a single gnomAD 4.x version need to be migrated to
        the combined 4.0/4.1 intersection filter - @see https://github.com/SACGF/variantgrid/issues/1582 """
    CohortGenotypeCollection = apps.get_model("snpdb", "CohortGenotypeCollection")
    common_cgc_qs = CohortGenotypeCollection.objects.filter(
        collection_type="C",  # CohortGenotypeCollectionType.COMMON
        common_filter__gnomad_version__in=GNOMAD_4_VERSIONS,
    ).select_related("common_filter")
    for cgc in common_cgc_qs:
        common_filter = cgc.common_filter
        gnomad_versions = {common_filter.gnomad_version, *common_filter.additional_gnomad_versions}
        if not gnomad_versions.issuperset(GNOMAD_4_VERSIONS):
            return True
    return False


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0187_cohortgenotypecommonfilterversion_additional_gnomad_versions"),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["migrate_common_filter_gnomad_versions"]),
                        note="Move non-intersection variants out of gnomAD 4.x common partitions then repoint "
                             "them to the combined 4.0/4.1 filter (#1582)",
                        test=_has_common_collections_needing_gnomad4_migration),
    ]
