# Generated by Django 6.0.5 on 2026-06-11 13:14

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0188_one_off_migrate_common_filter_gnomad_versions"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobsControl",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("paused", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True)),
                ("paused_by", models.TextField(blank=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_autopause_boot_time",
                    models.BigIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
