# Generated by Django 6.0.5 on 2026-06-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0189_jobscontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsoverride",
            name="node_grid_auto_load_max_variants",
            field=models.IntegerField(
                blank=True,
                help_text="Analysis nodes with at least this many variants don't auto-load their grid — the user clicks 'Load variants' to run the row query. Blank inherits the next level up.",
                null=True,
            ),
        ),
    ]
