# Generated by Django 6.0.5 on 2026-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0191_set_global_node_grid_auto_load_max_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettingsoverride",
            name="loading_animations",
            field=models.JSONField(
                blank=True,
                help_text="Animations randomly shown while a node's variant grid loads.",
                null=True,
            ),
        ),
    ]
