# Generated by Django 6.0.5 on 2026-07-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0193_vep116_plugin_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vcflengthstats",
            name="variant_class",
            field=models.CharField(
                choices=[
                    ("SN", "SNV"),
                    ("GM", "genetic_marker"),
                    ("SU", "substitution"),
                    ("TR", "tandem_repeat"),
                    ("AI", "Alu_insertion"),
                    ("HI", "HERV_insertion"),
                    ("LI", "LINE1_insertion"),
                    ("VI", "SVA_insertion"),
                    ("CA", "complex_structural_alteration"),
                    ("CS", "complex_substitution"),
                    ("CG", "copy_number_gain"),
                    ("CL", "copy_number_loss"),
                    ("CN", "copy_number_variation"),
                    ("DU", "duplication"),
                    ("CH", "chromosome_breakpoint"),
                    ("IB", "interchromosomal_breakpoint"),
                    ("IT", "interchromosomal_translocation"),
                    ("CB", "intrachromosomal_breakpoint"),
                    ("CT", "intrachromosomal_translocation"),
                    ("IN", "inversion"),
                    ("LO", "loss_of_heterozygosity"),
                    ("MD", "mobile_element_deletion"),
                    ("AD", "Alu_deletion"),
                    ("HD", "HERV_deletion"),
                    ("LD", "LINE1_deletion"),
                    ("VD", "SVA_deletion"),
                    ("MI", "mobile_element_insertion"),
                    ("NI", "novel_sequence_insertion"),
                    ("ST", "short_tandem_repeat_variation"),
                    ("TD", "tandem_duplication"),
                    ("TL", "translocation"),
                    ("DE", "deletion"),
                    ("ND", "indel"),
                    ("IS", "insertion"),
                    ("SA", "sequence_alteration"),
                    ("PR", "probe"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
