# Generated by Django 6.0.6 on 2026-07-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0195_delete_columnvcfinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="mme_enabled",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
