# Generated by Django 6.0.6 on 2026-08-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0198_alter_variant_end_not_null"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samplestatspassingfilter",
            name="code_version",
        ),
        migrations.RemoveField(
            model_name="samplestatspassingfilter",
            name="sample",
        ),
        migrations.DeleteModel(
            name="SampleStats",
        ),
        migrations.DeleteModel(
            name="SampleStatsPassingFilter",
        ),
    ]
