# Generated by Django 6.1 on 2026-08-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0202_sample_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcfsourcesettings',
            name='sample_field_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
