# Generated by Django 6.1 on 2026-08-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0204_vcf_source_settings_splicegirl'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='extraction_match_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='extraction_match_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='extraction_match_status',
            field=models.CharField(blank=True, choices=[('M', 'Matched'), ('P', 'Pending'), ('N', 'Needs attention')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='extraction_reference',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
