# Generated by Django 6.0.6 on 2026-08-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0205_sample_extraction_match_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contig",
            name="role",
            field=models.CharField(
                choices=[
                    ("AM", "assembled-molecule"),
                    ("ULS", "unlocalized-scaffold"),
                    ("UPS", "unplaced-scaffold"),
                    ("ALT", "alt-scaffold"),
                    ("FP", "fix-patch"),
                    ("NP", "novel-patch"),
                    ("GL", "gene-level"),
                ],
                max_length=3,
            ),
        ),
    ]
