# Generated by Django 6.1 on 2026-08-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0208_one_off_variant_tag_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcftag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='vcftag',
            name='vcf',
        ),
        migrations.DeleteModel(
            name='SampleTag',
        ),
        migrations.DeleteModel(
            name='VCFTag',
        ),
    ]
