# Generated by Django 6.1 on 2026-08-19 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0209_delete_vcf_and_sample_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='retired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
