# Generated by Django 6.1 on 2026-08-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0210_tag_merged_into_tag_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsoverride',
            name='variant_tag_stale_days',
            field=models.IntegerField(blank=True, choices=[(180, '6 months'), (365, '1 year'), (545, '18 months'), (730, '2 years'), (1825, '5 years')], help_text='Tag events older than this are considered stale: grids show fresh vs total counts and mark tags whose most recent event is older. Blank inherits the next level up / disables.', null=True),
        ),
    ]
