# Generated by Django 6.1 on 2026-08-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0212_tagcolor_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="allele_origin_bucket",
            field=models.CharField(
                choices=[("U", "Both"), ("G", "Germline only"), ("S", "Somatic only")],
                default="U",
                max_length=1,
            ),
        ),
    ]
