# Generated by Django 6.1 on 2026-08-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0215_jobscontrol_boot_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantzygositycountcollection",
            name="data_version",
            field=models.IntegerField(default=0),
        ),
    ]
