# Generated by Django 6.1 on 2026-08-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0219_somatic_classification_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodecountsettings',
            name='built_in_filter',
            field=models.CharField(choices=[('T', 'Total'), ('C', 'ClinVar LP/P'), ('O', 'OMIM Phenotype'), ('I', 'High or Mod impact'), ('G', 'Classified'), ('P', 'Classified Pathogenic'), ('S', 'Classified Tier I/II'), ('M', 'COSMIC')], max_length=1, null=True),
        ),
    ]
