# Generated by Django 6.1 on 2026-08-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0220_alter_nodecountsettings_built_in_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettingsoverride",
            name="show_tips",
            field=models.BooleanField(
                default=True,
                help_text="Show feature tips on loading screens and blank grids.",
                verbose_name="Show Tips",
            ),
        ),
    ]
