# Generated by Django 6.1 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0223_alter_nodecountsettings_built_in_filter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nodecountsettings",
            old_name="built_in_filter",
            new_name="node_count_type",
        ),
        migrations.AlterField(
            model_name="nodecountsettings",
            name="node_count_type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
