# Generated by Django 6.1 on 2026-08-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0228_clinvar_somatic_chip"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsoverride",
            name="variant_grid_two_line_rows",
            field=models.BooleanField(
                blank=True,
                help_text="Variant grid rows are two lines high, with the transcript, protein change and impact on the second line. Fewer variants per screen, more of each one",
                null=True,
            ),
        ),
    ]
