# Generated by Django 6.1 on 2026-09-01 05:54

from django.conf import settings
from django.db import migrations, models


def _set_global_default(apps, _schema):
    GlobalSettings = apps.get_model("snpdb", "GlobalSettings")
    global_settings = GlobalSettings.objects.get()
    if global_settings.show_user_awards is None:
        global_settings.show_user_awards = True
        global_settings.save()


def _reverse(apps, _schema):
    GlobalSettings = apps.get_model("snpdb", "GlobalSettings")
    global_settings = GlobalSettings.objects.get()
    global_settings.show_user_awards = None
    global_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0230_aloft_composite_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraward',
            options={},
        ),
        migrations.AddField(
            model_name='settingsoverride',
            name='show_user_awards',
            field=models.BooleanField(blank=True, help_text='Decorate users currently holding a title (crown, medal, trophy) on grids and in user labels', null=True),
        ),
        migrations.AddField(
            model_name='useraward',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraward',
            name='definition_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraward',
            name='kind',
            field=models.CharField(choices=[('T', 'Title'), ('B', 'Badge'), ('K', 'Kudos')], default='K', max_length=1),
        ),
        migrations.AddField(
            model_name='useraward',
            name='period',
            field=models.CharField(blank=True, choices=[('A', 'all time'), ('M', 'this month'), ('D', 'today')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='useraward',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='useraward',
            constraint=models.UniqueConstraint(condition=models.Q(('definition_key__isnull', False)), fields=('user', 'definition_key', 'subject', 'period'), name='user_award_unique_computed', nulls_distinct=False),
        ),
            migrations.RunPython(_set_global_default, _reverse),
    ]
