# Generated by Django 6.1 on 2026-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0234_trio_proband_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='quad',
            name='proband_sex',
            field=models.CharField(blank=True, choices=[('U', 'unknown'), ('M', 'male'), ('F', 'female')], max_length=1, null=True),
        ),
    ]
