# Generated by Django 6.1 on 2026-09-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0236_open_targets_l2g_scores_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeColumnMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField()),
                ('in_sort_menu', models.BooleanField(default=True)),
                ('column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='composite_membership', to='snpdb.variantgridcolumn')),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_members', to='snpdb.variantgridcolumn')),
            ],
            options={
                'ordering': ('composite', 'sort_order'),
            },
        ),
    ]
