# Generated by Django 6.1 on 2026-09-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0241_composite_pop_freq_other_uniprot"),
        ("snpdb", "0242_open_targets_lead_variants_backfill"),
    ]

    operations = []
