# Generated by Django 6.1 on 2026-09-04 06:36

import django.db.models.deletion
import django_extensions.db.fields
import library.django_utils
import library.django_utils.guardian_permissions_mixin
import library.preview_request
import snpdb.models.models_cohort
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0245_classifications_column_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.TextField(blank=True)),
                ('relationship', models.CharField(choices=[('M', 'Mother'), ('F', 'Father')], max_length=1)),
                ('parent_affected', models.BooleanField(default=False)),
                ('proband_sex', models.CharField(blank=True, choices=[('U', 'unknown'), ('M', 'male'), ('F', 'female')], max_length=1, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.cohort')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duo_parent', to='snpdb.cohortsample')),
                ('proband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duo_proband', to='snpdb.cohortsample')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(snpdb.models.models_cohort.FamilyGroupMixin, library.django_utils.guardian_permissions_mixin.GuardianPermissionsAutoInitialSaveMixin, library.preview_request.SvgSymbolPreviewIconMixin, library.preview_request.PreviewModelMixin, library.django_utils.SortByPKMixin, models.Model),
        ),
    ]
