# Generated by Django 6.1 on 2026-09-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0246_add_duo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsoverride',
            name='initially_show_zygosity_table',
            field=models.BooleanField(blank=True, help_text='Initially expand the zygosity requirements table in Duo/Trio/Quad node editors', null=True),
        ),
    ]
