# Generated by Django 6.1 on 2026-09-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0246_leading_columns_all_collections"),
        ("snpdb", "0247_zygosity_table_help_text"),
    ]

    operations = []
