# Generated by Django 6.1 on 2026-09-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0249_annotsv_composites'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='requires_classification',
            field=models.BooleanField(default=False),
        ),
    ]
