# Generated by Django 6.1 on 2026-09-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0251_one_off_tags_requiring_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcf',
            name='copy_number_field',
            field=models.TextField(null=True),
        ),
    ]
