# Generated by Django 6.1.1 on 2026-09-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0255_vcf_source_settings_fusion_processor_reads"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohortgenotypestats",
            name="fusions_count",
            field=models.IntegerField(default=0),
        ),
    ]
