# Generated by Django 6.1.1 on 2026-09-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0260_annotsv_acmg_class_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcf',
            name='gene_level_segment_field',
            field=models.TextField(null=True),
        ),
    ]
