# Generated by Django 4.2.25 on 2026-09-11 00:00
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0261_vcf_gene_level_segment_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="duo",
            old_name="parent",
            new_name="relative",
        ),
        migrations.RenameField(
            model_name="duo",
            old_name="parent_affected",
            new_name="relative_affected",
        ),
        migrations.AlterField(
            model_name="duo",
            name="relative",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="duo_relative", to="snpdb.cohortsample"),
        ),
        migrations.AlterField(
            model_name="duo",
            name="relationship",
            field=models.CharField(choices=[("M", "Mother"), ("F", "Father"), ("S", "Sibling")], max_length=1),
        ),
    ]
