# Generated by Django 6.1.1 on 2026-09-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0267_one_off_sample_patient_from_extraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="phenotype",
            field=models.TextField(blank=True, null=True),
        ),
    ]
