# Generated by Django 6.1.1 on 2026-09-18 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0270_one_off_manual_heavy_workers_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortgenotype',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='snpdb.cohortgenotypecollection'),
        ),
    ]
