# Generated by Django 6.1.1 on 2026-09-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0271_alter_cohortgenotype_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcolor',
            name='quick_tag',
            field=models.BooleanField(default=False),
        ),
    ]
