# Generated by Django 6.1.1 on 2026-09-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0273_rename_tagcolor_tagconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagconfigcollection',
            name='show_resolved_variant_tags',
            field=models.BooleanField(default=False, help_text="Tag work lists (variant page, variant tags page) keep taggings a classification has resolved, and new tag nodes start with 'include resolved' ticked."),
        ),
    ]
