# Generated by Django 6.1.1 on 2026-09-24 06:17

from django.db import migrations


def _delete_vcf_bed_intersection_variant_collections(apps, schema_editor):
    """ Each VCFBedIntersection owned its VariantCollection, which would otherwise be orphaned """
    VCFBedIntersection = apps.get_model("snpdb", "VCFBedIntersection")
    VariantCollection = apps.get_model("snpdb", "VariantCollection")

    vc_ids = list(VCFBedIntersection.objects.filter(variant_collection__isnull=False)
                  .values_list("variant_collection_id", flat=True))
    VCFBedIntersection.objects.all().delete()
    with schema_editor.connection.cursor() as cursor:
        for vc_id in vc_ids:
            cursor.execute(f'DROP TABLE IF EXISTS "snpdb_variantcollectionrecord_variant_collection_{vc_id}"')
            cursor.execute('DELETE FROM ONLY "snpdb_variantcollectionrecord" WHERE variant_collection_id = %s',
                           [vc_id])
    VariantCollection.objects.filter(pk__in=vc_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0276_one_off_manual_scss_watcher_root_files'),
    ]

    operations = [
        migrations.RunPython(_delete_vcf_bed_intersection_variant_collections, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='VCFBedIntersection',
        ),
    ]
