# Generated by Django 6.1.1 on 2026-10-01 06:16

from django.conf import settings
from django.db import migrations, models

RETIRED_BADGE_KEYS = ["night_owl", "early_bird"]


def _delete_titles_and_retired_badges(apps, _schema_editor):
    """ Titles ("Top X" crowns/medals/trophies) are gone, as are the late/early hours badges (#1819) """
    UserAward = apps.get_model("snpdb", "UserAward")
    UserAward.objects.filter(kind="T").delete()
    UserAward.objects.filter(definition_key__in=RETIRED_BADGE_KEYS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0277_delete_vcfbedintersection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_delete_titles_and_retired_badges, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="useraward",
            name="user_award_unique_computed",
        ),
        migrations.RemoveField(
            model_name="settingsoverride",
            name="show_user_awards",
        ),
        migrations.AlterField(
            model_name="useraward",
            name="kind",
            field=models.CharField(
                choices=[("B", "Badge"), ("K", "Kudos")], default="K", max_length=1
            ),
        ),
        migrations.AddConstraint(
            model_name="useraward",
            constraint=models.UniqueConstraint(
                condition=models.Q(("definition_key__isnull", False)),
                fields=("user", "definition_key"),
                name="user_award_unique_badge",
            ),
        ),
        migrations.RemoveField(
            model_name="useraward",
            name="period",
        ),
        migrations.RemoveField(
            model_name="useraward",
            name="subject",
        ),
    ]
