# Generated by Django 6.1.1 on 2026-10-08 03:38

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0019_specimen_measure_pathology_only"),
        ("snpdb", "0279_one_off_symbolic_alt_size_50"),
    ]

    operations = [
        migrations.AlterField(
            model_name="somalierrelatepairs",
            name="sample_a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_a",
                to="snpdb.sample",
            ),
        ),
        migrations.AlterField(
            model_name="somalierrelatepairs",
            name="sample_b",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_b",
                to="snpdb.sample",
            ),
        ),
        migrations.CreateModel(
            name="SomalierPatientRelate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("C", "Created"),
                            ("P", "Processing"),
                            ("E", "Error"),
                            ("S", "Success"),
                            ("K", "Skipped"),
                            ("T", "Terminated Early"),
                            ("Z", "Timed Out"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("error_exception", models.TextField(blank=True, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SomalierPatientRelatePair",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relatedness", models.FloatField()),
                ("ibs0", models.IntegerField()),
                ("ibs2", models.IntegerField()),
                ("hom_concordance", models.FloatField()),
                ("hets_a", models.IntegerField()),
                ("hets_b", models.IntegerField()),
                ("hets_ab", models.IntegerField()),
                ("shared_hets", models.IntegerField()),
                ("hom_alts_a", models.IntegerField()),
                ("hom_alts_b", models.IntegerField()),
                ("shared_hom_alts", models.IntegerField()),
                ("n", models.IntegerField()),
                ("x_ibs0", models.IntegerField()),
                ("x_ibs2", models.IntegerField()),
                (
                    "relate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.somalierpatientrelate",
                    ),
                ),
                (
                    "sample_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_a",
                        to="snpdb.sample",
                    ),
                ),
                (
                    "sample_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_b",
                        to="snpdb.sample",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
