# Generated by Django 6.1.1 on 2026-10-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0280_somalier_patient_relate"),
    ]

    operations = [
        migrations.AddField(
            model_name="genomicintervalscollection",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
