# Generated by Django 3.1 on 2020-10-01 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import library.django_utils.django_file_system_storage


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20201001_1658'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snpdb', '0003_auto_20201001_1658'),
        ('classification', '0004_auto_20201001_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=library.django_utils.django_file_system_storage.PrivateUploadStorage(), upload_to='classification_attachments')),
                ('file_type', models.CharField(choices=[('I', 'Image'), ('P', 'Image'), ('W', 'Word Doc'), ('T', 'Text'), ('S', 'Spreadsheet'), ('O', 'Image')], max_length=1)),
                ('thumbnail_path', models.TextField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='VariantClassificationImport',
            new_name='ClassificationImport',
        ),
        migrations.RenameModel(
            old_name='VariantClassificationImportAlleleSource',
            new_name='ClassificationImportAlleleSource',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='variant_classification_import',
            new_name='classification_import',
        ),
        migrations.RenameField(
            model_name='classificationimportallelesource',
            old_name='variant_classification_import',
            new_name='classification_import',
        ),
        migrations.RenameField(
            model_name='classificationmodification',
            old_name='variant_classification',
            new_name='classification',
        ),
        migrations.DeleteModel(
            name='VariantClassificationAttachment',
        ),
        migrations.AddField(
            model_name='classificationattachment',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.classification'),
        ),
    ]
