# Generated by Django 3.1 on 2020-10-16 05:42

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0005_auto_20201001_1706'),
    ]

    operations = [
        ManualOperation.task_id_manage(["fix_matching_flags", "--apply"])
    ]
