# Generated by Django 3.1 on 2020-10-16 05:42

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _check_has_flags_of_interest(apps):
    Flag = apps.get_model("flags", "Flag")
    flags_of_interest = Flag.objects.filter(flag_type__in=[
        "classification_transcript_version_change",
        "matching_variant_warning_flag",
    ]).filter(data__isnull=True)
    return flags_of_interest.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0005_auto_20201001_1706'),
        ('manual', '0002_deployment'),
    ]

    operations = [
        # These flags are no longer used, instead they are handled by ImportedAlleleInfo
        # ManualOperation(task_id=ManualOperation.task_id_manage(["fix_matching_flags", "--apply"]),
        #                 test=_check_has_flags_of_interest)
    ]
