# Generated by Django 3.1 on 2020-10-30 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import library.django_utils.guardian_permissions_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0005_auto_20201015_1611'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0006_auto_20201016_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionAliasSearchCache',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('search_text', models.TextField(primary_key=True, serialize=False)),
                ('cached_results', models.JSONField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source_text', models.TextField()),
                ('source_gene_symbol', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Resolved (Auto)'), ('R', 'Resolved'), ('U', 'Unmatchable')], default='P', max_length=1)),
                ('join_mode', models.CharField(choices=[('O', 'Or'), ('A', 'And')], default='O', max_length=1)),
                ('records_affected', models.IntegerField()),
                ('aliases', models.JSONField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.lab')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lab', 'source_text', 'source_gene_symbol')},
            },
            bases=(models.Model, library.django_utils.guardian_permissions_mixin.GuardianPermissionsMixin),
        ),
    ]
