# Generated by Django 3.1.3 on 2020-11-16 07:15

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def test_has_abbreviated_variant_coordinate(apps):
    Classification = apps.get_model("classification", "Classification")
    # For some reason JSON icontains works while contains doesn't?
    return Classification.objects.filter(evidence__variant_coordinate__value__icontains="..").exists()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0008_new_ekey_pubmed_search_terms'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_variant_coordinate_abbreviation"]),
                        test=test_has_abbreviated_variant_coordinate)
    ]
