# Generated by Django 3.1.3 on 2021-01-04 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0013_auto_20210104_1749'),
        ('classification', '0009_fix_variant_coordinate_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='annotation_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.annotationversion'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='clinical_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.clinicalcontext'),
        ),
    ]
