# Generated by Django 3.1 on 2020-11-25 04:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import library.django_utils.guardian_permissions_mixin
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0009_remove_settingsoverride_variant_tag_group_by_variant'),
        ('genes', '0003_transcript_version_json_del_gene_name'),
        ('classification', '0009_fix_variant_coordinate_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinVarExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transcript', models.TextField()),
                ('condition_text_normal', models.TextField(blank=True, null=True)),
                ('condition_xrefs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('condition_multi_operation', models.CharField(choices=[('N', 'Not decided'), ('U', 'Uncertain'), ('C', 'Co-occurring')], default='N', max_length=1)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('S', 'Submit When Ready'), ('P', 'Pending'), ('R', 'Reject')], default='P', max_length=1)),
                ('dirty_date', models.DateTimeField(blank=True, null=True)),
                ('submit_when_possible', models.BooleanField(default=False)),
                ('requires_user_input', models.BooleanField(default=False)),
                ('withdrawn', models.BooleanField(default=False)),
                ('allele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snpdb.allele')),
                ('classification_based_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.classificationmodification')),
                ('gene_symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genes.genesymbol')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.lab')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, library.django_utils.guardian_permissions_mixin.GuardianPermissionsMixin),
        ),
        migrations.CreateModel(
            name='ClinVarExportSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('evidence', models.JSONField()),
                ('submission_status', models.TextField()),
                ('clinvar_export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.clinvarexport')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, library.django_utils.guardian_permissions_mixin.GuardianPermissionsMixin),
        ),
    ]
