# Generated by Django 3.1 on 2021-01-05 23:46

from django.db import migrations
from django.db.migrations import RunPython


def create_source_url_evidence_key(apps, schema_editor):
    EvidenceKey = apps.get_model("classification", "EvidenceKey")

    kwargs = {
        'key': 'source_url',
        'mandatory': False,
        'max_share_level': 'logged_in_users',
        'order': 101,
        'label': 'Source URL',
        'sub_label': None,
        'description': 'Where this data was sourced from',
        'examples': [],
        'options': [],
        'see': None,
        'evidence_category': 'SO',
        'value_type': 'T',
        'default_crit_evaluation': None,
        'allow_custom_values': False,
        'hide': True,
        'immutable': False,
        'copy_consensus': False,
        'variantgrid_column_id': None,
    }
    EvidenceKey.objects.create(**kwargs)

class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0010_auto_20210104_1801'),
    ]

    operations = [
        RunPython(create_source_url_evidence_key)
    ]
