# Generated by Django 3.1 on 2020-12-10 23:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import library.django_utils.guardian_permissions_mixin
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0006_panel_app_config'),
        ('snpdb', '0009_remove_settingsoverride_variant_tag_group_by_variant'),
        ('classification', '0010_clinvarexport_clinvarexportsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('normalized_text', models.TextField()),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.lab')),
            ],
            options={
                'unique_together': {('normalized_text', 'lab')},
            },
            bases=(models.Model, library.django_utils.guardian_permissions_mixin.GuardianPermissionsMixin),
        ),
        migrations.CreateModel(
            name='ConditionTextMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('condition_xrefs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('condition_multi_operation', models.CharField(choices=[('X', 'Not decided'), ('U', 'Uncertain'), ('C', 'Co-occurring')], default='X', max_length=1)),
                ('classification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.classification')),
                ('condition_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.conditiontext')),
                ('gene_symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol')),
            ],
            options={
                'unique_together': {('condition_text', 'gene_symbol', 'classification')},
            },
            bases=(models.Model, library.django_utils.guardian_permissions_mixin.GuardianPermissionsMixin),
        ),
        migrations.AlterUniqueTogether(
            name='conditionalias',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conditionalias',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='conditionalias',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ConditionAliasSearchCache',
        ),
        migrations.RemoveField(
            model_name='clinvarexport',
            name='condition_multi_operation',
        ),
        migrations.RemoveField(
            model_name='clinvarexport',
            name='condition_text_normal',
        ),
        migrations.RemoveField(
            model_name='clinvarexport',
            name='condition_xrefs',
        ),
        migrations.RemoveField(
            model_name='clinvarexport',
            name='requires_user_input',
        ),
        migrations.DeleteModel(
            name='ConditionAlias',
        ),
    ]
