# Generated by Django 3.1 on 2020-12-11 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0011_auto_20201211_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditiontext',
            name='classifications_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conditiontext',
            name='classifications_count_outstanding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conditiontext',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conditiontext',
            name='requires_approval',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
