# Generated by Django 3.1 on 2020-12-14 00:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0007_activesamplegenelist_samplegenelist'),
        ('classification', '0012_auto_20201211_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditiontextmatch',
            name='mode_of_inheritance',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='conditiontextmatch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.conditiontextmatch'),
        ),
        migrations.AlterUniqueTogether(
            name='conditiontextmatch',
            unique_together={('condition_text', 'gene_symbol', 'mode_of_inheritance', 'classification')},
        ),
    ]
