# Generated by Django 3.1 on 2021-01-07 05:30

from django.db import migrations


def insert_default_report(apps, _schema):
    Organization = apps.get_model("snpdb", "Organization")
    ClassificationReportTemplate = apps.get_model("classification", "ClassificationReportTemplate")

    best_template = ""
    for org in Organization.objects.all():
        template = org.classification_report_template
        if template and len(template) > len(best_template):
            best_template = template

    ClassificationReportTemplate.objects.create(
        name="default_report",
        template=best_template
    )


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0012_classificationreporttemplate'),
    ]

    operations = [
        migrations.RunPython(insert_default_report)
    ]
