# Generated by Django 3.1 on 2021-01-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0013_auto_20210107_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationreporttemplate',
            name='template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
