# Generated by Django 3.1 on 2021-01-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0016_auto_20210112_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordancereport',
            name='resolved_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
