# Generated by Django 3.1.3 on 2021-02-17 06:39

from django.db import migrations


def _ekeys_gnomad3(apps, _schema_editor):
    EvidenceKey = apps.get_model("classification", "EvidenceKey")
    ek_vg_columns = {
        "gnomad_allele_count": "gnomad_ac",
        "gnomad_allele_number": "gnomad_an",
        "gnomad_popmax_allele_count": "gnomad_popmax_ac",
        "gnomad_popmax_allele_number": "gnomad_popmax_an",
    }

    for ek_pk, variantgrid_column_id in ek_vg_columns.items():
        EvidenceKey.objects.filter(pk=ek_pk).update(variantgrid_column_id=variantgrid_column_id)


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0017_discordancereport_resolved_text'),
    ]

    operations = [
        migrations.RunPython(_ekeys_gnomad3)
    ]
