# Generated by Django 3.1 on 2021-02-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0018_auto_20210201_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditiontext',
            name='status',
            field=models.CharField(choices=[('T', 'Terms Provided'), ('M', 'Multiple Terms Provided'), ('A', 'Auto-Matched'), ('N', 'Not Auto-Matched'), ('U', 'User Reviewed')], default='N', max_length=1),
        ),
    ]
