# Generated by Django 3.1 on 2021-02-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0019_auto_20210201_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditiontext',
            name='status',
        ),
        migrations.AddField(
            model_name='conditiontext',
            name='min_auto_match_score',
            field=models.IntegerField(default=0),
        ),
    ]
