# Generated by Django 3.1.6 on 2021-02-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0021_auto_20210211_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditiontextmatch',
            name='condition_multi_operation',
            field=models.CharField(choices=[('N', 'Not decided'), ('U', 'Uncertain'), ('C', 'Co-occurring')], default='N', max_length=1),
        ),
    ]
