# Generated by Django 3.1.6 on 2021-02-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0022_auto_20210217_1437'),
        ('classification', '0018_ekeys_gnomad3'),
    ]

    operations = [
    ]
