# Generated by Django 3.1.6 on 2021-04-22 02:15

from django.db import migrations

def _insert_sample_date_key(apps, schema_editor):
    """ This can be deleted if there is a blat_keys migration after it """
    EvidenceKey = apps.get_model("classification", "EvidenceKey")
    EvidenceKey.objects.create(
        key="sample_date",
        evidence_category="HT",
        order=0,
        value_type="D",
        copy_consensus=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0026_ekey_types'),
    ]

    operations = [
        migrations.RunPython(_insert_sample_date_key)
    ]
