# Generated by Django 3.1.6 on 2021-06-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0030_clinvar_mappings'),
        ('genes', '0028_one_off_fix_lowercase_gene_symbols'),  # This script needs clinvarexport.gene_symbol
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinvarexport',
            name='gene_symbol',
        ),
    ]
