# Generated by Django 3.1.6 on 2021-06-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0030_clinvar_mappings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinvarexport',
            name='gene_symbol',
        ),
    ]
