# Generated by Django 3.1.6 on 2021-06-14 23:44

from django.db import migrations


def _fix_variant_panel_frequency_key(apps, _schema_editor):
    """ This can be deleted if there is a blat_keys migration after it """
    EvidenceKey = apps.get_model("classification", "EvidenceKey")
    e_key = EvidenceKey.objects.get(key="variant_panel_frequency")
    e_key.value_type = "N"
    e_key.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0032_new_ekey_variant_panel_frequency'),
    ]

    operations = [
        migrations.RunPython(_fix_variant_panel_frequency_key)
    ]
