# Generated by Django 3.1.6 on 2021-07-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0033_new_ekey_variant_panel_frequency_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencekey',
            name='default_crit_evaluation',
            field=models.TextField(blank=True, choices=[('BA', 'Benign Standalone'), ('BS', 'Benign Strong'), ('BM', 'Benign Moderate'), ('BP', 'Benign Supporting'), ('N', 'Neutral'), ('PP', 'Pathogenic Supporting'), ('PM', 'Pathogenic Moderate'), ('PS', 'Pathogenic Strong'), ('PVS', 'Pathogenic Very Strong')], max_length=3, null=True),
        ),
    ]
