# Generated by Django 3.1.6 on 2021-07-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0034_auto_20210706_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencekey',
            name='default_crit_evaluation',
            field=models.TextField(blank=True, choices=[('BA', 'Benign Standalone'), ('BS', 'Benign Strong'), ('BM', 'Benign Moderate'), ('BP', 'Benign Supporting'), ('B?', 'Benign Unspecified Strength'), ('N', 'Neutral'), ('PP', 'Pathogenic Supporting'), ('PM', 'Pathogenic Moderate'), ('PS', 'Pathogenic Strong'), ('PVS', 'Pathogenic Very Strong'), ('P?', 'Pathogenic Unspecified Strength')], max_length=3, null=True),
        ),
    ]
