# Generated by Django 3.1.6 on 2021-07-15 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0037_auto_20210715_1128'),
        ('classification', '0035_auto_20210709_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinVarAllele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('allele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.allele')),
                ('clinvar_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.clinvarkey')),
            ],
            options={
                'verbose_name': 'ClinVar allele',
            },
        ),
        migrations.CreateModel(
            name='ClinVarExportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('condition', models.JSONField()),
                ('snv', models.TextField(blank=True, null=True)),
                ('content_last_submitted', models.JSONField(blank=True, null=True)),
                ('classification_based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.classificationmodification')),
                ('clinvar_allele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.clinvarallele')),
            ],
            options={
                'verbose_name': 'ClinVar export record',
            },
        ),
        migrations.CreateModel(
            name='ClinVarExportRecordSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Submitted'), ('A', 'Acknowledged'), ('E', 'In Error')], max_length=1)),
                ('submitted_json', models.JSONField()),
                ('clinvar_candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.clinvarexportrecord')),
            ],
            options={
                'verbose_name': 'ClinVar export record submission',
            },
        ),
        migrations.RemoveField(
            model_name='clinvarexportsubmission',
            name='clinvar_export',
        ),
        migrations.DeleteModel(
            name='ClinVarExport',
        ),
        migrations.DeleteModel(
            name='ClinVarExportSubmission',
        ),
    ]
