# Generated by Django 3.1.6 on 2021-07-16 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0039_clinvarkey_behalf_org_id'),
        ('classification', '0036_clinvar_mappings_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinVarAllele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('allele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.allele')),
                ('clinvar_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.clinvarkey')),
            ],
            options={
                'verbose_name': 'ClinVar allele',
            },
        ),
        migrations.CreateModel(
            name='ClinVarExportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('condition', models.JSONField()),
                ('scv', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('N', 'New Submission'), ('C', 'Changes Pending'), ('D', 'Up To Date'), ('E', 'In Error')], default='N', max_length=1)),
                ('classification_based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.classificationmodification')),
                ('clinvar_allele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.clinvarallele')),
            ],
            options={
                'verbose_name': 'ClinVar export record',
            },
        ),
        migrations.CreateModel(
            name='ClinVarExportRecordSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('submission_full', models.JSONField()),
                ('submission_body', models.JSONField()),
                ('submission_version', models.IntegerField()),
                ('classification_based_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.classificationmodification')),
                ('clinvar_candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.clinvarexportrecord')),
            ],
            options={
                'verbose_name': 'ClinVar export record submission',
            },
        ),
        migrations.CreateModel(
            name='ClinVarSubmissionBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('submission_version', models.IntegerField()),
                ('clinvar_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snpdb.clinvarkey')),
            ],
            options={
                'verbose_name': 'ClinVar submission batch',
            },
        ),
        migrations.RemoveField(
            model_name='clinvarexportsubmission',
            name='clinvar_export',
        ),
        migrations.DeleteModel(
            name='ClinVarExport',
        ),
        migrations.DeleteModel(
            name='ClinVarExportSubmission',
        ),
        migrations.AddField(
            model_name='clinvarexportrecordsubmission',
            name='submission_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.clinvarsubmissionbatch'),
        ),
    ]
