# Generated by Django 3.1.6 on 2021-07-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0036_auto_20210715_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinvarexportrecord',
            old_name='snv',
            new_name='scv',
        ),
    ]
