# Generated by Django 3.1.6 on 2021-07-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0039_clinvarkey_behalf_org_id'),
        ('classification', '0037_auto_20210716_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinVarExportRecord',
            new_name='ClinVarExport',
        ),
        migrations.RenameModel(
            old_name='ClinVarExportRecordSubmission',
            new_name='ClinVarExportSubmission',
        ),
        migrations.RenameModel(
            old_name='ClinVarSubmissionBatch',
            new_name='ClinVarExportSubmissionBatch',
        ),
        migrations.RenameField(
            model_name='clinvarexportsubmission',
            old_name='clinvar_candidate',
            new_name='clinvar_export',
        ),
    ]
