# Generated by Django 3.1.6 on 2021-07-16 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0039_clinvarkey_behalf_org_id'),
        ('classification', '0037_auto_20210716_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinvarexportrecordsubmission',
            old_name='submitted_json',
            new_name='submission_body',
        ),
        migrations.RemoveField(
            model_name='clinvarexportrecord',
            name='content_last_submitted',
        ),
        migrations.RemoveField(
            model_name='clinvarexportrecordsubmission',
            name='status',
        ),
        migrations.AddField(
            model_name='clinvarexportrecord',
            name='status',
            field=models.CharField(choices=[('U', 'Unknown'), ('N', 'New Submission'), ('C', 'Changes Pending'), ('D', 'Up To Date'), ('E', 'In Error')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='clinvarexportrecordsubmission',
            name='classification_based_on',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='classification.classificationmodification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinvarexportrecordsubmission',
            name='submission_full',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinvarexportrecordsubmission',
            name='submission_version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClinVarSubmissionBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('submission_version', models.IntegerField()),
                ('clinvar_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snpdb.clinvarkey')),
            ],
            options={
                'verbose_name': 'ClinVar submission batch',
            },
        ),
        migrations.AddField(
            model_name='clinvarexportrecordsubmission',
            name='submission_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.clinvarsubmissionbatch'),
        ),
    ]
