# Generated by Django 3.1.6 on 2021-07-21 02:46

from django.db import migrations


def _insert_variant_panel_frequency_key(apps, _schema_editor):
    """ This can be deleted if there is a blat_keys migration after it """
    EvidenceKey = apps.get_model("classification", "EvidenceKey")
    EvidenceKey.objects.get_or_create(
        key="sherloc_summary",
        defaults={
            "evidence_category": "HI",  # interpretation section
            "hide": True,
            "order": 5,
            "value_type": "T",  # free text
            "copy_consensus": False
        }
    )

    EvidenceKey.objects.get_or_create(
        key="reclassification_reason",
        defaults={
            "evidence_category": "HI",  # interpretation section
            "hide": True,
            "order": 6,
            "value_type": "T",  # free text
            "copy_consensus": False
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0038_auto_20210719_0849'),
    ]

    operations = [
        migrations.RunPython(_insert_variant_panel_frequency_key)
    ]
