# Generated by Django 3.1.6 on 2021-07-22 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0039_new_ekey_sherloc_reclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinvarexport',
            options={'verbose_name': 'ClinVar export'},
        ),
        migrations.AlterModelOptions(
            name='clinvarexportsubmission',
            options={'verbose_name': 'ClinVar export submission'},
        ),
        migrations.AlterModelOptions(
            name='clinvarexportsubmissionbatch',
            options={'verbose_name': 'ClinVar Export submission batch'},
        ),
        migrations.AlterField(
            model_name='clinvarexport',
            name='status',
            field=models.CharField(choices=[('N', 'New Submission'), ('C', 'Changes Pending'), ('D', 'Up to Date'), ('E', 'Error')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='clinvarexportsubmission',
            name='submission_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.clinvarexportsubmissionbatch'),
        ),
    ]
