# Generated by Django 3.1.6 on 2021-07-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0040_auto_20210723_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarexportsubmissionbatch',
            name='response_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinvarexportsubmissionbatch',
            name='status',
            field=models.CharField(choices=[('N', 'New Submission'), ('C', 'Changes Pending'), ('D', 'Up to Date'), ('E', 'Error')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='clinvarexportsubmissionbatch',
            name='submitted_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
