# Generated by Django 3.1.6 on 2021-07-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0041_auto_20210723_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinvarexportsubmissionbatch',
            name='status',
            field=models.CharField(choices=[('W', 'Awaiting Upload'), ('U', 'Uploading'), ('S', 'Submitted'), ('R', 'Rejected')], default='W', max_length=1),
        ),
    ]
