# Generated by Django 3.1.6 on 2021-07-23 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0042_auto_20210723_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarallele',
            name='classifications_missing_condition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinvarallele',
            name='last_evaluated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clinvarallele',
            name='submissions_invalid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinvarallele',
            name='submissions_valid',
            field=models.IntegerField(default=0),
        ),
    ]
