# Generated by Django 3.1.6 on 2021-08-04 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0042_auto_20210730_0855'),
        ('classification', '0045_clinvarexport_release_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinvarexportsubmission',
            name='clinvar_export',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.clinvarexport'),
        ),
        migrations.AlterField(
            model_name='clinvarexportsubmissionbatch',
            name='clinvar_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.clinvarkey'),
        ),
    ]
