# Generated by Django 3.1.6 on 2021-08-06 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0046_auto_20210805_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinvarexportsubmissionbatch',
            name='response_json',
        ),
        migrations.RemoveField(
            model_name='clinvarexportsubmissionbatch',
            name='submitted_json',
        ),
        migrations.AddField(
            model_name='clinvarexportsubmission',
            name='response_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinvarexportsubmission',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('S', 'Success'), ('E', 'Error')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='clinvarexportsubmissionbatch',
            name='status',
            field=models.CharField(choices=[('W', 'Awaiting Upload'), ('P', 'Processing'), ('S', 'Submitted'), ('R', 'Rejected')], default='W', max_length=1),
        ),
        migrations.CreateModel(
            name='ClinVarExportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('request_type', models.CharField(choices=[('S', 'Initial Submission'), ('P', 'Polling'), ('F', 'Response Files')], max_length=1)),
                ('request_json', models.JSONField(blank=True, null=True)),
                ('response_status_code', models.IntegerField()),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('submission_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.clinvarexportsubmissionbatch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
