# Generated by Django 3.1.6 on 2021-08-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0042_auto_20210730_0855'),
        ('classification', '0048_auto_20210809_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinVarExportSubmissionBatch',
            new_name='ClinVarExportBatch',
        ),
    ]
