# Generated by Django 3.1.6 on 2021-08-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0050_auto_20210810_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinvarexportbatch',
            options={'verbose_name': 'ClinVar export batch'},
        ),
        migrations.AlterField(
            model_name='clinvarexport',
            name='scv',
            field=models.TextField(blank=True, default=''),
        ),
    ]
