# Generated by Django 3.2.4 on 2021-09-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0051_auto_20210811_1446'),
    ]

    operations = [
        # This has been deleted
    ]
