# Generated by Django 3.2.4 on 2021-09-01 03:29

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_has_legacy_classifications(apps):
    Classification = apps.get_model("classification", "Classification")
    return Classification.objects.all().exists()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0051_auto_20210811_1446'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_legacy_classification_alignment_gap_hgvs_matching"]),
                        test=_test_has_legacy_classifications),
    ]
