# Generated by Django 3.2.6 on 2021-09-02 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0053_uploadedfilelab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfilelab',
            options={'verbose_name': 'Lab Classification File'},
        ),
    ]
