# Generated by Django 3.2.4 on 2021-09-08 04:50

from django.db import migrations


def _insert_lrg_id_key(apps, schema_editor):
    """ This can be deleted if there is a blat_keys migration after it """
    EvidenceKey = apps.get_model("classification", "EvidenceKey")

    EvidenceKey.objects.get_or_create(
        key="lrg_id",
        defaults={
            "evidence_category": "V",  # Variant section
            "order": 4,
            "value_type": "F",  # free text
            "copy_consensus": False,
            "max_share_level": "public",
            "label": "Locus Reference Genomic ID",
            "description": "Locus Reference Genomic (LRG) is a manually curated record that contains stable and thus, un-versioned reference sequences designed specifically for reporting sequence variants with clinical implications.",
            "see": "http://www.lrg-sequence.org/",
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0054_alter_uploadedfilelab_options'),
    ]

    operations = [
        migrations.RunPython(_insert_lrg_id_key)
    ]
