# Generated by Django 3.2.6 on 2021-11-29 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0054_auto_20211122_1407'),
        ('classification', '0058_auto_20211124_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='allele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='snpdb.allele'),
        ),
    ]
