# Generated by Django 3.2.6 on 2021-11-29 02:07

from django.db import migrations


def _set_alleles(apps, schema_editor):
    """ This can be deleted if there is a blat_keys migration after it """
    Classification = apps.get_model("classification", "Classification")
    VariantAllele = apps.get_model("snpdb", "VariantAllele")

    print("About to assign alleles to all classifications with variants")

    # don't want to trigger update date for changing this
    for (count, c) in enumerate(Classification.objects.filter(allele__isnull=True, variant__isnull=False)):
        if va := VariantAllele.objects.filter(variant=c.variant).first():
            c.allele = va.allele
            c.save(update_fields=['allele'])
        if count % 1000 == 0:
            print(f"Processed {count} classifications")

    print("Done")


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0059_classification_allele'),
    ]

    operations = [
        migrations.RunPython(_set_alleles)
    ]
