# Generated by Django 3.2.6 on 2021-12-08 04:21

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0060_one_off_set_alleles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationImportRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('identifier', models.TextField()),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.TextField(choices=[('O', 'Ongoing'), ('C', 'Completed'), ('U', 'Unfinished')], default='O')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clinicalcontext',
            name='pending_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalcontext',
            name='pending_status',
            field=models.TextField(blank=True, choices=[('C', 'Concordant'), ('D', '*Discordant*')], null=True),
        ),
    ]