# Generated by Django 4.0.2 on 2022-03-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0061_auto_20211208_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfilelab',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('AP', 'Automatically-Processed'), ('MP', 'Processed'), ('E', 'Error'), ('M', 'Mapping'), ('I', 'Importing')], default='P', max_length=2),
        ),
    ]
