# Generated by Django 4.0.2 on 2022-03-31 02:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snpdb', '0065_lab_contact_email_lab_contact_name_lab_contact_phone'),
        ('classification', '0062_alter_uploadedfilelab_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFileLab',
            new_name='UploadedClassificationsUnmapped',
        ),
    ]
