# Generated by Django 4.0.2 on 2022-03-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0063_rename_uploadedfilelab_uploadedclassificationsunmapped'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedclassificationsunmapped',
            options={'verbose_name': 'Classification upload file'},
        ),
        migrations.AddField(
            model_name='uploadedclassificationsunmapped',
            name='validation_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedclassificationsunmapped',
            name='validation_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
