# Generated by Django 4.0.2 on 2022-03-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0064_alter_uploadedclassificationsunmapped_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedclassificationsunmapped',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('MP', 'Processed'), ('E', 'Error'), ('M', 'Mapping'), ('I', 'Importing')], default='P', max_length=2),
        ),
    ]
