# Generated by Django 4.0.2 on 2022-04-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0067_alter_uploadedclassificationsunmapped_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationimportrun',
            name='logging_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificationimportrun',
            name='row_count_already_withdrawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificationimportrun',
            name='row_count_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificationimportrun',
            name='row_count_new',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificationimportrun',
            name='row_count_no_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificationimportrun',
            name='row_count_un_withdrawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificationimportrun',
            name='row_count_unknown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificationimportrun',
            name='row_count_update',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificationimportrun',
            name='row_count_withdrawn',
            field=models.IntegerField(default=0),
        ),
    ]
