# Generated by Django 4.0.4 on 2022-04-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0069_classification_last_import_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencekey',
            name='value_type',
            field=models.CharField(blank=True, choices=[('A', 'age'), ('T', 'free text (multi-line)'), ('F', 'free text'), ('S', 'select'), ('M', 'multi-select'), ('B', 'boolean'), ('D', 'date'), ('C', 'criteria'), ('U', 'user'), ('N', 'unit (0 to 1)'), ('I', 'integer'), ('L', 'float')], default='F', max_length=1),
        ),
    ]
