# Generated by Django 4.0.4 on 2022-05-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0070_alter_evidencekey_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedclassificationsunmapped',
            name='effective_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedclassificationsunmapped',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
