# Generated by Django 4.0.4 on 2022-05-10 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0056_one_off_link_hgnc_and_uniprot'),
        ('classification', '0072_one_off_source_id_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='transcript_version_grch37',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_37', to='genes.transcriptversion'),
        ),
        migrations.AddField(
            model_name='classification',
            name='transcript_version_grch38',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_38', to='genes.transcriptversion'),
        ),
    ]
