# Generated by Django 4.0.4 on 2022-05-10 23:50

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def test_has_classifications(apps):
    Classification = apps.get_model("classification", "Classification")
    return Classification.objects.all().exists()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0073_classification_transcript_version_grch37_and_more'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["classifications_cache_transcript_versions"]),
                        test=test_has_classifications)
    ]
