# Generated by Django 4.0.4 on 2022-06-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0076_one_off_manual_populate_clin_sig_buckets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordancereport',
            old_name='continued_discordance_text',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='discordancereport',
            name='notes',
            field=models.TextField(blank=True, default=''),
        )
    ]
