# Generated by Django 4.0.7 on 2022-08-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0079_new_dbnsfp_gene_ekeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordancereport',
            name='continued_discordance_reason',
            field=models.TextField(blank=True, choices=[('U', 'One or more labs was unresponsive'), ('D', 'Different curation methods are being employed'), ('X', 'See notes')], max_length=1, null=True),
        ),
    ]
