# Generated by Django 4.0.7 on 2022-11-22 06:35

from django.db import migrations, models

import classification.models.clinvar_export_models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0080_alter_discordancereport_continued_discordance_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarexport',
            name='submission_grouping_validated',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='clinvarexportbatch',
            name='assertion_criteria',
            field=models.JSONField(default=classification.models.clinvar_export_models.acmg_citation),
        ),
        migrations.AddField(
            model_name='clinvarexportbatch',
            name='release_status',
            field=models.TextField(default='public'),
        ),
        migrations.AddField(
            model_name='clinvarexportsubmission',
            name='submission_grouping',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
