# Generated by Django 4.0.7 on 2022-11-30 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0057_one_off_upgrade_pyhgvs'),
        ('snpdb', '0086_update_spliceai_columns'),
        ('classification', '0081_clinvarexport_submission_grouping_validated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedAlleleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('imported_c_hgvs', models.TextField(blank=True, null=True)),
                ('allele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.allele')),
            ],
        ),
        migrations.RemoveField(
            model_name='classification',
            name='chgvs_grch37',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='chgvs_grch37_full',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='chgvs_grch38',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='chgvs_grch38_full',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='transcript_version_grch37',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='transcript_version_grch38',
        ),
        migrations.CreateModel(
            name='ImportedVariantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('c_hgvs', models.TextField(blank=True, null=True)),
                ('c_hgvs_full', models.TextField(blank=True, null=True)),
                ('genomic_sort', models.TextField(blank=True, null=True)),
                ('allele_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classification.importedalleleinfo')),
                ('gene_symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.genesymbol')),
                ('genome_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.genomebuild')),
                ('transcript_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.transcriptversion')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.variant')),
            ],
            options={
                'unique_together': {('allele_info', 'genome_build')},
            },
        ),
        migrations.AddField(
            model_name='importedalleleinfo',
            name='grch37',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='classification.importedvariantinfo'),
        ),
        migrations.AddField(
            model_name='importedalleleinfo',
            name='grch38',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='classification.importedvariantinfo'),
        ),
        migrations.AddField(
            model_name='importedalleleinfo',
            name='imported_genome_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.genomebuild'),
        ),
        migrations.AddField(
            model_name='classification',
            name='allele_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.importedalleleinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='importedalleleinfo',
            unique_together={('imported_c_hgvs', 'imported_genome_build')},
        ),
    ]
