# Generated by Django 4.0.7 on 2022-12-15 03:05

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _check_has_classifications(apps):
    Classification = apps.get_model("classification", "Classification")
    return Classification.objects.filter(allele_info__isnull=True).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0082_importedalleleinfo_and_more'),
    ]

    operations = [
        ManualOperation(
            task_id=ManualOperation.task_id_manage(["fix_variant_matching", "--extra"]),
            test=_check_has_classifications
        )
    ]
