# Generated by Django 4.0.7 on 2023-01-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0092_tagcolor_created_tagcolor_modified_and_more'),
        ('classification', '0084_alter_importedalleleinfo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importedalleleinfo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='importedalleleinfo',
            name='imported_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='importedalleleinfo',
            unique_together={('imported_c_hgvs', 'imported_g_hgvs', 'imported_transcript', 'imported_genome_build_patch_version')},
        ),
    ]
