# Generated by Django 4.0.7 on 2023-01-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0085_alter_importedalleleinfo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedalleleinfo',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importedalleleinfo',
            name='status',
            field=models.CharField(choices=[('P', 'Processing'), ('I', 'Matched Imported Variant'), ('M', 'Matched All Builds'), ('F', 'Failed')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='importedalleleinfo',
            name='variant_coordinate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
