# Generated by Django 4.0.8 on 2023-01-17 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0087_one_off_set_imported_allele_info_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedAlleleInfoValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('validation_tags', models.JSONField(blank=True, null=True)),
                ('c_hgvs_37', models.TextField(blank=True, null=True)),
                ('c_hgvs_38', models.TextField(blank=True, null=True)),
                ('include', models.BooleanField()),
                ('confirmed', models.BooleanField(blank=True, default=False)),
                ('confirmed_by_note', models.TextField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('imported_allele_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.importedalleleinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='importedalleleinfo',
            name='latest_validation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.importedalleleinfovalidation'),
        ),
    ]
