# Generated by Django 4.0.8 on 2023-01-17 05:00

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _check_has_classifications(apps):
    Classification = apps.get_model("classification", "Classification")
    return Classification.objects.exists()

class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0088_importedalleleinfovalidation_and_more'),
    ]

    operations = [
        ManualOperation(
            task_id=ManualOperation.task_id_manage(["fix_variant_matching", "--revalidate_chgvs"]),
            test=_check_has_classifications
        )
    ]
