# Generated by Django 4.0.8 on 2023-01-22 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0092_tagcolor_created_tagcolor_modified_and_more'),
        ('classification', '0089_one_off_validate_imported_allele_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='classification_import',
        ),
        migrations.AddField(
            model_name='importedalleleinfo',
            name='classification_import',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.classificationimport'),
        ),
        migrations.AddField(
            model_name='importedalleleinfo',
            name='matched_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.variant'),
        ),
    ]
