# Generated by Django 4.0.7 on 2023-02-08 23:05

from django.db import migrations


REDUNDANT_FLAG_TYPES = [
    'classification_matching_variant',
    'classification_matching_variant_warning',
    'classification_transcript_version_change',
    'allele_37_not_38',
    'allele_missing_38',
    'allele_missing_37',
]


def _delete_redundant_flags(apps, _schema_editor):
    FlagType = apps.get_model("flags", "FlagType")
    Flag = apps.get_model("flags", "Flag")

    for type_str in REDUNDANT_FLAG_TYPES:
        if type_obj := FlagType.objects.filter(pk=type_str).first():
            type_obj_count = Flag.objects.filter(flag_type=type_obj).count()
            print(f"{type_str} has {type_obj_count} flags... deleting")
            type_obj.delete()
            # cascade delete will delete all the flags of that type
        else:
            print(f"{type_str} flag already deleted")


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0091_one_off_fix_genomic_sort_order'),
    ]

    operations = [
        migrations.RunPython(_delete_redundant_flags, migrations.RunPython.noop)
    ]
