# Generated by Django 4.0.7 on 2023-02-08 23:05

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _check_has_flags(apps):
    FlagType = apps.get_model("flags", "FlagType")
    return FlagType.objects.filter(id__in=[
        'classification_matching_variant',
        'classification_matching_variant_warning',
        'allele_37_not_38',
        'allele_missing_38',
        'allele_missing_37'
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0091_one_off_fix_genomic_sort_order'),
    ]

    operations = [
        ManualOperation(
            task_id=ManualOperation.task_id_manage(["remove_redundant_flags"]),
            test=_check_has_flags
        )
    ]
