# Generated by Django 4.0.7 on 2023-02-12 23:55
from typing import Dict, Optional, List

from django.db import migrations


def _inject_option_into_evidence_key(apps, _schema_editor, evidence_key_name, option: Dict):
    EvidenceKey = apps.get_model("classification", "EvidenceKey")
    if evidence_key := EvidenceKey.objects.filter(key=evidence_key_name).first():
        options: Optional[List[Dict]]
        if options := evidence_key.options:
            for old_option in options:
                if old_option.get('key') == option.get('key'):
                    print(f"{option.get('key')} already in options")
                    return  # value already tehre
            options.append(option)
            evidence_key.save()
        else:
            print("Evidence key doesn't have any options")
    else:
        print(f"Can't find evidence key {evidence_key_name}")

def _inject_5_prime(apps, _schema_editor):
    return _inject_option_into_evidence_key(
        apps,
        _schema_editor,
        'molecular_consequence',
        {
            "so": "SO:0001988",
            "key": "5_prime_UTR_premature_start_codon_gain_variant",
            "index": 37,
            "label": "5 prime UTR premature start codon gain variant"
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0092_one_off_delete_redundant_flags'),
    ]

    operations = [
        migrations.RunPython(_inject_5_prime)
    ]
