# Generated by Django 4.1.3 on 2023-02-13 04:36

from django.db import migrations

from library.utils.hash_utils import md5sum_str


def _one_off_populate_classification_variant_info_md5(apps, _schema_editor):
    ImportedAlleleInfo = apps.get_model("classification", "ImportedAlleleInfo")

    # There will only ever be g.HGVS or c.HGVS set - so do them separately
    c_records = []
    for iai in ImportedAlleleInfo.objects.filter(imported_c_hgvs__isnull=False, imported_c_hgvs_md5_hash__isnull=True):
        iai.imported_c_hgvs_md5_hash = md5sum_str(iai.imported_c_hgvs)
        c_records.append(iai)

    if c_records:
        print(f"Adding c.HGVS md5sum for {len(c_records)} classifications")
        ImportedAlleleInfo.objects.bulk_update(c_records, fields=["imported_c_hgvs_md5_hash"],
                                               batch_size=2000)

    g_records = []
    for iai in ImportedAlleleInfo.objects.filter(imported_g_hgvs__isnull=False, imported_g_hgvs_md5_hash__isnull=True):
        iai.imported_g_hgvs_md5_hash = md5sum_str(iai.imported_g_hgvs)
        g_records.append(iai)

    if g_records:
        print(f"Adding g.HGVS md5sum for {len(g_records)} classifications")
        ImportedAlleleInfo.objects.bulk_update(g_records, fields=["imported_g_hgvs_md5_hash"],
                                               batch_size=2000)


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0094_alter_importedalleleinfo_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(_one_off_populate_classification_variant_info_md5)
    ]
