# Generated by Django 4.1.5 on 2023-02-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0095_one_off_populate_classification_variant_info_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedalleleinfo',
            name='imported_md5_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
