# Generated by Django 4.1.5 on 2023-02-22 01:25

from django.db import migrations
from django.db.models import F


def _one_off_allele_info_combined(apps, _schema_editor):
    # We've already done the md5sum into the individual fields
    ImportedAlleleInfo = apps.get_model("classification", "ImportedAlleleInfo")

    # c.HGVS
    c_hgvs_qs = ImportedAlleleInfo.objects.filter(imported_c_hgvs_md5_hash__isnull=False)
    c_hgvs_qs.update(imported_md5_hash=F("imported_c_hgvs_md5_hash"))

    # g.HGVS
    g_hgvs_qs = ImportedAlleleInfo.objects.filter(imported_g_hgvs_md5_hash__isnull=False)
    g_hgvs_qs.update(imported_md5_hash=F("imported_g_hgvs_md5_hash"))


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0096_importedalleleinfo_imported_md5_hash'),
    ]

    operations = [
        migrations.RunPython(_one_off_allele_info_combined)
    ]
