# Generated by Django 4.1.5 on 2023-02-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0094_change_variantgridcolumn_annotation_levels'),
        ('classification', '0097_one_off_allele_info_combined'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importedalleleinfo',
            unique_together={('imported_md5_hash', 'imported_transcript', 'imported_genome_build_patch_version')},
        ),
        migrations.RemoveField(
            model_name='importedalleleinfo',
            name='imported_c_hgvs_md5_hash',
        ),
        migrations.RemoveField(
            model_name='importedalleleinfo',
            name='imported_g_hgvs_md5_hash',
        ),
    ]
