# Generated by Django 4.1.4 on 2023-02-25 03:52

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _check_has_non_coding_c_hgvs(apps):
    ResolvedVariantInfo = apps.get_model("classification", "ResolvedVariantInfo")
    rv_qs = ResolvedVariantInfo.objects.filter(allele_info__imported_c_hgvs__icontains='n.', c_hgvs__icontains='c.')
    return rv_qs.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0098_alter_importedalleleinfo_unique_together_and_more'),
    ]

    operations = [
        ManualOperation(
            task_id=ManualOperation.task_id_manage(["fix_variant_matching", "--non-coding"]),
            test=_check_has_non_coding_c_hgvs
        )
    ]
