# Generated by Django 4.1.4 on 2023-02-25 03:52

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0098_alter_importedalleleinfo_unique_together_and_more'),
    ]

    operations = [
        # This is intentionally blank - redundant with 0101 migration
    ]
