# Generated by Django 4.0.7 on 2023-02-26 22:36

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _has_c_hgvs_validation(apps):
    # We've already done the md5sum into the individual fields
    Classification = apps.get_model("classification", "Classification")
    return Classification.objects.filter(evidence__c_hgvs__validation__isnull=False).exists()
    for c in Classification.objects.filter(evidence__c_hgvs__validation__isnull=False):
        c.revalidate()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0098_alter_importedalleleinfo_unique_together_and_more'),
    ]

    operations = [
        ManualOperation(
            task_id=ManualOperation.task_id_manage(["fix_variant_matching", "--revalidate_chgvs"]),
            test=_has_c_hgvs_validation
        )
    ]
