# Generated by Django 4.0.7 on 2023-02-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0099_auto_20230227_0906'),
        ('classification', '0099_one_off_fix_variant_matching_non_coding'),
    ]

    operations = [
    ]
