# Generated by Django 4.1.4 on 2023-03-08 03:50

from django.db import migrations
from django.db.models import Q

from manual.operations.manual_operations import ManualOperation


def _check_has_non_coding_c_hgvs(apps):
    ResolvedVariantInfo = apps.get_model("classification", "ResolvedVariantInfo")

    q1 = Q(allele_info__imported_c_hgvs__icontains='n.', c_hgvs__icontains='c.')
    q2 = Q(allele_info__imported_c_hgvs__icontains='c.', c_hgvs__icontains='n.')
    rv_qs = ResolvedVariantInfo.objects.filter(q1 | q2)
    return rv_qs.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0100_merge_20230227_1009'),
    ]

    operations = [
        ManualOperation(
            task_id=ManualOperation.task_id_manage(["fix_variant_matching", "--non-coding"]),
            test=_check_has_non_coding_c_hgvs
        )
    ]
