# Generated by Django 4.0.7 on 2023-05-11 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
        ('classification', '0102_one_off_update_ekey_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordancereport',
            name='discussions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.discussedobject'),
        ),
    ]
