# Generated by Django 4.0.7 on 2023-05-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0103_discordancereport_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordancereport',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
