# Generated by Django 4.2.2 on 2023-08-14 23:42
from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_fix_orphanet_revalidation(apps):
    Classification = apps.get_model("classification", "Classification")
    search_term_orpha = "ORPHANET"
    return Classification.objects.filter(evidence__search_terms__icontains=search_term_orpha).exists()

class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0104_discordancereport_admin_note'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_orphanet_revalidation"]),
                        test=_test_fix_orphanet_revalidation)
    ]
