# Generated by Django 4.2.2 on 2023-08-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0098_columns_collections_add_internally_classified_labs'),
        ('classification', '0105_fix_orphanet_revalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordanceNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.TextField(blank=True, null=True)),
                ('notification_sent_date', models.DateTimeField(blank=True, null=True)),
                ('discordance_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.discordancereport')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.lab')),
            ],
        ),
    ]
