# Generated by Django 4.2.2 on 2023-08-22 02:14

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0106_discordancenotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordancenotification',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='discordancenotification',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discordancenotification',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
