# Generated by Django 4.2.2 on 2023-08-30 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snpdb', '0098_columns_collections_add_internally_classified_labs'),
        ('classification', '0107_update_ekey_molecular_consequence_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordanceReportTriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('triage_status', models.TextField(choices=[('P', 'Pending Review'), ('F', 'Reviewed - Will Amend'), ('D', 'Reviewed - For Joint Discussion'), ('R', 'Reviewed - Confident in Classification'), ('X', 'Low Penetrance/Risk Allele etc'), ('C', 'Discordance Closed - No Review Required')], default='P', max_length=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('triage_date', models.DateField(blank=True, null=True)),
                ('discordance_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.discordancereport')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.lab')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('discordance_report', 'lab')},
            },
        ),
    ]
