# Generated by Django 4.2.2 on 2023-09-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0108_discordancereporttriage'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordancereporttriage',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discordancereporttriage',
            name='triage_status',
            field=models.TextField(choices=[('P', 'Pending Triage'), ('F', 'Will Amend'), ('D', 'For Joint Discussion'), ('R', 'Confident in Classification'), ('X', 'Low Penetrance/Risk Allele etc')], default='P', max_length=1),
        ),
    ]
