# Generated by Django 4.2.2 on 2023-09-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0109_condition_matching_override_blank condition'),
        ('classification', '0109_discordancereporttriage_closed_and_more'),
    ]

    operations = [
    ]
