# Generated by Django 4.2.5 on 2023-10-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0112_one_off_check_variant_classification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedclassificationsunmapped',
            name='file_type_override',
            field=models.TextField(blank=True, default=''),
        ),
    ]
