# Generated by Django 4.2.5 on 2023-10-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0105_alter_settingsoverride_default_genome_build_and_more'),
        ('classification', '0113_uploadedclassificationsunmapped_file_type_override'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clinicalcontext',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classification',
            name='allele_origin_bucket',
            field=models.CharField(choices=[('G', 'Germline'), ('S', 'Somatic'), ('U', 'Unknown')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='clinicalcontext',
            name='allele_origin_bucket',
            field=models.CharField(choices=[('G', 'Germline'), ('S', 'Somatic'), ('U', 'Unknown')], default='G', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalcontext',
            unique_together={('allele', 'allele_origin_bucket', 'name')},
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['share_level'], name='classificat_share_l_15b182_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['withdrawn'], name='classificat_withdra_52a264_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalcontext',
            index=models.Index(fields=['name'], name='classificat_name_b32d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalcontext',
            index=models.Index(fields=['status'], name='classificat_status_c5ca44_idx'),
        ),
    ]
