# Generated by Django 4.2.5 on 2023-10-24 22:25

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0114_alter_clinicalcontext_unique_together_and_more'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(
            ["classification_set_allele_context"]
        ))
    ]
