# Generated by Django 4.2.5 on 2023-10-27 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0114_classification_withdraw_reason'),
        ('classification', '0115_auto_20231025_0855'),
    ]

    operations = [
    ]
