# Generated by Django 4.2.5 on 2023-11-09 23:11

from django.db import migrations
from classification.evidence_key_rename import EvidenceKeyRenamer

__ACMG_KEYS = [
    "ba1",
    "bp1",
    "bp2",
    "bp3",
    "bp4",
    "bp5",
    "bp6",
    "bp7",
    "bs1",
    "bs2",
    "bs3",
    "bs4",
    "pm1",
    "pm2",
    "pm3",
    "pm4",
    "pm5",
    "pm6",
    "pp1",
    "pp2",
    "pp3",
    "pp4",
    "pp5",
    "ps1",
    "ps2",
    "ps3",
    "ps4",
    "pvs1"
]


def _namespace_acmg_keys(apps, schema):
    acmg_key_dict = {}
    for key in __ACMG_KEYS:
        acmg_key_dict[key] = f"acmg:{key}"
    EvidenceKeyRenamer.rename(apps, key_dict=acmg_key_dict)


def _reverse_namespace_acmg_keys(apps, schema):
    acmg_key_dict = {}
    for key in __ACMG_KEYS:
        acmg_key_dict[f"acmg:{key}"] = key
    EvidenceKeyRenamer.rename(apps, key_dict=acmg_key_dict)


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0118_auto_20231031_1528'),
    ]

    operations = [
        migrations.RunPython(code=_namespace_acmg_keys, reverse_code=_reverse_namespace_acmg_keys)
    ]
