# Generated by Django 4.2.5 on 2023-11-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0121_clinvarallele_allele_origin_bucket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarexportbatch',
            name='allele_origin_bucket',
            field=models.CharField(choices=[('G', 'Germline'), ('S', 'Somatic'), ('U', 'Unknown')], default='G', max_length=1),
        ),
    ]
