# Generated by Django 4.2.5 on 2023-12-05 00:40

from django.db import migrations


def _update_clinical_significance_to_classification(apps, _schema):
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')
    clin_sig = EvidenceKey.objects.get(key='clinical_significance')
    clin_sig.label = "Classification"
    clin_sig.sub_label = "formerly Clinical Significance"
    if help_text := clin_sig.description:
        if "clinical significance" in help_text:
            help_text = "<i>Note this field was previously called \"Clinical Significance\".</i><br/>" + help_text.replace("clinical significance", "classification")
        clin_sig.description = help_text
    clin_sig.save()

    FlagType = apps.get_model("flags", "FlagType")
    clin_sig_change = FlagType.objects.get(id="classification_significance_change")
    clin_sig_change.label = "Classification Change"
    clin_sig_change.description = "This classification record has had its classification changed since it was last published. Please document here what caused the change."
    clin_sig_change.help_text = "This classification record has had its classification changed since it was last published."
    clin_sig_change.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0122_clinvarexportbatch_allele_origin_bucket'),
    ]

    operations = [
        migrations.RunPython(_update_clinical_significance_to_classification)
    ]
