# Generated by Django 4.2.5 on 2024-01-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0124_ekey_provide_horak_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencekey',
            name='namespace_overrides',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
