# Generated by Django 4.2.5 on 2024-01-16 01:55

from django.db import migrations


def _update_condition_for_somatic(apps, schema):
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')
    condition = EvidenceKey.objects.get(key='condition')
    condition.namespace_overrides = {
        "somatic": {
            "label": "Cancer Type",
            "sub_label": "Condition"
        }
    }
    condition.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0125_evidencekey_namespace_overrides'),
    ]

    operations = [
        migrations.RunPython(_update_condition_for_somatic)
    ]
