# Generated by Django 4.2.5 on 2024-01-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0115_new_vep_110_ekeys'),
        ('classification', '0126_ekey_update_condition_once_off'),
    ]

    operations = [
    ]
