# Generated by Django 4.2.5 on 2024-02-05 01:03

from django.db import migrations

from classification.evidence_key_rename import OptionUpdator


def _tweak_somatic_e_keys(apps, _schema_editor):
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')

    option_updator = OptionUpdator(EvidenceKey.objects.get(key='assertion_method'))
    option_updator.set_attributes("horak", label="ClinGen/CGC/VICC 2022", mandatory=True)
    option_updator.save()

    for horak_key in EvidenceKey.objects.filter(key__startswith="horak:", value_type="C"):
        horak_key.crit_allows_override_strengths = True
        horak_key.save()

    clinical_significance = EvidenceKey.objects.get(key="clinical_significance")
    clinical_significance.description = \
"""
The classification of the specified variant in the context of the condition analysed. Values are as specified by ACMG/AMP and ClinGen/CGC/VICC 2022 with an optional extension to VUS.<br/>
Options are
<ul class="compact">
<li>Benign</li>
<li>Likely Benign</li>
<li>VUS *</li>
<li>Likely Pathogenic/Oncogenic</li>
<li>Pathogenic/Oncogenic</li>
</ul>
* VUS can optionally be subdivided into the following
<ul class="compact">
<li>VUS-C : Variant of unknown significance with trending towards benign</li>
<li>VUS-B : Variant of unknown significance</li>
<li>VUS-A : Variant of unknown significance with trending towards pathogenic/oncogenic</li>
</ul>
Additional options may include
<ul class="compact">
<li>Artefact</li>
<li>Drug Response</li>
<li>Risk Factor</li>
</ul>

See <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4544753/">ACMG/AMP</a> for widely used Germline guidelines or
See <a href="https://pubmed.ncbi.nlm.nih.gov/35101336/">ClinGen/CGC/VICC 2022</a> for widely used Somatic guidelines
"""
    clinical_significance.see = None
    clinical_significance.save()

    condition = EvidenceKey.objects.get(key="condition")
    condition.namespace_overrides = {
      "somatic": {
        "sub_label": "or Cancer type"
      }
    }
    condition.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0127_merge_20240129_0943'),
    ]

    operations = [
        migrations.RunPython(_tweak_somatic_e_keys, None)
    ]
