# Generated by Django 4.2.5 on 2024-02-15 23:52

from django.db import migrations


def _tweak_assertion_method(apps, _schema_editor):
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')
    assertion_method = EvidenceKey.objects.get(key='assertion_method')
    assertion_method.value_type = "M"  # for multi-select
    assertion_method.save()

class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0128_ekey_update_somatic_tweaks'),
    ]

    operations = [
        migrations.RunPython(_tweak_assertion_method)
    ]
