# Generated by Django 4.2.5 on 2024-02-22 00:20

from django.db import migrations

from classification.evidence_key_rename import OptionUpdator


def _tweak_somatic_e_keys(apps, schema_editor):
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')

    option_updator = OptionUpdator(EvidenceKey.objects.get(key='assertion_method'))
    option_updator.ensure_option({"key": "amp", "label": "AMP/ASCO/CAP 2017", "namespaces": ["amp"]})
    option_updator.save()

    som_clin_sig = EvidenceKey.objects.get(key="somatic:clinical_significance")
    som_clin_sig.description =\
"""
Evidence-based variant categorisation. Somatic variants are classified into tiers based on their level of clinical significance in cancer diagnosis, prognosis, and/or therapeutics.<br/>
Tier I: Variants of Strong Clinical Significance<br/>
Tier II: Variants of Potential Clinical Significance<br/>
Tier III: Variants of Unknown Clinical Significance<br/>
Tier IV: Benign or Likely Benign Variants<br/>
Tier I/II: If specific tier of clinical significance is not denoted further than I/II as a group
"""
    som_clin_sig.save()

    option_updator = OptionUpdator(EvidenceKey.objects.get(key='sample_type'))
    option_updator.ensure_option({"key": "skin_biopsy", "index": 9})
    option_updator.ensure_option({"key": "cf_dna", "label": "cfDNA", "index": 10})
    option_updator.ensure_option({"key": "bone marrow", "index": 11})
    option_updator.set_attributes("tumor", label="Tumour")
    option_updator.alphabetical_order()
    option_updator.save()

    EvidenceKey.objects.get_or_create(key="somatic:tumor_cellularity", defaults={
        "label": "Tumour Cellularity",
        "evidence_category": "HT",
        "value_type": "N",
        "order": 0,
        "copy_consensus": False,
    })


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0129_ekey_multiple_assertion_methods'),
    ]

    operations = [
        migrations.RunPython(_tweak_somatic_e_keys)
    ]
