# Generated by Django 4.2.5 on 2024-02-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0130_ekey_update_somatic_tweaks_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencekey',
            name='evidence_category',
            field=models.CharField(choices=[('V', 'Variant'), ('H', 'Gene'), ('HP', 'Patient'), ('HT', 'Test'), ('P', 'Population Data'), ('CP', 'Computational and Predictive Data'), ('F', 'Functional Data'), ('S', 'Segregation Data'), ('D', 'De novo Data'), ('A', 'Allelic Data'), ('DB', 'Other Database'), ('O', 'Other Data'), ('L', 'Literature'), ('SC', 'Somatic Clinical Significance Evidence'), ('HI', 'Interpretation'), ('SO', 'Sign Off')], max_length=3),
        ),
    ]
