# Generated by Django 4.2.5 on 2024-02-28 03:43

from django.db import migrations


def _add_evidence_keys(apps, _schema_editor):
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')
    EvidenceKey.objects.filter(key__startswith='amp:level_').delete()

    evidence_key_datas = \
    [{
		"key": "amp:level_a",
		"order": 2,
		"label": "Level A",
		"description": "Biomarkers that predict response or resistance to US FDA-approved therapies for a specific type of tumour or have been included in professional guidelines as therapeutic, diagnostic, and/or prognostic biomarkers for specific types of tumours.\r\n\r\nSee <a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5707196/\">AMP/ASCO/CAP 2017</a>",
		"options": [
			{
				"key": "therapeutic",
				"index": 1
			},
			{
				"key": "diagnostic",
				"index": 2
			},
			{
				"key": "prognostic",
				"index": 3
			},
			{
				"key": "unspecified",
				"index": 4
			}
		],
		"evidence_category": "SC",
		"value_type": "M",
		"sub_label": "Evidence of strong clinical significance",
		"copy_consensus": True
	},
	{
		"key": "amp:level_b",
		"order": 2,
		"label": "Level B",
		"description": "Biomarkers that predict response or resistance to a therapy, or have diagnostic and/or prognostic significance, for a specific type of tumour based on well-powered studies with consensus from experts in the field.\r\n\r\nSee <a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5707196/\">AMP/ASCO/CAP 2017</a>",
		"options": [
			{
				"key": "therapeutic",
				"index": 1
			},
			{
				"key": "diagnostic",
				"index": 2
			},
			{
				"key": "prognostic",
				"index": 3
			},
			{
				"key": "unspecified",
				"index": 4
			}
		],
		"evidence_category": "SC",
		"value_type": "M",
		"sub_label": "Evidence of strong clinical significance",
		"copy_consensus": True
	},
	{
		"key": "amp:level_c",
		"order": 2,
		"label": "Level C",
		"description": "Biomarkers that predict response or resistance to therapies approved by FDA or professional societies for a different tumour type (i.e. off-label use of a drug), serve as inclusion criteria for clinical trials, or have diagnostic and/or prognostic significance based on the results of multiple small studies.\r\n\r\nSee <a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5707196/\">AMP/ASCO/CAP 2017</a>",
		"options": [
			{
				"key": "therapeutic",
				"index": 1
			},
			{
				"key": "diagnostic",
				"index": 2
			},
			{
				"key": "prognostic",
				"index": 3
			},
			{
				"key": "unspecified",
				"index": 4
			}
		],
		"evidence_category": "SC",
		"value_type": "M",
		"sub_label": "Evidence of potential clinical significance",
		"copy_consensus": True
	},
	{
		"key": "amp:level_d",
		"order": 2,
		"label": "Level D",
		"description": "Biomarkers that show plausible therapeutic significance based on preclinical studies, or may assist disease diagnosis and/or prognosis themselves or along with other biomarkers based on small studies or multiple case reports with no consensus.\r\n\r\nSee <a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5707196/\">AMP/ASCO/CAP 2017</a>",
		"options": [
			{
				"key": "therapeutic",
				"index": 1
			},
			{
				"key": "diagnostic",
				"index": 2
			},
			{
				"key": "prognostic",
				"index": 3
			},
			{
				"key": "unspecified",
				"index": 4
			}
		],
		"evidence_category": "SC",
		"value_type": "M",
		"allow_custom_values": 0,
		"sub_label": "Evidence of potential clinical significance",
		"copy_consensus": True
	}]

    for evidence_key_data in evidence_key_datas:
        EvidenceKey.objects.create(**evidence_key_data)


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0131_alter_evidencekey_evidence_category'),
    ]

    operations = [
        migrations.RunPython(_add_evidence_keys)
    ]
