# Generated by Django 4.2.5 on 2024-04-17 04:53

from django.db import migrations


def _new_ekey_testing_context(apps, _schema_editor):
    EvidenceKey = apps.get_model("classification", "EvidenceKey")
    # test section
    EvidenceKey.objects.create(
        key="somatic:testing_context",
        label="Testing Context",
        sub_label="Somatic",
        value_type="S",
        options=[
            {"key": "solid_tumor", "label": "Solid Tumour", "index": 1},
            {"key": "haematology", "index": 2},
            {"key": "non_cancer_somatic", "label": "Non-Cancer Somatic", "index": 3}
        ],
        evidence_category="HT"
    )

def _delete_new_ekey(apps, _schema_editor):
    EvidenceKey = apps.get_model("classification", "EvidenceKey")
    EvidenceKey.objects.filter(key="somatic:testing_context").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0135_fix_legacy_imported_allele_info_hgvs_error_provided_reference_length'),
    ]

    operations = [
        migrations.RunPython(_new_ekey_testing_context, _delete_new_ekey)
    ]
