# Generated by Django 4.2.10 on 2024-05-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0136_somatic_testing_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolvedvariantinfo',
            old_name='c_hgvs_full',
            new_name='c_hgvs_compat',
        ),
    ]
