# Generated by Django 4.2.10 on 2024-05-27 02:24

from django.db import migrations


def _rename_flag_type(apps, _schema_editor):
    FlagType = apps.get_model("flags", "FlagType")
    # test section
    if ft := FlagType.objects.filter(id="classification_significance_change").first():
        ft.label = "Assertion Change"
        ft.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0137_rename_c_hgvs_full_resolvedvariantinfo_c_hgvs_compat'),
    ]

    operations = [
        migrations.RunPython(_rename_flag_type, None)
    ]
