# Generated by Django 4.2.10 on 2024-05-29 04:26

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _has_classifications(apps):
    # Only fixes the allele origin bucket of existing classifications - none on a fresh install
    Classification = apps.get_model("classification", "Classification")
    return Classification.objects.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0138_auto_20240527_1154'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(
            ["classification_set_allele_context"]
        ), test=_has_classifications)
    ]
