# Generated by Django 4.2.10 on 2024-06-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0139_once_off_re_run_allele_origin_fix'),
    ]

    # The ManualOperation registering 'classification_populate_sort_orders' is neutralised: the column
    # it populated (somatic_clinical_significance_sort) was dropped again in
    # 0155_allelegrouping_alleleorigingrouping_and_more (sorting moved to Classification.summary), so the
    # command could only ever fail. The command has been deleted, so orphaned task rows in existing DBs
    # are cleared by manual/0004_complete_obsolete_manual_tasks (deleted command -> obsolete).
    operations = [
        migrations.AddField(
            model_name='classificationmodification',
            name='somatic_clinical_significance_sort',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
