# Generated by Django 4.2.10 on 2024-06-14 01:04

from django.db import migrations, models

from manual.operations.manual_operations import ManualOperation


def _has_classification_modifications(apps):
    # Only populates the sort column on existing modifications - none on a fresh install
    ClassificationModification = apps.get_model("classification", "ClassificationModification")
    return ClassificationModification.objects.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0139_once_off_re_run_allele_origin_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationmodification',
            name='somatic_clinical_significance_sort',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        ManualOperation(task_id=ManualOperation.task_id_manage(
            ["classification_populate_sort_orders"]
        ), test=_has_classification_modifications)
    ]
