# Generated by Django 4.2.10 on 2024-06-14 01:04

from django.db import migrations

# Accidental checked in migration, does nothing

class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0140_classificationmodification_somatic_clinical_significance_sort'),
    ]

    operations = [
    ]
