# Generated by Django 4.2.9 on 2024-06-26 04:17

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0142_importedalleleinfo_dirty_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='HGVSConverterVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hgvs_converter_type', models.TextField()),
                ('version', models.TextField()),
                ('method', models.TextField()),
                ('code_git_hash', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resolvedvariantinfo',
            name='c_hgvs_converter_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classification.hgvsconverterversion'),
        ),
    ]
