# Generated by Django 4.2.10 on 2024-07-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0144_one_off_populate_historical_resolved_variant_hgvsconverter_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedalleleinfo',
            name='hgvs_converter_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classification.hgvsconverterversion'),
        ),
    ]
