# Generated by Django 4.2.10 on 2024-07-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0145_importedalleleinfo_hgvs_converter_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='hgvsconverterversion',
            name='used_converter_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
