# Generated by Django 4.2.10 on 2024-07-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0147_one_off_populate_hgvsconverterversion_used_converter_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hgvsconverterversion',
            unique_together={('hgvs_converter_type', 'version', 'used_converter_type', 'code_git_hash')},
        ),
        migrations.RemoveField(
            model_name='hgvsconverterversion',
            name='method',
        ),
    ]
