# Generated by Django 4.2.9 on 2024-07-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0148_alter_hgvsconverterversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedalleleinfo',
            name='variant_coordinate_normalized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
