# Generated by Django 4.2.9 on 2024-07-10 00:31

from django.db import migrations
from django.db.models import F


def _one_off_populate_imported_allele_info_normalized_variant_coordinate(apps, schema_editor):
    """ https://github.com/SACGF/variantgrid_private/issues/3670 - normalization used to not work
        So anything that has gone through historically was not changed by normalization - thus we can just assign
        the un-normalized variant """
    ImportedAlleleInfo = apps.get_model('classification', 'ImportedAlleleInfo')
    ImportedAlleleInfo.objects.all().update(variant_coordinate_normalized=F("variant_coordinate"))


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0149_importedalleleinfo_variant_coordinate_normalized'),
    ]

    operations = [
        migrations.RunPython(_one_off_populate_imported_allele_info_normalized_variant_coordinate)
    ]
