# Generated by Django 4.2.11 on 2024-07-22 03:25

from django.db import migrations

from classification.evidence_key_rename import OptionUpdator


def inject_tier_1_2(apps, _schema_editor):
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')
    clin_sig = EvidenceKey.objects.get(key='somatic:clinical_significance')

    option_updator = OptionUpdator(clin_sig)
    option_updator.ensure_option(
        {
            "key": "tier_1_or_2",
            "tier": "1",
            "index": 5,
            "label": "Tier I / II",
            "aliases": ["1 or 2"]
        }
    )
    option_updator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0150_one_off_populate_imported_allele_info_normalized_variant_coordinate'),
    ]

    operations = [
        migrations.RunPython(inject_tier_1_2)
    ]
