# Generated by Django 4.2.11 on 2024-07-31 01:02

from django.db import migrations


def add_evidence_key(apps, _schema_editor):
    data = {
        "key": "allele_origin_confirmation",
        "order": 12,
        "evidence_category": "V",
        "value_type": "S",
        "description": "Paired or follow up testing to confirm allele origin of variant.",
        "options": [
            {
                "key": "confirmed",
                "index": 1
            },
            {
                "key": "unconfirmed",
                "index": 2
            }
        ],
        "copy_consensus": False
    }
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')
    EvidenceKey.objects.get_or_create(key="allele_origin_confirmation", defaults=data)


def remove_evidence_key(apps, _schema_editor):
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')
    if ek := EvidenceKey.objects.filter(key="allele_origin_confirmation").first():
        ek.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0151_one_off_tier_1_2'),
    ]

    operations = [
        migrations.RunPython(add_evidence_key, remove_evidence_key)
    ]
