# Generated by Django 4.2.15 on 2024-09-24 04:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0150_rename_cachedgeneratedfile2_cachedgeneratedfile'),
        ('classification', '0154_alter_importedalleleinfo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlleleGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('allele', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snpdb.allele')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlleleOriginGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('allele_origin_bucket', models.CharField(choices=[('G', 'Germline'), ('S', 'Somatic'), ('U', 'Unknown')], max_length=1)),
                ('overlap_status', models.IntegerField(choices=[(0, 'No Shared Records'), (10, 'Single Shared Submitter'), (20, 'Multiple Submitters'), (30, 'Agreement'), (40, 'Confidence'), (50, 'Discordance'), (60, 'Discordance')], default=0)),
                ('dirty', models.BooleanField(default=True)),
                ('classification_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('somatic_clinical_significance_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('allele_grouping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.allelegrouping')),
            ],
            options={
                'unique_together': {('allele_grouping', 'allele_origin_bucket')},
            },
        ),
        migrations.CreateModel(
            name='ClassificationGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('allele_origin_bucket', models.CharField(choices=[('G', 'Germline'), ('S', 'Somatic'), ('U', 'Unknown')], max_length=1)),
                ('share_level', models.CharField(choices=[('user', 'CURRENT_USER'), ('lab', 'LAB'), ('institution', 'INSTITUTION'), ('logged_in_users', 'ALL_USERS'), ('public', 'PUBLIC')], max_length=16)),
                ('quality_level', models.CharField(choices=[('S', 'Standard'), ('L', 'Legacy'), ('I', 'Incomplete')], default='S', max_length=1)),
                ('classification_bucket', models.CharField(choices=[('B', 'Benign'), ('V', 'VUS'), ('P', 'Pathogenic'), ('O', 'Oncogenic'), ('X', 'Other'), ('C', 'Conflicting'), ('N', 'No Data')], default='N', max_length=1)),
                ('classification_count', models.IntegerField(default=0)),
                ('dirty', models.BooleanField(default=True)),
                ('classification_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('somatic_clinical_significance_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('zygosity_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('latest_criteria', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('latest_curation_date', models.DateField(blank=True, null=True)),
                ('somatic_clinical_significance_sort', models.IntegerField(blank=True, db_index=True, null=True)),
                ('classification_sort_value', models.TextField(blank=True, null=True)),
                ('allele_origin_grouping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.alleleorigingrouping')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.lab')),
                ('latest_allele_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.importedalleleinfo')),
                ('latest_classification_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.classificationmodification')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassificationGroupingSearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('term', models.TextField()),
                ('term_type', models.CharField(choices=[('CR_ID', 'Classification Record ID'), ('CR_LAB_ID', 'Classification Lab Record ID'), ('SOURCE_ID', 'Classification Source ID'), ('CON_ID', 'Condition ID'), ('CON_TEXT', 'Condition Text'), ('SCV', 'Clinvar SCV'), ('GENE_SYMBOL', 'Gene Symbol'), ('USER', 'User'), ('DR', 'Discordance Report'), ('PATIENT_ID', 'Patient ID'), ('SAMPLE_ID', 'Sample ID')], max_length=20)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('grouping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.classificationgrouping')),
            ],
            options={
                'unique_together': {('grouping', 'term', 'term_type')},
            },
        ),
        migrations.CreateModel(
            name='ClassificationGroupingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.classification')),
                ('grouping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.classificationgrouping')),
            ],
            options={
                'unique_together': {('grouping', 'classification')},
            },
        ),
    ]
