# Generated by Django 4.2.15 on 2024-09-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0155_classificationgrouping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationgrouping',
            name='classification_sort_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationgrouping',
            name='somatic_clinical_significance_sort',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
