# Generated by Django 4.2.15 on 2024-11-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0155_allelegrouping_alleleorigingrouping_and_more'),
        ('classification', '0155_ekey_allele_origin_germline_somatic_only'),
    ]

    operations = [
    ]
