# Generated by Django 4.2.15 on 2024-09-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0155_allelegrouping_alleleorigingrouping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationgroupingsearchterm',
            name='term_type',
            field=models.CharField(choices=[('CON_ID', 'Condition ID'), ('SCV', 'Clinvar SCV'), ('GENE_SYMBOL', 'Gene Symbol'), ('DR', 'Discordance Report')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='classificationgroupingsearchterm',
            index=models.Index(fields=['term_type', 'term'], name='classificat_term_ty_e67ad5_idx'),
        ),
    ]
