# Generated by Django 4.2.15 on 2024-09-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0155_allelegrouping_alleleorigingrouping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alleleorigingrouping',
            name='overlap_status',
            field=models.IntegerField(choices=[(0, 'No Shared Records'), (10, 'Single Shared Submitter'), (20, 'Multiple Submitters'), (30, 'Agreement'), (40, 'Confidence'), (50, 'Discordance'), (60, 'Discordance')], default=0),
        ),
    ]
