# Generated by Django 4.2.15 on 2024-09-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0156_alter_classificationgroupingsearchterm_term_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alleleorigingrouping',
            name='classification_values',
        ),
        migrations.RemoveField(
            model_name='alleleorigingrouping',
            name='somatic_clinical_significance_values',
        ),
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='classification_sort_value',
        ),
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='classification_values',
        ),
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='somatic_clinical_significance_sort',
        ),
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='somatic_clinical_significance_values',
        ),
        migrations.RemoveField(
            model_name='classificationmodification',
            name='somatic_clinical_significance_sort',
        ),
        migrations.AddField(
            model_name='classification',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='classificationgrouping',
            name='classification_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='classificationgrouping',
            name='conflicting_ratings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classificationgrouping',
            name='somatic_clinical_significance',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alleleorigingrouping',
            name='allele_origin_bucket',
            field=models.CharField(choices=[('G', 'Germline'), ('S', 'Somatic'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['allele_origin_bucket'], name='classificat_allele__5ea017_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(models.F('summary__classification_sort'), name='summary__csort_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(models.F('summary__somatic_sort'), name='summary__ssort_idx'),
        ),
    ]
