# Generated by Django 4.2.15 on 2024-09-09 04:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0156_alter_alleleorigingrouping_overlap_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alleleorigingrouping',
            name='somatic_clinical_significance_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
