# Generated by Django 4.2.15 on 2024-11-19 00:28

from django.db import migrations

from classification.evidence_key_rename import EvidenceKeyRenamer, OptionUpdator


def _migrate_testing_context(apps, schema):
    EvidenceKeyRenamer.rename(apps, old_key="somatic:testing_context", new_key="testing_context")
    e_key = apps.get_model('classification', 'EvidenceKey').objects.get(key="testing_context")
    e_key.sub_label = None
    e_key.save()
    options = OptionUpdator(e_key=e_key)
    options.ensure_option({"key": "vascular", "label": "Vascular malformation & overgrowth"})
    options.ensure_option({"key": "suspected_mosaicism", "label": "Suspected mosaicism"})
    options.ensure_option({"key": "diagnostic_germline", "label": "Diagnostic germline"})
    options.ensure_option({"key": "reproductive_carrier_screening", "label": "Reproductive carrier screening"})
    options.ensure_option({"key": "other", "label": "Other"})
    options.alphabetical_order()
    options.save()


def _reverse_migrate_testing_context(apps, schema):
    EvidenceKeyRenamer.rename(apps, old_key="testing_context", new_key="somatic:testing_context")
    e_key = apps.get_model('classification', 'EvidenceKey').objects.get(key="somatic:testing_context")
    e_key.sub_label = "Somatic"
    e_key.save()
    options = OptionUpdator(e_key=e_key)
    options.remove_options(set(["vascular", "suspected_mosaicism", "diagnostic_germline", "reproductive_carrier_screening", "other"]))
    options.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0156_merge_20241119_0955'),
    ]

    operations = [
        migrations.RunPython(_migrate_testing_context, _reverse_migrate_testing_context),
    ]
