# Generated by Django 4.2.15 on 2024-09-03 00:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0156_classificationgrouping_classification_sort_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationgrouping',
            name='classification_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='classificationgrouping',
            name='latest_criteria',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='classificationgrouping',
            name='somatic_clinical_significance_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='classificationgrouping',
            name='zygosity_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
