# Generated by Django 4.2.15 on 2024-09-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0157_alleleorigingrouping_somatic_clinical_significance_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationgroupinggenesymbol',
            name='from_allele',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classificationgroupinggenesymbol',
            name='from_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classificationgroupinggenesymbol',
            name='from_normalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classificationgroupinggenesymbol',
            name='from_transcript',
            field=models.BooleanField(default=False),
        ),
    ]
