# Generated by Django 4.2.17 on 2025-02-03 22:41

from django.db import migrations

from classification.evidence_key_rename import OptionUpdator


def _ekey_allele_origin_germline_somatic_only(apps, _schema_editor):
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')
    clin_sig = EvidenceKey.objects.get(key='clinical_significance')

    # P/O LP/LO VUS A VUS B VUS VUS C LB B
    #I think things like drug response should be sorted below benign like Prod is currently

    option_updator = OptionUpdator(clin_sig)
    option_updator.set_attributes("D", sort_order=1)
    option_updator.set_attributes("R", sort_order=2)
    option_updator.set_attributes("B", sort_order=3)
    option_updator.set_attributes("LB", sort_order=4)
    option_updator.set_attributes("VUS_C", sort_order=5)
    option_updator.set_attributes("VUS", sort_order=6)
    option_updator.set_attributes("VUS_B", sort_order=7)
    option_updator.set_attributes("VUS_A", sort_order=8)
    option_updator.set_attributes("LO", sort_order=9)
    option_updator.set_attributes("LP", sort_order=9)
    option_updator.set_attributes("O", sort_order=10)
    option_updator.set_attributes("P", sort_order=10)
    option_updator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0157_auto_20241119_1058'),
    ]

    operations = [
        migrations.RunPython(_ekey_allele_origin_germline_somatic_only)
    ]
