# Generated by Django 4.2.15 on 2024-10-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0157_remove_alleleorigingrouping_classification_values_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='classification',
            name='summary__csort_idx',
        ),
        migrations.RemoveIndex(
            model_name='classification',
            name='summary__ssort_idx',
        ),
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='classification_value',
        ),
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='somatic_clinical_significance',
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(models.F('summary__pathogenicity__sort'), name='summary__p_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(models.F('summary__somatic__sort'), name='summary__s_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(models.F('summary__date__value'), name='summary__d_sort_idx'),
        ),
    ]
