# Generated by Django 4.2.15 on 2024-10-20 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0158_remove_classification_summary__csort_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='latest_criteria',
        ),
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='latest_curation_date',
        ),
    ]
