# Generated by Django 4.2.17 on 2025-02-05 03:05

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _has_classifications(apps):
    # Builds groupings/summaries for existing classifications - none on a fresh install
    Classification = apps.get_model("classification", "Classification")
    return Classification.objects.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0158_germline_evidence_key_sorting'),
    ]

    operations = [
        ManualOperation.operation_manage(["classification_groupings", "--summary", "--all"],
                                         test=_has_classifications)
    ]
