# Generated by Django 4.2.15 on 2024-09-24 03:26

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0158_classificationgroupinggenesymbol_from_allele_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationGroupingSearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('term', models.TextField()),
                ('term_type', models.CharField(choices=[('CR_ID', 'Classification Record ID'), ('CR_LAB_ID', 'Classification Lab Record ID'), ('SOURCE_ID', 'Classification Source ID'), ('CON_ID', 'Condition ID'), ('CON_TEXT', 'Condition Text'), ('SCV', 'Clinvar SCV'), ('GENE_SYMBOL', 'Gene Symbol'), ('USER', 'User'), ('DR', 'Discordance Report'), ('PATIENT_ID', 'Patient ID'), ('SAMPLE_ID', 'Sample ID')], max_length=20)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('grouping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.classificationgrouping')),
            ],
            options={
                'unique_together': {('grouping', 'term', 'term_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classificationgroupinggenesymbol',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classificationgroupinggenesymbol',
            name='gene_symbol',
        ),
        migrations.RemoveField(
            model_name='classificationgroupinggenesymbol',
            name='grouping',
        ),
        migrations.DeleteModel(
            name='ClassificationGroupingCondition',
        ),
        migrations.DeleteModel(
            name='ClassificationGroupingGeneSymbol',
        ),
    ]
