# Generated by Django 4.2.17 on 2025-02-05 03:05

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0158_germline_evidence_key_sorting'),
    ]

    operations = [
        ManualOperation.operation_manage(["classification_groupings", "--summary", "--all"])
    ]
