# Generated by Django 4.2.17 on 2025-03-31 01:45

from django.db import migrations
from classification.enums import AlleleOriginBucket



def delete_somatic_exports(apps, schema_editor):
    # Somatic ClinVar exports were never implemented
    # they were created but never sent, so safe to delete them
    # a future migration will set things up for Germline/Oncogenic/Clnical Impact - which is how ClinVar works
    apps.get_model('classification', 'ClinVarAllele').objects.filter(allele_origin_bucket__ne=AlleleOriginBucket.GERMLINE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0159_classification_grouping'),
    ]

    operations = [
        migrations.RunPython(delete_somatic_exports)
    ]
