# Generated by Django 4.2.15 on 2024-09-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0159_classificationgroupingsearchterm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classificationgrouping',
            old_name='latest_classification',
            new_name='latest_classification_modification',
        ),
    ]
