# Generated by Django 4.2.15 on 2024-10-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0159_remove_classificationgrouping_latest_criteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='classification_bucket',
        ),
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='conflicting_ratings',
        ),
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='quality_level',
        ),
        migrations.AddField(
            model_name='classificationgrouping',
            name='pathogenic_difference',
            field=models.IntegerField(choices=[(0, 'No Differences'), (1, 'Differences'), (2, 'Clinical Significance Difference')], default=0),
        ),
        migrations.AddField(
            model_name='classificationgrouping',
            name='somatic_difference',
            field=models.IntegerField(choices=[(0, 'No Differences'), (1, 'Same Tier, different AMP Level'), (2, 'Different Tier')], default=0),
        ),
    ]
