# Generated by Django 4.2.17 on 2025-04-04 02:23

from django.db import migrations

from classification.management.commands.fix_allele_info import Command as FixAlleleInfoCommand
from manual.operations.manual_operations import ManualOperation


def _test_needs_imported_allele_info_liftover(_apps):
    for _genome_build, iai_qs in FixAlleleInfoCommand.get_imported_allele_info_liftover_builds_and_qs():
        if iai_qs.exists():
            return True
    return False


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0164_one_off_add_genome_build_slug'),
        ('classification', '0159_classification_grouping'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_allele_info", "liftover"]),
                        test=_test_needs_imported_allele_info_liftover),
    ]
