# Generated by Django 4.2.17 on 2025-03-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0160_delete_non_germline_clinvar_exports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinvarallele',
            name='allele_origin_bucket',
        ),
        migrations.RemoveField(
            model_name='clinvarexport',
            name='allele_origin_bucket',
        ),
        migrations.AddField(
            model_name='clinvarallele',
            name='clinvar_export_bucket',
            field=models.CharField(choices=[('G', 'Germline'), ('O', 'Oncogenic'), ('C', 'Clinical Impact')], default='G', max_length=1),
        ),
    ]
