# Generated by Django 5.2.8 on 2026-03-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0160_one_off_run_fix_allele_info_liftover"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedalleleinfo",
            name="hgvs_converter_data_version",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="resolvedvariantinfo",
            name="c_hgvs_converter_data_version",
            field=models.TextField(blank=True, default=""),
        ),
    ]
