# Generated by Django 4.2.15 on 2025-12-03 04:25

from django.db import migrations

from classification.autopopulate_evidence_keys.clinvar_option_updator import EvidenceKeyOptionUpdator
from classification.evidence_key_rename import EvidenceSelectKeyRenamer


def clinical_impact_clinvar_mapping(apps, schema_editor):
    # provide values that the ClinVar
    option_updator = EvidenceKeyOptionUpdator(apps, 'somatic:clinical_significance')
    option_updator.set_clinvar_option("tier_1", "Tier I - Strong")
    option_updator.set_clinvar_option("tier_2", "Tier II - Potential")
    option_updator.set_clinvar_option("tier_3", "Tier III - Unknown")
    option_updator.set_clinvar_option("tier_4", "Tier IV - Benign/Likely benign")


def migrate_testing_context(apps, schema_editor):
    EvidenceSelectKeyRenamer(apps, "testing_context", "solid tumor", "solid_tumor").run()
    EvidenceSelectKeyRenamer(apps, "testing_context", "non-cancer somatic", "non_cancer_somatic").run()
    option_updator = EvidenceKeyOptionUpdator(apps, "testing_context")
    option_updator.set_testing_context_bucket("solid_tumor", "S")
    option_updator.set_testing_context_bucket("non_cancer_somatic", "N")
    option_updator.set_testing_context_bucket("haematology", "H")
    option_updator.set_testing_context_bucket("other", "O")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('classification', '0160_one_off_run_fix_allele_info_liftover'),
    ]

    operations = [
        migrations.RunPython(clinical_impact_clinvar_mapping, noop),
        migrations.RunPython(migrate_testing_context, noop)
    ]
