# Generated by Django 4.2.15 on 2025-12-04 02:53

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    def germline_fix(apps, schema_editor):
        AlleleOriginGrouping = apps.get_model("classification", "AlleleOriginGrouping")
        AlleleOriginGrouping.objects.filter(allele_origin_bucket="G").update(testing_context_bucket="G")

    def noop(self, apps, schema_editor):
        pass

    dependencies = [
        ('snpdb', '0171_sample_research_consent'),
        ('classification', '0161_once_off_fix_somatic_config'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alleleorigingrouping',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='allele_origin_bucket',
        ),
        migrations.AddField(
            model_name='alleleorigingrouping',
            name='testing_context_bucket',
            field=models.CharField(choices=[('N', 'Non-Cancer Somatic'), ('H', 'Haematology'), ('S', 'Solid Tumour'), ('O', 'Other'), ('G', 'Germline'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='alleleorigingrouping',
            name='tumor_type_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationgrouping',
            name='latest_cached_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='alleleorigingrouping',
            unique_together={('allele_grouping', 'allele_origin_bucket', 'testing_context_bucket', 'tumor_type_category')},
        ),
        migrations.CreateModel(
            name='Overlap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('overlap_type', models.TextField(choices=[('context', 'Single Context'), ('cross', 'Cross Context'), ('clinvar', 'ClinVar Expert Panel')])),
                ('value_type', models.TextField(choices=[('O', 'Onco-Path'), ('S', 'Clinical significance')], max_length=1)),
                ('testing_context', models.TextField(blank=True, choices=[('N', 'Non-Cancer Somatic'), ('H', 'Haematology'), ('S', 'Solid Tumour'), ('O', 'Other'), ('G', 'Germline'), ('U', 'Unknown')], max_length=1, null=True)),
                ('tumor_type_category', models.TextField(blank=True, null=True)),
                ('overlap_status', models.IntegerField(choices=[(0, 'No contributions'), (10, 'No counting contributions'), (20, 'Single submitter'), (30, 'Exact agreement'), (40, 'Terminology differences'), (50, 'Resolution differences'), (60, 'Minor differences'), (70, 'Tier 1 vs Tier 2 Differences'), (80, 'Discordance'), (90, 'Medically significant discordance')], default=0)),
                ('allele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.allele')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.lab')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationGroupingValueTriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('result_value_type', models.TextField(choices=[('O', 'Onco-Path'), ('S', 'Clinical significance')], max_length=1)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('triage_status', models.TextField(choices=[('P', 'Pending Triage'), ('F', 'Will Amend'), ('D', 'For Joint Discussion'), ('R', 'Confident in Classification'), ('X', 'Low Penetrance/Risk Allele etc')], default='P', max_length=1)),
                ('classification_grouping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.classificationgrouping')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationGroupingOverlapContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('contribution_status', models.TextField(choices=[('P', 'Pending Calculation'), ('C', 'Contributing'), ('N', 'Not-shared'), ('X', 'No value'), ('Z', 'Non-comparable value')], default='P', max_length=1)),
                ('classification_grouping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.classificationgrouping')),
                ('overlap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.overlap')),
            ],
        ),
        migrations.RemoveField(
            model_name='alleleorigingrouping',
            name='overlap_status',
        ),
        migrations.AddIndex(
            model_name='overlap',
            index=models.Index(fields=['overlap_type'], name='classificat_overlap_ea3d76_idx'),
        ),
        migrations.AddIndex(
            model_name='overlap',
            index=models.Index(fields=['allele'], name='classificat_allele__9e6be1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='overlap',
            unique_together={('overlap_type', 'allele', 'value_type', 'testing_context', 'tumor_type_category', 'lab')},
        ),
        migrations.AlterUniqueTogether(
            name='classificationgroupingvaluetriage',
            unique_together={('classification_grouping', 'result_value_type')},
        ),
        migrations.AlterUniqueTogether(
            name='classificationgroupingoverlapcontribution',
            unique_together={('classification_grouping', 'overlap')},
        ),
        migrations.RunPython(germline_fix, noop)
    ]
