# Generated by Django 4.2.17 on 2025-04-01 00:40

from django.db import migrations

from classification.evidence_key_rename import OptionUpdator


def clinical_impact_clinvar_mapping(apps, schema_editor):
    # provide values that the ClinVar
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')
    somatic_clin_sig = EvidenceKey.objects.get(key='somatic:clinical_significance')
    option_updator = OptionUpdator(somatic_clin_sig)
    option_updator.ensure_option({"key": "tier_1", "clinvar": "Tier I - Strong"}, update_existing=True)
    option_updator.ensure_option({"key": "tier_2", "clinvar": "Tier II - Potential"}, update_existing=True)
    option_updator.ensure_option({"key": "tier_3", "clinvar": "Tier III - Unknown"}, update_existing=True)
    option_updator.ensure_option({"key": "tier_4", "clinvar": "Tier IV - Benign/Likely benign"}, update_existing=True)
    option_updator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0161_remove_clinvarallele_allele_origin_bucket_and_more'),
    ]

    operations = [
        migrations.RunPython(clinical_impact_clinvar_mapping)
    ]
