# Generated by Django 4.2.15 on 2025-12-04 04:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0162_alter_alleleorigingrouping_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlap',
            name='overlap_type',
            field=models.TextField(choices=[('context', 'Single Context'), ('clinvar', 'ClinVar Expert Panel')]),
        ),
        migrations.AlterField(
            model_name='overlap',
            name='testing_context',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('N', 'Non-Cancer Somatic'), ('H', 'Haematology'), ('S', 'Solid Tumour'), ('O', 'Other'), ('G', 'Germline'), ('U', 'Unknown')], max_length=1), blank=True, null=True, size=None),
        ),
    ]
