# Generated by Django 4.2.17 on 2025-04-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0162_clinical_impact_clinvar_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinvarexportbatch',
            name='allele_origin_bucket',
        ),
        migrations.AddField(
            model_name='clinvarexport',
            name='delete_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='clinvarexport',
            name='delete_status',
            field=models.CharField(choices=[('L', 'Live Record'), ('R', 'Deletion Pending'), ('Z', 'Deleted')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='clinvarexport',
            name='status',
            field=models.CharField(choices=[('N', 'New Submission'), ('C', 'Changes Pending'), ('R', 'Deletion Pending'), ('Z', 'Deleted'), ('D', 'Up to Date'), ('E', 'Error'), ('X', 'Exclude')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='clinvarexportbatch',
            name='assertion_criteria',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
