# Generated by Django 6.0 on 2026-03-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0162_sharelevel_institution_to_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='share_level',
            field=models.CharField(choices=[('user', 'CURRENT_USER'), ('lab', 'LAB'), ('organisation', 'ORGANISATION'), ('logged_in_users', 'ALL_USERS'), ('public', 'PUBLIC')], default='lab', max_length=16),
        ),
        migrations.AlterField(
            model_name='classificationgrouping',
            name='share_level',
            field=models.CharField(choices=[('user', 'CURRENT_USER'), ('lab', 'LAB'), ('organisation', 'ORGANISATION'), ('logged_in_users', 'ALL_USERS'), ('public', 'PUBLIC')], max_length=16),
        ),
        migrations.AlterField(
            model_name='classificationmodification',
            name='share_level',
            field=models.CharField(blank=True, choices=[('user', 'CURRENT_USER'), ('lab', 'LAB'), ('organisation', 'ORGANISATION'), ('logged_in_users', 'ALL_USERS'), ('public', 'PUBLIC')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='evidencekey',
            name='max_share_level',
            field=models.CharField(choices=[('user', 'CURRENT_USER'), ('lab', 'LAB'), ('organisation', 'ORGANISATION'), ('logged_in_users', 'ALL_USERS'), ('public', 'PUBLIC')], default='logged_in_users', max_length=16),
        ),
    ]
