# Generated by Django 4.2.17 on 2025-04-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0163_remove_clinvarexportbatch_allele_origin_bucket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinvarexportsubmission',
            old_name='localId',
            new_name='local_id',
        ),
        migrations.RenameField(
            model_name='clinvarexportsubmission',
            old_name='localKey',
            new_name='local_key',
        ),
    ]
