# Generated by Django 4.2.15 on 2025-12-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0163_alter_overlap_overlap_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlap',
            name='overlap_type',
            field=models.TextField(choices=[('context', 'Single Context'), ('cross', 'Cross Context'), ('clinvar', 'ClinVar Expert Panel')]),
        ),
    ]
