# Generated by Django 4.2.17 on 2025-04-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0164_rename_localid_clinvarexportsubmission_local_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarexportsubmission',
            name='submission_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clinvarexportsubmission',
            name='local_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinvarexportsubmission',
            name='local_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
