# Generated by Django 4.2.15 on 2025-12-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0171_sample_research_consent'),
        ('classification', '0164_alter_overlap_overlap_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overlap',
            old_name='testing_context',
            new_name='testing_contexts',
        ),
        migrations.AlterUniqueTogether(
            name='overlap',
            unique_together={('overlap_type', 'allele', 'value_type', 'testing_contexts', 'tumor_type_category', 'lab')},
        ),
        migrations.AddField(
            model_name='overlap',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
