# Generated by Django 4.2.17 on 2025-04-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0165_clinvarexportsubmission_submission_deletion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinvarexport',
            name='status',
            field=models.CharField(choices=[('N', 'New Submission'), ('C', 'Changes Pending'), ('D', 'Up to Date'), ('E', 'Error'), ('X', 'Exclude')], default='N', max_length=1),
        ),
    ]
