# Generated by Django 4.2.15 on 2025-12-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0165_rename_testing_context_overlap_testing_contexts_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overlap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='overlap',
            name='cached_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overlap',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='overlap',
            name='lab',
        ),
    ]
