# Generated by Django 4.2.17 on 2025-04-10 02:08

from django.db import migrations


def reverse_once_off_clinvar_export_assert_method(apps, schema_editor):
    ClinVarExportAssertionMethod = apps.get_model('snpdb', 'ClinVarExportAssertionMethod')
    ClinVarExportAssertionMethod.objects.all().delete()


def once_off_clinvar_export_assert_method(apps, schema_editor):
    ClinVarExportAssertionMethod = apps.get_model('snpdb', 'ClinVarExportAssertionMethod')
    acmg_g = ClinVarExportAssertionMethod.objects.create(
        id="acmg_g",
        label="ACMG Guidelines, 2015",
        reference_db="PUBMED",
        reference_id="PMID:25741868",
        export_type="G",
        pattern=".*acmg.*"
    )
    ClinVarExportAssertionMethod.objects.create(
        id="horak_o",
        label="ClinGen/CGC/VICC 2022",
        reference_db="PUBMED",
        reference_id="PMID:35101336",
        export_type="O",
        pattern=".*(?:horak|clingen|cgc|vicc).*"
    )
    ClinVarExportAssertionMethod.objects.create(
        id="amp_ci",
        label="AMP/ASCO/CAP 2017",
        reference_db="PUBMED",
        reference_id="PMID:27993330",
        export_type="C",
        pattern=".*(?:amp|asco|cap).*"
    )
    ClinVarExportAssertionMethodMapping = apps.get_model('snpdb', 'ClinVarExportAssertionMethodMapping')
    ClinVarKey = apps.get_model('snpdb', 'ClinVarKey')
    for clinvar_key in ClinVarKey.objects.all():
        if assertion_method_lookups_json := clinvar_key.assertion_method_lookup:
            if lookups := assertion_method_lookups_json.get('lookups'):
                for index, lookup in enumerate(lookups):
                    pattern = lookup.get('match')
                    citation = lookup.get('citation')
                    if citation != 'acmg':
                        print(f"Can't automatically remap citation {pattern} against {citation}")
                        continue

                    ClinVarExportAssertionMethodMapping.objects.create(
                        clinvar_key=clinvar_key,
                        order=index+1,
                        pattern=pattern,
                        assertion_method=acmg_g,
                    )



class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0166_remove_clinvarallele_classifications_missing_condition_and_more'),
        ('snpdb', '0166_clinvarexportassertionmethod_and_more')
    ]

    operations = [
        migrations.RunPython(once_off_clinvar_export_assert_method, reverse_once_off_clinvar_export_assert_method)
    ]
