# Generated by Django 4.2.17 on 2025-04-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0166_alter_clinvarexport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinvarallele',
            name='classifications_missing_condition',
        ),
        migrations.RemoveField(
            model_name='clinvarallele',
            name='submissions_invalid',
        ),
        migrations.RemoveField(
            model_name='clinvarallele',
            name='submissions_valid',
        ),
    ]
