# Generated by Django 4.2.15 on 2026-01-12 01:49

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0166_alter_overlap_unique_together_overlap_cached_values_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlapContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source', models.TextField(choices=[('CLASS', 'CLASSIFICATION'), ('CLIN', 'CLINVAR')])),
                ('scv', models.TextField(blank=True, null=True)),
                ('value_type', models.TextField(choices=[('O', 'Onco-Path'), ('S', 'Clinical significance')])),
                ('value', models.TextField(blank=True, null=True)),
                ('contribution', models.TextField(choices=[('P', 'Pending Calculation'), ('C', 'Contributing'), ('N', 'Not-shared'), ('X', 'No value'), ('Z', 'Non-comparable value')])),
                ('testing_context_bucket', models.TextField(choices=[('N', 'Non-Cancer Somatic'), ('H', 'Haematology'), ('S', 'Solid Tumour'), ('O', 'Other'), ('G', 'Germline'), ('U', 'Unknown')])),
                ('tumor_type_category', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('classification_grouping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.classificationgrouping')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='overlap',
            name='contributions',
            field=models.ManyToManyField(to='classification.overlapcontribution'),
        ),
    ]
