# Generated by Django 4.2.15 on 2026-01-26 23:44

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0171_sample_research_consent'),
        ('classification', '0167_overlapcontribution_overlap_contributions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlapContributionSkew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('skew_perspective', models.TextField(choices=[('X', 'Pending Calculation'), ('C', 'Unanimously Complex'), ('T', 'Awaiting Your Triage'), ('A', 'Awaiting Your Amendment'), ('O', 'Awaiting Other Lab'), ('D', 'To Discuss'), ('N', 'Not Involved')], default='X', max_length=1)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='classificationgroupingoverlapcontribution',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classificationgroupingoverlapcontribution',
            name='classification_grouping',
        ),
        migrations.RemoveField(
            model_name='classificationgroupingoverlapcontribution',
            name='overlap',
        ),
        migrations.AlterUniqueTogether(
            name='classificationgroupingvaluetriage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classificationgroupingvaluetriage',
            name='classification_grouping',
        ),
        migrations.RemoveField(
            model_name='overlap',
            name='cached_values',
        ),
        migrations.RemoveField(
            model_name='overlap',
            name='contributions',
        ),
        migrations.RemoveField(
            model_name='overlap',
            name='testing_contexts',
        ),
        migrations.AddField(
            model_name='overlap',
            name='testing_context',
            field=models.TextField(blank=True, choices=[('N', 'Non-Cancer Somatic'), ('H', 'Haematology'), ('S', 'Solid Tumour'), ('O', 'Other'), ('G', 'Germline'), ('U', 'Unknown')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='overlapcontribution',
            name='allele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.allele'),
        ),
        migrations.AddField(
            model_name='overlapcontribution',
            name='effective_date_type',
            field=models.TextField(choices=[('created', 'Created'), ('curated', 'Curated'), ('sample', 'Sample'), ('verified', 'Verified'), ('unknown', 'Unknown')], default='unknown'),
        ),
        migrations.AddField(
            model_name='overlapcontribution',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overlapcontribution',
            name='triage_status',
            field=models.TextField(choices=[('P', 'Pending Triage'), ('F', 'Will Amend'), ('D', 'For Joint Discussion'), ('R', 'Confident in Value'), ('X', 'Low Penetrance/Risk Allele etc'), ('Z', 'Non-Interactive Party')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='overlap',
            name='overlap_status',
            field=models.IntegerField(choices=[(0, 'No contributions'), (10, 'No counting contributions'), (20, 'Single submitter'), (30, 'Exact agreement'), (40, 'Terminology differences'), (50, 'Resolution differences'), (60, 'Minor differences'), (70, 'Tier 1 vs Tier 2 differences'), (80, 'Discordance'), (90, 'Medically significant discordance')], default=0),
        ),
        migrations.AlterField(
            model_name='overlap',
            name='overlap_type',
            field=models.TextField(choices=[('context', 'Single Context'), ('cross', 'Cross Context')]),
        ),
        migrations.AddIndex(
            model_name='overlap',
            index=models.Index(fields=['value_type'], name='classificat_value_t_569d84_idx'),
        ),
        migrations.DeleteModel(
            name='ClassificationGroupingOverlapContribution',
        ),
        migrations.DeleteModel(
            name='ClassificationGroupingValueTriage',
        ),
        migrations.AddField(
            model_name='overlapcontributionskew',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.overlapcontribution'),
        ),
        migrations.AddField(
            model_name='overlapcontributionskew',
            name='overlap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.overlap'),
        ),
    ]
