# Generated by Django 4.2.17 on 2025-04-14 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0160_one_off_run_fix_allele_info_liftover'),
        ('classification', '0167_once_off_migrate_assertion_method_matches'),
    ]

    operations = [
    ]
