# Generated by Django 4.2.15 on 2026-01-12 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0171_sample_research_consent'),
        ('classification', '0167_overlapcontribution_overlap_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlapcontribution',
            name='allele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.allele'),
        ),
    ]
