# Generated by Django 4.2.15 on 2026-01-27 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0168_overlapcontributionskew_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overlapcontribution',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='overlapcontribution',
            unique_together={('classification_grouping', 'value_type')},
        ),
        migrations.CreateModel(
            name='OverlapContributionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('change_source', models.TextField(choices=[('U', 'Upload'), ('T', 'Triage')])),
                ('value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('triage_status', models.TextField(blank=True, choices=[('P', 'Pending Triage'), ('F', 'Will Amend'), ('D', 'For Joint Discussion'), ('R', 'Confident in Value'), ('X', 'Low Penetrance/Risk Allele etc'), ('Z', 'Non-Interactive Party')], max_length=1, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('overlap_contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.overlapcontribution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
