# Generated by Django 4.2.17 on 2025-04-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0168_merge_20250414_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinvarexport',
            name='status',
            field=models.CharField(choices=[('N', 'New Submission'), ('C', 'Changes Pending'), ('D', 'Up to Date'), ('E', 'Error'), ('X', 'Exclude'), ('Z', 'Deleted')], default='N', max_length=1),
        ),
    ]
