# Generated by Django 4.2.15 on 2026-01-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0168_overlapcontribution_allele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlap',
            name='cached_values',
        ),
        migrations.AddIndex(
            model_name='overlap',
            index=models.Index(fields=['value_type'], name='classificat_value_t_569d84_idx'),
        ),
    ]
