# Generated by Django 4.2.17 on 2025-04-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0169_alter_clinvarexport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarallele',
            name='accepted_condition_splits',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='clinvarallele',
            name='multiple_review_status',
            field=models.TextField(choices=[('S', 'Single Condition'), ('R', 'Requires Review'), ('A', 'Approved Multiple Conditions'), ('U', 'Unknown Status')], default='U', max_length=1),
        ),
    ]
