# Generated by Django 4.2.15 on 2026-01-13 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0169_remove_overlap_cached_values_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassificationGroupingOverlapContribution',
        ),
    ]
