# Generated by Django 4.2.15 on 2026-01-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0169_alter_overlapcontribution_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overlapcontribution',
            old_name='contribution',
            new_name='contribution_status',
        ),
    ]
