# Generated by Django 4.2.17 on 2025-05-14 04:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0169_merge_20250505_1251'),
        ('classification', '0170_clinvarallele_accepted_condition_splits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinVarLegacy',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('scv', models.TextField(primary_key=True, serialize=False)),
                ('clinvar_variation_id', models.TextField(blank=True, null=True)),
                ('clinvar_allele_id', models.TextField(blank=True, null=True)),
                ('your_variant_description_hgvs', models.TextField(blank=True, null=True)),
                ('your_variant_description_chromosome_coordinates', models.TextField(blank=True, null=True)),
                ('preferred_variant_name', models.TextField(blank=True, null=True)),
                ('your_condition_name', models.TextField(blank=True, null=True)),
                ('your_condition_identifier', models.TextField(blank=True, null=True)),
                ('clinvar_condition_name', models.TextField(blank=True, null=True)),
                ('germline_classification', models.TextField(blank=True, null=True)),
                ('date_last_evaluated', models.DateField(blank=True, null=True)),
                ('assertion_criteria', models.TextField(blank=True, null=True)),
                ('submitted_gene', models.TextField(blank=True, null=True)),
                ('allele_match_date', models.DateTimeField(blank=True, null=True)),
                ('allele_match_type', models.CharField(choices=[('N', 'Not Attempted'), ('F', 'Not Found'), ('C', 'Matched on ClinVar Allele'), ('H', 'Matched on HGVS')], default='N', max_length=1)),
                ('clinvar_bucket', models.TextField(choices=[('G', 'Germline'), ('O', 'Oncogenic'), ('C', 'Clinical Impact')], max_length=1)),
            ],
            options={
                'verbose_name': 'ClinVar legacy uploads',
            },
        ),
        migrations.AddIndex(
            model_name='clinvarexport',
            index=models.Index(fields=['scv'], name='classificat_scv_1ed3fd_idx'),
        ),
        migrations.AddField(
            model_name='clinvarlegacy',
            name='allele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.allele'),
        ),
        migrations.AddField(
            model_name='clinvarlegacy',
            name='clinvar_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.clinvarkey'),
        ),
        migrations.AddIndex(
            model_name='clinvarlegacy',
            index=models.Index(fields=['scv'], name='classificat_scv_a2612e_idx'),
        ),
    ]
