# Generated by Django 4.2.15 on 2026-01-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0170_delete_classificationgroupingoverlapcontribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlap',
            name='testing_contexts',
        ),
        migrations.AddField(
            model_name='overlap',
            name='testing_context',
            field=models.TextField(blank=True, choices=[('N', 'Non-Cancer Somatic'), ('H', 'Haematology'), ('S', 'Solid Tumour'), ('O', 'Other'), ('G', 'Germline'), ('U', 'Unknown')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='overlap',
            name='overlap_type',
            field=models.TextField(choices=[('context', 'Single Context'), ('cross', 'Cross Context')]),
        ),
    ]
