# Generated by Django 4.2.15 on 2026-01-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0170_rename_contribution_overlapcontribution_contribution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlapcontributionlog',
            name='contribution_status',
            field=models.TextField(choices=[('P', 'Pending Calculation'), ('C', 'Contributing'), ('N', 'Not-shared'), ('X', 'No value'), ('Z', 'Non-comparable value')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overlapcontributionlog',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overlapcontributionlog',
            name='effective_date_type',
            field=models.TextField(choices=[('created', 'Created'), ('curated', 'Curated'), ('sample', 'Sample'), ('verified', 'Verified'), ('unknown', 'Unknown')], default='unknown'),
        ),
    ]
