# Generated by Django 4.2.17 on 2025-05-06 23:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0169_merge_20250505_1251'),
        ('classification', '0170_clinvarallele_accepted_condition_splits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinVarLegacy',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('scv', models.TextField(primary_key=True, serialize=False)),
                ('clinvar_variation_id', models.TextField(blank=True, null=True)),
                ('clinvar_allele_id', models.TextField(blank=True, null=True)),
                ('your_variant_description_hgvs', models.TextField(blank=True, null=True)),
                ('your_variant_description_chromosome_coordinates', models.TextField(blank=True, null=True)),
                ('preferred_variant_name', models.TextField(blank=True, null=True)),
                ('your_condition_name', models.TextField(blank=True, null=True)),
                ('your_condition_identifier', models.TextField(blank=True, null=True)),
                ('clinvar_condition_name', models.TextField(blank=True, null=True)),
                ('clinical_significance', models.TextField(blank=True, null=True)),
                ('date_last_evaluated', models.DateField(blank=True, null=True)),
                ('assertion_criteria', models.TextField(blank=True, null=True)),
                ('submitted_gene', models.TextField(blank=True, null=True)),
                ('allele_match_date', models.DateTimeField(blank=True, null=True)),
                ('allele_match_type', models.CharField(choices=[('N', 'Not Attempted'), ('F', 'Not Found'), ('C', 'Matched on ClinVar Allele'), ('H', 'Matched on HGVS')], default='N', max_length=1)),
                ('allele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.allele')),
                ('clinvar_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.clinvarkey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinVarLegacyMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('matched_allele', models.BooleanField(default=False)),
                ('matched_condition', models.BooleanField(default=False)),
                ('matched_scv', models.BooleanField(default=False)),
                ('clinvar_export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.clinvarexport')),
                ('clinvar_legacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.clinvarlegacy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
