# Generated by Django 6.0.6 on 2026-08-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0171_copy_consensus_off_annotation_backed_keys"),
        ("genes", "0086_fusion_gene_id_and_gene_fusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedalleleinfo",
            name="gene_fusion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="genes.genefusion",
            ),
        ),
    ]
