# Generated by Django 4.2.15 on 2026-01-20 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0171_remove_overlap_testing_contexts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlap',
            name='overlap_status',
            field=models.IntegerField(choices=[(0, 'No contributions'), (10, 'No counting contributions'), (20, 'Single submitter'), (30, 'Exact agreement'), (40, 'Terminology differences'), (50, 'Resolution differences'), (60, 'Minor differences'), (70, 'Tier 1 vs Tier 2 differences'), (80, 'Discordance'), (90, 'Medically significant discordance')], default=0),
        ),
        migrations.CreateModel(
            name='ClassificationGroupingValueTriageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('new_value', models.TextField(blank=True, null=True)),
                ('triage_status', models.TextField(choices=[('P', 'Pending Triage'), ('F', 'Will Amend'), ('D', 'For Joint Discussion'), ('R', 'Confident in Classification'), ('X', 'Low Penetrance/Risk Allele etc')], default='P', max_length=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('state_data', models.JSONField(blank=True, null=True)),
                ('triage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.classificationgroupingvaluetriage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
