# Generated by Django 6.1 on 2026-08-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classification", "0171_copy_consensus_off_annotation_backed_keys"),
        ("genes", "0086_fusion_gene_id_and_gene_fusion"),
        ("snpdb", "0213_tag_allele_origin_bucket"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReclassificationEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allele_origin_bucket",
                    models.CharField(
                        choices=[("G", "Germline"), ("S", "Somatic"), ("U", "Unknown")],
                        default="G",
                        max_length=1,
                    ),
                ),
                (
                    "from_clinical_significance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Other"),
                            ("1", "Benign"),
                            ("2", "Likely Benign"),
                            ("3", "VUS"),
                            ("4", "Likely Pathogenic"),
                            ("5", "Pathogenic"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "to_clinical_significance",
                    models.CharField(
                        choices=[
                            ("0", "Other"),
                            ("1", "Benign"),
                            ("2", "Likely Benign"),
                            ("3", "VUS"),
                            ("4", "Likely Pathogenic"),
                            ("5", "Pathogenic"),
                        ],
                        max_length=1,
                    ),
                ),
                ("reclassified_date", models.DateField(db_index=True)),
                ("step", models.PositiveSmallIntegerField()),
                ("significance_delta", models.SmallIntegerField(blank=True, null=True)),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classification.classification",
                    ),
                ),
                (
                    "from_modification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="classification.classificationmodification",
                    ),
                ),
                (
                    "gene_symbol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="genes.genesymbol",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="snpdb.lab"
                    ),
                ),
                (
                    "to_modification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="classification.classificationmodification",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["lab", "reclassified_date"],
                        name="classificat_lab_id_956208_idx",
                    ),
                    models.Index(
                        fields=[
                            "from_clinical_significance",
                            "to_clinical_significance",
                        ],
                        name="classificat_from_cl_9c5538_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("classification", "step"),
                        name="unique_reclassification_step",
                    )
                ],
            },
        ),
    ]
