# Generated by Django 4.2.15 on 2026-03-31 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0171_overlapcontributionlog_contribution_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overlap',
            old_name='testing_context',
            new_name='testing_context_bucket',
        ),
    ]
