# Generated by Django 4.2.17 on 2025-07-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0171_clinvarlegacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alleleorigingrouping',
            name='testing_context_bucket',
            field=models.CharField(choices=[('N', 'Non-Cancer Somatic'), ('H', 'Haematology'), ('S', 'Solid Tumor'), ('O', 'Other'), ('G', 'Germline'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='alleleorigingrouping',
            name='tumor_type_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
