# Generated by Django 6.0.3 on 2026-04-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0164_somatic_hrd_msi_tmb_ekeys'),
        ('classification', '0172_rename_testing_context_overlap_testing_context_bucket'),
    ]

    operations = [
    ]
