# Generated by Django 6.1 on 2026-08-21 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0170_one_off_backfill_sv_conservation"),
        ("classification", "0172_reclassificationevent"),
        ("flags", "0010_alter_flagtype_options"),
        ("snpdb", "0213_tag_allele_origin_bucket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReclassificationEventBuildState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("built_to", models.DateTimeField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="classification",
            index=models.Index(
                fields=["modified"], name="classificat_modifie_2eaab6_idx"
            ),
        ),
    ]
