# Generated by Django 4.2.17 on 2025-07-17 03:45

from django.db import migrations

from classification.autopopulate_evidence_keys.clinvar_option_updator import EvidenceKeyOptionUpdator
from classification.evidence_key_rename import EvidenceSelectKeyRenamer


def migrate_testing_context(apps, schema_editor):
    EvidenceSelectKeyRenamer(apps, "testing_context", "solid tumor", "solid_tumor").run()
    EvidenceSelectKeyRenamer(apps, "testing_context", "non-cancer somatic", "non_cancer_somatic").run()
    option_updator = EvidenceKeyOptionUpdator(apps, "testing_context")
    option_updator.set_testing_context_bucket("solid_tumor", "S")
    option_updator.set_testing_context_bucket("non_cancer_somatic", "N")
    option_updator.set_testing_context_bucket("haematology", "H")
    option_updator.set_testing_context_bucket("other", "O")
    # non-cancer somatic


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0172_alleleorigingrouping_testing_context_bucket_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_testing_context, None)
    ]
