# Generated by Django 4.2.15 on 2026-01-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0172_alter_overlap_overlap_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlap',
            name='contributions',
        ),
    ]
