# Generated by Django 6.0.3 on 2026-04-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0173_merge_20260409_1113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverlapContributionLog',
        ),
    ]
