# Generated by Django 4.2.15 on 2026-01-21 22:55

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0173_remove_overlap_contributions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlapContributionSkew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('skew_perspective', models.TextField(choices=[('X', 'Pending Calculation'), ('C', 'Unanimously Complex'), ('T', 'Awaiting Your Triage'), ('A', 'Awaiting Your Amendment'), ('O', 'Awaiting Other Lab'), ('D', 'To Discuss'), ('N', 'Not Involved')], default='X', max_length=1)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.overlapcontribution')),
                ('overlap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.overlap')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
