# Generated by Django 4.2.17 on 2025-07-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0173_fix_testing_context_values'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alleleorigingrouping',
            unique_together={('allele_grouping', 'allele_origin_bucket', 'testing_context_bucket', 'tumor_type_category')},
        ),
    ]
