# Generated by Django 6.1 on 2026-08-21 03:23

from django.db import migrations, models


def _rebuild_reclassification_timelines(apps, _schema_editor):
    """ Existing rows predate event types and re-evaluations, so drop them and wind the watermark back -
        the analytics page and the nightly task rebuild from published history (#1523) """
    apps.get_model("classification", "ReclassificationEvent").objects.all().delete()
    apps.get_model("classification", "ReclassificationEventBuildState").objects.update(built_to=None)


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0173_reclassificationeventbuildstate"),
        ("genes", "0086_fusion_gene_id_and_gene_fusion"),
        ("snpdb", "0213_tag_allele_origin_bucket"),
    ]

    operations = [
        migrations.RunPython(_rebuild_reclassification_timelines, _rebuild_reclassification_timelines),
        migrations.AddField(
            model_name="reclassificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("I", "Initial Classification"),
                    ("R", "Reclassification"),
                    ("E", "Re-evaluation"),
                ],
                default="R",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="reclassificationevent",
            name="from_points",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reclassificationevent",
            name="to_points",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="reclassificationevent",
            index=models.Index(
                fields=["event_type", "reclassified_date"],
                name="classificat_event_t_e3395a_idx",
            ),
        ),
    ]
