# Generated by Django 4.2.15 on 2026-01-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0174_overlapcontributionskew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationgroupingvaluetriage',
            name='triage_status',
            field=models.TextField(choices=[('P', 'Pending Triage'), ('F', 'Will Amend'), ('D', 'For Joint Discussion'), ('R', 'Confident in Classification'), ('X', 'Low Penetrance/Risk Allele etc'), ('Z', 'Non-Interactive Party')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='classificationgroupingvaluetriagehistory',
            name='triage_status',
            field=models.TextField(choices=[('P', 'Pending Triage'), ('F', 'Will Amend'), ('D', 'For Joint Discussion'), ('R', 'Confident in Classification'), ('X', 'Low Penetrance/Risk Allele etc'), ('Z', 'Non-Interactive Party')], default='P', max_length=1),
        ),
    ]
