# Generated by Django 6.0.3 on 2026-04-21 02:36

import classification.models.overlaps_enums
import classification.models.overlaps_model
import library.utils.database_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0174_delete_overlapcontributionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlapcontribution',
            name='effective_date_type',
        ),
        migrations.RemoveField(
            model_name='overlapcontribution',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='overlapcontribution',
            name='triage_status',
        ),
        migrations.AddField(
            model_name='overlapcontribution',
            name='comment',
            field=library.utils.database_utils.JSONDataclassField(dataclass_type=classification.models.overlaps_model.TriageComment, default=classification.models.overlaps_model.TriageComment.default_json, illegal_value_result=None),
        ),
        migrations.AddField(
            model_name='overlapcontribution',
            name='triage_state',
            field=library.utils.database_utils.JSONDataclassField(dataclass_type=classification.models.overlaps_model.TriageState, default=classification.models.overlaps_model.TriageState.default_json, illegal_value_result=None),
        ),
        migrations.AlterField(
            model_name='overlapcontribution',
            name='contribution_status',
            field=library.utils.database_utils.TextFieldChoices(choices=[('P', 'Pending Calculation'), ('C', 'Contributing'), ('N', 'Not-shared'), ('X', 'No value'), ('Z', 'Non-comparable value')], choices_type=classification.models.overlaps_enums.OverlapContributionStatus),
        ),
        migrations.RemoveField(
            model_name='overlapcontribution',
            name='effective_date',
        ),
        migrations.AddField(
            model_name='overlapcontribution',
            name='effective_date',
            field=library.utils.database_utils.JSONDataclassField(dataclass_type=classification.models.overlaps_model.EffectiveDate, default=classification.models.overlaps_model.EffectiveDate.default_json, illegal_value_result=None),
        ),
    ]
