# Generated by Django 4.2.17 on 2025-07-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0174_alter_alleleorigingrouping_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationgrouping',
            name='allele_origin_bucket',
        ),
    ]
