# Generated by Django 6.1 on 2026-08-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0175_ekey_gene_fusion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditiontext',
            name='pending_automatch',
            field=models.BooleanField(default=False),
        ),
    ]
