# Generated by Django 6.0.3 on 2026-04-22 02:40

from django.db import migrations

from classification.evidence_key_rename import OptionUpdator


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0175_remove_overlapcontribution_effective_date_type_and_more'),
    ]

    def _ekey_testing_context_prenatal(apps, _schema_editor):
        EvidenceKey = apps.get_model('classification', 'EvidenceKey')
        testing_context = EvidenceKey.objects.get(key='testing_context')

        option_updator = OptionUpdator(testing_context)
        option_updator.ensure_option({
            "key": "prenatal",
            "index": 9,
            "label": "Prenatal",
            "testing_context_bucket": "G"
        })
        option_updator.save()

    operations = [
        migrations.RunPython(_ekey_testing_context_prenatal)
    ]
