# Generated by Django 4.2.17 on 2025-07-21 01:09

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0169_merge_20250505_1251'),
        ('classification', '0175_remove_classificationgrouping_allele_origin_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('conflict_type', models.CharField(choices=[('S', 'ClinSig'), ('P', 'OncPath')], max_length=1)),
                ('allele_origin_bucket', models.CharField(blank=True, choices=[('G', 'Germline'), ('S', 'Somatic'), ('U', 'Unknown')], max_length=1, null=True)),
                ('testing_context_bucket', models.CharField(blank=True, choices=[('N', 'Non-Cancer Somatic'), ('H', 'Haematology'), ('S', 'Solid Tumor'), ('O', 'Other'), ('G', 'Germline'), ('U', 'Unknown')], max_length=1, null=True)),
                ('tumor_type_category', models.TextField(blank=True, null=True)),
                ('allele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.allele')),
            ],
            options={
                'unique_together': {('allele', 'conflict_type', 'allele_origin_bucket', 'testing_context_bucket', 'tumor_type_category')},
            },
        ),
        migrations.CreateModel(
            name='ConflictHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('data', models.JSONField()),
                ('severity', models.IntegerField(choices=[(0, 'No Submissions'), (1, 'Single Submission'), (2, 'Same Values'), (3, 'Minor Diffs'), (4, 'Medium Diffs'), (5, 'Major Diffs')])),
                ('is_latest', models.BooleanField(default=False)),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.conflict')),
            ],
            options={
                'indexes': [models.Index(fields=['conflict', 'is_latest'], name='classificat_conflic_197ad4_idx')],
            },
        ),
    ]
