# Generated by Django 4.2.17 on 2025-07-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0176_conflict_conflicthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
    ]
