# Generated by Django 6.0.3 on 2026-04-22 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0176_testing_context_evidence_key'),
        ('snpdb', '0175_settingsoverride_initially_show_zygosity_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alleleorigingrouping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alleleorigingrouping',
            name='allele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.allele'),
        ),
        migrations.AlterUniqueTogether(
            name='alleleorigingrouping',
            unique_together={('allele', 'allele_origin_bucket', 'testing_context_bucket', 'tumor_type_category')},
        ),
    ]
