# Generated by Django 6.0.3 on 2026-04-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    def migrate_allele(apps, _schema_editor):
        AlleleOriginGrouping = apps.get_model('classification', 'AlleleOriginGrouping')
        for aog in AlleleOriginGrouping.objects.all().iterator():
            aog.allele = aog.allele_grouping.allele
            aog.save()

    dependencies = [
        ('classification', '0177_alter_alleleorigingrouping_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_allele)
    ]
