# Generated by Django 4.2.17 on 2025-07-28 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snpdb', '0169_merge_20250505_1251'),
        ('classification', '0177_conflict_meta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alleleorigingrouping',
            name='testing_context_bucket',
            field=models.CharField(choices=[('N', 'Non-Cancer Somatic'), ('H', 'Haematology'), ('S', 'Solid Tumour'), ('O', 'Other'), ('G', 'Germline'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='testing_context_bucket',
            field=models.CharField(blank=True, choices=[('N', 'Non-Cancer Somatic'), ('H', 'Haematology'), ('S', 'Solid Tumour'), ('O', 'Other'), ('G', 'Germline'), ('U', 'Unknown')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='ConflictLabComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField()),
                ('conflict_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.conflictlab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='conflictlab',
            name='conflict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.conflict'),
        ),
        migrations.AddField(
            model_name='conflictlab',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.lab'),
        ),
        migrations.AlterUniqueTogether(
            name='conflictlab',
            unique_together={('conflict', 'lab')},
        ),
    ]
