# Generated by Django 6.1.1 on 2026-09-14 06:57

import classification.models.classification_report_models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0177_evidence_key_copy_scope_and_allele_origin_values"),
        ("patients", "0018_alter_patient_last_name"),
        ("snpdb", "0262_duo_sibling"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationreporttemplate",
            name="allele_origin_bucket",
            field=models.CharField(
                blank=True,
                choices=[("G", "Germline"), ("S", "Somatic"), ("U", "Unknown")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="classificationreporttemplate",
            name="case_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="classificationreporttemplate",
            name="case_template",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="classificationreporttemplate",
            name="json_template",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="CaseReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("D", "Draft"), ("F", "Final"), ("S", "Superseded")],
                        default="D",
                        max_length=1,
                    ),
                ),
                (
                    "source_level",
                    models.CharField(
                        choices=[
                            ("S", "Sample"),
                            ("E", "Extraction"),
                            ("P", "Specimen"),
                            ("T", "Patient"),
                        ],
                        max_length=1,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("case_values", models.JSONField(blank=True, default=dict)),
                ("external_report_id", models.TextField(blank=True, null=True)),
                ("report_date", models.DateField(blank=True, null=True)),
                ("context_snapshot", models.JSONField(default=dict)),
                ("html", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=classification.models.classification_report_models.case_report_upload_path,
                    ),
                ),
                (
                    "docx_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=classification.models.classification_report_models.case_report_upload_path,
                    ),
                ),
                ("json_output", models.JSONField(blank=True, null=True)),
                (
                    "extraction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.extraction",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="snpdb.lab"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.patient",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="snpdb.sample",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.specimen",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classification.casereport",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classification.classificationreporttemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseReportClassification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("reported", models.BooleanField(default=True)),
                (
                    "case_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classification.casereport",
                    ),
                ),
                (
                    "classification_modification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classification.classificationmodification",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.AddIndex(
            model_name="casereport",
            index=models.Index(
                fields=["specimen"], name="classificat_specime_e60a3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casereport",
            index=models.Index(
                fields=["patient"], name="classificat_patient_efb9ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casereport",
            index=models.Index(
                fields=["sample"], name="classificat_sample__34b388_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="casereport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("extraction__isnull", True),
                        ("patient__isnull", False),
                        ("sample__isnull", True),
                        ("specimen__isnull", True),
                    ),
                    models.Q(
                        ("extraction__isnull", True),
                        ("patient__isnull", True),
                        ("sample__isnull", True),
                        ("specimen__isnull", False),
                    ),
                    models.Q(
                        ("extraction__isnull", False),
                        ("patient__isnull", True),
                        ("sample__isnull", True),
                        ("specimen__isnull", True),
                    ),
                    models.Q(
                        ("extraction__isnull", True),
                        ("patient__isnull", True),
                        ("sample__isnull", False),
                        ("specimen__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="case_report_one_source",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="casereportclassification",
            unique_together={("case_report", "classification_modification")},
        ),
    ]
