# Generated by Django 4.2.17 on 2025-07-31 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0169_merge_20250505_1251'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0178_conflictlab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField()),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.conflict')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='conflicthistory',
            name='severity',
            field=models.IntegerField(choices=[(0, 'No Submissions'), (1, 'Single Submitter'), (2, 'Same Values'), (3, 'Minor Diffs'), (4, 'Medium Diffs'), (5, 'Major Diffs')]),
        ),
        migrations.DeleteModel(
            name='ConflictLabComment',
        ),
    ]
