# Generated by Django 6.0.3 on 2026-04-22 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0178_migrate_from_allele_grouping'),
        ('snpdb', '0175_settingsoverride_initially_show_zygosity_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alleleorigingrouping',
            name='allele_grouping',
        ),
        migrations.AlterField(
            model_name='alleleorigingrouping',
            name='allele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.allele'),
        ),
        migrations.DeleteModel(
            name='AlleleGrouping',
        ),
    ]
