# Generated by Django 6.0.3 on 2026-04-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0179_remove_alleleorigingrouping_allele_grouping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlap',
            name='overlap_status_change_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overlapcontributionskew',
            name='skew_perspective',
            field=models.TextField(choices=[('X', 'Pending Calculation'), ('C', 'Unanimously Complex'), ('T', 'Awaiting Your Triage'), ('Y', 'Awaiting your Triage - others have triaged'), ('A', 'Awaiting Your Amendment'), ('O', 'Awaiting Other Lab'), ('D', 'To Discuss'), ('N', 'Not Involved')], default='X', max_length=1),
        ),
    ]
