# Generated by Django 4.2.17 on 2025-07-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0179_conflictcomment_alter_conflicthistory_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictcomment',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='conflictlab',
            name='status',
            field=models.TextField(choices=[('P', 'Pending Triage'), ('F', 'Will Amend'), ('D', 'For Joint Discussion'), ('R', 'Confident in Classification'), ('X', 'Low Penetrance/Risk Allele etc')], default='P'),
        ),
    ]
