# Generated by Django 4.2.17 on 2025-08-28 05:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0180_conflictcomment_meta_data_conflictlab_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictNotificationRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.TextField(choices=[('Q', 'Queued'), ('P', 'Processing'), ('C', 'Complete')], default='Q')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConflictNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.conflict')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classification.conflicthistory')),
                ('notification_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.conflictnotificationrun')),
                ('previous_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classification.conflicthistory')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
