# Generated by Django 6.0.3 on 2026-05-08 01:50

import classification.enums.classification_enums
import library.utils.database_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0181_alter_overlap_overlap_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlapdiscordancenotification',
            name='lab',
        ),
        migrations.AddField(
            model_name='overlapdiscordancenotification',
            name='new_status',
            field=library.utils.database_utils.IntegerFieldChoices(choices=[(0, 'No contributions'), (10, 'No counting contributions'), (20, 'Single submitter'), (30, 'Exact agreement'), (40, 'Terminology differences'), (50, 'Resolution differences'), (60, 'Minor differences'), (70, 'Tier 1 vs Tier 2 differences'), (80, 'Discordance'), (90, 'Medically significant discordance')], choices_type=classification.enums.classification_enums.OverlapStatus, default=0),
            preserve_default=False,
        ),
    ]
