# Generated by Django 4.2.17 on 2025-10-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0181_conflictnotificationrun_conflictnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflicthistory',
            name='severity',
            field=models.IntegerField(choices=[(0, 'No Submissions'), (1, 'Single Submitter'), (2, 'Same Values'), (3, 'Resolution Differences'), (4, 'Small Diffs'), (5, 'Discordance'), (6, 'Medical Significance Discordance')]),
        ),
    ]
