# Generated by Django 6.0.3 on 2026-05-11 04:08

import classification.models.overlaps_model
import library.utils.database_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0182_remove_overlapdiscordancenotification_lab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlapcontributionskew',
            name='skew_perspective',
        ),
        migrations.AddField(
            model_name='overlapcontributionskew',
            name='next_step',
            field=library.utils.database_utils.IntegerFieldChoices(choices=[(0, 'Not Involved'), (1, 'Pending Calculation'), (2, 'Awaiting Other Lab'), (3, 'Awaiting Your Triage'), (4, 'Awaiting your Triage - others have triaged'), (5, 'Pending Your Amendment'), (6, 'Unanimously Complex'), (7, 'To Discuss')], choices_type=classification.models.overlaps_model.TriageNextStep, default=1),
        ),
    ]
