# Generated by Django 4.2.17 on 2025-10-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0182_alter_conflicthistory_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationgrouping',
            name='pending_change_clin_sig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classificationgrouping',
            name='pending_change_onc_path',
            field=models.BooleanField(default=False),
        ),
    ]
