# Generated by Django 4.2.17 on 2025-10-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0183_classificationgrouping_pending_change_clin_sig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationgrouping',
            name='latest_cached_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
