# Generated by Django 6.0.3 on 2026-05-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0183_remove_overlapcontributionskew_skew_perspective_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alleleorigingrouping',
            name='dirty',
        ),
        migrations.AlterField(
            model_name='overlapcontribution',
            name='classification_grouping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.classificationgrouping'),
        ),
    ]
