# Generated by Django 4.2.17 on 2025-10-08 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_is_complete'),
        ('classification', '0184_classificationgrouping_latest_cached_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.reviewedobject'),
        ),
    ]
