# Generated by Django 6.0.3 on 2026-05-22 01:59

import annotation.models.data_enums
import classification.enums.overlaps_enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0184_remove_alleleorigingrouping_dirty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlapcontribution',
            name='comment',
            field=models.JSONField(default=classification.enums.overlaps_enums.TriageComment.default_json),
        ),
        migrations.AlterField(
            model_name='overlapcontribution',
            name='effective_date',
            field=models.JSONField(db_column='effective_date', default=annotation.models.data_enums.EffectiveDate.default_json),
        ),
        migrations.AlterField(
            model_name='overlapcontribution',
            name='triage_state',
            field=models.JSONField(default=classification.enums.overlaps_enums.TriageState.default_json),
        ),
    ]
