# Generated by Django 6.0.3 on 2026-05-22 02:36

import annotation.models.data_enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0185_alter_overlapcontribution_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlapcontribution',
            name='effective_date',
            field=models.JSONField(default=annotation.models.data_enums.EffectiveDate.default_json),
        ),
    ]
