# Generated by Django 6.0.3 on 2026-06-02 03:24

import classification.enums.classification_enums
import library.utils.database_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0186_alter_overlapcontribution_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlap',
            name='overlap_pending_status',
            field=library.utils.database_utils.IntegerFieldChoices(choices=[(0, 'No contributions'), (10, 'No counting contributions'), (20, 'Single submitter'), (30, 'Exact agreement'), (40, 'Terminology differences'), (50, 'Resolution differences'), (60, 'Minor differences'), (70, 'Tier 1 vs Tier 2 differences'), (80, 'Discordance'), (90, 'Medically significant discordance')], choices_type=classification.enums.classification_enums.OverlapStatus, default=0),
        ),
    ]
