# Generated by Django 6.0.3 on 2026-06-02 03:47

from django.db import migrations
from django.db.models import F


class Migration(migrations.Migration):

    def set_pending_calculation(apps, _schema_editor):
        Overlap = apps.get_model('classification', 'Overlap')
        Overlap.objects.update(overlap_pending_status=F('overlap_status'))

    dependencies = [
        ('classification', '0187_overlap_overlap_pending_status'),
    ]

    operations = [
        migrations.RunPython(set_pending_calculation, migrations.RunPython.noop)
    ]
