# Generated by Django 6.0.5 on 2026-06-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0165_pathogenicity_ekeys_raw_scores_and_cnv'),
        ('classification', '0189_overlap_overlap_max_ever_status'),
    ]

    operations = [
    ]
