# Generated by Django 6.0.6 on 2026-07-22 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0190_merge_20260622_1329'),
        ('review', '0004_review_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlap',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.reviewedobject'),
        ),
    ]
