# Generated by Django 6.0.6 on 2026-07-28 23:54

import classification.enums.overlaps_enums
import library.utils.database_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0191_overlap_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlap',
            name='value_type',
            field=library.utils.database_utils.TextFieldChoices(choices=[('O', 'Onco-Path'), ('S', 'Clinical significance')], choices_type=classification.enums.overlaps_enums.ClassificationResultValue, max_length=1),
        ),
    ]
