# Generated by Django 6.0.6 on 2026-07-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0192_alter_overlap_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlapcontribution',
            name='possibly_outdated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
