# Generated by Django 6.0.6 on 2026-08-03 02:55

import classification.enums.classification_enums
import library.utils.database_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0193_overlapcontribution_possibly_outdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlap',
            name='overlap_override_status',
            field=library.utils.database_utils.IntegerFieldChoices(choices=[(0, 'No override'), (10, 'Complex'), (20, 'Continued discordance')], choices_type=classification.enums.classification_enums.OverlapOverrideStatus, default=0),
        ),
        migrations.AddField(
            model_name='overlapcontribution',
            name='review_agreed_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
