# Generated by Django 6.0.6 on 2026-08-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0194_overlap_overlap_override_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlap',
            name='overlap_pending_status',
        ),
        migrations.AddField(
            model_name='overlap',
            name='has_pending_values',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
