# Generated by Django 6.0.6 on 2026-08-05 00:57

import classification.enums.classification_enums
import library.utils.database_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0195_remove_overlap_overlap_pending_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlap',
            name='overlap_override_status',
            field=library.utils.database_utils.IntegerFieldChoices(choices=[(0, 'No override'), (10, 'Complex'), (20, 'Continued discordance'), (30, 'Confident vs ClinVar'), (40, 'Ignoring older ClinVar records')], choices_type=classification.enums.classification_enums.OverlapOverrideStatus, default=0),
        ),
    ]
