# Generated by Django 6.0.6 on 2026-08-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0196_alter_overlap_overlap_override_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlapcontribution',
            name='possibly_outdated',
        ),
    ]
