# Generated by Django 6.0.6 on 2026-08-06 02:21

import classification.enums.overlaps_enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0197_remove_overlapcontribution_possibly_outdated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlapdiscordancenotification',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='overlapdiscordancenotification',
            name='old_status',
        ),
        migrations.AddField(
            model_name='overlapdiscordancenotification',
            name='new_state',
            field=models.JSONField(default=classification.enums.overlaps_enums.OverlapState.default_json),
        ),
        migrations.AddField(
            model_name='overlapdiscordancenotification',
            name='old_state',
            field=models.JSONField(default=classification.enums.overlaps_enums.OverlapState.default_json),
        ),
    ]
