# Generated by Django 6.0.6 on 2026-08-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0171_copy_consensus_off_annotation_backed_keys'),
        ('classification', '0198_remove_overlapdiscordancenotification_new_status_and_more'),
    ]

    operations = [
    ]
