# Generated by Django 6.0.6 on 2026-08-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0174_reclassificationevent_event_type_and_more'),
        ('classification', '0199_merge_20260817_0936'),
    ]

    operations = [
    ]
