# Generated by Django 6.0.6 on 2026-08-26 06:18

import classification.enums.overlaps_enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0200_merge_20260821_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlap',
            name='cached_overlap_state',
            field=models.JSONField(default=classification.enums.overlaps_enums.OverlapState.default_json),
        ),
    ]
