# Generated by Django 6.1 on 2026-08-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0201_overlap_cached_overlap_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlap',
            name='all_vus',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
