# Generated by Django 6.1 on 2026-09-04 06:05

import classification.models.overlaps_model
import library.utils.database_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0202_overlap_all_vus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlapcontributionskew',
            name='next_step',
            field=library.utils.database_utils.IntegerFieldChoices(choices=[(0, 'Not Involved'), (1, 'Pending Calculation'), (2, 'Awaiting Other Lab'), (3, 'Awaiting Your Triage'), (4, 'Awaiting Your Triage - others have triaged'), (5, 'Awaiting Your Amendment'), (6, 'Unanimously Complex'), (7, 'To Discuss')], choices_type=classification.models.overlaps_model.TriageNextStep, default=1),
        ),
    ]
