# Generated by Django 6.1 on 2026-09-04 07:25

import classification.enums.classification_enums
import library.utils.database_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0203_alter_overlapcontributionskew_next_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlap',
            name='overlap_override_status',
            field=library.utils.database_utils.IntegerFieldChoices(choices=[(0, 'No Override'), (10, 'Complex'), (20, 'Continued Discordance'), (30, 'Confident vs ClinVar'), (40, 'Ignoring Older ClinVar Records')], choices_type=classification.enums.classification_enums.OverlapOverrideStatus, default=0),
        ),
    ]
