# Generated by Django 6.1 on 2026-09-07 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0204_alter_overlap_overlap_override_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OverlapContributionSkew',
            new_name='OverlapContributionNextStep',
        ),
    ]
