# Generated by Django 6.1 on 2026-09-09 05:14

from django.db import migrations
from django.db.models import Count, Min


def _merge_duplicate_groupings(apps, _schema_editor):
    """ A get_or_create race (before this constraint existed) created duplicate groupings, and put the same
        classification into both. Keep the lowest pk, left dirty for classification_groupings to rebuild (#2024) """
    ClassificationGrouping = apps.get_model("classification", "ClassificationGrouping")
    ClassificationGroupingEntry = apps.get_model("classification", "ClassificationGroupingEntry")

    fields = ["allele_origin_grouping", "lab", "share_level"]
    duplicates = ClassificationGrouping.objects.values(*fields).annotate(count=Count("pk"), keep_pk=Min("pk")).filter(count__gt=1)
    for duplicate in duplicates:
        keep_pk = duplicate["keep_pk"]
        others = ClassificationGrouping.objects.filter(**{field: duplicate[field] for field in fields}).exclude(pk=keep_pk)
        kept_classifications = ClassificationGroupingEntry.objects.filter(grouping_id=keep_pk).values("classification")
        ClassificationGroupingEntry.objects.filter(grouping__in=others).exclude(classification__in=kept_classifications).update(grouping_id=keep_pk)
        others.delete()
        ClassificationGrouping.objects.filter(pk=keep_pk).update(dirty=True)

    duplicate_entries = ClassificationGroupingEntry.objects.values("classification").annotate(count=Count("pk"), keep_pk=Min("pk")).filter(count__gt=1)
    for duplicate in duplicate_entries:
        extra_entries = ClassificationGroupingEntry.objects.filter(classification=duplicate["classification"]).exclude(pk=duplicate["keep_pk"])
        ClassificationGrouping.objects.filter(pk__in=extra_entries.values("grouping")).update(dirty=True)
        extra_entries.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0205_rename_overlapcontributionskew_overlapcontributionnextstep'),
        ('snpdb', '0213_tag_allele_origin_bucket'),
    ]

    operations = [
        migrations.RunPython(_merge_duplicate_groupings, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='classificationgrouping',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='classificationgrouping',
            unique_together={('allele_origin_grouping', 'lab', 'share_level')},
        ),
    ]
