# Generated by Django 6.1 on 2026-09-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0205_rename_overlapcontributionskew_overlapcontributionnextstep'),
        ('snpdb', '0213_tag_allele_origin_bucket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificationgrouping',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='classificationgrouping',
            unique_together={('allele_origin_grouping', 'lab', 'share_level')},
        ),
    ]
