# Generated by Django 6.1 on 2026-09-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0182_splice_label_ekey'),
        ('classification', '0206_alter_classificationgrouping_options_and_more'),
    ]

    operations = [
    ]
