# Generated by Django 6.1.1 on 2026-09-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0186_one_off_rematch_failed_gene_level_allele_infos"),
        ("classification", "0207_merge_20260916_1601"),
    ]

    operations = []
