# Generated by Django 6.1 on 2026-09-21 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0186_alter_clinvar_version_alter_geneannotation_version_and_more'),
        ('classification', '0208_merge_20260921_1030'),
        ('flags', '0010_alter_flagtype_options'),
        ('snpdb', '0271_alter_cohortgenotype_collection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='classification',
            name='summary__d_sort_idx',
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(models.F('summary__date__date'), name='summary__d_sort_idx'),
        ),
    ]
