# Generated by Django 6.1 on 2026-09-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0187_copy_number_ekey_label'),
        ('classification', '0209_remove_classification_summary__d_sort_idx_and_more'),
    ]

    operations = [
    ]
