# Generated by Django 6.1 on 2026-09-22 23:36

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0210_merge_20260922_1204'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["classification_groupings", "--all"]))
    ]
