# Generated by Django 6.1 on 2026-09-23 01:24

from django.db import migrations
from classification.evidence_key_rename import OptionUpdator


def _add_other(apps, schema):
    EvidenceKey = apps.get_model('classification', 'EvidenceKey')
    for letter in ('a','b','c','d'):
        option_updator = OptionUpdator(EvidenceKey.objects.get(key=f"amp:level_{letter}"))
        option_updator.ensure_option({
            "key": "other",
            "index": 5
        })
        option_updator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0211_classification_groupings_by_texting_context'),
    ]

    operations = [
        migrations.RunPython(_add_other)
    ]
