# Generated by Django 6.1 on 2026-09-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0188_one_off_gene_level_strings_respace'),
        ('classification', '0212_add_other_to_amp_level'),
    ]

    operations = [
    ]
