# Generated by Django 6.1.1 on 2026-09-23 06:46

from django.db import migrations, models
from django.db.models import Count, Min


def _delete_duplicates(apps, _schema_editor):
    """ Overlaps are only on branch test servers so far; classification_overlaps --full_reset rebuilds them anyway """
    Overlap = apps.get_model("classification", "Overlap")
    OverlapContributionNextStep = apps.get_model("classification", "OverlapContributionNextStep")

    for model, fields in [
        (Overlap, ["overlap_type", "value_type", "allele", "testing_context_bucket", "tumor_type_category"]),
        (OverlapContributionNextStep, ["overlap", "contribution"]),
    ]:
        duplicates = model.objects.values(*fields).annotate(count=Count("pk"), keep_pk=Min("pk")).filter(count__gt=1)
        for duplicate in duplicates:
            model.objects.filter(**{field: duplicate[field] for field in fields}).exclude(pk=duplicate["keep_pk"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0213_merge_20260923_1201'),
        ('review', '0004_review_is_complete'),
        ('snpdb', '0274_tag_config_show_resolved_variant_tags'),
    ]

    operations = [
        migrations.RunPython(_delete_duplicates, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='alleleorigingrouping',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='overlapcontributionnextstep',
            unique_together={('overlap', 'contribution')},
        ),
        migrations.AddConstraint(
            model_name='alleleorigingrouping',
            constraint=models.UniqueConstraint(fields=('allele', 'allele_origin_bucket', 'testing_context_bucket', 'tumor_type_category'), name='allele_origin_grouping_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='overlap',
            constraint=models.UniqueConstraint(fields=('overlap_type', 'value_type', 'allele', 'testing_context_bucket', 'tumor_type_category'), name='overlap_unique', nulls_distinct=False),
        ),
    ]
