# Generated by Django 6.1 on 2026-10-01 00:45

from django.db import migrations

from classification.autopopulate_evidence_keys.clinvar_option_updator import EvidenceKeyOptionUpdator


def mode_of_inheritance_multifactorial(apps, _schema_editor):
    options = EvidenceKeyOptionUpdator(apps, "mode_of_inheritance")
    options.set_clinvar_option("multifactorial", "Multifactorial inheritance")


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0217_conditiontext_pending_automatch'),
    ]

    operations = [
        migrations.RunPython(mode_of_inheritance_multifactorial)
    ]
