# Generated by Django 6.1.1 on 2026-09-24 05:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0216_rename_c_hgvs_resolved_hgvs"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationimportrun",
            name="lab_record_ids_already_withdrawn",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list
            ),
        ),
    ]
