# Generated by Django 6.1 on 2026-10-05 23:30

from datetime import date

from django.db import migrations, models

from library.utils.collection_utils import batch_iterator


def _parse_date(date_str):
    try:
        return date.fromisoformat(date_str)
    except (TypeError, ValueError):
        return None


def _populate_sort_columns(apps, _schema_editor):
    """ Copies the sort values out of each grouping's own latest_cached_summary, as ClassificationGrouping.update does """
    ClassificationGrouping = apps.get_model("classification", "ClassificationGrouping")
    qs = ClassificationGrouping.objects.only("pk", "latest_cached_summary").order_by("pk")
    for batch in batch_iterator(qs.iterator(chunk_size=2000), 2000):
        for grouping in batch:
            summary = grouping.latest_cached_summary or {}
            grouping.latest_pathogenicity_sort = (summary.get("pathogenicity") or {}).get("sort")
            grouping.latest_somatic_sort = (summary.get("somatic") or {}).get("sort")
            grouping.latest_curated_date = _parse_date((summary.get("date") or {}).get("date"))
        ClassificationGrouping.objects.bulk_update(batch, fields=["latest_pathogenicity_sort", "latest_somatic_sort",
                                                                  "latest_curated_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0218_update_multifactoral_clinvar'),
        ('snpdb', '0278_remove_user_award_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationgrouping',
            name='latest_curated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationgrouping',
            name='latest_pathogenicity_sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationgrouping',
            name='latest_somatic_sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(_populate_sort_columns, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='classificationgrouping',
            index=models.Index(models.OrderBy(models.F('latest_pathogenicity_sort'), descending=True, nulls_last=True), models.OrderBy(models.F('latest_somatic_sort'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='cg_path_sort_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationgrouping',
            index=models.Index(models.OrderBy(models.F('latest_pathogenicity_sort'), nulls_last=True), models.OrderBy(models.F('latest_somatic_sort'), nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='cg_path_sort_asc_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationgrouping',
            index=models.Index(models.OrderBy(models.F('latest_somatic_sort'), descending=True, nulls_last=True), models.OrderBy(models.F('latest_pathogenicity_sort'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='cg_somatic_sort_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationgrouping',
            index=models.Index(models.OrderBy(models.F('latest_somatic_sort'), nulls_last=True), models.OrderBy(models.F('latest_pathogenicity_sort'), nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='cg_somatic_sort_asc_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationgrouping',
            index=models.Index(models.OrderBy(models.F('latest_curated_date'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='cg_curated_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationgrouping',
            index=models.Index(models.OrderBy(models.F('latest_curated_date'), nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='cg_curated_date_asc_idx'),
        ),
    ]
