# Generated by Django 6.1 on 2026-10-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0219_classificationgrouping_sort_columns'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='classification',
            name='summary__p_sort_idx',
        ),
        migrations.RemoveIndex(
            model_name='classification',
            name='summary__s_sort_idx',
        ),
        migrations.RemoveIndex(
            model_name='classification',
            name='summary__d_sort_idx',
        ),
    ]
