# Generated by Django 6.1.1 on 2026-10-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0220_remove_classification_summary__p_sort_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolvedvariantinfo',
            name='resolved_hgvs_compat',
        ),
    ]
