# Generated by Django 3.1 on 2021-01-08 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ontologyimport',
            name='notes',
        ),
        migrations.AddField(
            model_name='ontologyimport',
            name='context',
            field=models.TextField(default="mondo_file"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ontologyimport',
            name='processed_date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
