# Generated by Django 3.1 on 2021-01-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0002_auto_20210112_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyimport',
            name='ontology_service',
            field=models.CharField(choices=[('MONDO', 'MONDO'), ('OMIM', 'OMIM'), ('HP', 'HP'), ('PAAU', 'PanelApp AU')], max_length=5),
        ),
        migrations.AlterField(
            model_name='ontologyterm',
            name='ontology_service',
            field=models.CharField(choices=[('MONDO', 'MONDO'), ('OMIM', 'OMIM'), ('HP', 'HP'), ('PAAU', 'PanelApp AU')], max_length=5),
        ),
        migrations.AlterField(
            model_name='ontologytermrelation',
            name='relation',
            field=models.CharField(choices=[('is_a', 'is a'), ('exact', 'exact'), ('close', 'close'), ('broad', 'broad'), ('narrow', 'narrow'), ('frequency', 'has a frequency in')], max_length=10),
        ),
    ]
