# Generated by Django 3.1 on 2021-01-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0002_auto_20210108_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologyimport',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
