# Generated by Django 3.1 on 2021-01-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0003_auto_20210113_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologyimport',
            name='processor_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ontologytermrelation',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ontologytermrelation',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ontologyimport',
            name='ontology_service',
            field=models.CharField(choices=[('MONDO', 'MONDO'), ('OMIM', 'OMIM'), ('HP', 'HP'), ('HGNC', 'HGNC'), ('PAAU', 'PanelApp AU')], max_length=5),
        ),
        migrations.AlterField(
            model_name='ontologyterm',
            name='from_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ontology.ontologyimport'),
        ),
        migrations.AlterField(
            model_name='ontologyterm',
            name='ontology_service',
            field=models.CharField(choices=[('MONDO', 'MONDO'), ('OMIM', 'OMIM'), ('HP', 'HP'), ('HGNC', 'HGNC'), ('PAAU', 'PanelApp AU')], max_length=5),
        ),
        migrations.AlterField(
            model_name='ontologytermrelation',
            name='relation',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='OntologyTermGeneRelation',
        ),
    ]
