# Generated by Django 3.1 on 2021-01-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0004_auto_20210114_1604'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ontologytermrelation',
            unique_together={('source_term', 'dest_term', 'relation')},
        ),
        migrations.RemoveField(
            model_name='ontologytermrelation',
            name='deleted_date',
        ),
    ]
