# Generated by Django 3.1 on 2021-01-20 23:56

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0005_auto_20210115_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontologyimport',
            old_name='ontology_service',
            new_name='import_source',
        ),
        migrations.AlterField(
            model_name='ontologyimport',
            name='import_source',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ontologyterm',
            name='ontology_service',
            field=models.CharField(choices=[('MONDO', 'MONDO'), ('OMIM', 'OMIM'), ('HP', 'HP'), ('HGNC', 'HGNC')],
                                   max_length=5),
        )
    ]
