# Generated by Django 3.1 on 2021-01-27 04:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0006_auto_20210121_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologyterm',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
