# Generated by Django 4.0.2 on 2022-06-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0009_auto_20210316_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OntologyTermRelation',
            new_name='OldOntologyTermRelation',
        ),
    ]
