# Generated by Django 4.0.2 on 2022-06-17 07:07

from django.db import migrations


def _one_off_ontology_term_relationship_partitions_and_copy(apps, schema_editor):
    OldOntologyTermRelation = apps.get_model("ontology", "OldOntologyTermRelation")
    OntologyTermRelation = apps.get_model("ontology", "OntologyTermRelation")

    # Create partitions for existing imports
    import_sources = OldOntologyTermRelation.objects.all().values_list("from_import", flat=True).distinct()
    for import_source_id in import_sources:
        schema_editor.add_list_partition(
            model=OntologyTermRelation,
            name=f"import_source_{import_source_id}",
            values=[import_source_id],
        )

    records = []
    for values in OldOntologyTermRelation.objects.all().values():
        records.append(OntologyTermRelation(**values))
    if records:
        num_partitions = len(import_sources)
        print(f"Copying {len(records)} records into new partitioned OntologyTermRelation ({num_partitions=})")
        OntologyTermRelation.objects.bulk_create(records, batch_size=2000)


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0012_auto_20220617_1636'),
    ]

    operations = [
        migrations.RunPython(_one_off_ontology_term_relationship_partitions_and_copy),
    ]
