# Generated by Django 4.0.2 on 2022-06-17 07:07
from django.db import migrations


def _one_off_ontology_term_relationship_partitions_and_copy(apps, schema_editor):
    OldOntologyTermRelation = apps.get_model("ontology", "OldOntologyTermRelation")
    OntologyTermRelation = apps.get_model("ontology", "OntologyTermRelation")
    OntologyImport = apps.get_model("ontology", "OntologyImport")

    # Create partitions for existing imports (the last of each type used in OntologyVersion - as that is what
    # will be created as the legacy OntologyVersion)
    # The data below is copy/pasted from and is equivalent of OntologyVersion.in_ontology_version()
    MONDO = "MONDO"
    HPO = "HP"
    GENCC = 'gencc'

    _ONTOLOGY_VERSION_IMPORTS = [
        (GENCC, ['https://search.thegencc.org/download/action/submissions-export-csv', 'gencc-submissions.csv']),
        (MONDO, ['mondo.json']),
        (HPO, ['hp.owl']),
        (HPO, ['phenotype_to_genes.txt', 'OMIM_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt']),
    ]

    num_partitions = 0
    for from_import, filenames in _ONTOLOGY_VERSION_IMPORTS:
        if oi := OntologyImport.objects.filter(import_source=from_import, filename__in=filenames).order_by("pk").last():
            import_source_id = oi.pk
            schema_editor.add_list_partition(
                model=OntologyTermRelation,
                name=f"import_source_{import_source_id}",
                values=[import_source_id],
            )
            num_partitions += 1

    records = []
    for values in OldOntologyTermRelation.objects.all().values():
        records.append(OntologyTermRelation(**values))
    if records:
        print(f"Copying {len(records)} records into new partitioned OntologyTermRelation ({num_partitions=})")
        OntologyTermRelation.objects.bulk_create(records, batch_size=2000)


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0012_auto_20220617_1636'),
    ]

    operations = [
        migrations.RunPython(_one_off_ontology_term_relationship_partitions_and_copy),
    ]
