# Generated by Django 4.0.2 on 2022-06-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0013_one_off_ontology_term_relationship_partitions_and_copy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldOntologyTermRelation',
        ),
    ]
