# Generated by Django 4.0.2 on 2022-06-20 03:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0014_delete_oldontologytermrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologyimport',
            name='version',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='OntologyVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('gencc_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gencc_ontology_version', to='ontology.ontologyimport')),
                ('hp_owl_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hp_owl_ontology_version', to='ontology.ontologyimport')),
                ('hp_phenotype_to_genes_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hp_phenotype_to_genes_ontology_version', to='ontology.ontologyimport')),
                ('mondo_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mondo_ontology_version', to='ontology.ontologyimport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
