# Generated by Django 4.0.2 on 2022-06-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0016_one_off_assign_ontology_import_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyimport',
            name='version',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='ontologyimport',
            unique_together={('import_source', 'filename', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='ontologyversion',
            unique_together={('gencc_import', 'mondo_import', 'hp_owl_import', 'hp_phenotype_to_genes_import')},
        ),
    ]
