# Generated by Django 4.0.2 on 2022-06-29 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0017_alter_ontologyimport_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologytermrelation',
            name='source_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='ontology.ontologyterm'),
        ),
    ]
