# Generated by Django 4.0.4 on 2022-07-18 03:45

from django.db import migrations, models


def _populate_deprecated(apps, schema_editor):
    OntologyTerm = apps.get_model("ontology", "OntologyTerm")
    OntologyTerm.objects.filter(name__icontains='obsolete').update(deprecated=True)


def _dummy_reverse(apps, schema_editor):
    # code is reversable
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0018_alter_ontologytermrelation_source_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologyterm',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.RunPython(_populate_deprecated, reverse_code=_dummy_reverse)
    ]
