# Generated by Django 4.0.7 on 2022-08-29 05:58

from django.db import migrations, models


def _populate_status(apps, _schema_editor):
    OntologyTerm = apps.get_model("ontology", "OntologyTerm")
    OntologyTerm.objects.filter(deprecated=True).update(status='D')


def _dummy_reverse(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0019_ontologyterm_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologyterm',
            name='status',
            field=models.CharField(choices=[('C', 'Condition'), ('D', 'Deprecated'), ('N', 'Non Condition')], default='C', max_length=1),
        ),
        migrations.RunPython(_populate_status, _dummy_reverse)
    ]
