# Generated by Django 4.0.7 on 2022-08-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0020_ontologyterm_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ontologyterm',
            name='deprecated',
        ),
    ]
