# Generated by Django 4.0.7 on 2022-09-09 00:45

from django.db import migrations


def _remove_duplicates(apps, schema_editor):
    OntologyImport = apps.get_model("ontology", "OntologyImport")
    OntologyTermRelation = apps.get_model("ontology", "OntologyTermRelation")

    all_panelapp = OntologyImport.objects.filter(import_source="PAAU").order_by("context", "-created")
    delete_me = list()
    last_o_imp = None
    for o_imp in all_panelapp:
        if last_o_imp is None or last_o_imp.context != o_imp.context:
            last_o_imp = o_imp
        else:
            delete_me.append(o_imp)

    print(f"Found {len(delete_me)} duplicates, removing")
    for o_imp in delete_me:
        OntologyTermRelation.objects.filter(from_import=o_imp).delete()
        o_imp.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0021_remove_ontologyterm_deprecated'),
    ]

    operations = [
        migrations.RunPython(_remove_duplicates)
    ]
