# Generated by Django 4.0.7 on 2022-09-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0022_one_off_remove_panelappau_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyterm',
            name='status',
            field=models.CharField(choices=[('C', 'Condition'), ('D', 'Deprecated'), ('N', 'Non Condition'), ('S', 'Stub')], default='C', max_length=1),
        ),
    ]
