# Generated by Django 4.2.2 on 2023-08-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0024_alter_ontologyversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyterm',
            name='ontology_service',
            field=models.CharField(choices=[('MONDO', 'MONDO'), ('OMIM', 'OMIM'), ('HP', 'HP'), ('HGNC', 'HGNC'), ('DOID', 'DOID'), ('Orphanet', 'Orphanet'), ('MedGen', 'MedGen')], max_length=10),
        ),
    ]
