# Generated by Django 4.2.2 on 2023-08-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0025_alter_ontologyterm_ontology_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyterm',
            name='ontology_service',
            field=models.CharField(choices=[('MONDO', 'MONDO'), ('OMIM', 'OMIM'), ('HP', 'HP'), ('HGNC', 'HGNC'), ('DOID', 'DOID'), ('ORPHA', 'ORPHA'), ('MedGen', 'MedGen')], max_length=10),
        ),
    ]
