# Generated by Django 4.2.10 on 2024-05-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0026_alter_ontologyterm_ontology_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyterm',
            name='ontology_service',
            field=models.CharField(choices=[('MONDO', 'MONDO'), ('OMIM', 'OMIM'), ('HP', 'HP'), ('HGNC', 'HGNC'), ('DOID', 'DOID'), ('ORPHA', 'ORPHA'), ('MedGen', 'MedGen'), ('MeSH', 'MeSH')], max_length=10),
        ),
    ]
