# Generated by Django 4.0.7 on 2023-05-05 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionQuestionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscussionQuestion',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('help', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.TextField(choices=[('T', 'Text'), ('S', 'Select'), ('M', 'Multi-Select'), ('D', 'Date')])),
                ('provide_other', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.discussionquestiongroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscussionAnswerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.TextField()),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.discussionquestiongroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscussionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.JSONField(blank=True, null=True)),
                ('answer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.discussionanswergroup')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.discussionquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
