# Generated by Django 4.0.7 on 2023-05-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopic',
            name='heading',
            field=models.TextField(default=''),
        ),
    ]
