# Generated by Django 3.1 on 2020-11-30 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0007_activesamplegenelist_samplegenelist'),
        ('seqauto', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcgenelist',
            name='file_last_modified',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='qcgenelist',
            name='sample_gene_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.samplegenelist'),
        ),
    ]
