# Generated by Django 3.1.3 on 2021-01-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0004_one_off_fix_legacy_create_sample_gene_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqautorun',
            name='status',
            field=models.CharField(choices=[('c', 'Created'), ('s', 'Scanning Files'), ('m', 'Create Models'), ('j', 'Scripts and Jobs'), ('F', 'Finished'), ('E', 'Error')], default='c', max_length=1),
        ),
    ]
