# Generated by Django 3.1.3 on 2021-03-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0005_auto_20210104_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
