# Generated by Django 3.1.3 on 2021-03-24 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathtests', '0005_auto_20210324_1455'),
        ('upload', '0006_auto_20210324_1455'),
        ('seqauto', '0010_auto_20210324_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleSheetCombinedVCFFile',
        ),
        migrations.DeleteModel(
            name='SequencingRun',
        ),
        migrations.DeleteModel(
            name='SequencingRunCurrentSampleSheet',
        ),
        migrations.DeleteModel(
            name='SequencingSample',
        ),
        migrations.DeleteModel(
            name='SequencingSampleData',
        ),
        migrations.DeleteModel(
            name='UnalignedReads',
        ),
        migrations.DeleteModel(
            name='VCFFile',
        ),
        migrations.DeleteModel(
            name='VCFFromSequencingRun',
        ),
    ]
