# Generated by Django 3.1.3 on 2021-03-24 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0026_auto_20210319_1231'),
        ('pathtests', '0005_auto_20210324_1455'),
        ('upload', '0006_auto_20210324_1455'),
        ('patients', '0001_initial'),
        ('genes', '0022_auto_20210225_1521'),
        ('seqauto', '0011_auto_20210324_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BamFile2',
            new_name='BamFile',
        ),
        migrations.RenameModel(
            old_name='ExecSummaryReferenceRange2',
            new_name='ExecSummaryReferenceRange',
        ),
        migrations.RenameModel(
            old_name='Fastq2',
            new_name='Fastq',
        ),
        migrations.RenameModel(
            old_name='FastQC2',
            new_name='FastQC',
        ),
        migrations.RenameModel(
            old_name='Flagstats2',
            new_name='Flagstats',
        ),
        migrations.RenameModel(
            old_name='IlluminaFlowcellQC2',
            new_name='IlluminaFlowcellQC',
        ),
        migrations.RenameModel(
            old_name='IlluminaIndexQC2',
            new_name='IlluminaIndexQC',
        ),
        migrations.RenameModel(
            old_name='QC2',
            new_name='QC',
        ),
        migrations.RenameModel(
            old_name='QCExecSummary2',
            new_name='QCExecSummary',
        ),
        migrations.RenameModel(
            old_name='QCGeneCoverage2',
            new_name='QCGeneCoverage',
        ),
        migrations.RenameModel(
            old_name='QCGeneList2',
            new_name='QCGeneList',
        ),
        migrations.RenameModel(
            old_name='ReadQ302',
            new_name='ReadQ30',
        ),
        migrations.RenameModel(
            old_name='SampleFromSequencingSample2',
            new_name='SampleFromSequencingSample',
        ),
        migrations.RenameModel(
            old_name='SampleSheet2',
            new_name='SampleSheet',
        ),
        migrations.RenameModel(
            old_name='SampleSheetCombinedVCFFile2',
            new_name='SampleSheetCombinedVCFFile',
        ),
        migrations.RenameModel(
            old_name='SequencingRunCurrentSampleSheet2',
            new_name='SequencingRunCurrentSampleSheet',
        ),
        migrations.RenameModel(
            old_name='SequencingSample2',
            new_name='SequencingSample',
        ),
        migrations.RenameModel(
            old_name='SequencingSampleData2',
            new_name='SequencingSampleData',
        ),
        migrations.RenameModel(
            old_name='UnalignedReads2',
            new_name='UnalignedReads',
        ),
        migrations.RenameModel(
            old_name='VCFFile2',
            new_name='VCFFile',
        ),
        migrations.RenameModel(
            old_name='VCFFromSequencingRun2',
            new_name='VCFFromSequencingRun',
        ),
        migrations.RenameModel(
            old_name='SequencingRun2',
            new_name='SequencingRun',
        ),
        migrations.CreateModel(
            name='SequencingRunWiki',
            fields=[
                ('wiki_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snpdb.wiki')),
                ('sequencing_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seqauto.sequencingrun')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('snpdb.wiki',),
        ),
        migrations.CreateModel(
            name='JobScript',
            fields=[
                ('seqautorecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seqauto.seqautorecord')),
                ('out_file', models.TextField(null=True)),
                ('file_type', models.CharField(choices=[('S', 'SampleSheet'), ('I', 'Illumina_Flowcell_QC'), ('U', 'FastQ'), ('F', 'FastQC'), ('B', 'Bam'), ('T', 'Flagstats'), ('V', 'VCF'), ('C', 'CombinedVCF'), ('Q', 'QC'), ('M', 'Data Migration')], max_length=1)),
                ('job_id', models.TextField(null=True)),
                ('job_status', models.CharField(choices=[('C', 'Created'), ('S', 'Submitted'), ('F', 'Finished')], default='C', max_length=1)),
                ('return_code', models.IntegerField(null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='seqauto.seqautorecord')),
                ('seqauto_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seqauto.seqautorun')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('seqauto.seqautorecord',),
        ),
    ]
