# Generated by Django 3.1.3 on 2021-03-25 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0013_auto_20210324_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplesheet',
            old_name='sequencing_run',
            new_name='old_sequencing_run',
        ),
        migrations.RemoveField(
            model_name='sequencingrun',
            name='ready',
        ),
        migrations.AddField(
            model_name='seqautorecord',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seqautorecord',
            name='sequencing_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seqauto.sequencingrun'),
        ),
    ]
