# Generated by Django 3.1.3 on 2021-03-25 02:01

from django.db import migrations
from django.db.models import F


def _one_off_add_sequencing_run_field(apps, schema_editor):
    SequencingRun = apps.get_model("seqauto", "SequencingRun")
    SampleSheet = apps.get_model("seqauto", "SampleSheet")

    # These can be directly set off other fields
    #SequencingRun.objects.all().update(sequencing_run_id=F("name"))
    #SampleSheet.objects.all().update(sequencing_run_id=F("old_sequencing_run"))

    CLASSES_PATH_TO_SEQUENCING_RUN = {
        "SequencingRun": "name",
        "SampleSheet": "old_sequencing_run",
        "IlluminaFlowcellQC": "sample_sheet__sequencing_run",
        "ReadQ30": "illumina_flowcell_qc__sample_sheet__sequencing_run",
        "IlluminaIndexQC": "illumina_flowcell_qc__sample_sheet__sequencing_run",
        "Fastq": "sequencing_sample__sample_sheet__sequencing_run",
        "FastQC": "fastq__sequencing_sample__sample_sheet__sequencing_run",
        "UnalignedReads": "fastq_r1__sequencing_sample__sample_sheet__sequencing_run",
        "BamFile": "unaligned_reads__fastq_r1__sequencing_sample__sample_sheet__sequencing_run",
        "Flagstats": "bam_file__unaligned_reads__fastq_r1__sequencing_sample__sample_sheet__sequencing_run",
        "VCFFile":  "bam_file__unaligned_reads__fastq_r1__sequencing_sample__sample_sheet__sequencing_run",
        "SampleSheetCombinedVCFFile": "sample_sheet__sequencing_run",
        "QC": "bam_file__unaligned_reads__fastq_r1__sequencing_sample__sample_sheet__sequencing_run",
        "QCGeneList": "qc__bam_file__unaligned_reads__fastq_r1__sequencing_sample__sample_sheet__sequencing_run",
        "QCExecSummary": "qc__bam_file__unaligned_reads__fastq_r1__sequencing_sample__sample_sheet__sequencing_run",
        "ExecSummaryReferenceRange": "exec_summary__qc__bam_file__unaligned_reads__fastq_r1__sequencing_sample__sample_sheet__sequencing_run",
    }

    print("\n")
    for class_name, path_to_sequencing_run in CLASSES_PATH_TO_SEQUENCING_RUN.items():
        klass = apps.get_model("seqauto", class_name)
        print(f"{class_name=}")

        # Tried doing bulk update but it died expecting id (int) while PK=sequencing_run - I think
        # it has something to do with model inheritance
        for record in klass.objects.all():
            sequencing_run_id = klass.objects.all().values_list(path_to_sequencing_run, flat=True).distinct()[0]
            #print(f"Assigning {record} -> {sequencing_run_id=}")
            record.sequencing_run_id = sequencing_run_id
            record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0014_auto_20210325_1229'),
    ]

    operations = [
        migrations.RunPython(_one_off_add_sequencing_run_field)
    ]
