# Generated by Django 3.1.3 on 2021-03-25 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0015_one_off_add_sequencing_run_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplesheet',
            name='old_sequencing_run',
        ),
    ]
