# Generated by Django 3.1.3 on 2021-04-06 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0016_remove_samplesheet_old_sequencing_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcffromsequencingrun',
            name='variant_caller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqauto.variantcaller'),
        ),
        migrations.AlterField(
            model_name='vcffromsequencingrun',
            name='sequencing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seqauto.sequencingrun'),
        ),
        migrations.AlterUniqueTogether(
            name='vcffromsequencingrun',
            unique_together={('sequencing_run', 'variant_caller')},
        ),
    ]
