# Generated by Django 3.1.3 on 2021-04-07 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0019_auto_20210406_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrichmentkit',
            name='bed_file',
        ),
    ]
