# Generated by Django 3.1.3 on 2021-04-14 00:05

from django.db import migrations


def qc_columns(apps, _schema_editor):
    QCType = apps.get_model("seqauto", "QCType")
    QCColumn = apps.get_model("seqauto", "QCColumn")

    exec_summary_qc = QCType.objects.get(name="ExecSummaryQC")
    exec_summary_qc.qccolumn_set.all().delete()  # Delete old ones, will recreate

    EXEC_SUMMARY_QC = {
        'deduplicated_reads': 'Deduplicated Reads',
        'indels_dbsnp_percent': 'Indels in dbSNP (%)',
        'mean_coverage_across_genes': 'Mean coverage across genes',
        'mean_coverage_across_kit': 'Mean coverage across kit',
        'median_insert': 'Median insert',
        'number_indels': 'Number of indels',
        'number_snps': 'Number SNPs',
        'percent_10x_goi': 'Percent of bases >=10x in GOI',
        'percent_20x_goi': 'Percent of bases >=20x in GOI',
        'percent_20x_kit': 'Percent of bases >=20x in Kit',
        'percent_duplication': "Duplication (%)",
        'percent_error_rate': "Error Rate (%)",
        'percent_map_to_diff_chr': "Map to diff chrom (%)",
        'percent_read_enrichment': 'Read enrichment (%)',
        'percent_reads': "Reads (%)",
        'percent_softclip': "Softclip (%)",
        'reads': "Reads",
        'sample_id_lod': "SampleID LOD",
        'snp_dbsnp_percent': 'SNPs in dbSNP (%)',
        'ts_to_tv_ratio': 'Ts/TV ratio',
        'uniformity_of_coverage': 'Uniformity of coverage',
    }

    for field, name in EXEC_SUMMARY_QC.items():
        QCColumn.objects.create(qc_type=exec_summary_qc, name=name, field=field)


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0021_auto_20210413_1621'),
    ]

    operations = [
        migrations.RunPython(qc_columns),
    ]
