# Generated by Django 3.1.3 on 2021-04-15 01:54

from django.db import migrations


def _one_off_fix_link_sample_to_sequencing_samples(apps, schema_editor):
    VCFFromSequencingRun = apps.get_model("seqauto", "VCFFromSequencingRun")
    SampleFromSequencingSample = apps.get_model("seqauto", "SampleFromSequencingSample")

    for vcf_from_sequencing_run in VCFFromSequencingRun.objects.all():
        vcf = vcf_from_sequencing_run.vcf
        if vcf.sample_set.exclude(samplefromsequencingsample__isnull=False).exists():
            print(f"VCF {vcf} needs to link samples")
            backend_vcf = vcf.uploadedvcf.backendvcf
            samples_by_sequencing_sample = _get_samples_by_sequencing_sample(backend_vcf.combo_vcf.sample_sheet, vcf)
            for ss, sample in samples_by_sequencing_sample.items():
                SampleFromSequencingSample.objects.create(sample=sample, sequencing_sample=ss)


# Copy - so don't depend on model code
def _get_samples_by_sequencing_sample(sample_sheet, vcf):
    sequencing_samples_by_name = {}
    for ss in sample_sheet.sequencingsample_set.all():
        sequencing_samples_by_name[ss.sample_name] = ss

    def clean_sample_name(s):
        return s.upper().replace("-", "_")

    samples_by_sequencing_sample = {}
    for sample in vcf.sample_set.all():
        # Do a startswith match rather than hash lookup as it's less strict (diff naming conventions etc)
        for sequencing_sample_name, sequencing_sample in sequencing_samples_by_name.items():
            cleaned_sample_name = clean_sample_name(sample.name)
            cleaned_sequencing_sample_name = clean_sample_name(sequencing_sample_name)
            if cleaned_sample_name.startswith(cleaned_sequencing_sample_name):
                samples_by_sequencing_sample[sequencing_sample] = sample
    return samples_by_sequencing_sample

class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0023_auto_20210415_1107'),
    ]

    operations = [
        migrations.RunPython(_one_off_fix_link_sample_to_sequencing_samples),
    ]
