# Generated by Django 3.1.3 on 2021-04-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0024_one_off_fix_link_sample_to_sequencing_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcexecsummary',
            name='percent_100x_goi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='qcexecsummary',
            name='percent_100x_kit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='qcexecsummary',
            name='percent_250x_kit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='qcexecsummary',
            name='percent_500x_kit',
            field=models.FloatField(null=True),
        ),
    ]
