# Generated by Django 3.1.3 on 2021-06-15 02:43
import logging
import re
from datetime import datetime

from django.db import migrations
from django.utils.timezone import make_aware


def _one_off_set_sequencing_run_date(apps, schema_editor):
    SequencingRun = apps.get_model("seqauto", "SequencingRun")
    # Old ones look like: 210226_NB501009_0445_AHV7GVBGXH
    OLD_REGEX = r"^([12]\d{5})_"
    # New ones look like: Exome_20_001_200612_NB501009_0389_AH7TJTBGXG
    NEW_REGEX = r".*_([12]\d{5})_"

    old_pattern = re.compile(OLD_REGEX)
    new_pattern = re.compile(NEW_REGEX)

    sequencing_runs = []
    for sr in SequencingRun.objects.filter(date__isnull=True):
        if m := old_pattern.match(sr.name):
            date_str = m.group(1)
        elif m := new_pattern.match(sr.name):
            date_str = m.group(1)
        else:
            logging.warning("Couldn't work out date from: '%s'", sr.name)
            continue

        dt = datetime.strptime(date_str, "%y%m%d")
        sr.date = make_aware(dt).date()
        sequencing_runs.append(sr)

    if sequencing_runs:
        SequencingRun.objects.bulk_update(sequencing_runs, ["date"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0027_sequencingrun_date'),
    ]

    operations = [
        migrations.RunPython(_one_off_set_sequencing_run_date)
    ]
