# Generated by Django 3.2.4 on 2021-12-16 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('seqauto', '0028_one_off_set_sequencing_run_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqautorecord',
            name='hash',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='enrichment_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seqauto.enrichmentkit'),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqauto.experiment'),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='fake_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.fakedata'),
        ),
    ]
