# Generated by Django 4.0.2 on 2022-02-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0029_auto_20211216_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcexecsummary',
            name='indels_dbsnp_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='qcexecsummary',
            name='number_indels',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='qcexecsummary',
            name='number_snps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='qcexecsummary',
            name='snp_dbsnp_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='qcexecsummary',
            name='ts_to_tv_ratio',
            field=models.FloatField(null=True),
        ),
    ]
