# Generated by Django 4.0.3 on 2022-04-13 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0053_alter_canonicaltranscript_transcript_and_more'),
        ('seqauto', '0030_alter_qcexecsummary_indels_dbsnp_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldcoveragesummary',
            name='transcript_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.transcriptversion'),
        ),
    ]
