# Generated by Django 4.1.3 on 2023-02-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0032_alter_seqautorun_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmentkit',
            name='min_coverage',
            field=models.IntegerField(null=True),
        ),
    ]
