# Generated by Django 6.0 on 2026-01-27 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0079_one_off_panel_app_aus_url_change'),
        ('seqauto', '0033_enrichmentkit_min_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcgenecoverage',
            name='gene_coverage_collection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genes.genecoveragecollection'),
        ),
    ]
