# Generated by Django 5.2.8 on 2026-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seqauto", "0034_alter_qcgenecoverage_gene_coverage_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrichmentkit",
            name="sample_variants_type",
            field=models.CharField(
                choices=[
                    ("U", "Unknown"),
                    ("G", "Germline"),
                    ("M", "Mixed (Single Sample)"),
                    ("S", "Somatic only (Tumour minus normal)"),
                ],
                default="U",
                max_length=1,
            ),
        ),
    ]
