# Generated by Django 6.0.3 on 2026-05-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seqauto", "0035_alter_enrichmentkit_sample_variants_type"),
        ("upload", "0029_rename_combo_vcf_backendvcf_joint_called_vcf"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SampleSheetCombinedVCFFile",
            new_name="JointCalledVCF",
        ),
        migrations.AlterUniqueTogether(
            name="vcffromsequencingrun",
            unique_together=set(),
        ),
    ]
