# Generated by Django 6.0.5 on 2026-07-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seqauto", "0038_rename_vcffile_singlesamplevcf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seqautomessage",
            name="record",
        ),
        migrations.RemoveField(
            model_name="seqautomessage",
            name="seqauto_run",
        ),
        migrations.RemoveField(
            model_name="seqautorun",
            name="fake_data",
        ),
        migrations.DeleteModel(
            name="JobScript",
        ),
        migrations.DeleteModel(
            name="SeqAutoMessage",
        ),
        migrations.DeleteModel(
            name="SeqAutoRun",
        ),
    ]
