# Generated by Django 6.0.5 on 2026-07-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seqauto", "0039_remove_seqautomessage_record_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="softwarepipelinenode",
            name="softwarepipeline",
        ),
        migrations.RemoveField(
            model_name="softwarepipelineedge",
            name="child",
        ),
        migrations.RemoveField(
            model_name="softwarepipelineedge",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="softwarepipelinenode",
            name="children",
        ),
        migrations.DeleteModel(
            name="SoftwarePipeline",
        ),
        migrations.DeleteModel(
            name="SoftwarePipelineEdge",
        ),
        migrations.DeleteModel(
            name="SoftwarePipelineNode",
        ),
    ]
