# Generated by Django 6.0.5 on 2026-07-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seqauto", "0040_remove_softwarepipelinenode_softwarepipeline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seqautorecord",
            name="data_state",
        ),
        migrations.RemoveField(
            model_name="seqautorecord",
            name="is_valid",
        ),
    ]
