# Generated by Django 6.0.6 on 2026-08-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seqauto", "0044_bamfile_sequencing_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="jointcalledvcf",
            name="sequencing_samples",
            field=models.ManyToManyField(
                blank=True,
                related_name="joint_called_vcfs",
                to="seqauto.sequencingsample",
            ),
        ),
    ]
