# Generated by Django 6.1 on 2026-08-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqauto', '0046_sequencingsample_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingsample',
            name='extraction_match_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequencingsample',
            name='extraction_match_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequencingsample',
            name='extraction_match_status',
            field=models.CharField(blank=True, choices=[('M', 'Matched'), ('P', 'Pending'), ('N', 'Needs attention')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='sequencingsample',
            name='extraction_reference',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
