# Generated by Django 6.1.1 on 2026-09-22 07:05

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_alter_patient_last_name'),
        ('seqauto', '0047_sequencingsample_extraction_match_date_and_more'),
        ('upload', '0047_uploaded_dragen_tso500_metrics_output'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sequencing_run_name', models.TextField()),
                ('pair_id', models.TextField()),
                ('specimen_reference', models.TextField()),
                ('specimen_match_status', models.CharField(blank=True, choices=[('M', 'Matched'), ('P', 'Pending'), ('N', 'Needs attention')], max_length=1, null=True)),
                ('specimen_match_error', models.TextField(blank=True, null=True)),
                ('specimen_match_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('D', 'DNA library'), ('V', 'Small variants and TMB'), ('M', 'MSI'), ('C', 'CNV'), ('G', 'GIS'), ('R', 'RNA library')], max_length=1)),
                ('nucleic_acid', models.CharField(choices=[('D', 'DNA'), ('R', 'RNA')], max_length=1)),
                ('passed', models.BooleanField(null=True)),
                ('completed', models.BooleanField(null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('method', models.TextField(blank=True)),
                ('measured_date', models.DateTimeField(blank=True, null=True)),
                ('file_upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.fileupload')),
                ('sequencing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqauto.sequencingrun')),
                ('sequencing_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqauto.sequencingsample')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.specimen')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sequencing_run_name', 'pair_id', 'category')},
            },
        ),
    ]
