# Generated by Django 6.1.1 on 2026-09-23 03:36

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_specimen_measure_pathology_only'),
        ('seqauto', '0048_libraryqc'),
        ('snpdb', '0274_tag_config_show_resolved_variant_tags'),
        ('upload', '0048_gene_level_splice_vcf_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DragenTSO500CombinedVariantOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('specimen_reference', models.TextField()),
                ('specimen_match_status', models.CharField(blank=True, choices=[('M', 'Matched'), ('P', 'Pending'), ('N', 'Needs attention')], max_length=1, null=True)),
                ('specimen_match_error', models.TextField(blank=True, null=True)),
                ('specimen_match_date', models.DateTimeField(blank=True, null=True)),
                ('sequencing_run_name', models.TextField()),
                ('pair_id', models.TextField()),
                ('dna_sample_name', models.TextField(blank=True)),
                ('rna_sample_name', models.TextField(blank=True)),
                ('output_datetime', models.DateTimeField(blank=True, null=True)),
                ('module_version', models.TextField(blank=True)),
                ('pipeline_version', models.TextField(blank=True)),
                ('total_tmb', models.FloatField(blank=True, null=True)),
                ('coding_region_size_mb', models.FloatField(blank=True, null=True)),
                ('passing_eligible_variants', models.IntegerField(blank=True, null=True)),
                ('usable_msi_sites', models.IntegerField(blank=True, null=True)),
                ('total_msi_sites_unstable', models.IntegerField(blank=True, null=True)),
                ('percent_unstable_msi_sites', models.FloatField(blank=True, null=True)),
                ('genomic_instability_score', models.FloatField(blank=True, null=True)),
                ('tumor_fraction', models.FloatField(blank=True, null=True)),
                ('ploidy', models.FloatField(blank=True, null=True)),
                ('dna_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvo_dna_set', to='snpdb.sample')),
                ('dna_sequencing_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvo_dna_set', to='seqauto.sequencingsample')),
                ('file_upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.fileupload')),
                ('rna_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvo_rna_set', to='snpdb.sample')),
                ('rna_sequencing_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvo_rna_set', to='seqauto.sequencingsample')),
                ('sequencing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqauto.sequencingrun')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.specimen')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sequencing_run_name', 'pair_id')},
            },
        ),
    ]
