# Generated by Django 6.0.5 on 2026-10-09

from django.db import migrations

OLD_PREFIX = "bam_file__"
NEW_PREFIX = "alignment_file__"


def _rename_qc_object_paths(apps, _schema_editor):
    """ 0052 renamed QC.bam_file to alignment_file, but QCType.qc_object_path rows (0002_initial_data) still started
        with the old field, so the QC column graphs raised FieldError """
    QCType = apps.get_model("seqauto", "QCType")
    for qc_type in QCType.objects.filter(qc_object_path__startswith=OLD_PREFIX):
        qc_type.qc_object_path = NEW_PREFIX + qc_type.qc_object_path[len(OLD_PREFIX):]
        qc_type.save(update_fields=["qc_object_path"])


def _restore_qc_object_paths(apps, _schema_editor):
    QCType = apps.get_model("seqauto", "QCType")
    for qc_type in QCType.objects.filter(qc_object_path__startswith=NEW_PREFIX):
        qc_type.qc_object_path = OLD_PREFIX + qc_type.qc_object_path[len(NEW_PREFIX):]
        qc_type.save(update_fields=["qc_object_path"])


class Migration(migrations.Migration):

    dependencies = [
        ("seqauto", "0052_alignment_file"),
    ]

    operations = [
        migrations.RunPython(_rename_qc_object_paths, _restore_qc_object_paths),
    ]
