# Generated by Django 3.1.3 on 2021-01-21 07:17

from django.db import migrations, models
import django.db.models.deletion

def _gene_to_gene_symbol(apps, schema_editor):
    PathologyTestGeneModificationRequest = apps.get_model("pathtests", "PathologyTestGeneModificationRequest")
    GenomeBuild = apps.get_model("snpdb", "GenomeBuild")

    legacy_build = GenomeBuild.objects.get(pk="GRCh37")  # Legacy
    for ptgmr in PathologyTestGeneModificationRequest.objects.all():
        ptgmr.gene_symbol = ptgmr.gene.geneversion_set.filter(genome_build=legacy_build).order_by("-version").first()
        ptgmr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0014_auto_20210120_1723'),
        ('pathtests', '0002_auto_20201124_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathologytestorderomim',
            name='mim_morbid_alias',
        ),
        migrations.RemoveField(
            model_name='pathologytestorderomim',
            name='pathology_test_order',
        ),
        migrations.AddField(
            model_name='pathologytestgenemodificationrequest',
            name='gene_symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol'),
        ),
        migrations.DeleteModel(
            name='PathologyTestOrderHPO',
        ),
        migrations.DeleteModel(
            name='PathologyTestOrderOMIM',
        ),
        migrations.RunPython(_gene_to_gene_symbol)
    ]
