# Generated by Django 3.1.3 on 2021-01-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0014_auto_20210120_1723'),
        ('pathtests', '0003_auto_20210121_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathologytestgenemodificationrequest',
            name='gene',
        ),
        migrations.AlterField(
            model_name='pathologytestgenemodificationrequest',
            name='gene_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol'),
        ),
    ]
