# Generated by Django 3.1 on 2020-09-29 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import library.django_utils
import library.django_utils.guardian_permissions_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snpdb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('import_status', models.CharField(choices=[('C', 'created'), ('I', 'importing'), ('R', 'Requires user input'), ('E', 'error'), ('S', 'success'), ('M', 'Marked For Deletion'), ('D', 'Deleting')], default='C', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(library.django_utils.guardian_permissions_mixin.GuardianPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PedFileFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ped_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedigree.pedfile')),
            ],
        ),
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.cohort')),
                ('ped_file_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedigree.pedfilefamily')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(library.django_utils.guardian_permissions_mixin.GuardianPermissionsAutoInitialSaveMixin, library.django_utils.SortByPKMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PedFileRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.TextField()),
                ('sex', models.CharField(choices=[('U', 'unknown'), ('M', 'male'), ('F', 'female')], max_length=1, null=True)),
                ('affection', models.BooleanField(null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedigree.pedfilefamily')),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_rel', to='pedigree.pedfilerecord')),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_rel', to='pedigree.pedfilerecord')),
            ],
        ),
        migrations.CreateModel(
            name='CohortSamplePedFileRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.cohortsample')),
                ('ped_file_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedigree.pedfilerecord')),
                ('pedigree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedigree.pedigree')),
            ],
        ),
    ]
