# Generated by Django 3.1.3 on 2020-12-15 05:19

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0001_initial'),
        ('snpdb', '0010_somalierancestry_somalierancestryrun_somaliercohortrelate_somaliertriorelate_somaliervcfextract'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomalierPedigreeRelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField()),
                ('pedigree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedigree.pedigree')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
