# Generated by Django 4.0.7 on 2023-05-17 05:24

import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snpdb', '0097_new_column_internally_classified_labs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewTopic',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('heading', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewQuestion',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('help', models.TextField(blank=True, null=True)),
                ('heading', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.TextField(choices=[('D', 'Disagreement')], default='D')),
                ('enabled', models.BooleanField(blank=True, default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.reviewtopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('context', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField()),
                ('meeting_meta', models.JSONField()),
                ('reviewing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.reviewedobject')),
                ('reviewing_labs', models.ManyToManyField(to='snpdb.lab')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.reviewtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
