# Generated by Django 4.0.7 on 2023-05-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='context',
        ),
        migrations.AddField(
            model_name='review',
            name='post_review_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='post_review_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
