# Generated by Django 4.0.7 on 2023-05-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0097_new_column_internally_classified_labs'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewanswergroup',
            name='reviewing_labs',
            field=models.ManyToManyField(to='snpdb.lab'),
        ),
    ]
