# Generated by Django 4.0.7 on 2023-05-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_review_context_review_post_review_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='post_review_summary',
        ),
    ]
