# Generated by Django 4.0.7 on 2023-05-16 06:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snpdb', '0097_new_column_internally_classified_labs'),
        ('review', '0002_reviewanswergroup_reviewing_labs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewAnswerGroup',
            new_name='Review',
        ),
    ]
