# Generated by Django 4.0.7 on 2023-05-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_review_post_review_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
