# Generated by Django 3.1 on 2020-10-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genecounttype',
            old_name='uses_variant_classifications',
            new_name='uses_classifications',
        ),
    ]
