# Generated by Django 3.1 on 2020-11-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0003_transcript_version_json_del_gene_name'),
        ('annotation', '0004_auto_20201001_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonarchDiseaseOntologyGeneRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.TextField()),
                ('gene_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol')),
                ('mondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.monarchdiseaseontology')),
            ],
            options={
                'unique_together': {('mondo', 'relationship', 'gene_symbol')},
            },
        ),
    ]
