# Generated by Django 3.1 on 2020-11-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_monarchdiseaseontologymimmorbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationrun',
            old_name='variant_count',
            new_name='annotated_count',
        ),
        migrations.AddField(
            model_name='annotationrun',
            name='vep_skipped_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotationrun',
            name='vep_warnings',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='vep_skipped_reason',
            field=models.CharField(blank=True, choices=[('c', 'Unknown Contig'), ('i', 'Incomplete'), ('u', 'Unknown')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='variantannotation',
            name='variant_class',
            field=models.CharField(blank=True, choices=[('SN', 'SNV'), ('GM', 'genetic_marker'), ('SU', 'substitution'), ('TR', 'tandem_repeat'), ('AI', 'Alu_insertion'), ('CA', 'complex_structural_alteration'), ('CS', 'complex_substitution'), ('CG', 'copy_number_gain'), ('CL', 'copy_number_loss'), ('CN', 'copy_number_variation'), ('DU', 'duplication'), ('IB', 'interchromosomal_breakpoint'), ('IT', 'interchromosomal_translocation'), ('CB', 'intrachromosomal_breakpoint'), ('CT', 'intrachromosomal_translocation'), ('IN', 'inversion'), ('LO', 'loss_of_heterozygosity'), ('MD', 'mobile_element_deletion'), ('MI', 'mobile_element_insertion'), ('NI', 'novel_sequence_insertion'), ('ST', 'short_tandem_repeat_variation'), ('TD', 'tandem_duplication'), ('TL', 'translocation'), ('DE', 'deletion'), ('ND', 'indel'), ('IS', 'insertion'), ('SA', 'sequence_alteration'), ('PR', 'probe')], max_length=2, null=True),
        ),
    ]
