# Generated by Django 3.1 on 2020-11-12 05:25

from django.db import migrations
from django.db.models import F

from manual.operations.manual_operations import ManualOperation


def test_has_vep_skipped(apps):
    AnnotationRun = apps.get_model("annotation", "AnnotationRun")
    return AnnotationRun.objects.exclude(annotation_range_lock__count=F("annotated_count")).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_auto_20201112_1727'),
        ('manual', '0002_deployment'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_legacy_skipped_vep"]), test=test_has_vep_skipped)
    ]
