# Generated by Django 3.1 on 2020-11-13 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0005_auto_20201015_1611'),
        ('annotation', '0008_one_off_fix_legacy_skipped_vep'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCFAnnotationStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vep_skipped_count', models.IntegerField()),
                ('variant_annotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.variantannotationversion')),
                ('vcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.vcf')),
            ],
            options={
                'unique_together': {('vcf', 'variant_annotation_version')},
            },
        ),
    ]
