# Generated by Django 3.1 on 2020-11-23 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0010_one_off_recalculate_sample_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColumnVCFInfo',
        ),
    ]
