# Generated by Django 3.1.3 on 2020-12-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_delete_columnvcfinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualvariantentry',
            name='entry_type',
            field=models.CharField(choices=[('d', 'Dbsnp'), ('h', 'Hgvs'), ('v', 'Variant'), ('u', 'Unknown')], default='u', max_length=1),
        ),
    ]
