# Generated by Django 3.1 on 2020-12-15 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_delete_columnvcfinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonarchDiseaseOntologyRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.TextField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='annotation.monarchdiseaseontology')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='annotation.monarchdiseaseontology')),
            ],
        ),
    ]
