# Generated by Django 3.1.3 on 2021-01-04 07:19

from django.db import migrations, models

def _one_off_delete_clingen_disease_validity(apps, schema_editor):
    # Will cascade delete diseasevalidity - will be re-loaded when visiting annotation page
    CachedWebResource = apps.get_model("annotation", "CachedWebResource")
    CachedWebResource.objects.filter(name="ClinGenDiseaseValidity").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0012_manualvariantentry_entry_type'),
    ]

    operations = [
        migrations.RunPython(_one_off_delete_clingen_disease_validity),
        migrations.AlterField(
            model_name='clinvar',
            name='clinvar_review_status',
            field=models.CharField(choices=[('N', 'No assertion provided'), ('C', 'No assertion criteria provided'), ('I', 'No interpretation for the single variant'), ('F', 'Criteria provided - conflicting interpretations'), ('S', 'Criteria provided - single submitter'), ('M', 'Criteria provided - multiple submitters w/no conflicts'), ('E', 'Reviewed by expert panel'), ('P', 'Practice guideline')], max_length=1),
        ),
        migrations.AlterField(
            model_name='manualvariantentry',
            name='entry_type',
            field=models.CharField(choices=[('d', 'dbSNP'), ('h', 'HGVS'), ('v', 'Variant'), ('u', 'Unknown')], default='u', max_length=1),
        ),
    ]
