# Generated by Django 3.1.3 on 2021-01-21 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0005_auto_20210115_1325'),
        ('annotation', '0013_auto_20210104_1749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monarchdiseaseontologygenerelationship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monarchdiseaseontologygenerelationship',
            name='gene_symbol',
        ),
        migrations.RemoveField(
            model_name='monarchdiseaseontologygenerelationship',
            name='mondo',
        ),
        migrations.AlterUniqueTogether(
            name='monarchdiseaseontologymimmorbid',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monarchdiseaseontologymimmorbid',
            name='mondo',
        ),
        migrations.RemoveField(
            model_name='diseasevalidity',
            name='hpo_synonym',
        ),
        migrations.RemoveField(
            model_name='diseasevalidity',
            name='mim_morbid_alias',
        ),
        migrations.RemoveField(
            model_name='diseasevalidity',
            name='mondo',
        ),
        migrations.AddField(
            model_name='diseasevalidity',
            name='ontology_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontology.ontologyterm'),
        ),
        migrations.DeleteModel(
            name='MonarchDiseaseOntology',
        ),
        migrations.DeleteModel(
            name='MonarchDiseaseOntologyGeneRelationship',
        ),
        migrations.DeleteModel(
            name='MonarchDiseaseOntologyMIMMorbid',
        ),
    ]
