# Generated by Django 3.1 on 2021-01-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathtests', '0003_auto_20210121_1747'),
        ('analysis', '0015_auto_20210121_2201'),
        ('annotation', '0016_one_off_move_ontology'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hposynonym',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hposynonym',
            name='hpo',
        ),
        migrations.RemoveField(
            model_name='humanphenotypeontology',
            name='children',
        ),
        migrations.AlterUniqueTogether(
            name='mimgene',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mimgene',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='mimgene',
            name='mim_morbid',
        ),
        migrations.RemoveField(
            model_name='mimmorbidalias',
            name='mim_morbid',
        ),
        migrations.AlterUniqueTogether(
            name='phenotypemim',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='phenotypemim',
            name='hpo',
        ),
        migrations.RemoveField(
            model_name='phenotypemim',
            name='mim_morbid',
        ),
        migrations.RemoveField(
            model_name='textphenotypematch',
            name='hpo',
        ),
        migrations.RemoveField(
            model_name='textphenotypematch',
            name='omim_alias',
        ),
        migrations.DeleteModel(
            name='HPOEdge',
        ),
        migrations.DeleteModel(
            name='HPOSynonym',
        ),
        migrations.DeleteModel(
            name='HumanPhenotypeOntology',
        ),
        migrations.DeleteModel(
            name='MIMGene',
        ),
        migrations.DeleteModel(
            name='MIMMorbid',
        ),
        migrations.DeleteModel(
            name='MIMMorbidAlias',
        ),
        migrations.DeleteModel(
            name='PhenotypeMIM',
        ),
    ]
