# Generated by Django 3.1 on 2021-01-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0017_auto_20210121_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasevalidity',
            name='classification',
            field=models.CharField(choices=[('D', 'Definitive'), ('S', 'Strong'), ('M', 'Moderate'), ('L', 'Limited'), ('N', 'No Known Disease Relationship'), ('R', 'Refuted'), ('P', 'Disputed')], max_length=1),
        ),
    ]
