# Generated by Django 3.1 on 2021-02-01 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0007_ontologyterm_aliases'),
        ('genes', '0017_auto_20210201_1424'),
        ('annotation', '0018_auto_20210127_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantannotation',
            name='uniprot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.uniprot'),
        ),
        migrations.CreateModel(
            name='GeneAnnotationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('annotation_date', models.DateTimeField(auto_now_add=True)),
                ('rvis_import_date', models.DateTimeField()),
                ('gnomad_import_date', models.DateTimeField()),
                ('gene_annotation_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.geneannotationrelease')),
                ('last_ontology_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ontology.ontologyimport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='annotationversion',
            name='gene_annotation_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='annotation.geneannotationversion'),
        ),
        migrations.CreateModel(
            name='GeneAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpo_terms', models.TextField(null=True)),
                ('omim_terms', models.TextField(null=True)),
                ('oe_ratio_percentile', models.FloatField(null=True)),
                ('oe_lof', models.FloatField(null=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.gene')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.geneannotationversion')),
            ],
            options={
                'unique_together': {('version', 'gene')},
            },
        ),
    ]
