# Generated by Django 3.1 on 2021-02-03 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0017_new_columns'),
        ('annotation', '0019_auto_20210201_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleGeneAnnotationStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_count', models.IntegerField(default=0)),
                ('ref_omim_phenotype_count', models.IntegerField(default=0)),
                ('hom_omim_phenotype_count', models.IntegerField(default=0)),
                ('het_omim_phenotype_count', models.IntegerField(default=0)),
                ('unk_omim_phenotype_count', models.IntegerField(default=0)),
                ('gene_annotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.geneannotationversion')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.sample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleGeneAnnotationStatsPassingFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_count', models.IntegerField(default=0)),
                ('ref_omim_phenotype_count', models.IntegerField(default=0)),
                ('hom_omim_phenotype_count', models.IntegerField(default=0)),
                ('het_omim_phenotype_count', models.IntegerField(default=0)),
                ('unk_omim_phenotype_count', models.IntegerField(default=0)),
                ('gene_annotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.geneannotationversion')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.sample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ensemblgeneannotationversion',
            name='genome_build',
        ),
        migrations.RemoveField(
            model_name='ensemblgeneannotationversiondiff',
            name='version_from',
        ),
        migrations.RemoveField(
            model_name='ensemblgeneannotationversiondiff',
            name='version_to',
        ),
        migrations.RemoveField(
            model_name='ensemblgeneannotationversiondiff',
            name='versiondiff_ptr',
        ),
        migrations.RemoveField(
            model_name='sampleensemblgeneannotationstats',
            name='ensembl_gene_annotation_version',
        ),
        migrations.RemoveField(
            model_name='sampleensemblgeneannotationstats',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='sampleensemblgeneannotationstatspassingfilter',
            name='ensembl_gene_annotation_version',
        ),
        migrations.RemoveField(
            model_name='sampleensemblgeneannotationstatspassingfilter',
            name='sample',
        ),
        migrations.RenameField(
            model_name='geneannotation',
            old_name='oe_lof',
            new_name='gnomad_oe_lof',
        ),
        migrations.RenameField(
            model_name='geneannotation',
            old_name='oe_ratio_percentile',
            new_name='rvis_oe_ratio_percentile',
        ),
        migrations.RemoveField(
            model_name='annotationversion',
            name='ensembl_gene_annotation_version',
        ),
        migrations.DeleteModel(
            name='EnsemblGeneAnnotation',
        ),
        migrations.DeleteModel(
            name='EnsemblGeneAnnotationVersion',
        ),
        migrations.DeleteModel(
            name='EnsemblGeneAnnotationVersionDiff',
        ),
        migrations.DeleteModel(
            name='SampleEnsemblGeneAnnotationStats',
        ),
        migrations.DeleteModel(
            name='SampleEnsemblGeneAnnotationStatsPassingFilter',
        ),
    ]
