# Generated by Django 3.1 on 2021-02-04 02:00

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0021_auto_20210203_1726'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["gene_annotation", "--missing"])),
        ManualOperation(task_id=ManualOperation.task_id_manage(["calculate_sample_stats"])),
    ]
