# Generated by Django 3.1 on 2021-02-04 02:00
from django.conf import settings
from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _check_has_existing_samples(apps):
    Sample = apps.get_model("snpdb", "Sample")
    return Sample.objects.all().exists()


def _check_has_gene_annotation(_apps):
    return settings.ANNOTATION_GENE_ANNOTATION_VERSION_ENABLED


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0021_auto_20210203_1726'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["gene_annotation", "--missing"]),
                        test=_check_has_gene_annotation),
        ManualOperation(task_id=ManualOperation.task_id_manage(["calculate_sample_stats"]),
                        test=_check_has_existing_samples),
    ]
