# Generated by Django 3.1.3 on 2021-02-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0024_new_vep_annotation_gnomad3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geneannotation',
            name='rvis_oe_ratio_percentile',
        ),
        migrations.RemoveField(
            model_name='geneannotationversion',
            name='rvis_import_date',
        ),
    ]
