# Generated by Django 3.1.3 on 2021-03-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0025_auto_20210219_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvar',
            name='conflicting_clinical_significance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinvar',
            name='clinvar_review_status',
            field=models.CharField(choices=[('N', 'No assertion provided'), ('C', 'No assertion criteria provided'), ('I', 'No interpretation for the single variant'), ('F', 'Criteria provided - conflicting interpretations'), ('S', 'Criteria provided - single submitter'), ('M', 'Criteria provided - multiple submitters w/no conflicts'), ('E', 'Reviewed by expert panel'), ('P', 'Practice guideline')], max_length=1, null=True),
        ),
    ]
