# Generated by Django 3.1.3 on 2021-03-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0027_new_column_spliaceai_gene_vep_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantannotation',
            name='spliceai_gene_symbol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
