# Generated by Django 3.1.3 on 2021-03-20 04:24

from django.db import migrations
from django.db.models import Q

from manual.operations.manual_operations import ManualOperation


def _test_has_missing_transcript_versions(apps):
    VariantTranscriptAnnotation = apps.get_model("annotation", "VariantTranscriptAnnotation")
    return VariantTranscriptAnnotation.objects.filter(Q(transcript__isnull=True) | Q(transcript_version__isnull=True),
                                                      hgvs_c__isnull=False).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0028_variantannotation_spliceai_gene_symbol'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_annotation_link_transcript"]),
                        test=_test_has_missing_transcript_versions)
    ]
