# Generated by Django 3.2.1 on 2021-05-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0030_auto_20210429_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantannotationversion',
            name='distance',
            field=models.IntegerField(default=5000),
        ),
    ]
