# Generated by Django 3.2.1 on 2021-05-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0031_variantannotationversion_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantannotation',
            name='impact',
            field=models.CharField(blank=True, choices=[('1', 'MODIFIER'), ('2', 'LOW'), ('3', 'MODERATE'), ('*', 'MODERATE*'), ('4', 'HIGH')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='varianttranscriptannotation',
            name='impact',
            field=models.CharField(blank=True, choices=[('1', 'MODIFIER'), ('2', 'LOW'), ('3', 'MODERATE'), ('*', 'MODERATE*'), ('4', 'HIGH')], max_length=1, null=True),
        ),
    ]
