# Generated by Django 3.2.1 on 2021-05-24 11:48

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_has_annotation(apps):
    VariantAnnotation = apps.get_model("annotation", "VariantAnnotation")
    VariantTranscriptAnnotation = apps.get_model("annotation", "VariantTranscriptAnnotation")
    return VariantAnnotation.objects.exists() or VariantTranscriptAnnotation.objects.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0047_alter_damagenode_impact_min'),
        ('annotation', '0032_auto_20210524_2117'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_impact_change_choice"]),
                        test=_test_has_annotation)
    ]
