# Generated by Django 3.2.1 on 2021-05-24 11:48

from django.db import migrations
from django.db.models import When, Value, Case


def _get_case(field_name) -> Case:
    IMPACT_OLD_NEW = {
        "O": "1",
        "L": "2",
        "M": "3",
        "H": "4",
    }
    return Case(*[When(**{field_name: k}, then=Value(v)) for k, v in IMPACT_OLD_NEW.items()])


def _one_off_impact_change_order(apps, schema_editor):
    VariantAnnotation = apps.get_model("annotation", "VariantAnnotation")
    VariantTranscriptAnnotation = apps.get_model("annotation", "VariantTranscriptAnnotation")
    DamageNode = apps.get_model("analysis", "DamageNode")

    DamageNode.objects.update(impact_min=_get_case("impact_min"))

    impact_case = _get_case("impact")
    print("Updating VariantAnnotation... (may take a while)")
    VariantAnnotation.objects.update(impact=impact_case)
    print("Updating VariantTranscriptAnnotation... (may take a really long while)")
    VariantTranscriptAnnotation.objects.update(impact=impact_case)


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0047_alter_damagenode_impact_min'),
        ('annotation', '0032_auto_20210524_2117'),
    ]

    operations = [
        migrations.RunPython(_one_off_impact_change_order)
    ]
