# Generated by Django 3.2.8 on 2021-10-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0034_auto_20210622_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarcitationscollection',
            name='cached_web_resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.cachedwebresource'),
        ),
    ]
