# Generated by Django 3.2.4 on 2021-12-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0035_clinvarcitationscollection_cached_web_resource'),
        ('genes', '0028_one_off_fix_lowercase_gene_symbols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genediseasecurator',
            name='cached_web_resource',
        ),
        migrations.RemoveField(
            model_name='genediseasecurator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='genediseasevalidity',
            name='disease_validity',
        ),
        migrations.RemoveField(
            model_name='genediseasevalidity',
            name='gene_symbol',
        ),
        migrations.RemoveField(
            model_name='genediseasevalidityevidence',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='genediseasevalidityevidence',
            name='gene_disease',
        ),
        migrations.DeleteModel(
            name='DiseaseValidity',
        ),
        migrations.DeleteModel(
            name='GeneDiseaseCurator',
        ),
        migrations.DeleteModel(
            name='GeneDiseaseValidity',
        ),
        migrations.DeleteModel(
            name='GeneDiseaseValidityEvidence',
        ),
    ]
