# Generated by Django 3.2.4 on 2021-12-23 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0009_auto_20210316_1041'),
        ('annotation', '0037_one_off_move_pheno_match_to_hgnc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhenotypeMatchTypes',
        ),
        migrations.RemoveField(
            model_name='textphenotypematch',
            name='gene_symbol',
        ),
        migrations.RemoveField(
            model_name='textphenotypematch',
            name='match_type',
        ),
        migrations.AlterField(
            model_name='textphenotypematch',
            name='ontology_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.ontologyterm'),
        ),
    ]
