# Generated by Django 3.2.4 on 2021-12-24 03:11
from django.conf import settings
from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_needs_gene_annotation(apps):
    if not settings.ANNOTATION_GENE_ANNOTATION_VERSION_ENABLED:
        return False

    GeneAnnotation = apps.get_model("annotation", "GeneAnnotation")
    Analysis = apps.get_model("analysis", "Analysis")

    # We know this will have MONDO terms
    gata2_qs = GeneAnnotation.objects.filter(gene__geneversion__gene_symbol='GATA2')
    return Analysis.objects.exists() and gata2_qs.exists() and not gata2_qs.filter(mondo_terms__isnull=False).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0039_auto_20211224_1210'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["gene_annotation", "--add-new-to-existing"]),
                        test=_test_needs_gene_annotation),
    ]
