# Generated by Django 4.0.2 on 2022-03-02 05:42

import django.db.models.deletion
from django.db import migrations, models


def _one_off_delete_obsolete_column_vep_fields(apps, _schema_editor):
    ColumnVEPField = apps.get_model("annotation", "ColumnVEPField")
    # These were inserted in legacy code but have since been deleted
    DELETE_COLUMNS = ['feature', 'feature_type', 'gene_text']
    ColumnVEPField.objects.filter(column__in=DELETE_COLUMNS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0040_one_off_add_gene_annotation_columns'),
    ]

    operations = [
        migrations.RunPython(_one_off_delete_obsolete_column_vep_fields),
        migrations.RemoveField(
            model_name='variantannotation',
            name='cadd_raw',
        ),
        migrations.RemoveField(
            model_name='variantannotation',
            name='fathmm_pred',
        ),
        migrations.RemoveField(
            model_name='variantannotation',
            name='gene_text',
        ),
        migrations.RemoveField(
            model_name='variantannotation',
            name='hgnc_id',
        ),
        migrations.RemoveField(
            model_name='variantannotation',
            name='mutation_assessor_pred',
        ),
        migrations.RemoveField(
            model_name='variantannotation',
            name='mutation_taster_pred',
        ),
        migrations.RemoveField(
            model_name='variantannotation',
            name='polyphen2_hvar_pred',
        ),
        migrations.RemoveField(
            model_name='variantannotation',
            name='swissprot',
        ),
        migrations.RemoveField(
            model_name='variantannotation',
            name='symbol_source',
        ),
        migrations.RemoveField(
            model_name='variantannotation',
            name='trembl',
        ),
        migrations.RemoveField(
            model_name='variantannotation',
            name='uniparc',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='cadd_raw',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='dbsnp_rs_id',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='fathmm_pred',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='gene_text',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='hgnc_id',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='mutation_assessor_pred',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='mutation_taster_pred',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='phastcons_100_way_vertebrate',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='phastcons_30_way_mammalian',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='phastcons_46_way_mammalian',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='phylop_100_way_vertebrate',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='phylop_30_way_mammalian',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='phylop_46_way_mammalian',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='polyphen2_hvar_pred',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='pubmed',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='swissprot',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='symbol_source',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='trembl',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='uniparc',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='predictions_num_benign',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='predictions_num_pathogenic',
        ),
        migrations.AlterField(
            model_name='columnvepfield',
            name='variant_grid_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.variantgridcolumn'),
        ),
    ]
