# Generated by Django 4.0.2 on 2022-03-04 04:21

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _one_off_variant_annotation_version_gnomad(apps, schema_editor):
    VariantAnnotationVersion = apps.get_model("annotation", "VariantAnnotationVersion")
    # We do our own custom VEP annotation with gnomAD, use that for versions now, update historical ones
    vav_qs = VariantAnnotationVersion.objects.filter(gnomad='r2.1')
    vav_qs.filter(genome_build='GRCh37').update(gnomad='2.1.1')
    vav_qs.filter(genome_build='GRCh38').update(gnomad='3.1')


def _test_variant_annotation_run(apps):
    """ Only show this for old installations (ie that have done analyses before) - not new ones """
    AnnotationRun = apps.get_model("annotation", "AnnotationRun")
    return AnnotationRun.objects.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0041_remove_variantannotation_cadd_raw_and_more'),
    ]

    operations = [
        migrations.RunPython(_one_off_variant_annotation_version_gnomad),
        ManualOperation.operation_other(args=[
            "Get gnomad AF>5 vcf.gz for upload pre-processing see https://github.com/SACGF/variantgrid/issues/521#issuecomment-1058830717"],
        test=_test_variant_annotation_run),
    ]
