# Generated by Django 4.0.3 on 2022-04-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0043_alter_variantannotation_transcript_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantannotation',
            name='uniprot',
        ),
    ]
