# Generated by Django 4.0.3 on 2022-04-26 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0056_one_off_link_hgnc_and_uniprot'),
        ('annotation', '0044_remove_variantannotation_uniprot'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanproteinatlasannotation',
            name='gene_symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol'),
        ),
        migrations.AddField(
            model_name='humanproteinatlasannotation',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='humanproteinatlasannotationversion',
            name='unit',
            field=models.TextField(default='FPKM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='humanproteinatlasannotation',
            name='gene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.gene'),
        ),
        migrations.AlterField(
            model_name='humanproteinatlastissuesample',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
