# Generated by Django 4.0.3 on 2022-05-04 01:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0070_samplestats_created_samplestats_modified_and_more'),
        ('annotation', '0048_one_off_inherited_tables_schema_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleclinvarannotationstats',
            name='code_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AddField(
            model_name='sampleclinvarannotationstats',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleclinvarannotationstats',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='sampleclinvarannotationstatspassingfilter',
            name='code_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AddField(
            model_name='sampleclinvarannotationstatspassingfilter',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleclinvarannotationstatspassingfilter',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='samplegeneannotationstats',
            name='code_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AddField(
            model_name='samplegeneannotationstats',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplegeneannotationstats',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='samplegeneannotationstatspassingfilter',
            name='code_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AddField(
            model_name='samplegeneannotationstatspassingfilter',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplegeneannotationstatspassingfilter',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='samplevariantannotationstats',
            name='code_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AddField(
            model_name='samplevariantannotationstats',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplevariantannotationstats',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='samplevariantannotationstatspassingfilter',
            name='code_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AddField(
            model_name='samplevariantannotationstatspassingfilter',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplevariantannotationstatspassingfilter',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
