# Generated by Django 4.0.3 on 2022-05-04 01:10

from django.db import migrations


def _one_off_add_historical_sample_stats_code_version(apps, schema_editor):
    SampleStatsCodeVersion = apps.get_model("snpdb", "SampleStatsCodeVersion")
    SampleStats = apps.get_model("snpdb", "SampleStats")
    SampleStatsPassingFilter = apps.get_model("snpdb", "SampleStatsPassingFilter")

    SampleVariantAnnotationStats = apps.get_model("annotation", "SampleVariantAnnotationStats")
    SampleVariantAnnotationStatsPassingFilter = apps.get_model("annotation", "SampleVariantAnnotationStatsPassingFilter")

    SampleGeneAnnotationStats = apps.get_model("annotation", "SampleGeneAnnotationStats")
    SampleGeneAnnotationStatsPassingFilter = apps.get_model("annotation", "SampleGeneAnnotationStatsPassingFilter")

    SampleClinVarAnnotationStats = apps.get_model("annotation", "SampleClinVarAnnotationStats")
    SampleClinVarAnnotationStatsPassingFilter = apps.get_model("annotation", "SampleClinVarAnnotationStatsPassingFilter")

    historical_code_version = SampleStatsCodeVersion.objects.create(name="Historical SampleStats",
                                                                    version=0,
                                                                    code_git_hash="not_a_real_hash")

    CLASSES = [SampleStats, SampleStatsPassingFilter,
               SampleVariantAnnotationStats, SampleVariantAnnotationStatsPassingFilter,
               SampleGeneAnnotationStats, SampleGeneAnnotationStatsPassingFilter,
               SampleClinVarAnnotationStats, SampleClinVarAnnotationStatsPassingFilter]

    for klass in CLASSES:
        klass.objects.all().update(code_version=historical_code_version)


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0049_sampleclinvarannotationstats_code_version_and_more'),
        ('snpdb', '0070_samplestats_created_samplestats_modified_and_more'),
    ]

    operations = [
        migrations.RunPython(_one_off_add_historical_sample_stats_code_version)
    ]
