# Generated by Django 4.0.3 on 2022-05-04 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0071_alter_samplestats_code_version_and_more'),
        ('annotation', '0050_one_off_add_historical_sample_stats_code_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleclinvarannotationstats',
            name='code_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AlterField(
            model_name='sampleclinvarannotationstatspassingfilter',
            name='code_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AlterField(
            model_name='samplegeneannotationstats',
            name='code_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AlterField(
            model_name='samplegeneannotationstatspassingfilter',
            name='code_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AlterField(
            model_name='samplevariantannotationstats',
            name='code_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
        migrations.AlterField(
            model_name='samplevariantannotationstatspassingfilter',
            name='code_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.samplestatscodeversion'),
        ),
    ]
