# Generated by Django 4.0.3 on 2022-05-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0051_alter_sampleclinvarannotationstats_code_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnvepfield',
            name='max_vep_columns_version',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='columnvepfield',
            name='min_vep_columns_version',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='aloft_ensembl_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='aloft_high_confidence',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='aloft_pred',
            field=models.CharField(blank=True, choices=[('t', 'Tolerant'), ('r', 'Recessive'), ('d', 'Dominant')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='aloft_prob_dominant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='aloft_prob_recessive',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='aloft_prob_tolerant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='bayesdel_noaf_rankscore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='cadd_raw_rankscore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='clinpred_rankscore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='metalr_rankscore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='nmd_escaping_variant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='revel_rankscore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='vest4_rankscore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotationversion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variantannotationversion',
            name='columns_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='varianttranscriptannotation',
            name='nmd_escaping_variant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='columnvepfield',
            name='vep_plugin',
            field=models.CharField(choices=[('d', 'dbNSFP'), ('v', 'dbscSNV'), ('g', 'Grantham'), ('l', 'LoFtool'), ('n', 'Mastermind'), ('m', 'MaxEntScan'), ('N', 'NMD'), ('a', 'SpliceAI'), ('s', 'SpliceRegion')], max_length=1, null=True),
        ),
    ]
