# Generated by Django 4.0.3 on 2022-05-26 04:08

from django.db import migrations

from manual.operations.manual_operations import ManualOperation

def _check_has_columns_version2(apps):
    VariantAnnotationVersion = apps.get_model("annotation", "VariantAnnotationVersion")
    return VariantAnnotationVersion.objects.filter(columns_version=2).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0053_new_vep_columns'),
    ]

    operations = [
        ManualOperation.operation_manage(["fix_columns_version2_damage_counts"],
                                         test=_check_has_columns_version2)
    ]
