# Generated by Django 4.0.3 on 2022-05-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0053_new_vep_column_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantannotationversion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
