# Generated by Django 4.0.2 on 2022-06-20 05:30

from django.db import migrations


def _one_off_add_ontology_versions(apps, _schema_editor):
    AnnotationVersion = apps.get_model("annotation", "AnnotationVersion")
    OntologyVersion = apps.get_model("ontology", "OntologyVersion")

    # There should be 1 made in 0016_one_off_assign_ontology_import_versions if we were able to
    if ontology_version := OntologyVersion.objects.all().first():
        print("Assigning existing ontology_version to existing annotations versions.")
        av_qs = AnnotationVersion.objects.filter(variant_annotation_version__isnull=False)
        av_qs.update(ontology_version=ontology_version)


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0055_annotationversion_ontology_version'),
        ('ontology', '0016_one_off_assign_ontology_import_versions'),
    ]

    operations = [
        migrations.RunPython(_one_off_add_ontology_versions),
    ]
