# Generated by Django 4.0.6 on 2022-07-28 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0019_ontologyterm_deprecated'),
        ('annotation', '0056_one_off_add_ontology_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneannotationversion',
            name='ontology_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ontology.ontologyversion'),
        ),
    ]
