# Generated by Django 4.0.6 on 2022-07-29 02:01

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_diff_ontology_version(apps):
    """ Only for existing annotations, that have different versions (ie not new deploys) """
    AnnotationVersion = apps.get_model("annotation", "AnnotationVersion")

    for genome_build_name in ["GRCh37", "GRCh38"]:
        if av := AnnotationVersion.objects.filter(genome_build__name=genome_build_name).order_by("pk").last():
            if av.ontology_version and av.gene_annotation_version:
                if av.gene_annotation_version.ontology_version != av.ontology_version:
                    return True
    return False


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0059_remove_geneannotationversion_last_ontology_import'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["gene_annotation", "--missing"]),
                        test=_test_diff_ontology_version)
    ]
