# Generated by Django 4.0.7 on 2022-12-05 05:57

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


def duplicate_citations(apps, schema_editor):
    print("About to populate Citation2")
    Citation = apps.get_model("annotation", "Citation")
    Citation2 = apps.get_model("annotation", "Citation2")
    all_citation_2s = list()
    for citation in Citation.objects.all():
        source = citation.citation_source
        if source == "P":
            all_citation_2s.append(Citation2(
                pk=f"PMID:{citation.citation_id}",
                old_id=citation.pk,
                source="PMID",
                index=citation.citation_id
            ))
        elif source == "C":
            all_citation_2s.append(Citation2(
                pk=f"PMCID:PMC{citation.citation_id}",
                old_id=citation.pk,
                source="PMCID",
                index=citation.citation_id
            ))
        elif source == "N":
            all_citation_2s.append(Citation2(
                pk=f"{citation.citation_id}",
                old_id=citation.pk,
                source="NBK",
                index=citation.citation_id
            ))
    Citation2.objects.bulk_create(objs=all_citation_2s)
    print("Completed making Citation2 stubs")

    all_gene_symbols = list()
    GeneSymbolCitation = apps.get_model("annotation", "GeneSymbolCitation")




class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0062_one_off_add_dbnsfp_gene_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation2',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('PMID', 'PMID'), ('NBK', 'NCBIBookShelf'), ('PMCID', 'PubMedCentral')], max_length=10)),
                ('index', models.TextField(null=True)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('last_loaded', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('journal', models.TextField(blank=True, null=True)),
                ('journal_short', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('authors_short', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clinvarcitation',
            name='citation2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.citation2'),
        ),
        migrations.AddField(
            model_name='genesymbolcitation',
            name='citation2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.citation2'),
        ),
    ]
