# Generated by Django 4.0.6 on 2022-08-10 01:17

from django.db import migrations


def _one_off_remove_loftool_vep(apps, schema_editor):
    ColumnVEPField = apps.get_model("annotation", "ColumnVEPField")
    ColumnVEPField.objects.filter(variant_grid_column='loftool').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0062_one_off_add_dbnsfp_gene_annotation'),
        ('snpdb', '0081_new_dbnsfp_gene_columns'),  # Where we changed the path from variant to dbnsfp gene anno
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantannotation',
            name='loftool',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='loftool',
        ),
        migrations.RunPython(_one_off_remove_loftool_vep),
    ]
