# Generated by Django 4.0.7 on 2022-12-08 23:25

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0062_one_off_add_dbnsfp_gene_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation2',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('PMID', 'PubMed'), ('Bookshelf ID', 'NCBI Bookshelf'), ('PMCID', 'PubMedCentral')], max_length=16)),
                ('index', models.TextField(null=True)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('last_loaded', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('journal', models.TextField(blank=True, null=True)),
                ('journal_short', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('authors_short', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clinvarcitation',
            name='citation2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.citation2'),
        ),
        migrations.AddField(
            model_name='genesymbolcitation',
            name='citation2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.citation2'),
        ),
    ]
