# Generated by Django 4.0.7 on 2022-12-09 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0057_one_off_upgrade_pyhgvs'),
        ('annotation', '0064_one_off_migration_citations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clinvarcitation',
            name='citation',
        ),
        migrations.AlterField(
            model_name='clinvarcitation',
            name='citation2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.citation2'),
        ),
        migrations.AlterUniqueTogether(
            name='genesymbolcitation',
            unique_together={('gene_symbol', 'citation2')},
        ),
        migrations.DeleteModel(
            name='CachedCitation',
        ),
        migrations.RemoveField(
            model_name='genesymbolcitation',
            name='citation',
        ),
        migrations.DeleteModel(
            name='Citation',
        ),
    ]
