# Generated by Django 4.0.7 on 2022-12-09 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0057_one_off_upgrade_pyhgvs'),
        ('annotation', '0065_alter_citation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citation2',
            new_name='Citation',
        ),
        migrations.RenameField(
            model_name='clinvarcitation',
            old_name='citation2',
            new_name='citation',
        ),
        migrations.RenameField(
            model_name='genesymbolcitation',
            old_name='citation2',
            new_name='citation',
        ),
        migrations.AlterUniqueTogether(
            name='genesymbolcitation',
            unique_together={('gene_symbol', 'citation')},
        ),
    ]
