# Generated by Django 4.1.3 on 2022-12-12 11:48

import numpy as np
from django.db import migrations


def _one_off_fix_pandas_nan_to_none(apps, _schema_editor):
    # Pandas nan to none conversion failed and bad data got in DB

    GeneAnnotation = apps.get_model("annotation", "GeneAnnotation")
    GnomADGeneConstraint = apps.get_model("genes", "GnomADGeneConstraint")

    GeneAnnotation.objects.filter(gnomad_oe_lof=np.NaN).update(gnomad_oe_lof=None)

    g_qs = GnomADGeneConstraint.objects.all()
    g_qs.filter(oe_lof=np.NaN).update(oe_lof=None)
    g_qs.filter(oe_lof_lower=np.NaN).update(oe_lof_lower=None)
    g_qs.filter(oe_lof_upper=np.NaN).update(oe_lof_upper=None)


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0066_rename_citation2_citation_and_more'),
    ]

    operations = [
        migrations.RunPython(_one_off_fix_pandas_nan_to_none)
    ]
