# Generated by Django 4.1.4 on 2022-12-14 05:11

from django.db import migrations

from annotation.management.commands.gene_annotation import bad_gene_annotation
from manual.operations.manual_operations import ManualOperation


def _check_has_bad_gene_annotation(_apps):
    return bad_gene_annotation()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0067_one_off_fix_pandas_nan_to_none'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["gene_annotation", "--fix-bad-gene-annotation"]),
                        test=_check_has_bad_gene_annotation)
    ]
