# Generated by Django 4.1.4 on 2022-12-14 05:11

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _check_has_bad_gene_annotation(apps):
    """ Replicates annotation.management.commands.gene_annotation.bad_gene_annotation() against
    the historical model so the test query doesn't reference columns added by later migrations
    (e.g. data_archived_date from 0145) when applied to a fresh DB. """
    GeneAnnotationVersion = apps.get_model('annotation', 'GeneAnnotationVersion')
    Gene = apps.get_model('genes', 'Gene')
    bad = []
    for gav in GeneAnnotationVersion.objects.all():
        if gav.dbnsfp_gene_version and not gav.geneannotation_set.filter(dbnsfp_gene__isnull=False).exists():
            bad.append(gav)
            continue
        try:
            if ga := gav.geneannotation_set.first():
                _ = ga.gene
        except Gene.DoesNotExist:
            bad.append(gav)
    return bad


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0067_one_off_fix_pandas_nan_to_none'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["gene_annotation", "--fix-bad-gene-annotation"]),
                        test=_check_has_bad_gene_annotation)
    ]
