# Generated by Django 4.0.7 on 2023-04-12 03:12

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _has_citations_to_fix(apps):
    # Only loaded citations (with old IDs) can have the bad data this fixes - none on a fresh install
    Citation = apps.get_model("annotation", "Citation")
    return Citation.objects.filter(old_id__isnull=False, data_json__isnull=False).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0068_one_off_manual_fix_bad_gene_annotation'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["citations", "--fix"]),
                        test=_has_citations_to_fix)
    ]
