# Generated by Django 4.0.7 on 2023-04-12 03:12

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0068_one_off_manual_fix_bad_gene_annotation'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["citations", "--fix"]))
    ]
