# Generated by Django 4.0.7 on 2023-04-19 00:47

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0069_one_off_fix_bad_citations'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["citations", "--reload"]))
    ]
