# Generated by Django 4.0.7 on 2023-04-19 00:47

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _has_error_citations(apps):
    # Nothing to reload if no citations are currently in error - none on a fresh install
    Citation = apps.get_model("annotation", "Citation")
    return Citation.objects.filter(error__isnull=False).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0069_one_off_fix_bad_citations'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["citations", "--reload"]),
                        test=_has_error_citations)
    ]
