# Generated by Django 4.2.2 on 2023-08-04 05:38

import django.contrib.postgres.fields
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0070_one_off_fix_error_citations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinVarRecordCollection',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('clinvar_variation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rcvs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('last_loaded', models.DateTimeField(blank=True, null=True)),
                ('parser_version', models.IntegerField(blank=True, null=True)),
                ('min_stars_loaded', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ClinVar record collection',
            },
        ),
        migrations.AlterModelOptions(
            name='clinvar',
            options={'verbose_name': 'ClinVar annotation', 'verbose_name_plural': 'ClinVar annotations'},
        ),
        migrations.CreateModel(
            name='ClinVarRecord',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('record_id', models.TextField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('org_id', models.TextField()),
                ('genome_build', models.TextField()),
                ('review_status', models.TextField()),
                ('submitter', models.TextField()),
                ('submitter_date', models.DateField()),
                ('date_last_evaluated', models.DateField(blank=True, null=True)),
                ('c_hgvs', models.TextField(blank=True, null=True)),
                ('variant_coordinate', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('clinical_significance', models.TextField(blank=True, null=True)),
                ('gene_symbol', models.TextField(blank=True, null=True)),
                ('interpretation_summary', models.TextField(blank=True, null=True)),
                ('assertion_method', models.TextField(blank=True, null=True)),
                ('allele_origin', models.TextField(blank=True, null=True)),
                ('clinvar_record_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.clinvarrecordcollection')),
            ],
            options={
                'verbose_name': 'ClinVar record',
            },
        ),
    ]
