# Generated by Django 4.1.4 on 2023-04-28 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0070_one_off_fix_error_citations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationrun',
            options={},
        ),
        migrations.AddField(
            model_name='annotationrun',
            name='pipeline_type',
            field=models.CharField(choices=[('S', 'Standard Short Variant'), ('C', 'CNV')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='annotationrun',
            name='annotation_range_lock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.annotationrangelock'),
        ),
        migrations.AlterUniqueTogether(
            name='annotationrun',
            unique_together={('annotation_range_lock', 'pipeline_type')},
        ),
    ]
