# Generated by Django 4.2.2 on 2023-08-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0071_clinvarrecordcollection_alter_clinvar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinvarrecordcollection',
            name='min_stars_loaded',
        ),
    ]
