# Generated by Django 4.1.3 on 2023-05-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0071_alter_annotationrun_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationrun',
            name='dump_count',
            field=models.IntegerField(null=True),
        ),
    ]
