# Generated by Django 4.1.3 on 2023-05-01 06:12

from django.db import migrations
from django.db.models import F
from django.utils import timezone

from annotation.models import VariantAnnotationPipelineType, AnnotationStatus


def _one_off_create_empty_cnv_annotation_runs(apps, _schema_editor):
    AnnotationRun = apps.get_model("annotation", "AnnotationRun")

    now = timezone.now()
    records = []
    ar_qs = AnnotationRun.objects.filter(pipeline_type=VariantAnnotationPipelineType.STANDARD)
    # Update existing to have dump set to annotated (didn't skip)
    ar_qs.update(dump_count=F("annotated_count"))

    for ar in AnnotationRun.objects.filter(pipeline_type=VariantAnnotationPipelineType.STANDARD):
        cnv_ar = AnnotationRun(
            status=AnnotationStatus.FINISHED,
            annotation_range_lock=ar.annotation_range_lock,
            pipeline_type=VariantAnnotationPipelineType.CNV,
            dump_start=now,
            dump_end=now,
            annotation_start=now,
            annotation_end=now,
            upload_start=now,
            upload_end=now,
            upload_attempts=0,
            dump_count=0,
            annotated_count=0,
        )
        records.append(cnv_ar)

    AnnotationRun.objects.bulk_create(records)


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0072_annotationrun_dump_count'),
    ]

    operations = [
        migrations.RunPython(_one_off_create_empty_cnv_annotation_runs)
    ]
