# Generated by Django 4.2.2 on 2023-08-16 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0098_columns_collections_add_internally_classified_labs'),
        ('annotation', '0072_remove_clinvarrecordcollection_min_stars_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarrecordcollection',
            name='allele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.allele'),
        ),
        migrations.AddField(
            model_name='clinvarrecordcollection',
            name='expert_panel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.clinvarrecord'),
        ),
        migrations.AddField(
            model_name='clinvarrecordcollection',
            name='max_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
