# Generated by Django 4.2.2 on 2023-08-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0073_clinvarrecordcollection_allele_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinvarrecord',
            options={'ordering': ['-stars', '-date_last_evaluated'], 'verbose_name': 'ClinVar record'},
        ),
        migrations.AlterModelOptions(
            name='clinvarrecordcollection',
            options={'ordering': ['-max_stars', '-pk'], 'verbose_name': 'ClinVar record collection'},
        ),
        migrations.AlterField(
            model_name='clinvarrecord',
            name='genome_build',
            field=models.TextField(blank=True, null=True),
        ),
    ]
