# Generated by Django 4.2.2 on 2023-08-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0074_alter_clinvarrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarrecord',
            name='date_clinvar_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinvarrecord',
            name='date_clinvar_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinvarrecord',
            name='submitter_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
