# Generated by Django 4.2.2 on 2023-09-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0075_clinvarrecord_date_clinvar_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinvarrecordcollection',
            old_name='rcvs',
            new_name='urls',
        ),
    ]
