# Generated by Django 4.2.2 on 2023-08-29 06:08

from django.db import migrations
from django.db.models import F
from django.utils import timezone


def _one_off_create_empty_cnv_annotation_runs(apps, _schema_editor):
    AnnotationRun = apps.get_model("annotation", "AnnotationRun")

    # VariantAnnotationPipelineType
    VARIANT_ANNOTATION_PIPELINE_TYPE_STANDARD = "S"
    VARIANT_ANNOTATION_PIPELINE_TYPE_CNV = "C"
    ANNOTATION_STATUS_FINISHED = 'F'

    now = timezone.now()
    records = []
    ar_qs = AnnotationRun.objects.filter(pipeline_type=VARIANT_ANNOTATION_PIPELINE_TYPE_STANDARD)
    # Update existing to have dump set to annotated (didn't skip)
    ar_qs.update(dump_count=F("annotated_count"))

    for ar in AnnotationRun.objects.filter(pipeline_type=VARIANT_ANNOTATION_PIPELINE_TYPE_CNV):
        cnv_ar = AnnotationRun(
            status=ANNOTATION_STATUS_FINISHED,
            annotation_range_lock=ar.annotation_range_lock,
            pipeline_type=VARIANT_ANNOTATION_PIPELINE_TYPE_CNV,
            dump_start=now,
            dump_end=now,
            annotation_start=now,
            annotation_end=now,
            upload_start=now,
            upload_end=now,
            upload_attempts=0,
            dump_count=0,
            annotated_count=0,
        )
        records.append(cnv_ar)

    AnnotationRun.objects.bulk_create(records)


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0076_alter_annotationrun_options_annotationrun_dump_count_and_more'),
    ]

    operations = [
        migrations.RunPython(_one_off_create_empty_cnv_annotation_runs),
    ]
