# Generated by Django 4.1.4 on 2023-09-12 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0076_rename_rcvs_clinvarrecordcollection_urls"),
        ("annotation", "0077_one_off_create_empty_cnv_annotation_runs"),
    ]

    operations = []
