# Generated by Django 4.2.2 on 2023-11-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0078_merge_20230912_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantannotation',
            name='alphamissense_class',
            field=models.CharField(blank=True, choices=[('b', 'likely_benign'), ('a', 'ambiguous'), ('p', 'likely_pathogenic')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='alphamissense_pathogenicity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='gnomad_mid_af',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='mavedb_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='mavedb_urn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='columnvepfield',
            name='vep_plugin',
            field=models.CharField(choices=[('A', 'AlphaMissense'), ('d', 'dbNSFP'), ('v', 'dbscSNV'), ('g', 'Grantham'), ('l', 'LoFtool'), ('n', 'Mastermind'), ('V', 'MaveDb'), ('m', 'MaxEntScan'), ('N', 'NMD'), ('a', 'SpliceAI'), ('s', 'SpliceRegion'), ('o', 'StructuralVariantOverlap')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='variantannotation',
            name='gnomad_popmax',
            field=models.CharField(blank=True, choices=[('AFR', 'African/African American'), ('ASJ', 'Ashkenazi Jewish'), ('EAS', 'East Asian'), ('FIN', 'Finnish'), ('AMR', 'Latino / Mixed Amerindian'), ('MID', 'Middle Eastern'), ('NFE', 'Non-Finnish European'), ('OTH', 'Other'), ('SAS', 'South Asian')], max_length=3, null=True),
        ),
    ]
