# Generated by Django 4.2.2 on 2023-11-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0080_columnvepfield_pipeline_type_variantannotation_faf95_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantannotation',
            old_name='faf95',
            new_name='gnomad_faf95',
        ),
        migrations.RenameField(
            model_name='variantannotation',
            old_name='faf99',
            new_name='gnomad_faf99',
        ),
        migrations.RenameField(
            model_name='variantannotation',
            old_name='fafmax_faf95_max',
            new_name='gnomad_fafmax_faf95_max',
        ),
        migrations.RenameField(
            model_name='variantannotation',
            old_name='fafmax_faf99_max',
            new_name='gnomad_fafmax_faf99_max',
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='gnomad_hemi_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='gnomad_non_par',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='gnomad_xy_ac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='gnomad_xy_af',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='gnomad_xy_an',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varianttranscriptannotation',
            name='alphamissense_class',
            field=models.CharField(blank=True, choices=[('b', 'likely_benign'), ('a', 'ambiguous'), ('p', 'likely_pathogenic')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='varianttranscriptannotation',
            name='alphamissense_pathogenicity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varianttranscriptannotation',
            name='mavedb_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varianttranscriptannotation',
            name='mavedb_urn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='columnvepfield',
            name='category',
            field=models.CharField(choices=[('C', 'Conservation'), ('E', 'External ID'), ('F', 'Frequency Data'), ('f', 'Functional Effect'), ('G', 'Gene Annotations'), ('H', 'HGVS'), ('L', 'Literature'), ('N', 'Nearby Features'), ('P', 'Pathogenicity Predictions'), ('Y', 'Phenotype'), ('D', 'Protein Domains'), ('Q', 'Sequence'), ('S', 'Splicing Predictions'), ('V', 'Variant Data')], max_length=1),
        ),
    ]
