# Generated by Django 4.2.2 on 2023-11-29 06:00

from django.db import migrations

from library.django_utils import bulk_insert_class_data


def _new_vep_110_annotation(apps, _schema_editor):
    VEP_CUSTOM_GNOMAD_2 = 'g'
    VEP_CUSTOM_GNOMAD_3 = 'n'
    VEP_CUSTOM_GNOMAD_4 = 'o'

    VEP_PLUGIN_MAVEDB = 'V'
    VEP_PLUGIN_ALPHAMISSENSE = 'A'

    FREQUENCY_DATA = 'F'
    FUNCTIONAL_EFFECT = 'f'
    PATHOGENICITY_PREDICTIONS = 'P'

    ColumnVEPField = apps.get_model("annotation", "ColumnVEPField")

    # Make existing gnomAD3 have max column version of 2
    ColumnVEPField.objects.filter(vep_custom=VEP_CUSTOM_GNOMAD_3).update(max_vep_columns_version=2)

    COLUMN_VEP_FIELD = [
        # gnomAD 2.1 additional fields - issue #231
        {'column': 'gnomad2_ac', 'variant_grid_column_id': 'gnomad_ac',
         'genome_build_id': 'GRCh37', 'pipeline_type': 'S', 'category': 'F', 'source_field': 'AC',
         'source_field_processing_description': 'Sum of exome AC + genome AC',
         'vep_custom': VEP_CUSTOM_GNOMAD_2, 'source_field_has_custom_prefix': True},
        {'column': 'gnomad2_popmax_ac', 'variant_grid_column_id': 'gnomad_popmax_ac',
         'genome_build_id': 'GRCh37', 'pipeline_type': 'S', 'category': 'F', 'source_field': 'AC_popmax',
         'source_field_processing_description': 'Sum of exome AC_popmax + genome AC_popmax',
         'vep_custom': VEP_CUSTOM_GNOMAD_2, 'source_field_has_custom_prefix': True},
        {'column': 'gnomad2_an', 'variant_grid_column_id': 'gnomad_an',
         'genome_build_id': 'GRCh37', 'pipeline_type': 'S', 'category': 'F', 'source_field': 'AN',
         'source_field_processing_description': 'Sum of exome AN + genome AN',
         'vep_custom': VEP_CUSTOM_GNOMAD_2, 'source_field_has_custom_prefix': True},
        {'column': 'gnomad2_popmax_an', 'variant_grid_column_id': 'gnomad_popmax_an',
         'genome_build_id': 'GRCh37', 'pipeline_type': 'S', 'category': 'F', 'source_field': 'AN_popmax',
         'source_field_processing_description': 'Sum of exome AN_popmax + genome AN_popmax',
         'vep_custom': VEP_CUSTOM_GNOMAD_2, 'source_field_has_custom_prefix': True},
        {'column': 'gnomad2_nonpar', 'variant_grid_column_id': 'gnomad_non_par',
         'genome_build_id': 'GRCh37', 'pipeline_type': 'S', 'category': 'F', 'source_field': 'nonpar',
         'source_field_processing_description': 'nonpar from genomes',
         'vep_custom': VEP_CUSTOM_GNOMAD_2, 'source_field_has_custom_prefix': True},

        # gnomAD 4 - issue #938
        {'column': 'gnomad4_ac', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_ac', 'source_field': 'AC',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_af', 'source_field': 'AF',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_an', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_an', 'source_field': 'AN',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_afr_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_afr_af', 'source_field': 'AF_afr',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_amr_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_amr_af', 'source_field': 'AF_amr',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_asj_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_asj_af', 'source_field': 'AF_asj',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_eas_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_eas_af', 'source_field': 'AF_eas',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_fin_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_fin_af', 'source_field': 'AF_fin',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_mid_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_mid_af', 'source_field': 'AF_mid',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_nfe_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_nfe_af', 'source_field': 'AF_nfe',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_oth_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_oth_af', 'source_field': 'AF_remaining',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_sas_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_sas_af', 'source_field': 'AF_sas',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},

        {'column': 'gnomad4_nonpar', 'variant_grid_column_id': 'gnomad_non_par', 'min_vep_columns_version': 3,
         'genome_build_id': 'GRCh38', 'pipeline_type': 'S', 'category': 'F', 'source_field': 'non_par',
         'source_field_processing_description': 'nonpar from genomes',
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'source_field_has_custom_prefix': True},
        {'column': 'gnomad4_filtered', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_filtered',
         'source_field': 'gnomad_filtered', 'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_hom_alt', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_hom_alt', 'source_field': 'nhomalt',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_popmax', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_popmax', 'source_field': 'grpmax',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_popmax_ac', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_popmax_ac', 'source_field': 'AC_grpmax',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_popmax_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_popmax_af', 'source_field': 'AF_grpmax',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_popmax_an', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_popmax_an', 'source_field': 'AN_grpmax',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},

        {'column': 'gnomad4_xy_ac', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_xy_ac', 'source_field': 'AC_XY',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_xy_af', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_xy_af', 'source_field': 'AF_XY',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_xy_an', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_xy_an', 'source_field': 'AN_XY',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},

        {'column': 'gnomad4_faf95', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_faf95', 'source_field': 'faf95',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_faf99', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_faf99', 'source_field': 'faf99',
         'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_fafmax_faf95_max', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_fafmax_faf95_max',
         'source_field': 'fafmax_faf95_max', 'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},
        {'column': 'gnomad4_fafmax_faf99_max', 'source_field_has_custom_prefix': True, 'min_vep_columns_version': 3,
         'vep_custom': VEP_CUSTOM_GNOMAD_4, 'variant_grid_column_id': 'gnomad_fafmax_faf99_max',
         'source_field': 'fafmax_faf99_max', 'category': FREQUENCY_DATA, 'genome_build_id': 'GRCh38'},

        # I left this out don't think it really matters
        #        {'column': 'gnomad4_popmax_hom_alt', 'source_field_has_custom_prefix': True,
        #         'vep_custom': GNOMAD_4, 'variant_grid_column_id': 'gnomad_popmax_hom_alt', 'source_field': 'nhomalt_grpmax', 'category': FREQUENCY_DATA},

        # MAVE
        {'column': 'mavedb_score', 'min_vep_columns_version': 3,
         'vep_plugin': VEP_PLUGIN_MAVEDB, 'variant_grid_column_id': 'mavedb_score',
         'source_field': 'MaveDB_score', 'category': FUNCTIONAL_EFFECT, 'genome_build_id': 'GRCh38'},
        {'column': 'mavedb_urn', 'min_vep_columns_version': 3,
         'vep_plugin': VEP_PLUGIN_MAVEDB, 'variant_grid_column_id': 'mavedb_urn',
         'source_field': 'MaveDB_urn', 'category': FUNCTIONAL_EFFECT, 'genome_build_id': 'GRCh38'},

        # AlphaMissense
        {'column': 'alphamissense_class', 'min_vep_columns_version': 3,
         'vep_plugin': VEP_PLUGIN_ALPHAMISSENSE, 'variant_grid_column_id': 'alphamissense_class',
         'source_field': 'am_class', 'category': PATHOGENICITY_PREDICTIONS},
        {'column': 'alphamissense_pathogenicity', 'min_vep_columns_version': 3,
         'vep_plugin': VEP_PLUGIN_ALPHAMISSENSE, 'variant_grid_column_id': 'alphamissense_pathogenicity',
         'source_field': 'am_pathogenicity', 'category': PATHOGENICITY_PREDICTIONS},

    ]
    bulk_insert_class_data(apps, "annotation", [("ColumnVEPField", COLUMN_VEP_FIELD)])


class Migration(migrations.Migration):
    dependencies = [
        ('annotation', '0081_rename_faf95_variantannotation_gnomad_faf95_and_more'),
        ("snpdb", "0107_new_vep_110_columns_v3"),  # Defines new columns
    ]

    operations = [
        migrations.RunPython(_new_vep_110_annotation)
    ]
