# Generated by Django 4.2.2 on 2023-12-05 05:51

from django.db import migrations

def _one_off_move_alphamissense_dbnsfp(apps, _schema_editor):
    PATHOGENICITY_PREDICTIONS = 'P'
    VEP_PLUGIN_DBNSFP = 'd'

    ColumnVEPField = apps.get_model("annotation", "ColumnVEPField")
    # The old alphamissense VEPFields cascade deleted from 0108_one_off_move_alphamissense_dbnsfp

    data = {
        'column': 'alphamissense_pathogenicity', 'min_vep_columns_version': 3,
        'variant_grid_column_id': 'alphamissense_rankscore',
        'vep_plugin': VEP_PLUGIN_DBNSFP,
        'source_field': 'AlphaMissense_rankscore', 'category': PATHOGENICITY_PREDICTIONS
    }
    ColumnVEPField.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0082_new_vep_110_columns_v3'),
        ("snpdb", "0108_one_off_move_alphamissense_dbnsfp"),
    ]

    operations = [
        migrations.RunPython(_one_off_move_alphamissense_dbnsfp)
    ]
