# Generated by Django 4.2.2 on 2023-12-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0083_one_off_move_alphamissense_dbnsfp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantannotation',
            old_name='alphamissense_pathogenicity',
            new_name='alphamissense_rankscore',
        ),
        migrations.RemoveField(
            model_name='variantannotation',
            name='alphamissense_class',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='alphamissense_class',
        ),
        migrations.RemoveField(
            model_name='varianttranscriptannotation',
            name='alphamissense_pathogenicity',
        ),
        migrations.AlterField(
            model_name='columnvepfield',
            name='vep_plugin',
            field=models.CharField(choices=[('d', 'dbNSFP'), ('v', 'dbscSNV'), ('g', 'Grantham'), ('l', 'LoFtool'), ('n', 'Mastermind'), ('V', 'MaveDb'), ('m', 'MaxEntScan'), ('N', 'NMD'), ('a', 'SpliceAI'), ('s', 'SpliceRegion'), ('o', 'StructuralVariantOverlap')], max_length=1, null=True),
        ),
    ]
