# Generated by Django 4.1.4 on 2023-12-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "annotation",
            "0084_rename_alphamissense_pathogenicity_variantannotation_alphamissense_rankscore_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dbnsfpgeneannotationversion",
            options={},
        ),
        migrations.AlterField(
            model_name="dbnsfpgeneannotationversion",
            name="md5_hash",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name="dbnsfpgeneannotationversion",
            unique_together={("version", "md5_hash")},
        ),
    ]
