# Generated by Django 4.2.9 on 2024-01-05 04:28

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _has_pre_v3_annotation(apps):
    # Only need to do this for old deploys, with no latest
    VariantAnnotationVersion = apps.get_model("annotation", "VariantAnnotationVersion")
    return (VariantAnnotationVersion.objects.exists()
            and not VariantAnnotationVersion.objects.filter(columns_version__gte=3))


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0087_one_off_annotation_version_use_cosmic_vcf"),
    ]

    operations = [
        ManualOperation.operation_other([
            "You may want to update your annotation to VEP110 and latest annotation data " +
            "See https://github.com/SACGF/variantgrid/wiki/Annotation-Column-Versions",
        ],
            test=_has_pre_v3_annotation),
    ]
