# Generated by Django 4.2.9 on 2024-01-05 05:46
from django.conf import settings
from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _check_needs_hemi_count(apps):
    # This will have only happened on dev versions
    if not settings.DEBUG:
        return

    VariantAnnotation = apps.get_model("annotation", "VariantAnnotation")
    VariantAnnotationVersion = apps.get_model("annotation", "VariantAnnotationVersion")
    if VariantAnnotationVersion.objects.filter(columns_version=3).exists():
        return VariantAnnotation.objects.filter(version__columns_version=3,
                                                gnomad_xy_ac__isnull=False,
                                                gnomad_non_par=True,
                                                gnomad_hemi_count__isnull=True).exists()
    return False


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0088_update_annotations_message"),
    ]

    operations = [
        ManualOperation.operation_manage(["fix_columns_version3_gnomad_hemi_count"],
                                         test=_check_needs_hemi_count)
    ]
