# Generated by Django 4.2.9 on 2024-02-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0089_one_off_fix_gnomad_hemi_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinvar',
            name='clinvar_review_status',
            field=models.CharField(choices=[('N', 'No assertion provided'), ('C', 'No assertion criteria provided'), ('I', 'No interpretation for the single variant'), ('n', 'No Classification Provided'), ('F', 'Criteria provided - conflicting interpretations'), ('S', 'Criteria provided - single submitter'), ('M', 'Criteria provided - multiple submitters w/no conflicts'), ('E', 'Reviewed by expert panel'), ('P', 'Practice guideline')], max_length=1, null=True),
        ),
    ]
