# Generated by Django 4.2.9 on 2024-02-21 03:52

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_has_missing_symbolic_hgvs(apps):
    AnnotationRun = apps.get_model("annotation", "AnnotationRun")
    return AnnotationRun.objects.filter(pipeline_type='C').exists()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0090_alter_clinvar_clinvar_review_status'),
    ]

    operations = [
        ManualOperation.operation_other(args=[
            "Run 'python3 manage.py one_off_populate_missing_symbolic_hgvs' - this can be done outside of migrations (use screen)"],
                                        test=_test_has_missing_symbolic_hgvs),
    ]
