# Generated by Django 4.2.10 on 2024-03-18 02:30
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0091_one_off_populate_missing_symbolic_hgvs"),
    ]

    operations = [
        # This has been replaced by annotation_files_check
    ]
