# Generated by Django 4.2.10 on 2024-03-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0092_vep_download_fasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantannotation',
            name='gnomad_sv_overlap_af',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='gnomad_sv_overlap_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='gnomad_sv_overlap_percent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='columnvepfield',
            name='pipeline_type',
            field=models.CharField(blank=True, choices=[('S', 'Standard Short Variant'), ('C', 'CNV')], default='S', max_length=1, null=True),
        ),
    ]
