# Generated by Django 4.2.10 on 2024-04-02 03:43

from django.db import migrations


def _gnomad2_liftover_grch38_only(apps, _schema_editor):
    ColumnVEPField = apps.get_model("annotation", "ColumnVEPField")
    GenomeBuild = apps.get_model("snpdb", "GenomeBuild")
    grch38 = GenomeBuild.objects.get(name="GRCh38")

    # This led to 2 fields being displayed of the same 2.1 data for 37 variants - make for 38 only
    ColumnVEPField.objects.filter(column='gnomad2_liftover_af').update(genome_build=grch38)


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0097_modify_gnomad_sv_overlap_column_vep_fields'),
    ]

    operations = [
        migrations.RunPython(_gnomad2_liftover_grch38_only)
    ]
