# Generated by Django 4.2.10 on 2024-04-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0098_gnomad2_liftover_grch38_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantannotation',
            name='hgvs_g',
            field=models.TextField(blank=True, null=True),
        ),
    ]
