# Generated by Django 4.2.2 on 2024-04-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0100_one_off_fix_variant_annotation_add_hgvs_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvarrecord',
            name='allele_origin_bucket',
            field=models.TextField(blank=True, choices=[('G', 'Germline'), ('S', 'Somatic'), ('U', 'Unknown')], null=True),
        ),
        migrations.AddField(
            model_name='clinvarrecord',
            name='somatic_clinical_significance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
