# Generated by Django 4.2.10 on 2024-05-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0101_clinvarrecord_allele_origin_bucket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinvar',
            name='oncogenic_classification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinvar',
            name='oncogenic_conflicting_classification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinvar',
            name='oncogenic_disease_database_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinvar',
            name='oncogenic_preferred_disease_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinvar',
            name='oncogenic_review_status',
            field=models.CharField(choices=[('N', 'No assertion provided'), ('C', 'No assertion criteria provided'), ('I', 'No interpretation for the single variant'), ('n', 'No Classification Provided'), ('F', 'Criteria provided - conflicting interpretations'), ('S', 'Criteria provided - single submitter'), ('M', 'Criteria provided - multiple submitters w/no conflicts'), ('E', 'Reviewed by expert panel'), ('P', 'Practice guideline')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='clinvar',
            name='somatic_clinical_significance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinvar',
            name='somatic_disease_database_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinvar',
            name='somatic_preferred_disease_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinvar',
            name='somatic_review_status',
            field=models.CharField(choices=[('N', 'No assertion provided'), ('C', 'No assertion criteria provided'), ('I', 'No interpretation for the single variant'), ('n', 'No Classification Provided'), ('F', 'Criteria provided - conflicting interpretations'), ('S', 'Criteria provided - single submitter'), ('M', 'Criteria provided - multiple submitters w/no conflicts'), ('E', 'Reviewed by expert panel'), ('P', 'Practice guideline')], max_length=1, null=True),
        ),
    ]
