# Generated by Django 4.2.10 on 2024-05-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0102_clinvar_oncogenic_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinvar',
            name='clinvar_review_status',
            field=models.CharField(choices=[('N', 'No assertion provided'), ('C', 'No assertion criteria provided'), ('I', 'No interpretation for the single variant'), ('n', 'No Classification Provided'), ('f', 'No classifications from unflaggedrecords'), ('F', 'Criteria provided - conflicting interpretations'), ('S', 'Criteria provided - single submitter'), ('M', 'Criteria provided - multiple submitters w/no conflicts'), ('E', 'Reviewed by expert panel'), ('P', 'Practice guideline')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='clinvar',
            name='oncogenic_review_status',
            field=models.CharField(choices=[('N', 'No assertion provided'), ('C', 'No assertion criteria provided'), ('I', 'No interpretation for the single variant'), ('n', 'No Classification Provided'), ('f', 'No classifications from unflaggedrecords'), ('F', 'Criteria provided - conflicting interpretations'), ('S', 'Criteria provided - single submitter'), ('M', 'Criteria provided - multiple submitters w/no conflicts'), ('E', 'Reviewed by expert panel'), ('P', 'Practice guideline')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='clinvar',
            name='somatic_review_status',
            field=models.CharField(choices=[('N', 'No assertion provided'), ('C', 'No assertion criteria provided'), ('I', 'No interpretation for the single variant'), ('n', 'No Classification Provided'), ('f', 'No classifications from unflaggedrecords'), ('F', 'Criteria provided - conflicting interpretations'), ('S', 'Criteria provided - single submitter'), ('M', 'Criteria provided - multiple submitters w/no conflicts'), ('E', 'Reviewed by expert panel'), ('P', 'Practice guideline')], max_length=1, null=True),
        ),
    ]
