# Generated by Django 4.2.10 on 2024-06-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0105_md5_to_sha256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dbnsfpgeneannotationversion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clinvarversion',
            name='md5_hash',
        ),
        migrations.RemoveField(
            model_name='humanproteinatlasannotationversion',
            name='md5_hash',
        ),
        migrations.AlterField(
            model_name='clinvarversion',
            name='sha256_hash',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbnsfpgeneannotationversion',
            name='sha256_hash',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='humanproteinatlasannotationversion',
            name='sha256_hash',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='dbnsfpgeneannotationversion',
            unique_together={('version', 'sha256_hash')},
        ),
        migrations.RemoveField(
            model_name='dbnsfpgeneannotationversion',
            name='md5_hash',
        ),
    ]
