# Generated by Django 4.2.10 on 2024-07-05 07:39

from django.db import migrations


def _one_off_change_hgvs_g_too_long_message(apps, _schema_editor):
    VariantAnnotation = apps.get_model('annotation', 'VariantAnnotation')
    VariantTranscriptAnnotation = apps.get_model('annotation', 'VariantTranscriptAnnotation')

    OLD_MESSAGE = "c.HGVS not calculated due to length"
    NEW_MESSAGE = "HGVS not calculated due to length"

    print("Changing HGVS too long message...")

    VariantAnnotation.objects.filter(variant__svlen__isnull=False,
                                     hgvs_g=OLD_MESSAGE).update(hgvs_g=NEW_MESSAGE)
    # VariantTranscriptAnnotation has no hgvs_g

    VariantAnnotation.objects.filter(variant__svlen__isnull=False,
                                     hgvs_c=OLD_MESSAGE).update(hgvs_c=NEW_MESSAGE)
    VariantTranscriptAnnotation.objects.filter(variant__svlen__isnull=False,
                                               hgvs_c=OLD_MESSAGE).update(hgvs_c=NEW_MESSAGE)


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0106_alter_dbnsfpgeneannotationversion_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(_one_off_change_hgvs_g_too_long_message)
    ]
