# Generated by Django 4.2.10 on 2024-07-08 03:35

from django.db import migrations


def _major_version(version_str) -> str:
    return version_str.split(".")[0]


def _one_off_vep_version_major_only(apps, schema_editor):
    VariantAnnotationVersion = apps.get_model('annotation', 'VariantAnnotationVersion')

    for vav in VariantAnnotationVersion.objects.all():
        vav.ensembl = _major_version(vav.ensembl)
        vav.ensembl_io = _major_version(vav.ensembl_io)
        vav.save()


class Migration(migrations.Migration):
    dependencies = [
        ('annotation', '0107_one_off_change_hgvs_g_too_long_message'),
    ]

    operations = [
        migrations.RunPython(_one_off_vep_version_major_only)
    ]
