# Generated by Django 4.2.9 on 2024-07-09 04:01

from django.db import migrations


def _major_version(version_str) -> str:
    return version_str.split(".")[0]


def _one_off_vep_version_major_only(apps, _schema_editor):
    VariantAnnotationVersion = apps.get_model('annotation', 'VariantAnnotationVersion')

    for vav in VariantAnnotationVersion.objects.all():
        vav.ensembl_variation = _major_version(vav.ensembl_variation)
        vav.save()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0108_one_off_vep_version_major_only'),
    ]

    operations = [
        migrations.RunPython(_one_off_vep_version_major_only),
    ]
