# Generated by Django 4.2.11 on 2024-07-09 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0109_alter_clinvar_clinvar_review_status_and_more'),
        ('annotation', '0109_one_off_vep_version_major_only_ensembl_variation'),
    ]

    operations = [
    ]
