# Generated by Django 4.2.10 on 2024-07-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0111_one_off_replace_mito_hgvs'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnvepfield',
            name='summary_stats',
            field=models.TextField(blank=True, null=True),
        ),
    ]
