# Generated by Django 4.2.10 on 2024-07-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0112_columnvepfield_summary_stats'),
    ]

    operations = [
        # This is deliberately empty - and undone in 0115
    ]
