# Generated by Django 4.2.10 on 2024-07-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0113_one_off_populate_column_vep_field_summary_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columnvepfield',
            old_name='max_vep_columns_version',
            new_name='max_columns_version',
        ),
        migrations.RenameField(
            model_name='columnvepfield',
            old_name='min_vep_columns_version',
            new_name='min_columns_version',
        ),
        migrations.AddField(
            model_name='columnvepfield',
            name='max_vep_version',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='columnvepfield',
            name='min_vep_version',
            field=models.IntegerField(null=True),
        ),
    ]
