# Generated by Django 4.2.10 on 2024-07-19 05:41

from django.db import migrations

from library.django_utils import bulk_insert_class_data


def _one_off_undo_0113(apps, schema_editor):
    ColumnVEPField = apps.get_model('annotation', 'ColumnVEPField')
    bigwigs = [
        'phastcons_100_way_vertebrate',
        'phylop_100_way_vertebrate',
        'phastcons_46_way_mammalian',
        'phylop_46_way_mammalian',
        'phastcons_30_way_mammalian',
        'phylop_30_way_mammalian'
    ]
    ColumnVEPField.objects.filter(column__in=bigwigs).update(summary_stats=None)


def _one_off_vep_112_summary_stats_fields(apps, schema_editor):
    ColumnVEPField = apps.get_model('annotation', 'ColumnVEPField')
    bigwigs = [
        'phastcons_100_way_vertebrate',
        'phylop_100_way_vertebrate',
        'phastcons_46_way_mammalian',
        'phylop_46_way_mammalian',
        'phastcons_30_way_mammalian',
        'phylop_30_way_mammalian',
    ]
    # Mark the existing ones as VEP pre-112
    ColumnVEPField.objects.filter(column__in=bigwigs).update(max_vep_version=111)

    _new_columns = [
        {'column': 'phastcons_30_way_mammalian_max',
         'variant_grid_column_id': 'phastcons_30_way_mammalian',
         'genome_build_id': 'GRCh38',
         'pipeline_type': None,
         'category': 'C',
         'source_field': 'max',
         'source_field_processing_description': 'max() for indels',
         'vep_plugin': None,
         'vep_custom': '2',
         'source_field_has_custom_prefix': True,
         'min_columns_version': None,
         'max_columns_version': None,
         'min_vep_version': 112,
         'max_vep_version': None,
         'summary_stats': 'max'},
        {'column': 'phastcons_100_way_vertebrate_max',
         'variant_grid_column_id': 'phastcons_100_way_vertebrate',
         'genome_build_id': None,
         'pipeline_type': None,
         'category': 'C',
         'source_field': 'max',
         'source_field_processing_description': 'max() for indels',
         'vep_plugin': None,
         'vep_custom': '1',
         'source_field_has_custom_prefix': True,
         'min_columns_version': None,
         'max_columns_version': None,
         'min_vep_version': 112,
         'max_vep_version': None,
         'summary_stats': 'max'},
        {'column': 'phylop_100_way_vertebrate_max',
         'variant_grid_column_id': 'phylop_100_way_vertebrate',
         'genome_build_id': None,
         'pipeline_type': None,
         'category': 'C',
         'source_field': 'max',
         'source_field_processing_description': 'max() for indels',
         'vep_plugin': None,
         'vep_custom': '4',
         'source_field_has_custom_prefix': True,
         'min_columns_version': None,
         'max_columns_version': None,
         'min_vep_version': 112,
         'max_vep_version': None,
         'summary_stats': 'max'},
        {'column': 'phastcons_46_way_mammalian_max',
         'variant_grid_column_id': 'phastcons_46_way_mammalian',
         'genome_build_id': 'GRCh37',
         'pipeline_type': None,
         'category': 'C',
         'source_field': 'max',
         'source_field_processing_description': 'max() for indels',
         'vep_plugin': None,
         'vep_custom': '3',
         'source_field_has_custom_prefix': True,
         'min_columns_version': None,
         'max_columns_version': None,
         'min_vep_version': 112,
         'max_vep_version': None,
         'summary_stats': 'max'},
        {'column': 'phylop_46_way_mammalian_max',
         'variant_grid_column_id': 'phylop_46_way_mammalian',
         'genome_build_id': 'GRCh37',
         'pipeline_type': None,
         'category': 'C',
         'source_field': 'max',
         'source_field_processing_description': 'max() for indels',
         'vep_plugin': None,
         'vep_custom': '6',
         'source_field_has_custom_prefix': True,
         'min_columns_version': None,
         'max_columns_version': None,
         'min_vep_version': 112,
         'max_vep_version': None,
         'summary_stats': 'max'},
        {'column': 'phylop_30_way_mammalian_max',
         'variant_grid_column_id': 'phylop_30_way_mammalian',
         'genome_build_id': 'GRCh38',
         'pipeline_type': None,
         'category': 'C',
         'source_field': 'max',
         'source_field_processing_description': 'max() for indels',
         'vep_plugin': None,
         'vep_custom': '5',
         'source_field_has_custom_prefix': True,
         'min_columns_version': None,
         'max_columns_version': None,
         'min_vep_version': 112,
         'max_vep_version': None,
         'summary_stats': 'max'
         }
    ]
    bulk_insert_class_data(apps, "annotation", [("ColumnVEPField", _new_columns)])



class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0114_rename_max_vep_columns_version_columnvepfield_max_columns_version_and_more'),
    ]

    operations = [
        migrations.RunPython(_one_off_undo_0113),
        migrations.RunPython(_one_off_vep_112_summary_stats_fields)
    ]
