# Generated by Django 4.2.10 on 2024-08-08 02:28

from django.db import migrations

def _one_off_update_vep_112_conservation_sv(apps, schema_editor):
    """
        These were accidentally left as short/standard variant only due to copy/paste
        I have modified the migration 0115 - so can delete this if squishing migrations
    """
    ColumnVEPField = apps.get_model('annotation', 'ColumnVEPField')
    ColumnVEPField.objects.filter(min_vep_version=112).update(pipeline_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0115_one_off_vep_column_fields_vep112'),
    ]

    operations = [
        migrations.RunPython(_one_off_update_vep_112_conservation_sv)
    ]
