# Generated by Django 4.2.11 on 2024-08-09 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0116_one_off_update_vep_112_conservation_sv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinvar",
            old_name="clinvar_clinical_sources",
            new_name="clinical_sources",
        ),
        migrations.RenameField(
            model_name="clinvar",
            old_name="clinvar_disease_database_name",
            new_name="disease_database_name",
        ),
        migrations.RenameField(
            model_name="clinvar",
            old_name="clinvar_origin",
            new_name="origin",
        ),
        migrations.RenameField(
            model_name="clinvar",
            old_name="clinvar_preferred_disease_name",
            new_name="preferred_disease_name",
        ),
        migrations.RenameField(
            model_name="clinvar",
            old_name="clinvar_review_status",
            new_name="review_status",
        ),
        migrations.RenameField(
            model_name="clinvar",
            old_name="clinvar_suspect_reason_code",
            new_name="suspect_reason_code",
        ),
    ]
