# Generated by Django 4.2.9 on 2024-12-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotation",
            "0117_rename_clinvar_clinical_sources_clinvar_clinical_sources_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="variantannotationversion",
            name="vep_cache",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="variantannotationversion",
            name="cosmic",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variantannotationversion",
            name="dbnsfp",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variantannotationversion",
            name="dbsnp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variantannotationversion",
            name="gencode",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variantannotationversion",
            name="gnomad",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variantannotationversion",
            name="hgmd",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variantannotationversion",
            name="regbuild",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variantannotationversion",
            name="sift",
            field=models.TextField(blank=True, null=True),
        ),
    ]
