# Generated by Django 4.2.9 on 2024-12-04 04:18

from django.db import migrations
from django.db.models import F


def _one_off_historical_vep_cache_version(apps, _schema_editor):
    VariantAnnotationVersion = apps.get_model("annotation", "VariantAnnotationVersion")
    VariantAnnotationVersion.objects.filter(vep_cache__isnull=True).update(vep_cache=F("vep"))

    # This used to be non-nullable, now might as well just store that
    VariantAnnotationVersion.objects.filter(dbnsfp='n/a').update(dbnsfp=None)


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0118_variantannotationversion_vep_cache_and_more"),
    ]

    operations = [
        migrations.RunPython(_one_off_historical_vep_cache_version)
    ]
