# Generated by Django 4.2.15 on 2024-12-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0119_one_off_historical_vep_cache_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantannotationversion',
            name='thousand_genomes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
