# Generated by Django 4.2.17 on 2025-01-17 04:00

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _check_has_sv_annotation(apps):
    AnnotationRun = apps.get_model("annotation", "AnnotationRun")

    VAP_STRUCTURAL_VARIANT = 'C'
    AS_FINISHED = 'F'

    qs = AnnotationRun.objects.filter(pipeline_type=VAP_STRUCTURAL_VARIANT,
                                      status=AS_FINISHED,
                                      annotated_count__gt=0)
    return qs.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0122_vep_gnomad_t2t'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_annotation_sv_c_hgvs"]),
                        test=_check_has_sv_annotation)
    ]
