# Generated by Django 4.2.18 on 2025-04-08 03:56
from django.conf import settings
from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_has_missing_omim(apps):
    GeneAnnotationVersion = apps.get_model("annotation", "GeneAnnotationVersion")

    if settings.ANNOTATION_GENE_ANNOTATION_VERSION_ENABLED:
        for gav in GeneAnnotationVersion.objects.filter(ontology_version__omim_import__isnull=True):
            if not gav.geneannotation_set.filter(omim_terms__isnull=False).exists():
                return True
    return False

class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0125_one_off_historical_vep_too_long'),
        ('ontology', '0024_alter_ontologyversion_unique_together_and_more')
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["gene_annotation", "--add-missing-omim"]),
                        test=_test_has_missing_omim)
    ]
