# Generated by Django 4.2.20 on 2025-04-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0126_one_off_recalculate_missing_gene_annotation_omim_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualvariantentry',
            name='warning_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
