# Generated by Django 4.2.20 on 2025-07-09 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0079_one_off_panel_app_aus_url_change'),
        ('annotation', '0127_manualvariantentry_warning_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenePubMedCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('cached_web_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.cachedwebresource')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.gene')),
            ],
        ),
        migrations.DeleteModel(
            name='GeneSymbolPubMedCount',
        ),
    ]
