# Generated by Django 6.0.3 on 2026-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0131_dbnsfp_v4_pathogenicity_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantannotationversion",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
