# Generated by Django 6.0.3 on 2026-04-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0133_denovo_db_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationrun",
            name="annotsv_error",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="annotationrun",
            name="annotsv_imported",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="annotationrun",
            name="annotsv_tsv_filename",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_acmg_class",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_acmg_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_b_gain_af_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_b_ins_af_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_b_inv_af_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_b_loss_af_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_encode_blacklist_characteristics_left",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_encode_blacklist_characteristics_right",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_encode_blacklist_left",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_encode_blacklist_right",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_re_gene",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_repeat_type_left",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_repeat_type_right",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_segdup_left",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_segdup_right",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="annotsv_bundle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="annotsv_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
