# Generated by Django 6.0.3 on 2026-04-30 07:03

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0136_one_off_fix_historical_spliceai_max_ds"),
        ("snpdb", "0178_cohortgenotypestats"),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortGenotypeClinVarAnnotationStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("filter_key", models.TextField(null=True)),
                ("passing_filter", models.BooleanField(default=False)),
                ("clinvar_count", models.IntegerField(default=0)),
                ("ref_clinvar_pathogenic_count", models.IntegerField(default=0)),
                ("het_clinvar_pathogenic_count", models.IntegerField(default=0)),
                ("hom_clinvar_pathogenic_count", models.IntegerField(default=0)),
                ("unk_clinvar_pathogenic_count", models.IntegerField(default=0)),
                (
                    "clinvar_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.clinvarversion",
                    ),
                ),
                (
                    "code_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.samplestatscodeversion",
                    ),
                ),
                (
                    "cohort_genotype_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinvar_annotation_stats",
                        to="snpdb.cohortgenotypecollection",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.sample",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", False), ("filter_key__isnull", True)
                        ),
                        fields=(
                            "cohort_genotype_collection",
                            "sample",
                            "clinvar_version",
                            "passing_filter",
                        ),
                        name="cohort_genotype_clinvar_ann_stats_per_sample_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", True), ("filter_key__isnull", True)
                        ),
                        fields=(
                            "cohort_genotype_collection",
                            "clinvar_version",
                            "passing_filter",
                        ),
                        name="cohort_genotype_clinvar_ann_stats_aggregate_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", True), ("filter_key__isnull", False)
                        ),
                        fields=(
                            "cohort_genotype_collection",
                            "clinvar_version",
                            "filter_key",
                            "passing_filter",
                        ),
                        name="cohort_genotype_clinvar_ann_stats_aggregate_filter_uniq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CohortGenotypeGeneAnnotationStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("filter_key", models.TextField(null=True)),
                ("passing_filter", models.BooleanField(default=False)),
                ("gene_count", models.IntegerField(default=0)),
                ("ref_omim_phenotype_count", models.IntegerField(default=0)),
                ("het_omim_phenotype_count", models.IntegerField(default=0)),
                ("hom_omim_phenotype_count", models.IntegerField(default=0)),
                ("unk_omim_phenotype_count", models.IntegerField(default=0)),
                (
                    "code_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.samplestatscodeversion",
                    ),
                ),
                (
                    "cohort_genotype_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gene_annotation_stats",
                        to="snpdb.cohortgenotypecollection",
                    ),
                ),
                (
                    "gene_annotation_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.geneannotationversion",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.sample",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", False), ("filter_key__isnull", True)
                        ),
                        fields=(
                            "cohort_genotype_collection",
                            "sample",
                            "gene_annotation_version",
                            "passing_filter",
                        ),
                        name="cohort_genotype_gene_ann_stats_per_sample_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", True), ("filter_key__isnull", True)
                        ),
                        fields=(
                            "cohort_genotype_collection",
                            "gene_annotation_version",
                            "passing_filter",
                        ),
                        name="cohort_genotype_gene_ann_stats_aggregate_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", True), ("filter_key__isnull", False)
                        ),
                        fields=(
                            "cohort_genotype_collection",
                            "gene_annotation_version",
                            "filter_key",
                            "passing_filter",
                        ),
                        name="cohort_genotype_gene_ann_stats_aggregate_filter_uniq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CohortGenotypeVariantAnnotationStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("filter_key", models.TextField(null=True)),
                ("passing_filter", models.BooleanField(default=False)),
                ("variant_dbsnp_count", models.IntegerField(default=0)),
                ("insertions_dbsnp_count", models.IntegerField(default=0)),
                ("snp_dbsnp_count", models.IntegerField(default=0)),
                ("deletions_dbsnp_count", models.IntegerField(default=0)),
                ("ref_high_or_moderate_count", models.IntegerField(default=0)),
                ("het_high_or_moderate_count", models.IntegerField(default=0)),
                ("hom_high_or_moderate_count", models.IntegerField(default=0)),
                ("unk_high_or_moderate_count", models.IntegerField(default=0)),
                (
                    "code_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.samplestatscodeversion",
                    ),
                ),
                (
                    "cohort_genotype_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_annotation_stats",
                        to="snpdb.cohortgenotypecollection",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.sample",
                    ),
                ),
                (
                    "variant_annotation_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.variantannotationversion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", False), ("filter_key__isnull", True)
                        ),
                        fields=(
                            "cohort_genotype_collection",
                            "sample",
                            "variant_annotation_version",
                            "passing_filter",
                        ),
                        name="cohort_genotype_var_ann_stats_per_sample_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", True), ("filter_key__isnull", True)
                        ),
                        fields=(
                            "cohort_genotype_collection",
                            "variant_annotation_version",
                            "passing_filter",
                        ),
                        name="cohort_genotype_var_ann_stats_aggregate_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sample__isnull", True), ("filter_key__isnull", False)
                        ),
                        fields=(
                            "cohort_genotype_collection",
                            "variant_annotation_version",
                            "filter_key",
                            "passing_filter",
                        ),
                        name="cohort_genotype_var_ann_stats_aggregate_filter_uniq",
                    ),
                ],
            },
        ),
    ]
