# Generated by Django 6.0.3 on 2026-05-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0139_variantannotationversion_mave_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantannotation",
            name="alphamissense_pred",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B", "benign"),
                    ("b", "likely_benign"),
                    ("a", "ambiguous"),
                    ("p", "likely_pathogenic"),
                    ("P", "pathogenic"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="varianttranscriptannotation",
            name="alphamissense_pred",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B", "benign"),
                    ("b", "likely_benign"),
                    ("a", "ambiguous"),
                    ("p", "likely_pathogenic"),
                    ("P", "pathogenic"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
