# Generated by Django 6.0.3 on 2026-05-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0140_alter_variantannotation_alphamissense_pred_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantannotationversion",
            name="transcript_resolver",
            field=models.TextField(blank=True, null=True),
        ),
    ]
