# Generated by Django 6.0.3 on 2026-05-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0141_variantannotationversion_transcript_resolver"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_acmg_criteria",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_dist_nearest_ss",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_exons_spanned",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_frameshift",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_nearest_ss_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_omim_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_omim_inheritance",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_omim_morbid",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_omim_phenotype",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="annotsv_pathogenic_overlaps",
            field=models.JSONField(null=True),
        ),
    ]
