# Generated by Django 6.0.3 on 2026-05-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0146_one_off_cols_v4_pathogenic_counts"),
        ("genes", "0080_genecoveragecollection_data_archive"),
        ("snpdb", "0182_cohortgenotypecollection_data_archive_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantannotation",
            name="max_af",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="variantannotation",
            index=models.Index(
                condition=models.Q(("max_af__lte", 0.05)),
                fields=["max_af"],
                name="va_max_af_low_idx",
            ),
        ),
    ]
