# Generated by Django 6.0.3 on 2026-05-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0148_one_off_backfill_max_af"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantannotationversion",
            name="gencode_subset",
            field=models.TextField(
                blank=True,
                choices=[("basic", "GENCODE Basic"), ("primary", "GENCODE Primary")],
                null=True,
            ),
        ),
    ]
