# Generated by Django 6.0.3 on 2026-05-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0149_variantannotationversion_gencode_subset"),
        ("genes", "0080_genecoveragecollection_data_archive"),
        ("snpdb", "0182_cohortgenotypecollection_data_archive_reason_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variantgeneoverlap",
            unique_together={("version", "variant", "gene")},
        ),
    ]
