# Generated by Django 6.0.5 on 2026-06-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0151_variantannotationversion_backfill_flags"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="variantannotation",
            name="va_max_af_low_idx",
        ),
        migrations.RemoveField(
            model_name="variantannotationversion",
            name="backfilled_max_af",
        ),
        migrations.RemoveField(
            model_name="variantannotation",
            name="max_af",
        ),
    ]
