# Generated by Django 6.0.5 on 2026-06-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0152_remove_variantannotation_va_max_af_low_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationrun',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annotationrun',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('x', 'Deleting'), ('d', 'Dump Started'), ('D', 'Dump Completed'), ('e', 'Awaiting external annotation'), ('a', 'Annotation Started'), ('A', 'Annotation Completed'), ('U', 'Upload Started'), ('F', 'Finished'), ('E', 'Error')], default='C', max_length=1),
        ),
    ]
