# Generated by Django 6.0.3 on 2026-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0153_annotationrun_external_alter_annotationrun_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationrun",
            name="attempt_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="annotationrun",
            name="lease_expires",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="annotationrun",
            name="leased_by",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
