# Generated by Django 6.0.6 on 2026-07-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0156_vep116_plugin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationrun',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
