# Generated by Django 6.0.6 on 2026-08-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0159_one_off_legacy_annotation_version_ontology_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sampleclinvarannotationstatspassingfilter",
            name="clinvar_version",
        ),
        migrations.RemoveField(
            model_name="sampleclinvarannotationstatspassingfilter",
            name="code_version",
        ),
        migrations.RemoveField(
            model_name="sampleclinvarannotationstatspassingfilter",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="samplegeneannotationstats",
            name="code_version",
        ),
        migrations.RemoveField(
            model_name="samplegeneannotationstats",
            name="gene_annotation_version",
        ),
        migrations.RemoveField(
            model_name="samplegeneannotationstats",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="samplegeneannotationstatspassingfilter",
            name="code_version",
        ),
        migrations.RemoveField(
            model_name="samplegeneannotationstatspassingfilter",
            name="gene_annotation_version",
        ),
        migrations.RemoveField(
            model_name="samplegeneannotationstatspassingfilter",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="samplevariantannotationstats",
            name="code_version",
        ),
        migrations.RemoveField(
            model_name="samplevariantannotationstats",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="samplevariantannotationstats",
            name="variant_annotation_version",
        ),
        migrations.RemoveField(
            model_name="samplevariantannotationstatspassingfilter",
            name="code_version",
        ),
        migrations.RemoveField(
            model_name="samplevariantannotationstatspassingfilter",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="samplevariantannotationstatspassingfilter",
            name="variant_annotation_version",
        ),
        migrations.DeleteModel(
            name="SampleClinVarAnnotationStats",
        ),
        migrations.DeleteModel(
            name="SampleClinVarAnnotationStatsPassingFilter",
        ),
        migrations.DeleteModel(
            name="SampleGeneAnnotationStats",
        ),
        migrations.DeleteModel(
            name="SampleGeneAnnotationStatsPassingFilter",
        ),
        migrations.DeleteModel(
            name="SampleVariantAnnotationStats",
        ),
        migrations.DeleteModel(
            name="SampleVariantAnnotationStatsPassingFilter",
        ),
    ]
