# Generated by Django 6.0.6 on 2026-08-06 03:54

from django.conf import settings
from django.db import migrations, models

from annotation.vep_config import vep_component_version_kwargs


def _backfill_vep_components(apps, _schema_editor):
    """ Stamp the versions the scheduler can still match with what current settings say (#462).

        get_or_create_variant_annotation_version_from_current_vep() looks a version up by every VEP
        kwarg, so leaving these NULL would make a deployment whose annotation config hasn't changed
        mint a fresh VariantAnnotationVersion and reannotate. HISTORICAL versions are left NULL -
        we don't know what data they ran against, and nothing looks them up by config again. """

    VariantAnnotationVersion = apps.get_model("annotation", "VariantAnnotationVersion")
    for vav in VariantAnnotationVersion.objects.filter(status__in=["NEW", "ACTIVE"]):
        build_settings = settings.ANNOTATION.get(vav.genome_build_id)
        if build_settings is None:
            continue  # Build no longer configured on this deployment
        kwargs = vep_component_version_kwargs(build_settings)
        for field, value in kwargs.items():
            setattr(vav, field, value)
        vav.save(update_fields=list(kwargs))


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotation",
            "0160_remove_sampleclinvarannotationstatspassingfilter_clinvar_version_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="variantannotationversion",
            name="conservation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="dbscsnv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="eve",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="fasta",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="gnomad_sv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="mastermind",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="maxentscan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="pick_order",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="promoter_ai",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="protvar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="repeat_masker",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="sift_enabled",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="sv_max_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="sv_overlap_min_fraction",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="topmed",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="transcript_blocklist",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="uk10k",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="vep_args",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(_backfill_vep_components, migrations.RunPython.noop),
    ]
