# Generated by Django 6.0.6 on 2026-08-06 08:38

from django.db import migrations, models


def _flip_existing_vavs_false(apps, schema_editor):
    """ Existing VAVs were annotated before the PTC calculation existed, so their
        nmd_escape_status is null until `manage.py backfill_ptc_annotation` fills the
        partition in. @see VariantAnnotationVersion.backfilled_ptc """
    VariantAnnotationVersion = apps.get_model("annotation", "VariantAnnotationVersion")
    VariantAnnotationVersion.objects.all().update(backfilled_ptc=False)


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0161_vep_command_line_component_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantannotation",
            name="nmd_escape_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "Escapes NMD"),
                    ("N", "NMD predicted"),
                    ("A", "Not applicable"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="ptc_distance_codons",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotation",
            name="ptc_last_junction_distance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantannotationversion",
            name="backfilled_ptc",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="varianttranscriptannotation",
            name="nmd_escape_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "Escapes NMD"),
                    ("N", "NMD predicted"),
                    ("A", "Not applicable"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="varianttranscriptannotation",
            name="ptc_distance_codons",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="varianttranscriptannotation",
            name="ptc_last_junction_distance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(_flip_existing_vavs_false, migrations.RunPython.noop),
    ]
