# Generated by Django 6.0.6 on 2026-08-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0163_one_off_backfill_ptc_annotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationrun",
            name="vep_skipped_variants_filename",
            field=models.TextField(null=True),
        ),
    ]
