# Generated by Django 6.0.6 on 2026-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0165_one_off_truncated_vep_output_runs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationrun",
            name="pipeline_type",
            field=models.CharField(
                choices=[
                    ("S", "Standard Short Variant"),
                    ("C", "Structural Variant"),
                    ("G", "Gene Level"),
                ],
                default="S",
                max_length=1,
            ),
        ),
    ]
