# Generated by Django 6.1 on 2026-08-18 10:32

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0166_alter_annotationrun_pipeline_type"),
        ("snpdb", "0207_gene_level_contig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationrun",
            name="annotsv_error",
        ),
        migrations.RemoveField(
            model_name="annotationrun",
            name="annotsv_imported",
        ),
        migrations.RemoveField(
            model_name="annotationrun",
            name="annotsv_tsv_filename",
        ),
        migrations.RemoveField(
            model_name="variantannotationversion",
            name="annotsv_bundle",
        ),
        migrations.RemoveField(
            model_name="variantannotationversion",
            name="annotsv_code",
        ),
        migrations.AlterField(
            model_name="annotationrun",
            name="pipeline_type",
            field=models.CharField(
                choices=[
                    ("S", "Standard Short Variant"),
                    ("C", "Structural Variant"),
                    ("G", "Gene Level"),
                    ("A", "AnnotSV"),
                ],
                default="S",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="AnnotationPipelineVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "pipeline_type",
                    models.CharField(
                        choices=[
                            ("S", "Standard Short Variant"),
                            ("C", "Structural Variant"),
                            ("G", "Gene Level"),
                            ("A", "AnnotSV"),
                        ],
                        max_length=1,
                    ),
                ),
                ("code_version", models.TextField()),
                ("data_version", models.TextField(blank=True, null=True)),
                (
                    "genome_build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.genomebuild",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("pipeline_type", "genome_build", "code_version", "data_version")
                },
            },
        ),
        migrations.AddField(
            model_name="annotationrun",
            name="pipeline_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="annotation.annotationpipelineversion",
            ),
        ),
    ]
