# Generated by Django 6.1 on 2026-08-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0167_annotsv_annotation_pipeline"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="annotationrun",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="annotationpipelineversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("ACTIVE", "Active"),
                    ("HISTORICAL", "Historical"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="annotationrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pipeline_version__isnull", True)),
                fields=("annotation_range_lock", "pipeline_type"),
                name="one_unversioned_run_per_range_lock_and_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotationrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pipeline_version__isnull", False)),
                fields=("annotation_range_lock", "pipeline_type", "pipeline_version"),
                name="one_versioned_run_per_range_lock_type_and_version",
            ),
        ),
    ]
