# Generated by Django 6.1 on 2026-08-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0175_one_off_rebackfill_annotation_run_pipeline_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinvar",
            name="highest_oncogenicity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clinvar",
            name="somatic_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tier_1", "Tier I"),
                    ("tier_1_or_2", "Tier I/II"),
                    ("tier_2", "Tier II"),
                    ("tier_3", "Tier III"),
                    ("tier_4", "Tier IV"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
