# Generated by Django 6.1.1 on 2026-09-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0181_one_off_fix_gnomad_sv_overlap_chosen_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantannotation',
            name='annotsv_acmg_class',
            field=models.IntegerField(blank=True, choices=[(1, 'Benign'), (2, 'Likely benign'), (3, 'Uncertain'), (4, 'Likely pathogenic'), (5, 'Pathogenic')], null=True),
        ),
    ]
