# Generated by Django 6.1.1 on 2026-09-17 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0184_alter_variantannotation_variant_class"),
        ("snpdb", "0268_cohort_phenotype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortTextPhenotype",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cohort",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_text_phenotype",
                        to="snpdb.cohort",
                    ),
                ),
                (
                    "phenotype_description",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.phenotypedescription",
                    ),
                ),
            ],
        ),
    ]
