# Generated by Django 6.1.1 on 2026-09-18 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0185_cohorttextphenotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinvar',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.clinvarversion'),
        ),
        migrations.AlterField(
            model_name='geneannotation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.geneannotationversion'),
        ),
        migrations.AlterField(
            model_name='humanproteinatlasannotation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.humanproteinatlasannotationversion'),
        ),
        migrations.AlterField(
            model_name='variantannotation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.variantannotationversion'),
        ),
        migrations.AlterField(
            model_name='variantgeneoverlap',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.variantannotationversion'),
        ),
        migrations.AlterField(
            model_name='varianttranscriptannotation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.variantannotationversion'),
        ),
    ]
