# Generated by Django 6.1.1 on 2026-09-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotation",
            "0186_alter_clinvar_version_alter_geneannotation_version_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versiondiffchangecountresult",
            name="version_diff",
        ),
        migrations.RemoveField(
            model_name="versiondifffromtoresult",
            name="version_diff",
        ),
        migrations.RemoveField(
            model_name="versiondiffchangecountresult",
            name="vg_column",
        ),
        migrations.RemoveField(
            model_name="versiondifffromtoresult",
            name="vg_column",
        ),
        migrations.DeleteModel(
            name="VariantAnnotationVersionDiff",
        ),
        migrations.DeleteModel(
            name="VersionDiff",
        ),
        migrations.DeleteModel(
            name="VersionDiffChangeCountResult",
        ),
        migrations.DeleteModel(
            name="VersionDiffFromToResult",
        ),
    ]
