# Generated by Django 6.1.1 on 2026-10-09 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0189_variantannotationversion_structural_variant_min_size'),
        ('ontology', '0028_backfill_phenotype_to_genes'),
    ]

    operations = [
        migrations.AddField(
            model_name='textphenotype',
            name='matcher_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textphenotype',
            name='ontology_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontology.ontologyversion'),
        ),
    ]
