# Generated by Django 6.1.1 on 2026-10-09 02:55

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0189_variantannotationversion_structural_variant_min_size"),
        ("ontology", "0028_backfill_phenotype_to_genes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhenotypeMatchVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("matcher_version", models.IntegerField()),
                (
                    "ontology_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ontology.ontologyversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="textphenotype",
            name="match_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="annotation.phenotypematchversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="phenotypematchversion",
            constraint=models.UniqueConstraint(
                fields=("matcher_version", "ontology_version"),
                name="phenotype_match_version_unique",
                nulls_distinct=False,
            ),
        ),
    ]
