# Generated by Django 6.1.1 on 2026-10-09

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _has_matched_phenotype_sentences(apps):
    """ Every sentence matched before #2131 has no match_version, so is stale """
    TextPhenotype = apps.get_model("annotation", "TextPhenotype")
    return TextPhenotype.objects.filter(processed=True).exists()


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0190_phenotypematchversion"),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["match_patient_phenotypes", "--stale"]),
                        note="Rematch phenotype sentences matched before the matcher was versioned (#2131)",
                        requires=["ontology-imported"],
                        test=_has_matched_phenotype_sentences),
    ]
