# Generated by Django 6.1.1 on 2026-10-09

from django.db import migrations

from manual.operations.manual_operations import ManualOperation

# cdot's 'fake-rna-<gene>' MT transcripts were skipped on import before #2139
IMPORT_CDOT_TASK_ID = ManualOperation.task_id_manage(["import_cdot_latest", "--annotation-consortium", "RefSeq",
                                                      "--force"])


def _has_refseq_variant_annotation(apps):
    VariantAnnotationVersion = apps.get_model("annotation", "VariantAnnotationVersion")
    return VariantAnnotationVersion.objects.filter(annotation_consortium="R").exists()


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0191_one_off_match_patient_phenotypes_stale"),
    ]

    operations = [
        ManualOperation(task_id=IMPORT_CDOT_TASK_ID,
                        note="Import cdot's mitochondrial 'fake-rna' RefSeq transcripts (#2139)",
                        test=_has_refseq_variant_annotation),
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_annotation_mitochondrial_transcripts"]),
                        note="Link RefSeq mitochondrial annotation to transcripts and store m.HGVS (#2139)",
                        requires=[f"after:{IMPORT_CDOT_TASK_ID}"],
                        test=_has_refseq_variant_annotation),
    ]
