# Generated by Django 6.1.1 on 2026-10-09

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _has_stale_phenotype_sentences(apps):
    """ Sentences matched before PHENOTYPE_MATCHER_VERSION 2 """
    TextPhenotype = apps.get_model("annotation", "TextPhenotype")
    return TextPhenotype.objects.filter(processed=True).exclude(match_version__matcher_version=2).exists()


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0191_one_off_match_patient_phenotypes_stale"),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["match_patient_phenotypes", "--stale"]),
                        note="Rematch phenotype sentences now fuzzy matching is one typo in one word (#2130)",
                        requires=["ontology-imported"],
                        test=_has_stale_phenotype_sentences),
    ]
