# Generated by Django 3.1 on 2020-09-29 06:11

from django.db import migrations

from library.django_utils import bulk_insert_class_data


def _initial_data(apps, schema_editor):
    NODE_GRAPH_TYPE = [
        {'name': 'Homozygosity percent',
         'required_column': 'observedvariant__zygosity',
         'graph_class': 'analysis.graphs.node_homozygosity_percent_graph.NodeHomozygosityPercentGraph',
         'description': 'Homozygosity percent'},
        {'name': 'Chromosome SNP Density',
         'required_column': 'id',
         'graph_class': 'analysis.graphs.chromosome_density_graph.ChromosomeDensityGraph',
         'description': 'Plot density of SNPs in 1Mb bins'},
        {'name': 'Allele Frequency Histogram',
         'required_column': 'observedvariant__allele_frequency',
         'graph_class': 'analysis.graphs.node_allele_frequency_histogram_graph.NodeAlleleFrequencyHistogramGraph',
         'description': 'AF Histogram (single input sample)'}
    ]

    bulk_insert_class_data(apps, "analysis", [("NodeGraphType", NODE_GRAPH_TYPE)])


class Migration(migrations.Migration):
    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_initial_data)
    ]
