# Generated by Django 3.1 on 2020-09-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
    ]
