# Generated by Django 3.1 on 2020-10-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_auto_20201001_1635'),
        ('analysis', '0003_auto_20201001_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalysisVariantClassification',
            new_name='AnalysisClassification',
        ),
    ]
