# Generated by Django 3.1 on 2020-10-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20201001_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistemplate',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='analysis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.analysis'),
        ),
        migrations.AlterField(
            model_name='analysistemplaterun',
            name='template_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='analysis.analysistemplateversion'),
        ),
    ]
