# Generated by Django 3.1 on 2020-10-26 01:36

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20201006_2209'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_analysis_permissions"]))
    ]
