# Generated by Django 3.1.3 on 2021-01-17 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0013_vcfallelesource'),
        ('analysis', '0011_genelistnodepanelapppanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisNodeAlleleSource',
            fields=[
                ('allelesource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snpdb.allelesource')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.analysisnode')),
            ],
            bases=('snpdb.allelesource',),
        ),
    ]
