# Generated by Django 3.1.3 on 2021-01-21 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0006_auto_20210121_1026'),
        ('analysis', '0012_analysisnodeallelesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhenotypeNodeOntologyTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.ontologyterm')),
                ('phenotype_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.phenotypenode')),
            ],
            options={
                'unique_together': {('phenotype_node', 'ontology_term')},
            },
        ),
    ]
