# Generated by Django 3.1 on 2021-01-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_one_off_move_ontology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenotypenodeomim',
            name='mim_morbid_alias',
        ),
        migrations.RemoveField(
            model_name='phenotypenodeomim',
            name='phenotype_node',
        ),
        migrations.DeleteModel(
            name='PhenotypeNodeHPO',
        ),
        migrations.DeleteModel(
            name='PhenotypeNodeOMIM',
        ),
    ]
