# Generated by Django 3.1.3 on 2021-02-11 04:08

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_has_variant_tags(apps):
    VariantTag = apps.get_model("analysis", "VariantTag")
    return VariantTag.objects.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_auto_20210121_2201'),
        ('snpdb', '0018_variantallelecollectionrecord_variantallelecollectionsource'),  # Need to run management cmd
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_liftover_existing_variant_tags"]),
                        test=_test_has_variant_tags)
    ]
