# Generated by Django 3.1.3 on 2021-02-23 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0021_delete_rvis'),
        ('analysis', '0017_auto_20210218_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelistnodepanelapppanel',
            name='panel_app_panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.panelapppanel'),
        ),
        migrations.AlterField(
            model_name='genelistnodepanelapppanel',
            name='panel_app_panel_local_cache_gene_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.panelapppanellocalcachegenelist'),
        ),
    ]
