# Generated by Django 3.1.3 on 2021-02-23 05:28

from django.db import migrations


def _one_off_gene_list_panel_app(apps, schema_editor):
    GeneListNodePanelAppPanel = apps.get_model("analysis", "GeneListNodePanelAppPanel")
    for glnpa in GeneListNodePanelAppPanel.objects.filter(panel_app_panel__isnull=True,
                                                          panel_app_panel_local_cache_gene_list__isnull=False):
        glnpa.panel_app_panel = glnpa.panel_app_panel_local_cache_gene_list.panel_app_panel
        glnpa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_auto_20210223_1557'),
    ]

    operations = [
        migrations.RunPython(_one_off_gene_list_panel_app)
    ]
