# Generated by Django 3.1.3 on 2021-02-23 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0021_delete_rvis'),
        ('analysis', '0019_one_off_gene_list_panel_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genelistnodepanelapppanel',
            name='panel_app_panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.panelapppanel'),
        ),
    ]
