# Generated by Django 3.1.3 on 2021-03-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_auto_20210223_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damagenode',
            old_name='min_damage_predictions',
            new_name='damage_predictions_min',
        ),
        migrations.RenameField(
            model_name='builtinfilternode',
            old_name='min_clinvar_stars',
            new_name='clinvar_stars_min',
        ),
        migrations.RemoveField(
            model_name='damagenode',
            name='accordion_panel',
        ),
        migrations.RemoveField(
            model_name='damagenode',
            name='fathmm_prediction',
        ),
        migrations.RemoveField(
            model_name='damagenode',
            name='mutation_assessor_prediction',
        ),
        migrations.RemoveField(
            model_name='damagenode',
            name='mutation_taster_prediction',
        ),
        migrations.RemoveField(
            model_name='damagenode',
            name='polyphen2_prediction',
        ),
        migrations.RemoveField(
            model_name='damagenode',
            name='remove_low_complexity_regions',
        ),
        migrations.RemoveField(
            model_name='damagenode',
            name='sift_prediction',
        ),
        migrations.AddField(
            model_name='builtinfilternode',
            name='cosmic_count_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='cadd_score_allow_null',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='cadd_score_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='cosmic_count_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='cosmic_count_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='damage_predictions_allow_null',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='damage_predictions_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='impact_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='protein_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='protein_domain_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='published_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='revel_score_allow_null',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='revel_score_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='splice_allow_null',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='splice_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='splice_required',
            field=models.BooleanField(default=False),
        ),
    ]
