# Generated by Django 3.1.3 on 2021-02-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_auto_20210223_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagenode',
            name='remove_low_complexity_regions',
        ),
        migrations.AddField(
            model_name='builtinfilternode',
            name='cosmic_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='cadd_filter',
            field=models.CharField(choices=[('O', 'OR'), ('L', 'Required (allow null)'), ('A', 'Required')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='damage_filter',
            field=models.CharField(choices=[('O', 'OR'), ('L', 'Required (allow null)'), ('A', 'Required')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='impact_filter',
            field=models.CharField(choices=[('O', 'OR'), ('A', 'Required')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='protein_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='protein_filter',
            field=models.CharField(choices=[('O', 'OR'), ('L', 'Required (allow null)'), ('A', 'Required')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='published_filter',
            field=models.CharField(choices=[('O', 'OR'), ('L', 'Required (allow null)'), ('A', 'Required')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='revel_filter',
            field=models.CharField(choices=[('O', 'OR'), ('L', 'Required (allow null)'), ('A', 'Required')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='splice_filter',
            field=models.CharField(choices=[('O', 'OR'), ('L', 'Required (allow null)'), ('A', 'Required')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='splice_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builtinfilternode',
            name='min_clinvar_stars',
            field=models.IntegerField(default=0),
        ),
    ]
