# Generated by Django 3.1.3 on 2021-02-26 06:53

from django.db import migrations


def _damage_node_changes(apps, schema_editor):
    DamageNode = apps.get_model("analysis", "DamageNode")

    # Move legacy DamageNodes to new config, keeping backwards compatibility of what they filter
    OR = "O"
    AND_NULL = "L"
    AND = "A"

    DamageNode.objects.filter(allow_null=True).update(cadd_filter=AND_NULL,
                                                      revel_filter=AND_NULL,
                                                      damage_filter=AND_NULL)

    DamageNode.objects.filter(allow_null=False).update(cadd_filter=AND,
                                                       revel_filter=AND,
                                                       damage_filter=AND)

    DamageNode.objects.filter(always_keep_splice_variants_regardless_of_impact=True).update(splice_min=0.5,
                                                                                            impact_filter=OR,
                                                                                            splice_filter=OR)


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_auto_20210226_1723'),
    ]

    operations = [
        migrations.RunPython(_damage_node_changes)
    ]
