# Generated by Django 3.1.3 on 2021-03-02 00:29

from django.db import migrations


def _one_off_damage_node_changes(apps, schema_editor):
    DamageNode = apps.get_model("analysis", "DamageNode")

    # Attempt to keep backwards compatibility
    DamageNode.objects.filter(allow_null=False).update(splice_allow_null=False,
                                                       cadd_score_allow_null=False,
                                                       revel_score_allow_null=False,
                                                       damage_predictions_allow_null=False)

    DamageNode.objects.filter(always_keep_splice_variants_regardless_of_impact=True).update(splice_min=0.5)

    # Used to be AND by default
    DamageNode.objects.filter(always_keep_splice_variants_regardless_of_impact=False,
                              impact_min__isnull=False).update(impact_required=True)
    DamageNode.objects.filter(cadd_score_min__isnull=False).update(cadd_score_required=True)
    DamageNode.objects.filter(revel_score_min__isnull=False).update(revel_score_required=True)
    DamageNode.objects.filter(damage_predictions_min__isnull=False).update(damage_predictions_required=True)


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_auto_20210301_1739'),
    ]

    operations = [
        migrations.RunPython(_one_off_damage_node_changes)
    ]
