# Generated by Django 3.1.3 on 2021-03-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_one_off_damage_node_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtinfilternode',
            name='clinvar_stars_min',
            field=models.IntegerField(default=0),
        ),
    ]
