# Generated by Django 3.1.3 on 2021-03-22 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0026_auto_20210319_1231'),
        ('analysis', '0023_auto_20210302_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagnode',
            name='mode',
            field=models.CharField(choices=[('P', 'Parent'), ('T', 'This Analysis'), ('L', 'All Analyses')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='TagNodeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.tag')),
                ('tag_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.tagnode')),
            ],
            options={
                'unique_together': {('tag_node', 'tag')},
            },
        ),
    ]
