# Generated by Django 3.1.3 on 2021-03-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0026_auto_20210322_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeallelefrequencyrange',
            name='max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nodeallelefrequencyrange',
            name='min',
            field=models.FloatField(),
        ),
    ]
