# Generated by Django 3.1.3 on 2021-03-30 23:32

from django.db import migrations
from django.db.models import F, Value


def _one_off_allele_frequency_filter_percent_to_unit(apps, _schema_editor):
    NodeAlleleFrequencyRange = apps.get_model("analysis", "NodeAlleleFrequencyRange")
    NodeAlleleFrequencyRange.objects.all().update(min=F("min") / Value(100.0),
                                                  max=F("max") / Value(100.0))


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_auto_20210331_1002'),
    ]

    operations = [
        migrations.RunPython(_one_off_allele_frequency_filter_percent_to_unit)
    ]
