# Generated by Django 3.1.3 on 2021-03-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0028_one_off_allele_frequency_filter_percent_to_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationsnode',
            name='benign',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationsnode',
            name='likely_benign',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationsnode',
            name='likely_pathogenic',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationsnode',
            name='other',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationsnode',
            name='pathogenic',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationsnode',
            name='vus',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
