# Generated by Django 3.1.3 on 2021-03-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0030_one_off_classification_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationsnode',
            name='clinical_significance',
        ),
        migrations.RemoveField(
            model_name='classificationsnode',
            name='comparison',
        ),
    ]
