# Generated by Django 3.1.3 on 2021-04-09 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0030_one_off_fix_cohort_sample_order'),
        ('analysis', '0031_auto_20210331_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttag',
            name='genome_build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.genomebuild'),
        ),
        migrations.AddField(
            model_name='varianttag',
            name='location',
            field=models.CharField(choices=[('A', 'Analysis'), ('E', 'External Import'), ('G', 'Gene Page'), ('V', 'Variant Details')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='varianttag',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.analysis'),
        ),
    ]
