# Generated by Django 3.2.1 on 2021-05-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0038_auto_20210506_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genelistnode',
            name='has_gene_coverage',
        ),
    ]
