# Generated by Django 3.2.1 on 2021-05-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0040_genelistnode_has_gene_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplenode',
            name='has_gene_coverage',
            field=models.BooleanField(null=True),
        ),
    ]
