# Generated by Django 3.2.1 on 2021-05-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0041_samplenode_has_gene_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagnode',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagnode',
            name='parent_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tagnode',
            name='mode',
            field=models.CharField(choices=[('T', 'This Analysis'), ('L', 'All Tags')], default='T', max_length=1),
        ),
    ]
