# Generated by Django 3.2.1 on 2021-05-12 05:27

from django.db import migrations


def _one_off_tags_node_new_config(apps, _schema_editor):
    TagNode = apps.get_model("analysis", "TagNode")
    PARENT = 'P'
    THIS_ANALYSIS = 'T'
    ALL_TAGS = 'L'

    # Parent input defaults to True
    TagNode.objects.filter(mode__in=[THIS_ANALYSIS, ALL_TAGS]).update(parent_input=False)
    TagNode.objects.filter(mode=PARENT).update(mode=THIS_ANALYSIS, parent_input=True)


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0042_auto_20210512_1457'),
    ]

    operations = [
        migrations.RunPython(_one_off_tags_node_new_config)
    ]
