# Generated by Django 3.2.1 on 2021-05-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0043_one_off_tags_node_new_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zygositynode',
            name='zygosity',
            field=models.CharField(choices=[('R', 'REF'), ('E', 'HET'), ('O', 'HOM_ALT'), ('U', '?'), ('M', 'Multiple hits in gene')], max_length=1, null=True),
        ),
    ]
