# Generated by Django 3.2.1 on 2021-05-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0046_auto_20210519_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagenode',
            name='impact_min',
            field=models.CharField(blank=True, choices=[('1', 'MODIFIER'), ('2', 'LOW'), ('3', 'MODERATE'), ('*', 'MODERATE*'), ('4', 'HIGH')], max_length=1, null=True),
        ),
    ]
