# Generated by Django 3.1.3 on 2021-06-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0047_alter_damagenode_impact_min'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeHelp',
        ),
    ]
