# Generated by Django 3.2.1 on 2021-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0048_delete_nodehelp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedvarianttag',
            name='analysis_name',
            field=models.TextField(null=True),
        ),
    ]
