# Generated by Django 3.2.4 on 2021-12-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0052_alter_analysis_canonical_transcript_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='node_queryset_filter_contigs',
            field=models.BooleanField(default=False),
        ),
    ]
