# Generated by Django 3.2.4 on 2021-12-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0053_analysis_node_queryset_filter_contigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationnode',
            name='show_gnomad_filtered',
            field=models.BooleanField(default=True),
        ),
    ]
