# Generated by Django 3.2.6 on 2022-01-04 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0009_auto_20210316_1041'),
        ('patients', '0001_initial'),
        ('analysis', '0054_populationnode_show_gnomad_filtered'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOINode',
            fields=[
                ('analysisnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analysis.analysisnode')),
                ('min_classification', models.CharField(choices=[('1', 'Refuted Evidence'), ('2', 'No Known Disease Relationship'), ('3', 'Animal Model Only'), ('4', 'Disputed Evidence'), ('5', 'Limited'), ('6', 'Supportive'), ('7', 'Moderate'), ('8', 'Strong'), ('9', 'Definitive')], default='7', max_length=1)),
                ('min_date', models.DateField(blank=True, null=True)),
                ('max_date', models.DateField(blank=True, null=True)),
                ('accordion_panel', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=('analysis.analysisnode',),
        ),
        migrations.CreateModel(
            name='MOINodeSubmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter', models.TextField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.moinode')),
            ],
            options={
                'unique_together': {('node', 'submitter')},
            },
        ),
        migrations.CreateModel(
            name='MOINodeOntologyTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.moinode')),
                ('ontology_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.ontologyterm')),
            ],
            options={
                'unique_together': {('node', 'ontology_term')},
            },
        ),
        migrations.CreateModel(
            name='MOINodeModeOfInheritance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_inheritance', models.TextField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.moinode')),
            ],
            options={
                'unique_together': {('node', 'mode_of_inheritance')},
            },
        ),
    ]
