# Generated by Django 3.2.4 on 2022-02-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0055_moinode_moinodemodeofinheritance_moinodeontologyterm_moinodesubmitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedvarianttag',
            name='gene_symbol_string',
            field=models.TextField(null=True),
        ),
    ]
