# Generated by Django 3.2.4 on 2022-02-08 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0057_new_gene_annotation_columns'),
        ('analysis', '0056_alter_importedvarianttag_gene_symbol_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttag',
            name='allele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='snpdb.allele'),
        ),
    ]
