# Generated by Django 4.0.2 on 2022-02-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0058_one_off_set_variant_tag_allele'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importedvarianttag',
            old_name='user_name',
            new_name='username',
        ),
    ]
