# Generated by Django 4.0.2 on 2022-02-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0059_rename_user_name_importedvarianttag_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagenode',
            name='allow_null',
        ),
        migrations.RemoveField(
            model_name='damagenode',
            name='always_keep_splice_variants_regardless_of_impact',
        ),
    ]
