# Generated by Django 4.0.2 on 2022-02-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0061_one_off_proband_het_to_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trionode',
            name='inheritance',
            field=models.CharField(choices=[('R', 'Recessive'), ('C', 'C. Het'), ('D', 'Dominant'), ('N', 'Denovo'), ('X', 'X-Linked Recessive')], default='R', max_length=1),
        ),
    ]
