# Generated by Django 4.0.3 on 2022-04-20 03:54

from django.db import migrations


def _one_off_fix_filter_node_columns(apps, _schema_editor):
    FilterNodeItem = apps.get_model("analysis", "FilterNodeItem")
    if not FilterNodeItem.objects.exists():
        return

    CHANGE_COLUMNS = {
        'variantannotation__gene__ensemblgeneannotation__omim_id': 'variantannotation__transcript_version__gene_version__hgnc__omim_ids',
        'variantannotation__gene__ensemblgeneannotation__omim_phenotypes': 'variantannotation__gene__geneannotation__omim_terms',
        'variantannotation__gene__ensemblgeneannotation__tissue_specificity_from_uniprotkb': 'variantannotation__uniprot__tissue_specificity',
        'variantannotation__gene__ensemblgeneannotation__gene_family_tag': 'variantannotation__transcript_version__gene_version__hgnc__gene_group_ids',
        'variantannotation__gene__ensemblgeneannotation__hgnc_symbol': 'variantannotation__transcript_version__gene_version__hgnc__gene_symbol__symbol',
    }
    REMOVE_COLUMNS = [
        # hom/het count are now queryset annotations, thus can't be searched (as that requires being a model field)
        'hom_count',
        'het_count',
        'variantannotation__gene__ensemblgeneannotation__in_cancer_gene_census',  # This was removed
    ]

    for old_column, new_column in CHANGE_COLUMNS.items():
        FilterNodeItem.objects.filter(field=old_column).update(field=new_column)

    _, deleted = FilterNodeItem.objects.filter(field__in=REMOVE_COLUMNS).delete()
    if deleted:
        print(f"Deleted: {deleted} records")


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0062_alter_trionode_inheritance'),
    ]

    operations = [
        migrations.RunPython(_one_off_fix_filter_node_columns)
    ]
