# Generated by Django 4.0.3 on 2022-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0063_one_off_fix_filter_node_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuenode',
            name='group_operation',
            field=models.CharField(choices=[('L', 'All'), ('Y', 'Any')], default='L', max_length=1),
        ),
    ]
