# Generated by Django 4.0.3 on 2022-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0065_one_off_set_variant_tag_allele_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagenode',
            name='aloft',
            field=models.CharField(blank=True, choices=[('a', 'Recessive / Dominant'), ('r', 'Recessive'), ('d', 'Dominant')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='aloft_allow_null',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='aloft_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='bayesdel_noaf_rankscore_allow_null',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='bayesdel_noaf_rankscore_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='bayesdel_noaf_rankscore_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='cadd_raw_rankscore_allow_null',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='cadd_raw_rankscore_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='cadd_raw_rankscore_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='clinpred_rankscore_allow_null',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='clinpred_rankscore_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='clinpred_rankscore_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='metalr_rankscore_allow_null',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='metalr_rankscore_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='metalr_rankscore_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='nmd_escaping_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='nmd_escaping_variant_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='revel_rankscore_allow_null',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='revel_rankscore_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='revel_rankscore_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='vest4_rankscore_allow_null',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='vest4_rankscore_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagenode',
            name='vest4_rankscore_required',
            field=models.BooleanField(default=False),
        ),
    ]
