# Generated by Django 4.0.4 on 2022-07-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0066_damagenode_aloft_damagenode_aloft_allow_null_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'Analysis', 'verbose_name_plural': 'Analyses'},
        ),
    ]
