# Generated by Django 4.1.3 on 2023-01-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0068_default_analysis_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genelistnodepanelapppanel',
            name='panel_app_panel_local_cache_gene_list',
        ),
        migrations.AddField(
            model_name='genelistnode',
            name='min_panel_app_confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Intermediate'), ('3', 'High')], default='1', max_length=1),
        ),
    ]
