# Generated by Django 4.1.3 on 2023-02-02 02:10

from django.db import migrations
from manual.operations.manual_operations import ManualOperation

def _might_have_obsolete_node_cache(apps):
    AnalysisNode = apps.get_model("analysis", "AnalysisNode")
    return AnalysisNode.objects.filter(parents_should_cache=True).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0070_genelistnodepanelapppanel_panel_app_panel_local_cache'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["fix_delete_unused_node_cache"]),
                        test=_might_have_obsolete_node_cache),

    ]
