# Generated by Django 4.1.3 on 2023-02-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0071_one_off_fix_delete_unused_node_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisnode',
            name='parents_should_cache',
        ),
    ]
