# Generated by Django 4.1.3 on 2023-04-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0097_new_column_internally_classified_labs'),
        ('analysis', '0072_remove_analysisnode_parents_should_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationsNodeLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.lab')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.classificationsnode')),
            ],
        ),
    ]
