# Generated by Django 4.1.5 on 2023-06-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0073_classificationsnodelab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intersectionnode',
            old_name='hgvs_name',
            new_name='hgvs_string',
        ),
    ]
