# Generated by Django 4.1.4 on 2023-09-15 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0074_rename_hgvs_name_intersectionnode_hgvs_string"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExpressionNode",
        ),
    ]
