# Generated by Django 4.1.4 on 2023-10-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0075_delete_expressionnode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allvariantsnode",
            old_name="maximum_count",
            new_name="max_het_or_hom_count",
        ),
        migrations.RenameField(
            model_name="allvariantsnode",
            old_name="minimum_count",
            new_name="min_het_or_hom_count",
        ),
        migrations.RenameField(
            model_name="cohortnode",
            old_name="maximum_count",
            new_name="max_het_or_hom_count",
        ),
        migrations.RenameField(
            model_name="cohortnode",
            old_name="minimum_count",
            new_name="min_het_or_hom_count",
        ),
        migrations.AddField(
            model_name="allvariantsnode",
            name="max_unk_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allvariantsnode",
            name="min_unk_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cohortnode",
            name="max_unk_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cohortnode",
            name="min_unk_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
