# Generated by Django 4.2.2 on 2023-11-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0076_rename_maximum_count_allvariantsnode_max_het_or_hom_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationnodegnomadpopulation',
            name='population',
            field=models.CharField(choices=[('AFR', 'African/African American'), ('ASJ', 'Ashkenazi Jewish'), ('EAS', 'East Asian'), ('FIN', 'Finnish'), ('AMR', 'Latino / Mixed Amerindian'), ('MID', 'Middle Eastern'), ('NFE', 'Non-Finnish European'), ('OTH', 'Other'), ('SAS', 'South Asian')], max_length=3),
        ),
    ]
