# Generated by Django 4.2.10 on 2024-03-07 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snpdb", "0120_one_off_fix_symbolic_variants"),
        ("analysis", "0078_damagenode_alphamissense_rankscore_allow_null_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortAnalysisTemplateRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_template_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.analysistemplaterun",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="snpdb.cohort"
                    ),
                ),
            ],
            options={
                "unique_together": {("cohort", "analysis_template_run")},
            },
        ),
    ]
