# Generated by Django 4.2.10 on 2024-03-07 08:09

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_for_existing_templates(apps):
    AnalysisTemplate = apps.get_model("analysis", "AnalysisTemplate")
    return AnalysisTemplate.objects.all().exists()


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0079_cohortanalysistemplaterun"),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["analysis_create_default_templates"]),
                        test=_test_for_existing_templates),
    ]
