# Generated by Django 4.2.10 on 2024-03-14 00:39
from django.conf import settings
from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _has_old_sample_tab_auto_analysis(apps):
    AnalysisTemplate = apps.get_model("analysis", "AnalysisTemplate")
    SampleNode = apps.get_model("analysis", "SampleNode")

    if analysis_template := AnalysisTemplate.objects.filter(name=settings.ANALYSIS_TEMPLATES_AUTO_SAMPLE).first():
        if sample_node := SampleNode.objects.filter(analysis=analysis_template.analysis, name='All variants').first():
            return not all([sample_node.zygosity_ref, sample_node.zygosity_unk, sample_node.output_node])
    return False


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0080_add_new_templates'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["one_off_fix_sample_tab_auto_analysis_template"]),
                        test=_has_old_sample_tab_auto_analysis),
    ]
