# Generated by Django 4.2.10 on 2024-05-10 06:21
import logging

from django.db import migrations


def _one_off_karyomapping_gene_to_symbol(apps, _schema_editor):
    GenomeBuild = apps.get_model("snpdb", "GenomeBuild")
    KaryomappingGene = apps.get_model("analysis", "KaryomappingGene")

    records = []
    for genome_build_name in ["GRCh37", "GRCh38"]:
        genome_build = GenomeBuild.objects.get(name=genome_build_name)

        for kg in KaryomappingGene.objects.filter(karyomapping_analysis__trio__cohort__genome_build=genome_build):
            gene_version = kg.gene.geneversion_set.filter(genome_build=genome_build).order_by("-version").first()
            if gene_version is None:
                raise ValueError(f"Couldn't obtain latest gene version for '{kg.gene}'")
            kg.gene_symbol = gene_version.gene_symbol
            records.append(kg)

    if records:
        logging.info("Updating %d KaryomappingGene genes to symbols", len(records))
        KaryomappingGene.objects.bulk_update(records, ["gene_symbol"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0082_karyomappinggene_gene_symbol'),
    ]

    operations = [
        migrations.RunPython(_one_off_karyomapping_gene_to_symbol)
    ]
