# Generated by Django 4.2.10 on 2024-05-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0071_rename_oe_lof_gnomadgeneconstraint_lof_oe_and_more'),
        ('analysis', '0083_one_off_karyomapping_gene_to_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyomappinggene',
            name='gene',
        ),
        migrations.AlterField(
            model_name='karyomappinggene',
            name='gene_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.genesymbol'),
        ),
    ]
