# Generated by Django 4.2.10 on 2024-05-22 06:52

from django.db import migrations
from django.db.models import Subquery, OuterRef, F


def _one_off_delete_redundant_karyomapping_genes(apps, _schema_editor):
    KaryomappingGene = apps.get_model("analysis", "KaryomappingGene")
    qs = KaryomappingGene.objects.values('karyomapping_analysis', 'gene_symbol', "upstream_kb", "downstream_kb")
    qs = qs.annotate(min_id=Subquery(
            KaryomappingGene.objects.filter(
                karyomapping_analysis=OuterRef('karyomapping_analysis'),
                gene_symbol=OuterRef('gene_symbol'),
                upstream_kb=OuterRef('upstream_kb'),
                downstream_kb=OuterRef('downstream_kb'),
            ).order_by('id').values('id')[:1]
    ))
    dupes = qs.exclude(pk=F("min_id")).values_list("pk", flat=True)
    KaryomappingGene.objects.filter(pk__in=dupes).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0085_allvariantsnode_complex_subsitution_and_more"),
    ]

    operations = [
        migrations.RunPython(_one_off_delete_redundant_karyomapping_genes)
    ]
