# Generated by Django 4.2.10 on 2024-05-22 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genes", "0071_rename_oe_lof_gnomadgeneconstraint_lof_oe_and_more"),
        ("analysis", "0086_one_off_delete_redundant_karyomapping_genes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="karyomappinggene",
            unique_together={
                ("karyomapping_analysis", "gene_symbol", "upstream_kb", "downstream_kb")
            },
        ),
    ]
