# Generated by Django 4.2.11 on 2024-11-27 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0087_alter_karyomappinggene_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConservationNode",
            fields=[
                (
                    "analysisnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="analysis.analysisnode",
                    ),
                ),
                ("any_scaled_min", models.FloatField(default=0.0)),
                ("gerp_pp_rs", models.FloatField(default=0.0)),
                ("phylop_30_way_mammalian", models.FloatField(blank=True, default=0.0)),
                ("phylop_46_way_mammalian", models.FloatField(blank=True, default=0.0)),
                ("phylop_100_way_vertebrate", models.FloatField(default=0.0)),
                (
                    "phastcons_30_way_mammalian",
                    models.FloatField(blank=True, default=0.0),
                ),
                (
                    "phastcons_46_way_mammalian",
                    models.FloatField(blank=True, default=0.0),
                ),
                ("phastcons_100_way_vertebrate", models.FloatField(default=0.0)),
                ("allow_null", models.BooleanField(blank=True, default=False)),
                (
                    "use_individual_sliders",
                    models.BooleanField(blank=True, default=False),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("analysis.analysisnode",),
        ),
    ]
