# Generated by Django 4.2.11 on 2024-11-27 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0088_conservationnode"),
        ("analysis", "0088_one_off_hide_auto_analysis_templates"),
    ]

    operations = []
