# Generated by Django 4.2.9 on 2024-12-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0089_merge_20241127_2356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conservationnode",
            name="phastcons_100_way_vertebrate",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name="conservationnode",
            name="phylop_100_way_vertebrate",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
