# Generated by Django 4.2.20 on 2025-07-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0090_alter_conservationnode_phastcons_100_way_vertebrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='grid_sample_label_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
