# Generated by Django 4.2.15 on 2025-07-21 05:35

from django.db import migrations
from django.db.models.aggregates import Min
from django.db.models.expressions import F


def _one_off_shift_analysis_nodes(apps, _schema_editor):
    Analysis = apps.get_model("analysis", "Analysis")
    AnalysisNode = apps.get_model("analysis", "AnalysisNode")
    MIN_Y = 35

    modified_analyses = 0
    modified_nodes = 0
    for analysis in Analysis.objects.filter(analysisnode__visible=True, analysisnode__y__lt=MIN_Y):
        nodes_qs = AnalysisNode.objects.filter(analysis=analysis, visible=True)
        data = nodes_qs.filter(y__lt=MIN_Y).aggregate(min_y=Min("y"))
        if min_y := data.get("min_y"):
            shift = MIN_Y - min_y
            num_nodes = nodes_qs.update(y=F("y") + shift)
            modified_nodes += num_nodes
            modified_analyses += 1

    if modified_analyses > 0:
        print(f"Modified {modified_nodes} nodes in {modified_analyses} analyses")


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0091_analysis_grid_sample_label_template"),
    ]

    operations = [
        migrations.RunPython(_one_off_shift_analysis_nodes)
    ]
