# Generated by Django 5.2.8 on 2025-11-13 08:04

import django.db.models.deletion
import django.utils.timezone
import library.django_utils.guardian_permissions_mixin
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0092_one_off_shift_analysis_nodes"),
        ("annotation", "0128_genepubmedcount_delete_genesymbolpubmedcount"),
        ("classification", "0160_one_off_run_fix_allele_info_liftover"),
        ("snpdb", "0171_sample_research_consent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="analysis_horizontal_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CandidateSearchVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("R", "Reanalysis - new annotation"),
                            ("S", "Cross Sample Classification"),
                            ("E", "Classification Evidence Update"),
                        ],
                        max_length=1,
                    ),
                ),
                ("code_version", models.IntegerField()),
            ],
            options={
                "unique_together": {("search_type", "code_version")},
            },
        ),
        migrations.CreateModel(
            name="CandidateSearchRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("config_snapshot", models.JSONField(default=dict)),
                ("git_hash", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.candidatesearchversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                library.django_utils.guardian_permissions_mixin.GuardianPermissionsAutoInitialSaveMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ClassificationEvidenceUpdateCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("O", "OPEN"),
                            ("R", "RESOLVED"),
                            ("D", "HIDDEN"),
                            ("L", "HIGHLIGHTED"),
                        ],
                        default="O",
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("reviewer_comment", models.TextField(blank=True, null=True)),
                (
                    "annotation_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.annotationversion",
                    ),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classification.classification",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.candidatesearchrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CrossSampleClassificationCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("O", "OPEN"),
                            ("R", "RESOLVED"),
                            ("D", "HIDDEN"),
                            ("L", "HIGHLIGHTED"),
                        ],
                        default="O",
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("reviewer_comment", models.TextField(blank=True, null=True)),
                (
                    "zygosity",
                    models.CharField(
                        choices=[
                            ("R", "REF"),
                            ("E", "HET"),
                            ("O", "HOM_ALT"),
                            ("U", "?"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classification.classification",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="snpdb.sample"
                    ),
                ),
                (
                    "search_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.candidatesearchrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReanalysisCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("O", "OPEN"),
                            ("R", "RESOLVED"),
                            ("D", "HIDDEN"),
                            ("L", "HIGHLIGHTED"),
                        ],
                        default="O",
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("reviewer_comment", models.TextField(blank=True, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.analysis",
                    ),
                ),
                (
                    "annotation_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.annotationversion",
                    ),
                ),
                (
                    "clinvar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.clinvar",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.candidatesearchrun",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.variant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
