# Generated by Django 5.2.8 on 2025-11-17 01:14

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0093_analysis_analysis_horizontal_mode_and_more"),
        ("annotation", "0128_genepubmedcount_delete_genesymbolpubmedcount"),
        ("classification", "0160_one_off_run_fix_allele_info_liftover"),
        ("snpdb", "0171_sample_research_consent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crosssampleclassificationcandidate",
            name="classification",
        ),
        migrations.RemoveField(
            model_name="crosssampleclassificationcandidate",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="crosssampleclassificationcandidate",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="crosssampleclassificationcandidate",
            name="search_run",
        ),
        migrations.RemoveField(
            model_name="reanalysiscandidate",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="reanalysiscandidate",
            name="annotation_version",
        ),
        migrations.RemoveField(
            model_name="reanalysiscandidate",
            name="clinvar",
        ),
        migrations.RemoveField(
            model_name="reanalysiscandidate",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="reanalysiscandidate",
            name="search_run",
        ),
        migrations.RemoveField(
            model_name="reanalysiscandidate",
            name="variant",
        ),
        migrations.AddField(
            model_name="candidatesearchrun",
            name="celery_task",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="candidatesearchversion",
            name="celery_task_name",
            field=models.TextField(default="NOT_REAL_CELERY_TASK"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidatesearchversion",
            name="methods",
            field=models.TextField(default="NOT_REAL_METHODS"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("O", "OPEN"),
                            ("R", "RESOLVED"),
                            ("D", "HIDDEN"),
                            ("L", "HIGHLIGHTED"),
                        ],
                        default="O",
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("reviewer_comment", models.TextField(blank=True, null=True)),
                (
                    "zygosity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("R", "REF"),
                            ("E", "HET"),
                            ("O", "HOM_ALT"),
                            ("U", "?"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.analysis",
                    ),
                ),
                (
                    "annotation_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.annotationversion",
                    ),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classification.classification",
                    ),
                ),
                (
                    "clinvar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.clinvar",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.sample",
                    ),
                ),
                (
                    "search_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.candidatesearchrun",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snpdb.variant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.DeleteModel(
            name="ClassificationEvidenceUpdateCandidate",
        ),
        migrations.DeleteModel(
            name="CrossSampleClassificationCandidate",
        ),
        migrations.DeleteModel(
            name="ReanalysisCandidate",
        ),
    ]
