# Generated by Django 5.2.8 on 2025-11-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "analysis",
            "0094_remove_crosssampleclassificationcandidate_classification_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="clinvar",
        ),
    ]
