# Generated by Django 5.2.8 on 2026-01-29 01:13

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0095_remove_candidate_clinvar"),
        ("seqauto", "0034_alter_qcgenecoverage_gene_coverage_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoLaunchAnalysisTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("sample_regex", models.TextField(blank=True, null=True)),
                (
                    "enrichment_kit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seqauto.enrichmentkit",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.analysistemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("template", "enrichment_kit", "sample_regex")},
            },
        ),
    ]
