# Generated by Django 6.0.3 on 2026-03-30 02:17

import analysis.models.nodes.cohort_mixin
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0097_sapath_auto_launch_analysis_templates"),
        ("snpdb", "0174_add_quad"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuadNode",
            fields=[
                (
                    "analysisnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="analysis.analysisnode",
                    ),
                ),
                ("min_ad", models.IntegerField(default=0)),
                ("min_dp", models.IntegerField(default=0)),
                ("min_gq", models.IntegerField(default=0)),
                ("max_pl", models.IntegerField(blank=True, null=True)),
                (
                    "min_ad_op",
                    models.CharField(
                        choices=[("L", "All"), ("Y", "Any")], default="Y", max_length=1
                    ),
                ),
                (
                    "min_dp_op",
                    models.CharField(
                        choices=[("L", "All"), ("Y", "Any")], default="Y", max_length=1
                    ),
                ),
                (
                    "min_gq_op",
                    models.CharField(
                        choices=[("L", "All"), ("Y", "Any")], default="Y", max_length=1
                    ),
                ),
                (
                    "max_pl_op",
                    models.CharField(
                        choices=[("L", "All"), ("Y", "Any")], default="Y", max_length=1
                    ),
                ),
                (
                    "inheritance",
                    models.CharField(
                        choices=[
                            ("R", "Recessive"),
                            ("C", "C. Het"),
                            ("D", "Dominant"),
                            ("N", "Denovo"),
                            ("X", "X-Linked Recessive"),
                        ],
                        default="R",
                        max_length=1,
                    ),
                ),
                ("require_zygosity", models.BooleanField(default=True)),
                (
                    "quad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="snpdb.quad",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                analysis.models.nodes.cohort_mixin.CohortMixin,
                "analysis.analysisnode",
            ),
        ),
    ]
