# Generated by Django 6.0.3 on 2026-05-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0098_add_quad_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagenode",
            name="alphamissense_pred",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B", "benign"),
                    ("b", "likely_benign"),
                    ("a", "ambiguous"),
                    ("p", "likely_pathogenic"),
                    ("P", "pathogenic"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="alphamissense_pred_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="alphamissense_pred_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="alphamissense_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="alphamissense_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="alphamissense_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="bayesdel_noaf_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="bayesdel_noaf_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="bayesdel_noaf_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="cadd_phred_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="cadd_phred_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="cadd_phred_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="clinpred_pred",
            field=models.CharField(
                blank=True,
                choices=[("T", "Tolerated"), ("D", "Damaging")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="clinpred_pred_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="clinpred_pred_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="clinpred_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="clinpred_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="clinpred_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="metarnn_pred",
            field=models.CharField(
                blank=True,
                choices=[("T", "Tolerated"), ("D", "Damaging")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="metarnn_pred_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="metarnn_pred_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="metarnn_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="metarnn_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="metarnn_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="mpc_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="mpc_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="mpc_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="mutpred2_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="mutpred2_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="mutpred2_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="primateai_pred",
            field=models.CharField(
                blank=True,
                choices=[("T", "Tolerated"), ("D", "Damaging")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="primateai_pred_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="primateai_pred_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="primateai_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="primateai_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="primateai_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="varity_er_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="varity_er_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="varity_er_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="varity_r_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="varity_r_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="varity_r_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="vest4_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="vest4_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="vest4_score_required",
            field=models.BooleanField(default=False),
        ),
    ]
