# Generated by Django 6.0.3 on 2026-05-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0099_damagenode_alphamissense_pred_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="analysis_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Singleton"),
                    ("C", "Cohort"),
                    ("T", "Trio"),
                    ("Q", "Quad"),
                    ("P", "Pedigree"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
