# Generated by Django 6.0.3 on 2026-05-22 05:33

import analysis.models.nodes.analysis_node
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0101_nodecount_created_nodecount_modified_and_more"),
        ("snpdb", "0183_lab_research"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllVariantsNodeContig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "all_variants_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.allvariantsnode",
                    ),
                ),
                (
                    "contig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="snpdb.contig"
                    ),
                ),
            ],
            options={
                "unique_together": {("all_variants_node", "contig")},
            },
            bases=(analysis.models.nodes.analysis_node.NodeAuditLogMixin, models.Model),
        ),
    ]
