# Generated by Django 6.0.3 on 2026-05-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0103_alter_quadnode_inheritance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quadnode",
            name="inheritance",
            field=models.CharField(
                choices=[
                    ("R", "Recessive"),
                    ("A", "All Recessive (AR + XLR)"),
                    ("C", "C. Het"),
                    ("D", "Dominant"),
                    ("N", "Denovo"),
                    ("X", "X-Linked Recessive"),
                    ("Y", "Any Affected (variant in ≥1 affected)"),
                ],
                default="R",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="trionode",
            name="inheritance",
            field=models.CharField(
                choices=[
                    ("R", "Recessive"),
                    ("A", "All Recessive (AR + XLR)"),
                    ("C", "C. Het"),
                    ("D", "Dominant"),
                    ("N", "Denovo"),
                    ("X", "X-Linked Recessive"),
                    ("Y", "Any Affected (variant in ≥1 affected)"),
                ],
                default="R",
                max_length=1,
            ),
        ),
    ]
