# Generated by Django 6.0.5 on 2026-06-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0105_nodetask_lease_on_node_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="populationnode",
            name="af_1kg",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="populationnode",
            name="af_uk10k",
            field=models.BooleanField(default=False),
        ),
    ]
