# Generated by Django 6.0.5 on 2026-06-11 14:16

import analysis.models.nodes.analysis_node
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0107_quadnode_require_parent_sibling_zygosity"),
        ("snpdb", "0189_jobscontrol"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntersectionNodeContig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="snpdb.contig"
                    ),
                ),
                (
                    "intersection_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.intersectionnode",
                    ),
                ),
            ],
            options={
                "unique_together": {("intersection_node", "contig")},
            },
            bases=(analysis.models.nodes.analysis_node.NodeAuditLogMixin, models.Model),
        ),
    ]
