# Generated by Django 6.0.6 on 2026-08-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0109_gate_default_templates_on_annotation_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagenode",
            name="ptc_nmd_escaping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="ptc_nmd_escaping_required",
            field=models.BooleanField(default=False),
        ),
    ]
