# Generated by Django 6.1 on 2026-08-12 06:16

import analysis.models.nodes.analysis_node
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0110_damagenode_ptc_nmd_escaping'),
        ('patients', '0017_specimenmeasure'),
        ('snpdb', '0205_sample_extraction_match_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplenode',
            name='extraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.extraction'),
        ),
        migrations.AddField(
            model_name='samplenode',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='samplenode',
            name='source_level',
            field=models.CharField(choices=[('S', 'Sample'), ('E', 'Extraction'), ('P', 'Specimen'), ('T', 'Patient')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='samplenode',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.specimen'),
        ),
        migrations.CreateModel(
            name='SampleNodeSampleThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_ad', models.IntegerField(default=0)),
                ('min_dp', models.IntegerField(default=0)),
                ('min_gq', models.IntegerField(default=0)),
                ('max_pl', models.IntegerField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.samplenode')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpdb.sample')),
            ],
            options={
                'unique_together': {('node', 'sample')},
            },
            bases=(analysis.models.nodes.analysis_node.NodeAuditLogMixin, models.Model),
        ),
    ]
