# Generated by Django 5.2.5 on 2026-08-18 10:00

from django.db import migrations, models


def _one_off_tag_node_input(apps, _schema_editor):
    """ parent_input/exclude were 2 booleans encoding 3 valid states - collapse into a single choice """
    TagNode = apps.get_model("analysis", "TagNode")
    TAGGED_VARIANTS = 'T'
    PARENT_TAGGED = 'I'
    PARENT_NOT_TAGGED = 'E'

    TagNode.objects.filter(parent_input=False).update(node_input=TAGGED_VARIANTS)
    TagNode.objects.filter(parent_input=True, exclude=False).update(node_input=PARENT_TAGGED)
    TagNode.objects.filter(parent_input=True, exclude=True).update(node_input=PARENT_NOT_TAGGED)


def _one_off_tag_node_input_reverse(apps, _schema_editor):
    TagNode = apps.get_model("analysis", "TagNode")
    TAGGED_VARIANTS = 'T'
    PARENT_NOT_TAGGED = 'E'

    TagNode.objects.update(parent_input=True, exclude=False)
    TagNode.objects.filter(node_input=TAGGED_VARIANTS).update(parent_input=False)
    TagNode.objects.filter(node_input=PARENT_NOT_TAGGED).update(exclude=True)


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0111_sample_node_source_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagnode',
            name='node_input',
            field=models.CharField(choices=[('T', 'Tagged variants (no parent)'),
                                            ('I', 'Parent variants that ARE tagged'),
                                            ('E', 'Parent variants that are NOT tagged')],
                                   default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='tagnode',
            name='mode',
            field=models.CharField(choices=[('T', 'This analysis'), ('L', 'All analyses')],
                                   default='T', max_length=1),
        ),
        migrations.RunPython(_one_off_tag_node_input, _one_off_tag_node_input_reverse),
        migrations.RemoveField(
            model_name='tagnode',
            name='parent_input',
        ),
        migrations.RemoveField(
            model_name='tagnode',
            name='exclude',
        ),
    ]
