# Generated by Django 6.1 on 2026-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0112_tagnode_node_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagnode',
            name='tagged_within_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
