# Generated by Django 6.1 on 2026-08-24 02:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0114_analysis_variant_tag_stale_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodecount",
            name="variant_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True
            ),
        ),
        migrations.AddField(
            model_name="nodeversion",
            name="live_data_sources",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="varianttag",
            name="node_live_data_sources",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="varianttag",
            name="node_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analysis.nodeversion",
            ),
        ),
    ]
