# Generated by Django 6.1 on 2026-08-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0115_nodecount_variant_ids_nodeversion_live_data_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationsnode',
            name='allele_origin',
            field=models.CharField(choices=[('A', 'All'), ('G', 'Germline'), ('S', 'Somatic')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='classificationsnode',
            name='tier_1',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationsnode',
            name='tier_2',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationsnode',
            name='tier_3',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationsnode',
            name='tier_4',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='analysisnodecountconfigrecord',
            name='built_in_filter',
            field=models.CharField(choices=[('T', 'Total'), ('C', 'ClinVar LP/P'), ('O', 'OMIM Phenotype'), ('I', 'High or Mod impact'), ('G', 'Classified'), ('P', 'Classified Pathogenic'), ('S', 'Classified Tier I/II'), ('M', 'COSMIC')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='builtinfilternode',
            name='built_in_filter',
            field=models.CharField(choices=[('C', 'ClinVar LP/P'), ('O', 'OMIM Phenotype'), ('I', 'High or Mod impact'), ('G', 'Classified'), ('P', 'Classified Pathogenic'), ('S', 'Classified Tier I/II'), ('M', 'COSMIC')], max_length=1, null=True),
        ),
    ]
