# Generated by Django 6.1 on 2026-08-28 04:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0120_intersectionnode_variant_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_benign",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_conflicting",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_conflicting_significance",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_likely_benign",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_likely_pathogenic",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_pathogenic",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_record",
            field=models.CharField(
                choices=[
                    ("A", "Any"),
                    ("P", "Has a ClinVar record"),
                    ("N", "No ClinVar record"),
                ],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_significance_exclude",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_stars_min",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_uncertain",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_variation_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="node_input",
            field=models.CharField(
                choices=[
                    ("C", "Matching variants (no parent)"),
                    ("I", "Parent variants that MATCH"),
                    ("E", "Parent variants that DO NOT match"),
                ],
                default="C",
                max_length=1,
            ),
        ),
    ]
