# Generated by Django 6.1 on 2026-08-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0121_classificationsnode_node_input_and_clinvar"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_benign_onc",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_likely_benign_onc",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_likely_oncogenic",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_oncogenic",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_tier_1",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_tier_2",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_tier_3",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_tier_4",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="classificationsnode",
            name="clinvar_uncertain_onc",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
