# Generated by Django 6.1 on 2026-08-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0122_classificationsnode_clinvar_somatic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisnodecountconfigrecord",
            name="built_in_filter",
            field=models.CharField(
                choices=[
                    ("T", "Total"),
                    ("C", "ClinVar significant"),
                    ("O", "OMIM Phenotype"),
                    ("I", "High or Mod impact"),
                    ("G", "Classified"),
                    ("P", "Classified Pathogenic"),
                    ("S", "Classified Tier I/II"),
                    ("M", "COSMIC"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="builtinfilternode",
            name="built_in_filter",
            field=models.CharField(
                choices=[
                    ("C", "ClinVar significant"),
                    ("O", "OMIM Phenotype"),
                    ("I", "High or Mod impact"),
                    ("G", "Classified"),
                    ("P", "Classified Pathogenic"),
                    ("S", "Classified Tier I/II"),
                    ("M", "COSMIC"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
