# Generated by Django 6.1 on 2026-08-28 07:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analysis",
            "0123_alter_analysisnodecountconfigrecord_built_in_filter_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinVarNode",
            fields=[
                (
                    "analysisnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="analysis.analysisnode",
                    ),
                ),
                (
                    "node_input",
                    models.CharField(
                        choices=[
                            ("C", "Matching variants (no parent)"),
                            ("I", "Parent variants that MATCH"),
                            ("E", "Parent variants that DO NOT match"),
                        ],
                        default="I",
                        max_length=1,
                    ),
                ),
                (
                    "allele_origin",
                    models.CharField(
                        choices=[("A", "All"), ("G", "Germline"), ("S", "Somatic")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("germline_pathogenic", models.BooleanField(blank=True, default=True)),
                (
                    "germline_likely_pathogenic",
                    models.BooleanField(blank=True, default=True),
                ),
                ("germline_uncertain", models.BooleanField(blank=True, default=True)),
                (
                    "germline_likely_benign",
                    models.BooleanField(blank=True, default=True),
                ),
                ("germline_benign", models.BooleanField(blank=True, default=True)),
                ("germline_other", models.BooleanField(blank=True, default=True)),
                ("somatic_tier_1", models.BooleanField(blank=True, default=True)),
                ("somatic_tier_2", models.BooleanField(blank=True, default=True)),
                ("somatic_tier_3", models.BooleanField(blank=True, default=True)),
                ("somatic_tier_4", models.BooleanField(blank=True, default=True)),
                ("somatic_tier_none", models.BooleanField(blank=True, default=True)),
                (
                    "oncogenicity_oncogenic",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "oncogenicity_likely_oncogenic",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "oncogenicity_uncertain",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "oncogenicity_likely_benign",
                    models.BooleanField(blank=True, default=True),
                ),
                ("oncogenicity_benign", models.BooleanField(blank=True, default=True)),
                ("oncogenicity_none", models.BooleanField(blank=True, default=True)),
                ("stars_min", models.IntegerField(default=0)),
                ("conflicting", models.BooleanField(blank=True, default=False)),
                ("conflicting_significance", models.TextField(blank=True, null=True)),
                (
                    "variation_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, default=list
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("analysis.analysisnode",),
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_benign",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_benign_onc",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_conflicting",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_conflicting_significance",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_likely_benign",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_likely_benign_onc",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_likely_oncogenic",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_likely_pathogenic",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_oncogenic",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_pathogenic",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_record",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_significance_exclude",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_stars_min",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_tier_1",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_tier_2",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_tier_3",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_tier_4",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_uncertain",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_uncertain_onc",
        ),
        migrations.RemoveField(
            model_name="classificationsnode",
            name="clinvar_variation_ids",
        ),
        migrations.AlterField(
            model_name="classificationsnode",
            name="node_input",
            field=models.CharField(
                choices=[
                    ("C", "Matching variants (no parent)"),
                    ("I", "Parent variants that MATCH"),
                    ("E", "Parent variants that DO NOT match"),
                ],
                default="I",
                max_length=1,
            ),
        ),
    ]
