# Generated by Django 6.1 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0124_clinvarnode_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysisnodecountconfigrecord",
            old_name="built_in_filter",
            new_name="node_count_type",
        ),
        migrations.AlterField(
            model_name="analysisnodecountconfigrecord",
            name="node_count_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="node_count_auto_add_tags",
            field=models.BooleanField(
                default=True,
                help_text="Tagging a variant adds a node count for that tag. "
                          "Turn this off to choose the tag counts yourself on the Node Counts tab.",
            ),
        ),
    ]
