# Generated by Django 6.1 on 2026-08-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0125_analysis_node_count_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagenode",
            name="eve_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Benign", "Benign"),
                    ("Uncertain", "Uncertain"),
                    ("Pathogenic", "Pathogenic"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="eve_class_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="eve_class_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="eve_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="eve_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="eve_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="popeve_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="popeve_score_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="popeve_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="promoter_ai_score_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="promoter_ai_score_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="promoter_ai_score_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="protvar_stability_allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="protvar_stability_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="damagenode",
            name="protvar_stability_required",
            field=models.BooleanField(default=False),
        ),
    ]
