# Generated by Django 6.1 on 2026-08-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0126_damage_node_vep116_plugin_filters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinvarnode",
            name="oncogenicity_none",
        ),
        migrations.RemoveField(
            model_name="clinvarnode",
            name="somatic_tier_none",
        ),
    ]
