# Generated by Django 4.2.11 on 2026-09-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0128_intersectionnode_remove_legacy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistemplateversion',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
