# Generated by Django 6.1 on 2026-09-03 12:57

from collections import defaultdict

import django.contrib.postgres.fields
from django.db import migrations, models

# Node versions per batch - each can carry a variant_ids array of ANALYSIS_NODE_STORE_ID_SIZE_MAX pks
BATCH_SIZE = 500


def _fold_node_counts_into_node_versions(apps, _schema_editor):
    """ Open analyses keep their badges without a forced reload """
    NodeCount = apps.get_model("analysis", "NodeCount")
    NodeVersion = apps.get_model("analysis", "NodeVersion")

    node_version_ids = list(NodeCount.objects.order_by("node_version_id")
                            .values_list("node_version_id", flat=True).distinct())
    for i in range(0, len(node_version_ids), BATCH_SIZE):
        batch = node_version_ids[i:i + BATCH_SIZE]
        counts = defaultdict(dict)
        variant_ids = {}
        node_counts_qs = NodeCount.objects.filter(node_version__in=batch)
        for nv_id, label, count, nc_variant_ids in node_counts_qs.values_list("node_version_id", "label",
                                                                             "count", "variant_ids"):
            counts[nv_id][label] = count
            if nc_variant_ids is not None:  # Only ever on the TOTAL row
                variant_ids[nv_id] = nc_variant_ids

        node_versions = []
        for node_version in NodeVersion.objects.filter(pk__in=batch):
            node_version.load_data = {"counts": counts[node_version.pk]}
            node_version.variant_ids = variant_ids.get(node_version.pk)
            node_versions.append(node_version)
        NodeVersion.objects.bulk_update(node_versions, ["load_data", "variant_ids"])


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0131_analysisnode_ignore_field_errors"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodeversion",
            name="load_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="nodeversion",
            name="variant_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True
            ),
        ),
        migrations.RunPython(_fold_node_counts_into_node_versions, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="NodeCount",
        ),
    ]
