# Generated by Django 6.1 on 2026-09-04 06:36

import analysis.models.nodes.cohort_mixin
import analysis.models.nodes.family_inheritance
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0132_nodeversion_load_data'),
        ('snpdb', '0246_add_duo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.CharField(blank=True, choices=[('S', 'Singleton'), ('C', 'Cohort'), ('T', 'Trio'), ('Q', 'Quad'), ('U', 'Duo'), ('P', 'Pedigree')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='DuoNode',
            fields=[
                ('analysisnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analysis.analysisnode')),
                ('min_ad', models.IntegerField(default=0)),
                ('min_dp', models.IntegerField(default=0)),
                ('min_gq', models.IntegerField(default=0)),
                ('max_pl', models.IntegerField(blank=True, null=True)),
                ('min_ad_op', models.CharField(choices=[('L', 'All'), ('Y', 'Any')], default='Y', max_length=1)),
                ('min_dp_op', models.CharField(choices=[('L', 'All'), ('Y', 'Any')], default='Y', max_length=1)),
                ('min_gq_op', models.CharField(choices=[('L', 'All'), ('Y', 'Any')], default='Y', max_length=1)),
                ('max_pl_op', models.CharField(choices=[('L', 'All'), ('Y', 'Any')], default='Y', max_length=1)),
                ('inheritance', models.CharField(choices=[('R', 'Recessive'), ('A', 'All Recessive (AR + XLR)'), ('C', 'C. Het (half phased)'), ('D', 'Dominant'), ('N', 'Absent in parent'), ('X', 'X-Linked Recessive'), ('Y', 'Any Affected (variant in ≥1 affected)')], default='R', max_length=1)),
                ('require_zygosity', models.BooleanField(default=True)),
                ('duo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.duo')),
            ],
            options={
                'abstract': False,
            },
            bases=(analysis.models.nodes.family_inheritance.FamilyInheritanceNodeMixin, analysis.models.nodes.cohort_mixin.CohortMixin, 'analysis.analysisnode'),
        ),
    ]
