# Generated by Django 6.1 on 2026-09-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0134_mosaic_parent_inheritance'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadnode',
            name='mosaic_max_af',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='quadnode',
            name='mosaic_min_alt_reads',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='quadnode',
            name='inheritance',
            field=models.CharField(choices=[('R', 'Recessive'), ('A', 'All Recessive (AR + XLR)'), ('C', 'C. Het'), ('D', 'Dominant'), ('M', 'Dominant (mosaic parent)'), ('N', 'Denovo'), ('X', 'X-Linked Recessive'), ('Y', 'Any Affected (variant in ≥1 affected)')], default='R', max_length=1),
        ),
    ]
