# Generated by Django 6.1 on 2026-09-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0135_quad_mosaic_parent'),
        ('snpdb', '0250_tag_requires_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttag',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.sample'),
        ),
    ]
