# Generated by Django 6.1 on 2026-09-07 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0137_one_off_backfill_variant_tag_sample"),
        ("classification", "0175_ekey_gene_fusion_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="varianttag",
            name="resolved",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="varianttag",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_variant_tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="varianttag",
            name="resolved_classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classification.classification",
            ),
        ),
    ]
