# Generated by Django 6.1 on 2026-09-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0138_varianttag_resolved"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagnode",
            name="include_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
