# Generated by Django 6.1 on 2026-09-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0138_varianttag_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagenode',
            name='structural',
            field=models.CharField(choices=[('A', 'Any'), ('O', 'Structural only'), ('E', 'Exclude structural')], default='A', max_length=1),
        ),
    ]
