# Generated by Django 6.1 on 2026-09-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0139_damagenode_structural"),
        ("analysis", "0139_tagnode_include_resolved"),
    ]

    operations = []
