# Generated by Django 6.1 on 2026-09-07 10:26

from django.conf import settings
from django.db import migrations, models
from django.db.models import Min


def _delete_repeated_analysis_taggings(apps, _schema_editor):
    """ The constraint can't go on while an analysis holds repeats of one tagging. Data made before it can
        (a tag merge used to leave them) - the earliest of each set stays, the same rule as
        'manage.py variant_tags delete-duplicates'. Global (variant page) taggings are outside the
        constraint and untouched """
    VariantTag = apps.get_model("analysis", "VariantTag")
    analysis_taggings = VariantTag.objects.filter(analysis__isnull=False)
    earliest_qs = analysis_taggings.values("variant_id", "tag_id", "analysis_id", "user_id", "sample_id") \
        .annotate(earliest=Min("pk")).values("earliest")
    num_deleted, _ = analysis_taggings.exclude(pk__in=earliest_qs).delete()
    if num_deleted:
        print(f"Deleted {num_deleted} repeated analysis taggings")


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0140_merge_20260907_1354'),
        ('classification', '0177_evidence_key_copy_scope_and_allele_origin_values'),
        ('snpdb', '0257_one_off_fail_samples_of_failed_vcfs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_delete_repeated_analysis_taggings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='varianttag',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis__isnull', False)), fields=('variant', 'tag', 'analysis', 'user', 'sample'), name='varianttag_one_per_sample_in_analysis', nulls_distinct=False),
        ),
    ]
