# Generated by Django 6.1 on 2026-09-07 10:26

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def _check_no_repeated_analysis_taggings(apps, _schema_editor):
    """ The constraint can't go on while an analysis holds repeats of one tagging. Data made before it can
        (a tag merge used to leave them), and 'manage.py variant_tags delete-duplicates' clears them out """
    VariantTag = apps.get_model("analysis", "VariantTag")
    repeats = VariantTag.objects.filter(analysis__isnull=False) \
        .values("variant_id", "tag_id", "analysis_id", "user_id", "sample_id") \
        .annotate(num_taggings=Count("id")).filter(num_taggings__gt=1).count()
    if repeats:
        raise RuntimeError(f"{repeats} analysis taggings are repeated - run "
                           "'manage.py variant_tags delete-duplicates', then this migration again")


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0140_merge_20260907_1354'),
        ('classification', '0177_evidence_key_copy_scope_and_allele_origin_values'),
        ('snpdb', '0257_one_off_fail_samples_of_failed_vcfs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_check_no_repeated_analysis_taggings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='varianttag',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis__isnull', False)), fields=('variant', 'tag', 'analysis', 'user', 'sample'), name='varianttag_one_per_sample_in_analysis', nulls_distinct=False),
        ),
    ]
