# Generated by Django 6.1.1 on 2026-09-09 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from manual.operations.manual_operations import ManualOperation


def _has_variant_tags_needing_patient(apps):
    VariantTag = apps.get_model("analysis", "VariantTag")
    return VariantTag.objects.filter(patient__isnull=True, analysis__isnull=False,
                                     node__isnull=False).exists()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0142_backfill_variant_tag_allele'),
        ('classification', '0177_evidence_key_copy_scope_and_allele_origin_values'),
        ('patients', '0018_alter_patient_last_name'),
        ('snpdb', '0261_vcf_gene_level_segment_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='varianttag',
            name='varianttag_one_per_sample_in_analysis',
        ),
        migrations.AddField(
            model_name='varianttag',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AddConstraint(
            model_name='varianttag',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis__isnull', False)), fields=('variant', 'tag', 'analysis', 'user', 'sample', 'patient'), name='varianttag_one_per_person_in_analysis', nulls_distinct=False),
        ),
        ManualOperation(task_id=ManualOperation.task_id_manage(["one_off_backfill_variant_tag_patient"]),
                        note="Work out which patient existing taggings were about, so a tagging made above "
                             "sample level reaches the patient's Classify & Report tab (#1854)",
                        test=_has_variant_tags_needing_patient),
    ]
