# Generated by Django 6.1.1 on 2026-09-17 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0145_alter_damagenode_variant_class"),
        ("snpdb", "0268_cohort_phenotype"),
    ]

    operations = [
        migrations.AddField(
            model_name="phenotypenode",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="snpdb.cohort",
            ),
        ),
    ]
