# Generated by Django 6.1.1 on 2026-09-18 03:46

from django.db import migrations, models


def _gene_level_types_follow_structural_variants(apps, _schema_editor):
    """ Gene-level variants used to be selected by structural_variants, so keep existing nodes' results """
    AllVariantsNode = apps.get_model("analysis", "AllVariantsNode")
    AllVariantsNode.objects.filter(structural_variants=False).update(fusions=False, copy_number=False, splicing=False)


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0146_phenotypenode_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="allvariantsnode",
            name="copy_number",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="allvariantsnode",
            name="fusions",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="allvariantsnode",
            name="splicing",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.RunPython(_gene_level_types_follow_structural_variants, migrations.RunPython.noop),
    ]
