# Generated by Django 6.1.1 on 2026-09-22 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0148_analysis_tag_config_collection'),
        ('snpdb', '0273_rename_tagcolor_tagconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='tag_config_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.tagconfigcollection'),
        ),
    ]
