# Generated by Django 6.1.1 on 2026-09-24 06:17

from django.db import migrations
from django.db.models import Q

OLD_BACKEND_ENRICHMENT_KIT = 2
OLD_CONTIG = 3
SELECTED_INTERVALS = 0
VARIANTS = 1
CONTIG = 2


def _remove_enrichment_kit_panel(apps, _schema_editor):
    """ accordion_panel is the editor's card index - the enrichment kit card (VCFBedIntersection) is gone,
        so contig moves down one. Enrichment kit nodes go to a panel they left empty, so they still don't filter """
    IntersectionNode = apps.get_model("analysis", "IntersectionNode")

    enrichment_kit_nodes = IntersectionNode.objects.filter(accordion_panel=OLD_BACKEND_ENRICHMENT_KIT)
    no_variant_text_q = Q(variant_text__isnull=True) | Q(variant_text="")
    variants_ids = list(enrichment_kit_nodes.filter(genomic_intervals_collection__isnull=False)
                        .filter(no_variant_text_q).values_list("pk", flat=True))
    enrichment_kit_nodes.exclude(pk__in=variants_ids).update(accordion_panel=SELECTED_INTERVALS)
    IntersectionNode.objects.filter(pk__in=variants_ids).update(accordion_panel=VARIANTS)
    IntersectionNode.objects.filter(accordion_panel=OLD_CONTIG).update(accordion_panel=CONTIG)


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0149_analysis_tag_config_collection_no_help_text'),
    ]

    operations = [
        migrations.RunPython(_remove_enrichment_kit_panel, migrations.RunPython.noop),
    ]
