# Generated by Django 6.1.1 on 2026-10-01 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0150_intersection_node_remove_enrichment_kit_panel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisnode",
            name="shadow_color",
        ),
    ]
