# Generated by Django 6.1.1 on 2026-10-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0151_remove_analysisnode_shadow_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allelefrequencynode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="allvariantsnode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="analysisnode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="builtinfilternode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="classificationsnode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="clinvarnode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="conservationnode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="damagenode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="filternode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="genelistnode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="intersectionnode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="mergenode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="moinode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="phenotypenode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="populationnode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="samplenode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="selectedinparentnode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="tagnode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="tissuenode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="vennnode",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="zygositynode",
            options={"get_latest_by": "modified"},
        ),
    ]
