# Generated by Django 6.1.1 on 2026-10-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0152_node_get_latest_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplenode',
            name='max_copy_loss_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplenode',
            name='min_copy_gain_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
