import os
import shlex
import tarfile
from urllib.parse import urlparse

import requests
from django.core.management.base import BaseCommand
from tqdm import tqdm

from variantgrid.deployment_validation.annotation_files_check import annotation_data_exists

# vep_config entries that point at a directory of files rather than a single file.
# These are hosted as '<dir>.tar.gz' on variantgrid.com and extracted in place.
_DIRECTORY_ARCHIVE_KEYS = {"maxentscan"}


def _is_directory_archive(key):
    # key may be plain ("maxentscan") or flattened ("GRCh37/maxentscan")
    return key.rsplit("/", 1)[-1] in _DIRECTORY_ARCHIVE_KEYS


class Command(BaseCommand):
    help = "Check for missing annotation data files and download them from variantgrid.com"

    def add_arguments(self, parser):
        parser.add_argument('--dry-run', action='store_true',
                            help="List what would be downloaded without downloading")
        parser.add_argument('--force', action='store_true',
                            help="Re-download even if file already exists")
        parser.add_argument('--bash-script', nargs='?', const='-', metavar='PATH',
                            help="Write a bash script that downloads every annotation file "
                                 "(to PATH, or stdout if no path given) instead of downloading now")

    def handle(self, *args, **options):
        dry_run = options["dry_run"]
        force = options["force"]
        bash_script = options["bash_script"]

        checks = annotation_data_exists(flat=True, include_tbi_for_gz=True)

        if bash_script is not None:
            self._write_bash_script(checks, bash_script)
            return

        missing = []
        for key, data in checks.items():
            if force or not data.get("valid"):
                url, dirname = _parse_fix(data.get("fix", ""))
                if url is None:
                    self.stderr.write(f"Could not parse fix for {key}: {data.get('fix')}")
                    continue
                is_archive = _is_directory_archive(key)
                if is_archive:
                    # The config value is a directory; download the hosted tarball and extract it
                    url = url + ".tar.gz"
                filename = os.path.join(dirname, os.path.basename(urlparse(url).path))
                missing.append((key, url, dirname, filename, is_archive))

        if not missing:
            self.stdout.write("All annotation data files present.")
            return

        self.stdout.write(f"Found {len(missing)} missing annotation file(s):")
        for key, url, _dirname, _filename, _is_archive in missing:
            self.stdout.write(f"  {key}: {url}")

        if dry_run:
            self.stdout.write("Dry run; not downloading.")
            return

        failures = []
        for key, url, dirname, filename, is_archive in missing:
            self.stdout.write(f"\nDownloading {key}: {url}")
            try:
                os.makedirs(dirname, exist_ok=True)
                _download(url, filename)
                if is_archive:
                    _extract_tarball(filename, dirname)
                    os.remove(filename)
                self.stdout.write(f"  -> {filename}")
            except Exception as e:
                self.stderr.write(f"  FAILED: {e}")
                failures.append((key, url, str(e)))

        if failures:
            self.stdout.write(f"\n{len(failures)} download(s) failed:")
            for key, url, err in failures:
                self.stdout.write(f"  {key}: {url}  ({err})")
        else:
            self.stdout.write("\nAll downloads complete.")

    def _write_bash_script(self, checks, path):
        lines = [
            "#!/bin/bash",
            "# Generated by 'manage.py download_annotation_data --bash-script'",
            "# Downloads all VariantGrid annotation data files.",
            "set -euo pipefail",
            "",
        ]
        skipped = []
        for key, data in checks.items():
            url, dirname = _parse_fix(data.get("fix", ""))
            if url is None:
                skipped.append(key)
                continue
            lines.append(f"# {key}")
            lines.append(f"mkdir -p {shlex.quote(dirname)}")
            if _is_directory_archive(key):
                url = url + ".tar.gz"
                tarball = os.path.join(dirname, os.path.basename(urlparse(url).path))
                lines.append(f"wget -c -P {shlex.quote(dirname)} {shlex.quote(url)}")
                lines.append(f"tar -xzf {shlex.quote(tarball)} -C {shlex.quote(dirname)}")
                lines.append(f"rm {shlex.quote(tarball)}")
            else:
                lines.append(f"wget -c -P {shlex.quote(dirname)} {shlex.quote(url)}")
            lines.append("")

        for key in skipped:
            self.stderr.write(f"Could not parse fix for {key}: {checks[key].get('fix')}")

        script = "\n".join(lines)
        if path == "-":
            self.stdout.write(script)
        else:
            with open(path, "w") as f:
                f.write(script + "\n")
            os.chmod(path, 0o755)
            self.stdout.write(f"Wrote download script to {path}")


def _parse_fix(fix):
    """Parse a fix instruction of the form 'cd <dir>;wget <url>'."""
    if not fix or ";" not in fix:
        return None, None
    cd_part, _, wget_part = fix.partition(";")
    cd_part = cd_part.strip()
    wget_part = wget_part.strip()
    if not cd_part.startswith("cd ") or not wget_part.startswith("wget "):
        return None, None
    return wget_part[len("wget "):].strip(), cd_part[len("cd "):].strip()


def _extract_tarball(tarball, dest):
    with tarfile.open(tarball, "r:gz") as tf:
        try:
            tf.extractall(dest, filter="data")  # guards against path traversal (Python 3.12+)
        except TypeError:
            tf.extractall(dest)


def _download(url, dest):
    tmp = dest + ".part"
    with requests.get(url, stream=True, timeout=60) as resp:
        resp.raise_for_status()
        total = int(resp.headers.get("content-length", 0)) or None
        with open(tmp, "wb") as f, tqdm(
            total=total, unit="B", unit_scale=True, desc=os.path.basename(dest)
        ) as pbar:
            for chunk in resp.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    f.write(chunk)
                    pbar.update(len(chunk))
    os.replace(tmp, dest)
