# Generated by Django 3.1 on 2020-10-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedvariantclassificationimport',
            old_name='variant_classification_import',
            new_name='classification_import',
        ),
    ]
