# Generated by Django 3.1 on 2020-10-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0005_auto_20201001_1706'),
        ('upload', '0002_auto_20201001_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedVariantClassificationImport',
            new_name='UploadedClassificationImport',
        ),
    ]
