# Generated by Django 3.1 on 2020-10-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20201001_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadstep',
            name='items_to_process',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadstepmultifileoutput',
            name='items_to_process',
            field=models.IntegerField(null=True),
        ),
    ]
