# Generated by Django 3.1 on 2020-11-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20201009_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleVCFImportInfo',
            fields=[
                ('vcfimportinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload.vcfimportinfo')),
                ('type', models.TextField()),
                ('has_more_details', models.BooleanField(default=False)),
                ('message_string', models.TextField()),
            ],
            bases=('upload.vcfimportinfo',),
        ),
    ]
