# Generated by Django 3.1.3 on 2021-03-29 01:07
import os

import pandas as pd
from django.db import migrations


def _one_off_restore_backend_vcfs(apps, _schema_editor):
    BackEndVCF = apps.get_model("upload", "BackEndVCF")
    backend_vcf_filename = "data/migrations/backend_vcf_new_pks.csv"
    if os.path.exists(backend_vcf_filename):
        df = pd.read_csv(backend_vcf_filename)
        print(f"Restoring {len(df)} BackEndVCF records")
        for _, row in df.iterrows():
            BackEndVCF.objects.filter(pk=row["id"]).update(combo_vcf_id=row["combo_vcf_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20210324_1455'),
    ]

    operations = [
        migrations.RunPython(_one_off_restore_backend_vcfs)
    ]
