# Generated by Django 3.1.3 on 2021-04-09 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_auto_20210409_1724'),
        ('upload', '0007_one_off_restore_backend_vcfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('B', 'BED'), ('L', 'Clinvar'), ('T', 'Clinvar Citations'), ('C', 'CuffDiff'), ('G', 'Gene List'), ('O', 'Gene Coverage'), ('I', 'Liftover'), ('P', 'Pedigree'), ('R', 'Patient Records'), ('S', 'Variant Classifications'), ('A', 'Variant Tags'), ('V', 'VCF'), ('Y', 'VCF - Insert variants only (no samples etc)')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='UploadedVariantTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.uploadedfile')),
                ('variant_tags_import', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.varianttagsimport')),
            ],
        ),
    ]
