# Generated by Django 3.2.1 on 2021-05-26 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20210409_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvarianttags',
            name='uploaded_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.uploadedfile'),
        ),
    ]
