# Generated by Django 3.2.4 on 2021-11-29 04:29

from django.db import migrations


def _one_off_convert_skipped_gvcf_to_standard_vcf_info(apps, _schema_editor):
    VCFSkippedGVCFNonVarBlocks = apps.get_model("upload", "VCFSkippedGVCFNonVarBlocks")
    SimpleVCFImportInfo = apps.get_model("upload", "SimpleVCFImportInfo")

    for skipped_gvcf in VCFSkippedGVCFNonVarBlocks.objects.all():
        # We can't bulk create multi-table inheritance models, do individually
        message_string = f"{skipped_gvcf.num_skipped} gVCF reference blocks skipped (we only store variants)"
        SimpleVCFImportInfo.objects.create(severity=skipped_gvcf.severity,
                                           type="<NON_REF>",
                                           upload_step=skipped_gvcf.upload_step,
                                           accepted_date=skipped_gvcf.accepted_date,
                                           message_string=message_string)

    VCFSkippedGVCFNonVarBlocks.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20211019_1742'),
    ]

    operations = [
        migrations.RunPython(_one_off_convert_skipped_gvcf_to_standard_vcf_info),
    ]
