# Generated by Django 4.0.2 on 2022-02-10 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0058_importedwikicollection_importedwiki'),
        ('upload', '0012_delete_vcfskippedgvcfnonvarblocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('B', 'BED'), ('L', 'Clinvar'), ('C', 'CuffDiff'), ('G', 'Gene List'), ('O', 'Gene Coverage'), ('I', 'Liftover'), ('P', 'Pedigree'), ('R', 'Patient Records'), ('S', 'Variant Classifications'), ('A', 'Variant Tags'), ('V', 'VCF'), ('Y', 'VCF - Insert variants only (no samples etc)'), ('w', 'Gene Wiki records'), ('W', 'Variant Wiki records')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='UploadedWikiCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.uploadedfile')),
                ('wiki_collection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='snpdb.importedwikicollection')),
            ],
        ),
    ]
