# Generated by Django 4.0.3 on 2022-04-27 06:35

from django.db import migrations


def _one_off_add_sequencing_run_field(apps, schema_editor):
    UploadSettings = apps.get_model("upload", "UploadSettings")
    UploadSettingsFileType = apps.get_model("upload", "UploadSettingsFileType")

    BED = 'B'
    CLINVAR = 'L'
    CUFFDIFF = 'C'
    GENE_LIST = 'G'
    GENE_COVERAGE = 'O'
    PED = 'P'
    PATIENT_RECORDS = 'R'
    VARIANT_CLASSIFICATIONS = 'S'
    VARIANT_TAGS = "A"
    VCF = 'V'
    WIKI_GENE = "w"
    WIKI_VARIANT = "W"

    _NON_INTERNAL_TYPES = [
        BED,
        CLINVAR,
        CUFFDIFF,
        GENE_LIST,
        GENE_COVERAGE,
        PED,
        PATIENT_RECORDS,
        VARIANT_CLASSIFICATIONS,
        VARIANT_TAGS,
        VCF,
        WIKI_GENE,
        WIKI_VARIANT,
    ]

    records = []
    for upload_settings in UploadSettings.objects.all():
        for uft in _NON_INTERNAL_TYPES:
            records.append(UploadSettingsFileType(upload_settings=upload_settings, file_type=uft))

    if records:
        UploadSettingsFileType.objects.bulk_create(records)


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_remove_uploadedfile_visible_and_more'),
    ]

    operations = [
        migrations.RunPython(_one_off_add_sequencing_run_field),
    ]
