# Generated by Django 4.1.4 on 2023-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0015_one_off_create_upload_settings_view_file_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("B", "BED"),
                    ("L", "Clinvar"),
                    ("G", "Gene List"),
                    ("O", "Gene Coverage"),
                    ("I", "Liftover"),
                    ("P", "Pedigree"),
                    ("R", "Patient Records"),
                    ("S", "Variant Classifications"),
                    ("A", "Variant Tags"),
                    ("V", "VCF"),
                    ("Y", "VCF - Insert variants only (no samples etc)"),
                    ("w", "Gene Wiki records"),
                    ("W", "Variant Wiki records"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="uploadsettingsfiletype",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("B", "BED"),
                    ("L", "Clinvar"),
                    ("G", "Gene List"),
                    ("O", "Gene Coverage"),
                    ("I", "Liftover"),
                    ("P", "Pedigree"),
                    ("R", "Patient Records"),
                    ("S", "Variant Classifications"),
                    ("A", "Variant Tags"),
                    ("V", "VCF"),
                    ("Y", "VCF - Insert variants only (no samples etc)"),
                    ("w", "Gene Wiki records"),
                    ("W", "Variant Wiki records"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="UploadedExpressionFile",
        ),
    ]
