# Generated by Django 4.1.4 on 2023-10-19 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0078_merge_20230912_1032"),
        ("upload", "0016_alter_uploadedfile_file_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedclinvarversion",
            name="clinvar_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="annotation.clinvarversion",
            ),
        ),
    ]
