# Generated by Django 4.2.10 on 2024-05-29 05:39

from django.db import migrations


def _one_off_move_modified_imported_variants_to_norm_substep(apps, _schema_editor):
    ModifiedImportedVariants = apps.get_model("upload", "ModifiedImportedVariants")

    # These are useless, get rid of them so we speed up migration
    ModifiedImportedVariants.objects.filter(modifiedimportedvariant__isnull=True).delete()

    # Move the step from "Preprocess VCF" to "normalize" (same pipeline)
    records = []
    for mivs in ModifiedImportedVariants.objects.filter(upload_step__name='Preprocess VCF'):
        up = mivs.upload_step.upload_pipeline
        # Should always be there but just in case use first()
        if norm_step := up.uploadstep_set.filter(name='normalize').first():
            mivs.upload_step = norm_step
            records.append(mivs)

    if records:
        ModifiedImportedVariants.objects.bulk_update(records, ['upload_step'])


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_alter_uploadedclinvarversion_clinvar_version'),
    ]

    operations = [
        migrations.RunPython(_one_off_move_modified_imported_variants_to_norm_substep)
    ]
