# Generated by Django 4.2.10 on 2024-06-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0018_one_off_move_modified_imported_variants_to_norm_substep'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='sha256_hash',
            field=models.TextField(null=True),
        ),
    ]
