# Generated by Django 4.2.10 on 2024-06-20 04:44
import logging
import os

from django.db import migrations

from library.utils import file_sha256sum


def _md5_to_sha256(apps, _schema_editor):
    UploadedFile = apps.get_model('upload', 'UploadedFile')
    WEB_UPLOAD = 'U'

    uf_with_hash_qs = UploadedFile.objects.filter(md5_hash__isnull=False)
    logging.info("Calculating sha256sum for %d uploaded files with md5sum...", UploadedFile.objects.count())

    uf_records = []
    for uf in uf_with_hash_qs:
        if uf.import_source == WEB_UPLOAD:
            filename = uf.uploaded_file.path
        else:
            filename = uf.path

        if os.path.exists(filename):
            uf.sha256_hash = file_sha256sum(filename)
        else:
            uf.sha256_hash = "old-md5sum-hash-" + uf.md5_hash
        uf_records.append(uf)

    if uf_records:
        UploadedFile.objects.bulk_update(uf_records, ['sha256_hash'])


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0019_uploadedfile_sha256_hash'),
    ]

    operations = [
        migrations.RunPython(_md5_to_sha256)
    ]
