# Generated by Django 4.2.10 on 2024-06-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0020_md5_to_sha256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='md5_hash',
        ),
    ]
