# Generated by Django 4.2.11 on 2024-08-06 12:04
import json
import os

from django.conf import settings
from django.db import migrations

from library.utils import mk_path


def _delete_bad_modified_imported_variants(apps, schema_editor):
    ModifiedImportedVariant = apps.get_model("upload", "ModifiedImportedVariant")
    qs = ModifiedImportedVariant.objects.all().filter(variant__svlen__isnull=False)
    if miv_values := list(qs.values()):
        migrations_dir = os.path.join(settings.PRIVATE_DATA_ROOT, "migrations")
        mk_path(migrations_dir)
        bad_modifications_filename = os.path.join(migrations_dir, "bad_modifications_filename.json")
        with open(bad_modifications_filename, "w") as f:
            json.dump(miv_values, f)
        print(f"Wrote {len(miv_values)} incorretly normalized symbolic variants to '{bad_modifications_filename}'")
        qs.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0021_remove_uploadedfile_md5_hash"),
        ("classification", "0153_one_off_remind_rematch_allele_info_bad_end_norm")
    ]

    operations = [
        migrations.RunPython(_delete_bad_modified_imported_variants)
    ]
