# Generated by Django 4.2.15 on 2024-09-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0022_one_off_delete_bad_end_bcftools_symbolic_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadstep',
            name='split_file_rows',
            field=models.IntegerField(null=True),
        ),
    ]
