# Generated by Django 4.2.11 on 2025-01-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0023_uploadstep_split_file_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="modifiedimportedvariant",
            name="operation",
            field=models.CharField(
                choices=[("N", "Normalization"), ("R", "Removed Duplicate")],
                default="N",
                max_length=1,
            ),
        ),
    ]
