# Generated by Django 4.2.17 on 2025-03-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0025_simplevcfimportinfo_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadstep',
            name='pipeline_stage',
            field=models.CharField(choices=[('U', 'Pre-Data Insertion'), ('D', 'Data Insertion'), ('A', 'Annotation Complete'), ('F', 'Finish')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='uploadstep',
            name='pipeline_stage_dependency',
            field=models.CharField(choices=[('U', 'Pre-Data Insertion'), ('D', 'Data Insertion'), ('A', 'Annotation Complete'), ('F', 'Finish')], max_length=1, null=True),
        ),
    ]
