# Generated by Django 4.2.20 on 2025-04-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0026_alter_uploadstep_pipeline_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('B', 'BED'), ('L', 'Clinvar'), ('G', 'Gene List'), ('O', 'Gene Coverage'), ('I', 'Liftover'), ('M', 'Manual Variant Entry'), ('P', 'Pedigree'), ('R', 'Patient Records'), ('S', 'Variant Classifications'), ('A', 'Variant Tags'), ('V', 'VCF'), ('Y', 'VCF - Insert variants only (no samples etc)'), ('w', 'Gene Wiki records'), ('W', 'Variant Wiki records')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='uploadsettingsfiletype',
            name='file_type',
            field=models.CharField(choices=[('B', 'BED'), ('L', 'Clinvar'), ('G', 'Gene List'), ('O', 'Gene Coverage'), ('I', 'Liftover'), ('M', 'Manual Variant Entry'), ('P', 'Pedigree'), ('R', 'Patient Records'), ('S', 'Variant Classifications'), ('A', 'Variant Tags'), ('V', 'VCF'), ('Y', 'VCF - Insert variants only (no samples etc)'), ('w', 'Gene Wiki records'), ('W', 'Variant Wiki records')], max_length=1, null=True),
        ),
    ]
