# Generated by Django 5.2.8 on 2026-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0027_alter_uploadedfile_file_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modifiedimportedvariant",
            name="operation",
            field=models.CharField(
                choices=[("N", "Normalisation"), ("R", "Removed Duplicate")],
                default="N",
                max_length=1,
            ),
        ),
    ]
