# Generated by Django 6.0.3 on 2026-05-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0028_alter_modifiedimportedvariant_operation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="backendvcf",
            old_name="combo_vcf",
            new_name="joint_called_vcf",
        ),
    ]
