# Generated by Django 6.0.6 on 2026-07-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0195_delete_columnvcfinfo'),
        ('upload', '0030_rename_vcf_file_backendvcf_single_sample_vcf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedvcf',
            name='max_variant',
        ),
        migrations.CreateModel(
            name='UploadedVCFPipelineMaxVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type', models.CharField(choices=[('S', 'Standard Short Variant'), ('C', 'Structural Variant')], max_length=1)),
                ('max_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snpdb.variant')),
                ('uploaded_vcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_max_variants', to='upload.uploadedvcf')),
            ],
            options={
                'unique_together': {('uploaded_vcf', 'pipeline_type')},
            },
        ),
    ]
