# Generated by Django 6.1 on 2026-08-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0033_rename_uploadedfile_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
