# Generated by Django 6.1 on 2026-08-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0034_fileupload_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedimportedvariant',
            name='operation_detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modifiedimportedvariant',
            name='operation',
            field=models.CharField(choices=[('N', 'Normalisation'), ('R', 'Removed Duplicate'), ('L', 'Shared Locus - allele depths summed')], default='N', max_length=1),
        ),
    ]
