# Generated by Django 6.0.6 on 2026-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0035_modifiedimportedvariant_operation_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedvcfpipelinemaxvariant",
            name="pipeline_type",
            field=models.CharField(
                choices=[
                    ("S", "Standard Short Variant"),
                    ("C", "Structural Variant"),
                    ("G", "Gene Level"),
                ],
                max_length=1,
            ),
        ),
    ]
