# Generated by Django 6.0.6 on 2026-08-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0036_alter_uploadedvcfpipelinemaxvariant_pipeline_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("B", "BED"),
                    ("L", "Clinvar"),
                    ("F", "Gene Fusions"),
                    ("G", "Gene List"),
                    ("O", "Gene Coverage"),
                    ("I", "Liftover"),
                    ("M", "Manual Variant Entry"),
                    ("P", "Pedigree"),
                    ("R", "Patient Records"),
                    ("S", "Variant Classifications"),
                    ("A", "Variant Tags"),
                    ("V", "VCF"),
                    ("Y", "VCF - Insert variants only (no samples etc)"),
                    ("y", "VCF - Insert gene-level variants only"),
                    ("w", "Gene Wiki records"),
                    ("W", "Variant Wiki records"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="uploadsettingsfiletype",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("B", "BED"),
                    ("L", "Clinvar"),
                    ("F", "Gene Fusions"),
                    ("G", "Gene List"),
                    ("O", "Gene Coverage"),
                    ("I", "Liftover"),
                    ("M", "Manual Variant Entry"),
                    ("P", "Pedigree"),
                    ("R", "Patient Records"),
                    ("S", "Variant Classifications"),
                    ("A", "Variant Tags"),
                    ("V", "VCF"),
                    ("Y", "VCF - Insert variants only (no samples etc)"),
                    ("y", "VCF - Insert gene-level variants only"),
                    ("w", "Gene Wiki records"),
                    ("W", "Variant Wiki records"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
