# Generated by Django 6.1 on 2026-08-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0037_alter_fileupload_file_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedvcfpipelinemaxvariant",
            name="pipeline_type",
            field=models.CharField(
                choices=[
                    ("S", "Standard Short Variant"),
                    ("C", "Structural Variant"),
                    ("G", "Gene Level"),
                    ("A", "AnnotSV"),
                ],
                max_length=1,
            ),
        ),
    ]
