# Generated by Django 6.1 on 2026-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0039_upload_settings_show_dragen_tso500_all_fusions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modifiedimportedvariant",
            name="operation",
            field=models.CharField(
                choices=[
                    ("N", "Normalisation"),
                    ("R", "Removed Duplicate"),
                    ("L", "Shared Locus - allele depths summed"),
                    ("M", "Merged Records - multiple VCF records became one variant"),
                ],
                default="N",
                max_length=1,
            ),
        ),
    ]
