# Generated by Django 6.1 on 2026-08-31 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0124_clinvarnode_and_more"),
        ("upload", "0040_alter_modifiedimportedvariant_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("N", "Analysis"),
                    ("B", "BED"),
                    ("L", "Clinvar"),
                    ("F", "DRAGEN TSO500 AllFusions"),
                    ("G", "Gene List"),
                    ("O", "Gene Coverage"),
                    ("I", "Liftover"),
                    ("M", "Manual Variant Entry"),
                    ("P", "Pedigree"),
                    ("R", "Patient Records"),
                    ("S", "Variant Classifications"),
                    ("A", "Variant Tags"),
                    ("V", "VCF"),
                    ("Y", "VCF - Insert variants only (no samples etc)"),
                    ("y", "VCF - Insert gene-level variants only"),
                    ("w", "Gene Wiki records"),
                    ("W", "Variant Wiki records"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="uploadsettingsfiletype",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("N", "Analysis"),
                    ("B", "BED"),
                    ("L", "Clinvar"),
                    ("F", "DRAGEN TSO500 AllFusions"),
                    ("G", "Gene List"),
                    ("O", "Gene Coverage"),
                    ("I", "Liftover"),
                    ("M", "Manual Variant Entry"),
                    ("P", "Pedigree"),
                    ("R", "Patient Records"),
                    ("S", "Variant Classifications"),
                    ("A", "Variant Tags"),
                    ("V", "VCF"),
                    ("Y", "VCF - Insert variants only (no samples etc)"),
                    ("y", "VCF - Insert gene-level variants only"),
                    ("w", "Gene Wiki records"),
                    ("W", "Variant Wiki records"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="UploadedAnalysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.analysis",
                    ),
                ),
                (
                    "file_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload.fileupload",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
