# Generated by Django 6.1.1 on 2026-09-16 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0183_ekey_splicing_variant_options'),
        ('upload', '0045_rename_gene_level_api_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedclassificationimport',
            name='classification_import',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.classificationimport'),
        ),
    ]
