# Generated by Django 6.1.1 on 2026-09-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0047_uploaded_dragen_tso500_metrics_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(choices=[('N', 'Analysis'), ('B', 'BED'), ('L', 'Clinvar'), ('F', 'DRAGEN TSO500 AllFusions'), ('C', 'DRAGEN TSO500 Combined Variant Output'), ('Q', 'DRAGEN TSO500 Metrics Output'), ('G', 'Gene List'), ('O', 'Gene Coverage'), ('I', 'Liftover'), ('M', 'Manual Variant Entry'), ('P', 'Pedigree'), ('R', 'Patient Records'), ('S', 'Variant Classifications'), ('A', 'Variant Tags'), ('V', 'VCF'), ('Y', 'VCF - Insert variants only (no samples etc)'), ('y', 'VCF - Insert gene-level variants only'), ('c', 'VCF - Gene-level copy number'), ('s', 'VCF - Gene-level splice'), ('w', 'Gene Wiki records'), ('W', 'Variant Wiki records')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='uploadsettingsfiletype',
            name='file_type',
            field=models.CharField(choices=[('N', 'Analysis'), ('B', 'BED'), ('L', 'Clinvar'), ('F', 'DRAGEN TSO500 AllFusions'), ('C', 'DRAGEN TSO500 Combined Variant Output'), ('Q', 'DRAGEN TSO500 Metrics Output'), ('G', 'Gene List'), ('O', 'Gene Coverage'), ('I', 'Liftover'), ('M', 'Manual Variant Entry'), ('P', 'Pedigree'), ('R', 'Patient Records'), ('S', 'Variant Classifications'), ('A', 'Variant Tags'), ('V', 'VCF'), ('Y', 'VCF - Insert variants only (no samples etc)'), ('y', 'VCF - Insert gene-level variants only'), ('c', 'VCF - Gene-level copy number'), ('s', 'VCF - Gene-level splice'), ('w', 'Gene Wiki records'), ('W', 'Variant Wiki records')], max_length=1, null=True),
        ),
    ]
