# Generated by Django 6.1.1 on 2026-09-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0048_gene_level_splice_vcf_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDragenTSO500CombinedVariantOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.fileupload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
