# Generated by Django 6.1.1 on 2026-10-01 08:04

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # upload_modifiedimportedvariant is ~75M rows on large deployments - build without locking out writes
    atomic = False

    dependencies = [
        ("upload", "0049_uploaded_dragen_tso500_combined_variant_output"),
    ]

    operations = [
        # An earlier version of this migration built plain btrees, which fail on long values and can leave
        # an INVALID index behind from the concurrent build
        migrations.RunSQL(
            "DROP INDEX CONCURRENTLY IF EXISTS upload_miv_old_multiallelic",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP INDEX CONCURRENTLY IF EXISTS upload_miv_old_var_fmt",
            reverse_sql=migrations.RunSQL.noop,
        ),
        AddIndexConcurrently(
            model_name="modifiedimportedvariant",
            index=django.contrib.postgres.indexes.HashIndex(
                condition=models.Q(("old_multiallelic__isnull", False)),
                fields=["old_multiallelic"],
                name="upload_miv_old_multi_hash",
            ),
        ),
        AddIndexConcurrently(
            model_name="modifiedimportedvariant",
            index=models.Index(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Substr("old_variant_formatted", 1, 200),
                    name="text_pattern_ops",
                ),
                condition=models.Q(("old_variant_formatted__isnull", False)),
                name="upload_miv_old_var_prefix",
            ),
        ),
    ]
