# Generated by Django 6.1.1 on 2026-10-01 08:04

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # upload_modifiedimportedvariant is ~75M rows on large deployments - build without locking out writes
    atomic = False

    dependencies = [
        ("upload", "0049_uploaded_dragen_tso500_combined_variant_output"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="modifiedimportedvariant",
            index=models.Index(
                condition=models.Q(("old_multiallelic__isnull", False)),
                fields=["old_multiallelic"],
                name="upload_miv_old_multiallelic",
            ),
        ),
        AddIndexConcurrently(
            model_name="modifiedimportedvariant",
            index=models.Index(
                condition=models.Q(("old_variant_formatted__isnull", False)),
                fields=["old_variant_formatted"],
                name="upload_miv_old_var_fmt",
                opclasses=["text_pattern_ops"],
            ),
        ),
    ]
