# Generated by Django 6.1.1 on 2026-10-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "upload",
            "0052_one_off_backfill_uploaded_dragen_tso500_combined_variant_output",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadpipeline",
            name="error_summary",
            field=models.TextField(null=True),
        ),
    ]
