# Generated by Django 6.0.6 on 2026-07-28 06:22

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_deployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualGateSatisfied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField()),
                ('source_version', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='manualmigrationtask',
            name='requires',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
