# Generated by Django 3.1 on 2020-09-29 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import library.django_utils.guardian_permissions_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuffDiffFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('annotation_level', models.CharField(choices=[('T', 'Transcript'), ('G', 'Gene Symbol')], max_length=1)),
                ('import_status', models.CharField(choices=[('C', 'created'), ('I', 'importing'), ('R', 'Requires user input'), ('E', 'error'), ('S', 'success'), ('M', 'Marked For Deletion'), ('D', 'Deleting')], default='C', max_length=1)),
                ('sample_1', models.TextField()),
                ('sample_2', models.TextField()),
                ('imported_records', models.IntegerField(null=True)),
                ('matched_records', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(library.django_utils.guardian_permissions_mixin.GuardianPermissionsAutoInitialSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CuffDiffRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.TextField()),
                ('reference_id', models.TextField()),
                ('locus', models.TextField()),
                ('status', models.TextField()),
                ('value_1', models.FloatField()),
                ('value_2', models.FloatField()),
                ('log2_fold_change', models.FloatField()),
                ('test_stat', models.FloatField()),
                ('p_value', models.FloatField()),
                ('q_value', models.FloatField()),
                ('cuff_diff_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expression.cuffdifffile')),
                ('gene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.gene')),
                ('transcript', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genes.transcript')),
            ],
        ),
    ]
