# Generated by Django 4.1.4 on 2023-09-15 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0016_alter_uploadedfile_file_type_and_more"),
        ("analysis", "0075_delete_expressionnode"),
        ("expression", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuffdiffrecord",
            name="cuff_diff_file",
        ),
        migrations.RemoveField(
            model_name="cuffdiffrecord",
            name="gene",
        ),
        migrations.RemoveField(
            model_name="cuffdiffrecord",
            name="transcript",
        ),
        migrations.DeleteModel(
            name="CuffDiffFile",
        ),
        migrations.DeleteModel(
            name="CuffDiffRecord",
        ),
    ]
