"""
Adversarial unit tests for analysis node filter logic.

Targets three confirmed bugs:

  Bug 1 — AbstractZygosityCountNode.get_zygosity_count_arg_q_dict() (zygosity_count_node.py:38)
    `if max_count:` is falsy when max_count=0, so the __lte filter is silently skipped.
    User intent: "show variants seen in 0 samples" — but no filter is applied.

  Bug 2 — AbstractZygosityCountNode._get_zygosity_count_description() (zygosity_count_node.py:56-62)
    Same `if max_count:` falsy check, so max=0 never appears in the display description.

  Bug 3 — PopulationNode.modifies_parents() (population_node.py:60-61)
    `self.gnomad_hom_alt_max` is 0 → falsy → modifies_parents() returns False →
    the gnomad_hom_alt filter generated by _get_node_q() is never applied to the queryset.

Tests 1-3 (ZygosityCountZeroBug) and 4-6 (PopulationNodeModifiesParents) FAIL before the fix.
Tests 7-8 (PopulationNodeGroupOperationQ) document the intentionally-inverted ANY/ALL operator;
they PASS before and after (no bug, just a correctness invariant).
"""

from django.contrib.auth.models import User
from django.test import TestCase, override_settings

from analysis.models import Analysis, AllVariantsNode
from analysis.models.enums import GroupOperation
from analysis.models.nodes.filters.population_node import PopulationNode
from annotation.fake_annotation import get_fake_annotation_version
from snpdb.models import GenomeBuild


# ---------------------------------------------------------------------------
# Shared setup mixin — creates the minimum DB state needed by all test classes
# ---------------------------------------------------------------------------

class _AnalysisSetupMixin:
    """Provides cls.analysis and cls.grch37 via setUpTestData."""

    @classmethod
    def setUpTestData(cls):
        super().setUpTestData()
        user = User.objects.get_or_create(username=f"node_filter_bug_{cls.__name__}")[0]
        cls.grch37 = GenomeBuild.get_name_or_alias("GRCh37")
        get_fake_annotation_version(cls.grch37)
        cls.analysis = Analysis(genome_build=cls.grch37)
        cls.analysis.set_defaults_and_save(user)


# ---------------------------------------------------------------------------
# Bug 1 & 2: AbstractZygosityCountNode — max_count=0 falsy check
# ---------------------------------------------------------------------------

@override_settings(ANALYSIS_NODE_CACHE_Q=False)
class TestZygosityCountZeroBug(_AnalysisSetupMixin, TestCase):
    """
    AbstractZygosityCountNode.get_zygosity_count_arg_q_dict():

        if max_count:                      # line 38 — BUG
            q_and.append(Q(col__lte=max_count))

    When max_count=0 the condition is False, so the filter is never created.
    """

    def _node_with_max_zero(self):
        node = AllVariantsNode(analysis=self.analysis)
        node.max_het_or_hom_count = 0
        return node

    def test_max_count_zero_produces_lte_filter(self):
        """max_count=0 must generate a col__lte=0 filter — `if max_count:` silently drops it."""
        node = self._node_with_max_zero()
        arg_q_dict = node.get_zygosity_count_arg_q_dict()

        all_q_strs = [
            str(q)
            for q_dict in arg_q_dict.values()
            for q in q_dict.values()
        ]
        self.assertTrue(
            any("__lte" in s for s in all_q_strs),
            f"max_count=0 produced no __lte filter — falsy-check bug present. "
            f"Got Q strings: {all_q_strs}",
        )

    def test_max_count_zero_differs_from_no_max(self):
        """max_count=0 and max_count=None must produce different Q dicts."""
        node_zero = self._node_with_max_zero()
        node_none = AllVariantsNode(analysis=self.analysis)
        # max_het_or_hom_count defaults to None (nullable field)

        q_zero = str(node_zero.get_zygosity_count_arg_q_dict())
        q_none = str(node_none.get_zygosity_count_arg_q_dict())

        self.assertNotEqual(
            q_zero,
            q_none,
            "max_count=0 and max_count=None produce identical Q dicts — "
            "the falsy-check bug treats 0 the same as None",
        )

    def test_description_shows_max_zero(self):
        """_get_zygosity_count_description() must include '0' when max_count=0."""
        node = self._node_with_max_zero()
        desc = node._get_zygosity_count_description()
        self.assertIn(
            "0",
            desc,
            f"max_count=0 disappeared from description (falsy-check bug). "
            f"Got: {desc!r}",
        )


# ---------------------------------------------------------------------------
# Bug 3: PopulationNode.modifies_parents() — gnomad_hom_alt_max=0 falsy
# ---------------------------------------------------------------------------

@override_settings(ANALYSIS_NODE_CACHE_Q=False)
class TestPopulationNodeModifiesParents(_AnalysisSetupMixin, TestCase):
    """
    PopulationNode.modifies_parents() (population_node.py:60-61):

        return any([self.filtering_by_population, self.use_internal_counts,
                    self.gnomad_hom_alt_max,          # BUG: 0 is falsy
                    not self.show_gnomad_filtered])

    When gnomad_hom_alt_max=0 (filter out variants with ANY hom-alt carriers),
    modifies_parents() returns False and the filter generated by _get_node_q()
    is never applied to the queryset.
    """

    def _node(self, **kwargs):
        """Return an unsaved PopulationNode with 100% (no population AF filter) by default."""
        defaults = dict(percent=PopulationNode.EVERYTHING, show_gnomad_filtered=True)
        defaults.update(kwargs)
        return PopulationNode(analysis=self.analysis, **defaults)

    # --- the bug ---

    def test_gnomad_hom_alt_max_zero_modifies_parents(self):
        """gnomad_hom_alt_max=0 IS a real filter; modifies_parents() must return True."""
        node = self._node(gnomad_hom_alt_max=0)
        self.assertTrue(
            node.modifies_parents(),
            "gnomad_hom_alt_max=0 causes modifies_parents()=False — "
            "falsy-check bug; filter is silently skipped",
        )

    def test_gnomad_hom_alt_max_zero_q_filter_is_not_none(self):
        """_get_node_q() must generate a Q object for gnomad_hom_alt_max=0."""
        node = self._node(gnomad_hom_alt_max=0)
        q = node._get_node_q()
        # _get_node_q() already uses `is not None`, so this passes even before the fix.
        # Its purpose: confirm the Q exists and the only missing piece is modifies_parents().
        self.assertIsNotNone(
            q,
            "_get_node_q() returned None for gnomad_hom_alt_max=0 — "
            "filter not generated at all",
        )

    # --- correct behaviour for neighbouring cases ---

    def test_gnomad_hom_alt_max_none_does_not_modify_alone(self):
        """gnomad_hom_alt_max=None with no other filters → modifies_parents() is False."""
        node = self._node(gnomad_hom_alt_max=None)
        self.assertFalse(node.modifies_parents())

    def test_gnomad_hom_alt_max_positive_modifies_parents(self):
        """Positive gnomad_hom_alt_max still works correctly (not regressed by fix)."""
        node = self._node(gnomad_hom_alt_max=5)
        self.assertTrue(node.modifies_parents())


# ---------------------------------------------------------------------------
# PopulationNode group operation Q structure (no bug — invariant documentation)
# ---------------------------------------------------------------------------

@override_settings(ANALYSIS_NODE_CACHE_Q=False)
class TestPopulationNodeGroupOperationQ(_AnalysisSetupMixin, TestCase):
    """
    PopulationNode uses *inverted* operators for ANY/ALL (see comment in source):

        OPERATIONS = {
            GroupOperation.ALL: operator.or_,   # inverted
            GroupOperation.ANY: operator.and_,  # inverted
        }

    Semantics:
      ANY (strict)  — remove if above cutoff in ANY database → AND all per-db filters.
      ALL (lenient) — remove only if above cutoff in ALL databases → OR per-db filters.

    These tests document that the observable Q structure is correct. They pass before
    and after any bug fixes.
    """

    def _pop_node_q(self, group_operation):
        """Create a saved node using gnomad_af + af_1kg + af_uk10k at 1% and return _get_node_q().
        Must be saved so that self.populationnodegnomadpopulation_set.all() can run."""
        node = PopulationNode.objects.create(
            analysis=self.analysis,
            percent=1.0,
            group_operation=group_operation,
            gnomad_af=True,
            gnomad_popmax_af=False,
            af_1kg=True,
            af_uk10k=True,
            topmed_af=False,
        )
        return node._get_node_q()

    def test_any_group_operation_combines_with_and(self):
        """GroupOperation.ANY → AND of per-db filters (all must pass → strict)."""
        q = self._pop_node_q(GroupOperation.ANY)
        self.assertIsNotNone(q)
        q_str = str(q)
        self.assertTrue(
            q_str.startswith("(AND:"),
            f"ANY mode should combine filters with AND, got: {q_str!r}",
        )

    def test_all_group_operation_combines_with_or(self):
        """GroupOperation.ALL → OR of per-db filters (any can pass → lenient)."""
        q = self._pop_node_q(GroupOperation.ALL)
        self.assertIsNotNone(q)
        q_str = str(q)
        self.assertTrue(
            q_str.startswith("(OR:"),
            f"ALL mode should combine filters with OR, got: {q_str!r}",
        )
