# Generated by Django 4.0.2 on 2022-03-03 04:32

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_match_patient_phenotypes(apps):
    PatientTextPhenotype = apps.get_model("annotation", "PatientTextPhenotype")
    return PatientTextPhenotype.objects.exists()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0038_auto_20211223_1532'),  # After refactoring to add ontology terms etc
        ('patients', '0001_initial'),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["match_patient_phenotypes", "--clear"]),
                        test=_test_match_patient_phenotypes),
    ]
