# Generated by Django 4.2.11 on 2024-11-26 01:17

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _test_match_patient_phenotypes(apps):
    PatientTextPhenotype = apps.get_model("annotation", "PatientTextPhenotype")
    return PatientTextPhenotype.objects.exists()


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_one_off_manual_rematch_patients"),
    ]

    operations = [
        ManualOperation(task_id=ManualOperation.task_id_manage(["match_patient_phenotypes", "--clear"]),
                        test=_test_match_patient_phenotypes),
    ]
