# Generated by Django 4.2.15 on 2025-07-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_one_off_fix_patient_imports_and_modifications"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientrecord",
            old_name="sample_id",
            new_name="sample_identifier",
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_patient",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="patient_match",
            field=models.CharField(
                choices=[("C", "CREATED"), ("E", "EXACT"), ("P", "PARTIAL")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="specimen",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_specimen",
                to="patients.specimen",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="specimen_match",
            field=models.CharField(
                choices=[("C", "CREATED"), ("E", "EXACT"), ("P", "PARTIAL")],
                max_length=1,
                null=True,
            ),
        ),
    ]
