# Generated by Django 4.2.15 on 2025-07-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snpdb", "0169_alter_settingsoverride_grid_sample_label_template"),
        ("patients", "0005_rename_sample_id_patientrecord_sample_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="sample",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="snpdb.sample",
            ),
        ),
    ]
