# Generated by Django 4.2.15 on 2025-07-07 07:11

from django.db import migrations
from django.db.models.expressions import F
from django.db.models.query_utils import Q


def _one_off_new_patient_records(apps, _schema_editor):
    Sample = apps.get_model("snpdb", "Sample")
    PatientRecord = apps.get_model("patients", "PatientRecord")

    sample_ids = set(str(s) for s in Sample.objects.values_list("id", flat=True))

    # Properly link to FK
    pr_qs = PatientRecord.objects.filter(matched_sample_id__isnull=False)
    pr_qs.filter(matched_sample_id__in=sample_ids).update(sample_id=F("matched_sample_id"))

    PATIENT_RECORD_MATCH_CREATED = 'C'
    PATIENT_RECORD_MATCH_EXACT = 'E'
    PATIENT_RECORD_MATCH_PARTIAL = 'P'

    # Created
    PatientRecord.objects.filter(created_patient__isnull=False).update(patient=F("created_patient"),
                                                                       patient_match=PATIENT_RECORD_MATCH_CREATED,
                                                                       created_patient=None)
    PatientRecord.objects.filter(created_specimen__isnull=False).update(specimen=F("created_specimen"),
                                                                        specimen_match=PATIENT_RECORD_MATCH_CREATED,
                                                                        created_specimen=None)

    # Matched
    # Find partials first
    q_sex_partial = Q(sex__isnull=False, matched_patient__sex='U')
    q_dob_partial = Q(date_of_birth__isnull=False, matched_patient__date_of_birth__isnull=True)
    PatientRecord.objects.filter(q_sex_partial | q_dob_partial).update(patient=F("matched_patient"),
                                                                       patient_match=PATIENT_RECORD_MATCH_PARTIAL,
                                                                       matched_patient=None)
    # Anything left must be exact match
    PatientRecord.objects.filter(matched_patient__isnull=False).update(patient=F("matched_patient"),
                                                                       patient_match=PATIENT_RECORD_MATCH_EXACT,
                                                                       matched_patient=None)

    PatientRecord.objects.filter(matched_specimen__isnull=False).update(specimen=F("matched_specimen"),
                                                                        specimen_match=PATIENT_RECORD_MATCH_EXACT,
                                                                        matched_specimen=None)


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_patientrecord_sample"),
    ]

    operations = [
        migrations.RunPython(_one_off_new_patient_records),
    ]
