# Generated by Django 4.2.15 on 2025-07-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_one_off_new_patient_records"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientrecord",
            name="created_patient",
        ),
        migrations.RemoveField(
            model_name="patientrecord",
            name="created_specimen",
        ),
        migrations.RemoveField(
            model_name="patientrecord",
            name="matched_patient",
        ),
        migrations.RemoveField(
            model_name="patientrecord",
            name="matched_sample_id",
        ),
        migrations.RemoveField(
            model_name="patientrecord",
            name="matched_specimen",
        ),
    ]
