# Generated by Django 4.2.20 on 2025-07-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_patientrecord_created_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_match',
            field=models.CharField(choices=[('C', 'CREATED'), ('E', 'MATCHED EXACT'), ('P', 'MATCHED PARTIAL')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='specimen_match',
            field=models.CharField(choices=[('C', 'CREATED'), ('E', 'MATCHED EXACT'), ('P', 'MATCHED PARTIAL')], max_length=1, null=True),
        ),
    ]
