# Generated by Django 5.2.8 on 2025-11-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_alter_patientrecord_patient_match_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="research_consent",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
