# Generated by Django 6.0.3 on 2026-05-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0010_patient_research_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="patient_code",
            field=models.TextField(null=True),
        ),
    ]
