# Generated by Django 6.1 on 2026-08-11 12:03

import django.db.models.deletion
import django_extensions.db.fields
import library.django_utils.guardian_permissions_mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_specimen_tissue_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('measure_type', models.CharField(choices=[('T', 'Tumour mutational burden'), ('M', 'Microsatellite instability'), ('G', 'Genomic instability score'), ('F', 'Tumour fraction'), ('P', 'Ploidy')], max_length=1)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('call', models.TextField(blank=True, null=True)),
                ('threshold', models.TextField(blank=True, null=True)),
                ('threshold_source', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('measured_date', models.DateTimeField(blank=True, null=True)),
                ('extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.extraction')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.specimen')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('specimen', 'measure_type')},
            },
            bases=(library.django_utils.guardian_permissions_mixin.GuardianPermissionsMixin, models.Model),
        ),
    ]
