# Generated by Django 6.1 on 2026-08-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_specimenmeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
