from dataclasses import dataclass
from typing import Optional

from annotation.models.models_enums import (
    ColumnAnnotationCategory,
    VariantAnnotationPipelineType,
    VEPCustom,
    VEPPlugin,
)


@dataclass(frozen=True)
class VEPColumnDef:
    """ Maps a VEP CSQ / plugin / custom output field -> one or more VariantGridColumn destinations.
        Empty `genome_builds` / `pipeline_types` mean "applies to all". """

    source_field: Optional[str]
    variant_grid_columns: tuple[str, ...]
    category: ColumnAnnotationCategory
    vep_plugin: Optional[VEPPlugin] = None
    vep_custom: Optional[VEPCustom] = None
    source_field_has_custom_prefix: bool = False
    genome_builds: frozenset[str] = frozenset()
    pipeline_types: frozenset[VariantAnnotationPipelineType] = frozenset()
    min_columns_version: Optional[int] = None
    max_columns_version: Optional[int] = None
    min_vep_version: Optional[int] = None
    max_vep_version: Optional[int] = None
    summary_stats: Optional[str] = None
    source_field_processing_description: Optional[str] = None

    @property
    def vep_info_field(self) -> Optional[str]:
        """ Replicates ColumnVEPField.vep_info_field. """
        vif = self.source_field
        if self.vep_custom and self.source_field_has_custom_prefix:
            prefix = self.vep_custom.label
            vif = f"{prefix}_{vif}" if vif else prefix
        return vif

    @property
    def columns_version_description(self) -> str:
        limits = []
        if self.min_columns_version:
            limits.append(f"column version >= {self.min_columns_version}")
        if self.max_columns_version:
            limits.append(f"column version <= {self.max_columns_version}")
        return " and ".join(limits)

    def applies_to(
        self,
        *,
        genome_build_name: Optional[str] = None,
        pipeline_type: Optional[VariantAnnotationPipelineType] = None,
        columns_version: Optional[int] = None,
        vep_version: Optional[int] = None,
    ) -> bool:
        if genome_build_name is not None and self.genome_builds and genome_build_name not in self.genome_builds:
            return False
        if pipeline_type is not None and self.pipeline_types and pipeline_type not in self.pipeline_types:
            return False
        if columns_version is not None:
            if self.min_columns_version is not None and columns_version < self.min_columns_version:
                return False
            if self.max_columns_version is not None and columns_version > self.max_columns_version:
                return False
        if vep_version is not None:
            if self.min_vep_version is not None and vep_version < self.min_vep_version:
                return False
            if self.max_vep_version is not None and vep_version > self.max_vep_version:
                return False
        return True


VEP_COLUMNS: tuple[VEPColumnDef, ...] = (
    VEPColumnDef(
        source_field='AF',
        variant_grid_columns=('af_1kg',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
    ),
    VEPColumnDef(
        source_field='AF',
        variant_grid_columns=('af_uk10k',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.UK10K,
        source_field_has_custom_prefix=True,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='Ensembl_transcriptid',
        variant_grid_columns=('aloft_ensembl_transcript',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
        source_field_processing_description='Most damaging transcript prediction chosen, and Ensembl transcript stored.',
    ),
    VEPColumnDef(
        source_field='Aloft_Confidence',
        variant_grid_columns=('aloft_high_confidence',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
        source_field_processing_description='Most damaging transcript prediction chosen, and Ensembl transcript stored.',
    ),
    VEPColumnDef(
        source_field='Aloft_pred',
        variant_grid_columns=('aloft_pred',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
        source_field_processing_description='Most damaging transcript prediction chosen, and Ensembl transcript stored.',
    ),
    VEPColumnDef(
        source_field='Aloft_prob_Dominant',
        variant_grid_columns=('aloft_prob_dominant',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
        source_field_processing_description='Most damaging transcript prediction chosen, and Ensembl transcript stored.',
    ),
    VEPColumnDef(
        source_field='Aloft_prob_Recessive',
        variant_grid_columns=('aloft_prob_recessive',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
        source_field_processing_description='Most damaging transcript prediction chosen, and Ensembl transcript stored.',
    ),
    VEPColumnDef(
        source_field='Aloft_prob_Tolerant',
        variant_grid_columns=('aloft_prob_tolerant',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
        source_field_processing_description='Most damaging transcript prediction chosen, and Ensembl transcript stored.',
    ),
    VEPColumnDef(
        source_field='AlphaMissense_rankscore',
        variant_grid_columns=('alphamissense_rankscore',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='Amino_acids',
        variant_grid_columns=('amino_acids',),
        category=ColumnAnnotationCategory.GENE_ANNOTATIONS,
    ),
    VEPColumnDef(
        source_field='BayesDel_noAF_rankscore',
        variant_grid_columns=('bayesdel_noaf_rankscore',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
    ),
    VEPColumnDef(
        source_field='CADD_phred',
        variant_grid_columns=('cadd_phred',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=1,
    ),
    VEPColumnDef(
        source_field='CADD_raw_rankscore',
        variant_grid_columns=('cadd_raw_rankscore',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
    ),
    VEPColumnDef(
        source_field='CANONICAL',
        variant_grid_columns=('canonical',),
        category=ColumnAnnotationCategory.GENE_ANNOTATIONS,
    ),
    VEPColumnDef(
        source_field='ClinPred_rankscore',
        variant_grid_columns=('clinpred_rankscore',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
    ),
    VEPColumnDef(
        source_field='Codons',
        variant_grid_columns=('codons',),
        category=ColumnAnnotationCategory.GENE_ANNOTATIONS,
    ),
    VEPColumnDef(
        source_field='Consequence',
        variant_grid_columns=('consequence',),
        category=ColumnAnnotationCategory.GENE_ANNOTATIONS,
    ),
    VEPColumnDef(
        source_field='CNT',
        variant_grid_columns=('cosmic_count',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.COSMIC,
        source_field_has_custom_prefix=True,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='Existing_variation',
        variant_grid_columns=('cosmic_id',),
        category=ColumnAnnotationCategory.EXTERNAL_ID,
        source_field_processing_description='Extract COSMIC IDs',
    ),
    VEPColumnDef(
        source_field='LEGACY_ID',
        variant_grid_columns=('cosmic_legacy_id',),
        category=ColumnAnnotationCategory.EXTERNAL_ID,
        vep_custom=VEPCustom.COSMIC,
        source_field_has_custom_prefix=True,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='ada_score',
        variant_grid_columns=('dbscsnv_ada_score',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.DBSCSNV,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='rf_score',
        variant_grid_columns=('dbscsnv_rf_score',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.DBSCSNV,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='Existing_variation',
        variant_grid_columns=('dbsnp_rs_id',),
        category=ColumnAnnotationCategory.EXTERNAL_ID,
        source_field_processing_description='Extract rsIDs',
    ),
    VEPColumnDef(
        source_field='DISTANCE',
        variant_grid_columns=('distance',),
        category=ColumnAnnotationCategory.NEARBY_FEATURES,
    ),
    VEPColumnDef(
        source_field='DOMAINS',
        variant_grid_columns=('domains',),
        category=ColumnAnnotationCategory.PROTEIN_DOMAINS,
    ),
    VEPColumnDef(
        source_field='ENSP',
        variant_grid_columns=('ensembl_protein',),
        category=ColumnAnnotationCategory.EXTERNAL_ID,
    ),
    VEPColumnDef(
        source_field='EXON',
        variant_grid_columns=('exon',),
        category=ColumnAnnotationCategory.GENE_ANNOTATIONS,
    ),
    VEPColumnDef(
        source_field='FATHMM_pred',
        variant_grid_columns=('fathmm_pred_most_damaging',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=1,
        source_field_processing_description='Most damaging',
    ),
    VEPColumnDef(
        source_field='FLAGS',
        variant_grid_columns=('flags',),
        category=ColumnAnnotationCategory.GENE_ANNOTATIONS,
    ),
    VEPColumnDef(
        source_field='GERP++_RS',
        variant_grid_columns=('gerp_pp_rs',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='AF',
        variant_grid_columns=('gnomad2_liftover_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='AC',
        variant_grid_columns=('gnomad_ac',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AC',
        variant_grid_columns=('gnomad_ac',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AC',
        variant_grid_columns=('gnomad_ac',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='AC',
        variant_grid_columns=('gnomad_ac',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='Sum of exome AC + genome AC',
    ),
    VEPColumnDef(
        source_field='AF',
        variant_grid_columns=('gnomad_sv_overlap_af', 'gnomad_af'),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF',
        variant_grid_columns=('gnomad_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AF',
        variant_grid_columns=('gnomad_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='AF',
        variant_grid_columns=('gnomad_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='(exome_AC+genome_AC)/(exome_AN+genome_AN)',
    ),
    VEPColumnDef(
        source_field='AF_afr',
        variant_grid_columns=('gnomad_afr_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='(exome_AC+genome_AC)/(exome_AN+genome_AN)',
    ),
    VEPColumnDef(
        source_field='afr_AF',
        variant_grid_columns=('gnomad_afr_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF_afr',
        variant_grid_columns=('gnomad_afr_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AF-afr',
        variant_grid_columns=('gnomad_afr_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='AFR_AF',
        variant_grid_columns=('gnomad_afr_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF-amr',
        variant_grid_columns=('gnomad_amr_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='AF_amr',
        variant_grid_columns=('gnomad_amr_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='amr_AF',
        variant_grid_columns=('gnomad_amr_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AMR_AF',
        variant_grid_columns=('gnomad_amr_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF_amr',
        variant_grid_columns=('gnomad_amr_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='(exome_AC+genome_AC)/(exome_AN+genome_AN)',
    ),
    VEPColumnDef(
        source_field='AN',
        variant_grid_columns=('gnomad_an',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='Sum of exome AN + genome AN',
    ),
    VEPColumnDef(
        source_field='AN',
        variant_grid_columns=('gnomad_an',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AN',
        variant_grid_columns=('gnomad_an',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AN',
        variant_grid_columns=('gnomad_an',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='AF_asj',
        variant_grid_columns=('gnomad_asj_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AF-asj',
        variant_grid_columns=('gnomad_asj_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='asj_AF',
        variant_grid_columns=('gnomad_asj_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF_asj',
        variant_grid_columns=('gnomad_asj_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='(exome_AC+genome_AC)/(exome_AN+genome_AN)',
    ),
    VEPColumnDef(
        source_field='AF_eas',
        variant_grid_columns=('gnomad_eas_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='eas_AF',
        variant_grid_columns=('gnomad_eas_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF-eas',
        variant_grid_columns=('gnomad_eas_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='EAS_AF',
        variant_grid_columns=('gnomad_eas_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF_eas',
        variant_grid_columns=('gnomad_eas_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='(exome_AC+genome_AC)/(exome_AN+genome_AN)',
    ),
    VEPColumnDef(
        source_field='faf95',
        variant_grid_columns=('gnomad_faf95',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='faf99',
        variant_grid_columns=('gnomad_faf99',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='fafmax_faf95_max',
        variant_grid_columns=('gnomad_fafmax_faf95_max',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='fafmax_faf99_max',
        variant_grid_columns=('gnomad_fafmax_faf99_max',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='FILTER',
        variant_grid_columns=('gnomad_filtered',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='gnomad_filtered',
        variant_grid_columns=('gnomad_filtered',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='gnomad_filtered',
        variant_grid_columns=('gnomad_filtered',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='Filtered in either exome or genomes VCF',
    ),
    VEPColumnDef(
        source_field='AF-fin',
        variant_grid_columns=('gnomad_fin_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='AF_fin',
        variant_grid_columns=('gnomad_fin_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AF_fin',
        variant_grid_columns=('gnomad_fin_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='(exome_AC+genome_AC)/(exome_AN+genome_AN)',
    ),
    VEPColumnDef(
        source_field='fin_AF',
        variant_grid_columns=('gnomad_fin_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='nhomalt',
        variant_grid_columns=('gnomad_hom_alt',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='nhomalt',
        variant_grid_columns=('gnomad_hom_alt',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='exome_nhomalt + genome_nhomalt',
    ),
    VEPColumnDef(
        source_field='nhomalt',
        variant_grid_columns=('gnomad_hom_alt',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='N_HOMALT',
        variant_grid_columns=('gnomad_hom_alt',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF_mid',
        variant_grid_columns=('gnomad_mid_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='mid_AF',
        variant_grid_columns=('gnomad_mid_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF-nfe',
        variant_grid_columns=('gnomad_nfe_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='nfe_AF',
        variant_grid_columns=('gnomad_nfe_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='EUR_AF',
        variant_grid_columns=('gnomad_nfe_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF_nfe',
        variant_grid_columns=('gnomad_nfe_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AF_nfe',
        variant_grid_columns=('gnomad_nfe_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='(exome_AC+genome_AC)/(exome_AN+genome_AN)',
    ),
    VEPColumnDef(
        source_field='nonpar',
        variant_grid_columns=('gnomad_non_par',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='nonpar from genomes',
    ),
    VEPColumnDef(
        source_field='non_par',
        variant_grid_columns=('gnomad_non_par',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
        source_field_processing_description='nonpar from genomes',
    ),
    VEPColumnDef(
        source_field='oth_AF',
        variant_grid_columns=('gnomad_oth_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF_remaining',
        variant_grid_columns=('gnomad_oth_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AF_oth',
        variant_grid_columns=('gnomad_oth_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='OTH_AF',
        variant_grid_columns=('gnomad_oth_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF-oth',
        variant_grid_columns=('gnomad_oth_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='grpmax',
        variant_grid_columns=('gnomad_popmax',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='popmax',
        variant_grid_columns=('gnomad_popmax',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='popmax',
        variant_grid_columns=('gnomad_popmax',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='AC_grpmax',
        variant_grid_columns=('gnomad_popmax_ac',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AC_popmax',
        variant_grid_columns=('gnomad_popmax_ac',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='Sum of exome AC_popmax + genome AC_popmax',
    ),
    VEPColumnDef(
        source_field='AC_popmax',
        variant_grid_columns=('gnomad_popmax_ac',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='AF_grpmax',
        variant_grid_columns=('gnomad_popmax_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AF_popmax',
        variant_grid_columns=('gnomad_popmax_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='Re-calculated from max (exome_AC+genome_AC)/(exome_AN+genome_AN)',
    ),
    VEPColumnDef(
        source_field='AF_popmax',
        variant_grid_columns=('gnomad_popmax_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='POPMAX_AF',
        variant_grid_columns=('gnomad_popmax_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AN_popmax',
        variant_grid_columns=('gnomad_popmax_an',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='AN_popmax',
        variant_grid_columns=('gnomad_popmax_an',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='Sum of exome AN_popmax + genome AN_popmax',
    ),
    VEPColumnDef(
        source_field='AN_grpmax',
        variant_grid_columns=('gnomad_popmax_an',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='nhomalt_popmax',
        variant_grid_columns=('gnomad_popmax_hom_alt',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='sas_AF',
        variant_grid_columns=('gnomad_sas_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AF_sas',
        variant_grid_columns=('gnomad_sas_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='(exome_AC+genome_AC)/(exome_AN+genome_AN)',
    ),
    VEPColumnDef(
        source_field='AF-sas',
        variant_grid_columns=('gnomad_sas_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_3,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=2,
    ),
    VEPColumnDef(
        source_field='AF_sas',
        variant_grid_columns=('gnomad_sas_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='',
        variant_grid_columns=('gnomad_sv_overlap_coords', 'gnomad_sv_overlap_percent'),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV,
        source_field_has_custom_prefix=True,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='gnomAD_SV_name',
        variant_grid_columns=('gnomad_sv_overlap_name',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_SV_NAME,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STRUCTURAL_VARIANT}),
    ),
    VEPColumnDef(
        source_field='AC_male',
        variant_grid_columns=('gnomad_xy_ac',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AC_XY',
        variant_grid_columns=('gnomad_xy_ac',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AF_male',
        variant_grid_columns=('gnomad_xy_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AF_XY',
        variant_grid_columns=('gnomad_xy_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AN_XY',
        variant_grid_columns=('gnomad_xy_an',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_4,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38', 'T2T-CHM13v2.0'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='AN_male',
        variant_grid_columns=('gnomad_xy_an',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.GNOMAD_2,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='Grantham',
        variant_grid_columns=('grantham',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.GRANTHAM,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='HGNC_ID',
        variant_grid_columns=('hgnc_id',),
        category=ColumnAnnotationCategory.EXTERNAL_ID,
    ),
    VEPColumnDef(
        source_field='HGVSc',
        variant_grid_columns=('hgvs_c',),
        category=ColumnAnnotationCategory.HGVS,
    ),
    VEPColumnDef(
        source_field='HGVSp',
        variant_grid_columns=('hgvs_p',),
        category=ColumnAnnotationCategory.HGVS,
    ),
    VEPColumnDef(
        source_field='IMPACT',
        variant_grid_columns=('impact',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
    ),
    VEPColumnDef(
        source_field='Interpro_domain',
        variant_grid_columns=('interpro_domain',),
        category=ColumnAnnotationCategory.PROTEIN_DOMAINS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='INTRON',
        variant_grid_columns=('intron',),
        category=ColumnAnnotationCategory.GENE_ANNOTATIONS,
    ),
    VEPColumnDef(
        source_field='Mastermind_counts',
        variant_grid_columns=('mastermind_count_1_cdna',),
        category=ColumnAnnotationCategory.LITERATURE,
        vep_plugin=VEPPlugin.MASTERMIND,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='MMCNT1',
    ),
    VEPColumnDef(
        source_field='Mastermind_counts',
        variant_grid_columns=('mastermind_count_2_cdna_prot',),
        category=ColumnAnnotationCategory.LITERATURE,
        vep_plugin=VEPPlugin.MASTERMIND,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='MMCNT2',
    ),
    VEPColumnDef(
        source_field='Mastermind_counts',
        variant_grid_columns=('mastermind_count_3_aa_change',),
        category=ColumnAnnotationCategory.LITERATURE,
        vep_plugin=VEPPlugin.MASTERMIND,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        source_field_processing_description='MMCNT3',
    ),
    VEPColumnDef(
        source_field='Mastermind_MMID3',
        variant_grid_columns=('mastermind_mmid3',),
        category=ColumnAnnotationCategory.LITERATURE,
        vep_plugin=VEPPlugin.MASTERMIND,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='MaveDB_score',
        variant_grid_columns=('mavedb_score',),
        category=ColumnAnnotationCategory.FUNCTIONAL_EFFECT,
        vep_plugin=VEPPlugin.MAVEDB,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='MaveDB_urn',
        variant_grid_columns=('mavedb_urn',),
        category=ColumnAnnotationCategory.FUNCTIONAL_EFFECT,
        vep_plugin=VEPPlugin.MAVEDB,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=3,
    ),
    VEPColumnDef(
        source_field='MaxEntScan_alt',
        variant_grid_columns=('maxentscan_alt',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.MAXENTSCAN,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='MaxEntScan_diff',
        variant_grid_columns=('maxentscan_diff',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.MAXENTSCAN,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='MaxEntScan_ref',
        variant_grid_columns=('maxentscan_ref',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.MAXENTSCAN,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='MetaLR_rankscore',
        variant_grid_columns=('metalr_rankscore',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
    ),
    VEPColumnDef(
        source_field='MutationAssessor_pred',
        variant_grid_columns=('mutation_assessor_pred_most_damaging',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=1,
        source_field_processing_description='Most damaging',
    ),
    VEPColumnDef(
        source_field='MutationTaster_pred',
        variant_grid_columns=('mutation_taster_pred_most_damaging',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=1,
        source_field_processing_description='Most damaging',
    ),
    VEPColumnDef(
        source_field='NMD',
        variant_grid_columns=('nmd_escaping_variant',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.NMD,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
    ),
    VEPColumnDef(
        source_field='phastCons100way_vertebrate',
        variant_grid_columns=('phastcons_100_way_vertebrate',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHASTCONS_100_WAY,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_vep_version=111,
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='max',
        variant_grid_columns=('phastcons_100_way_vertebrate',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHASTCONS_100_WAY,
        source_field_has_custom_prefix=True,
        min_vep_version=112,
        summary_stats='max',
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='max',
        variant_grid_columns=('phastcons_30_way_mammalian',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHASTCONS_30_WAY,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        min_vep_version=112,
        summary_stats='max',
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='phastCons30way_mammalian',
        variant_grid_columns=('phastcons_30_way_mammalian',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHASTCONS_30_WAY,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_vep_version=111,
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='max',
        variant_grid_columns=('phastcons_46_way_mammalian',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHASTCONS_46_WAY,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        min_vep_version=112,
        summary_stats='max',
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='phastCons46way_mammalian',
        variant_grid_columns=('phastcons_46_way_mammalian',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHASTCONS_46_WAY,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_vep_version=111,
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='phyloP100way_vertebrate',
        variant_grid_columns=('phylop_100_way_vertebrate',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHYLOP_100_WAY,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_vep_version=111,
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='max',
        variant_grid_columns=('phylop_100_way_vertebrate',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHYLOP_100_WAY,
        source_field_has_custom_prefix=True,
        min_vep_version=112,
        summary_stats='max',
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='phyloP30way_mammalian',
        variant_grid_columns=('phylop_30_way_mammalian',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHYLOP_30_WAY,
        genome_builds=frozenset({'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_vep_version=111,
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='max',
        variant_grid_columns=('phylop_30_way_mammalian',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHYLOP_30_WAY,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh38'}),
        min_vep_version=112,
        summary_stats='max',
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='max',
        variant_grid_columns=('phylop_46_way_mammalian',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHYLOP_46_WAY,
        source_field_has_custom_prefix=True,
        genome_builds=frozenset({'GRCh37'}),
        min_vep_version=112,
        summary_stats='max',
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='phyloP46way_mammalian',
        variant_grid_columns=('phylop_46_way_mammalian',),
        category=ColumnAnnotationCategory.CONSERVATION,
        vep_custom=VEPCustom.PHYLOP_46_WAY,
        genome_builds=frozenset({'GRCh37'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_vep_version=111,
        source_field_processing_description='max() for indels',
    ),
    VEPColumnDef(
        source_field='Polyphen2_HVAR_pred',
        variant_grid_columns=('polyphen2_hvar_pred_most_damaging',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=1,
        source_field_processing_description='Most damaging',
    ),
    VEPColumnDef(
        source_field='Protein_position',
        variant_grid_columns=('protein_position',),
        category=ColumnAnnotationCategory.GENE_ANNOTATIONS,
    ),
    VEPColumnDef(
        source_field='PUBMED',
        variant_grid_columns=('pubmed',),
        category=ColumnAnnotationCategory.LITERATURE,
    ),
    VEPColumnDef(
        source_field='REPEAT_MASKER',
        variant_grid_columns=('repeat_masker',),
        category=ColumnAnnotationCategory.SEQUENCE,
        vep_custom=VEPCustom.REPEAT_MASKER,
    ),
    VEPColumnDef(
        source_field='REVEL_rankscore',
        variant_grid_columns=('revel_rankscore',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
    ),
    VEPColumnDef(
        source_field='REVEL_score',
        variant_grid_columns=('revel_score',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        max_columns_version=1,
    ),
    VEPColumnDef(
        source_field='SIFT',
        variant_grid_columns=('sift',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
    ),
    VEPColumnDef(
        source_field='SOMATIC',
        variant_grid_columns=('somatic',),
        category=ColumnAnnotationCategory.EXTERNAL_ID,
        source_field_processing_description='Any values present',
    ),
    VEPColumnDef(
        source_field='SpliceAI_pred_SYMBOL',
        variant_grid_columns=('spliceai_gene_symbol',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.SPLICEAI,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='SpliceAI_pred_DP_AG',
        variant_grid_columns=('spliceai_pred_dp_ag',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.SPLICEAI,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='SpliceAI_pred_DP_AL',
        variant_grid_columns=('spliceai_pred_dp_al',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.SPLICEAI,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='SpliceAI_pred_DP_DG',
        variant_grid_columns=('spliceai_pred_dp_dg',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.SPLICEAI,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='SpliceAI_pred_DP_DL',
        variant_grid_columns=('spliceai_pred_dp_dl',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.SPLICEAI,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='SpliceAI_pred_DS_AG',
        variant_grid_columns=('spliceai_pred_ds_ag',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.SPLICEAI,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='SpliceAI_pred_DS_AL',
        variant_grid_columns=('spliceai_pred_ds_al',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.SPLICEAI,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='SpliceAI_pred_DS_DG',
        variant_grid_columns=('spliceai_pred_ds_dg',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.SPLICEAI,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='SpliceAI_pred_DS_DL',
        variant_grid_columns=('spliceai_pred_ds_dl',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.SPLICEAI,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='SpliceRegion',
        variant_grid_columns=('splice_region',),
        category=ColumnAnnotationCategory.SPLICING_PREDICTIONS,
        vep_plugin=VEPPlugin.SPLICEREGION,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='SYMBOL',
        variant_grid_columns=('symbol',),
        category=ColumnAnnotationCategory.GENE_ANNOTATIONS,
    ),
    VEPColumnDef(
        source_field='TOPMED',
        variant_grid_columns=('topmed_af',),
        category=ColumnAnnotationCategory.FREQUENCY_DATA,
        vep_custom=VEPCustom.TOPMED,
        source_field_has_custom_prefix=True,
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
    ),
    VEPColumnDef(
        source_field='VARIANT_CLASS',
        variant_grid_columns=('variant_class',),
        category=ColumnAnnotationCategory.GENE_ANNOTATIONS,
    ),
    VEPColumnDef(
        source_field='VEST4_rankscore',
        variant_grid_columns=('vest4_rankscore',),
        category=ColumnAnnotationCategory.PATHOGENICITY_PREDICTIONS,
        vep_plugin=VEPPlugin.DBNSFP,
        genome_builds=frozenset({'GRCh37', 'GRCh38'}),
        pipeline_types=frozenset({VariantAnnotationPipelineType.STANDARD}),
        min_columns_version=2,
    ),
)


def filter_for(
    *,
    genome_build_name: Optional[str] = None,
    pipeline_type: Optional[VariantAnnotationPipelineType] = None,
    columns_version: Optional[int] = None,
    vep_version: Optional[int] = None,
    vep_plugin: Optional[VEPPlugin] = None,
    vep_custom: Optional[VEPCustom] = None,
) -> tuple[VEPColumnDef, ...]:
    return tuple(
        c for c in VEP_COLUMNS
        if c.applies_to(
            genome_build_name=genome_build_name,
            pipeline_type=pipeline_type,
            columns_version=columns_version,
            vep_version=vep_version,
        )
        and (vep_plugin is None or c.vep_plugin == vep_plugin)
        and (vep_custom is None or c.vep_custom == vep_custom)
    )


def source_fields_for(**kwargs) -> list[str]:
    """ Distinct source_fields for the given filter, sorted case-insensitively
        (matches postgres `ORDER BY source_field` under default en_US collation). """
    return sorted({c.source_field for c in filter_for(**kwargs) if c.source_field}, key=str.lower)


def for_variant_grid_column(vgc_id: str) -> tuple[VEPColumnDef, ...]:
    return tuple(c for c in VEP_COLUMNS if vgc_id in c.variant_grid_columns)


def all_variant_grid_column_ids() -> frozenset[str]:
    return frozenset(vgc for c in VEP_COLUMNS for vgc in c.variant_grid_columns)
