VEP_COLUMNS = {
    'AF': [{'category': 'F', 'variant_grid_column': 'af_1kg'},
           {'pipeline_type': 'S',
            'category': 'F',
            'vep_custom': 'u',
            'source_field_has_custom_prefix': True,
            'variant_grid_column': 'af_uk10k'},
           {'genome_build_id': 'GRCh38',
            'pipeline_type': 'S',
            'category': 'F',
            'vep_custom': 'g',
            'source_field_has_custom_prefix': True,
            'variant_grid_column': 'gnomad2_liftover_af'},
           {'genome_build_id': 'GRCh37',
            'pipeline_type': 'S',
            'category': 'F',
            'source_field_processing_description': '(exome_AC+genome_AC)/(exome_AN+genome_AN)',
            'vep_custom': 'g',
            'source_field_has_custom_prefix': True,
            'variant_grid_column': 'gnomad_af'},
           {'pipeline_type': 'C',
            'category': 'F',
            'vep_custom': 'S',
            'source_field_has_custom_prefix': True,
            'variant_grid_column': 'gnomad_af'},
           {'genome_build_id': 'GRCh38',
            'pipeline_type': 'S',
            'category': 'F',
            'vep_custom': 'o',
            'source_field_has_custom_prefix': True,
            'min_columns_version': 3,
            'variant_grid_column': 'gnomad_af'},
           {'genome_build_id': 'GRCh38',
            'pipeline_type': 'S',
            'category': 'F',
            'vep_custom': 'n',
            'source_field_has_custom_prefix': True,
            'max_columns_version': 2,
            'variant_grid_column': 'gnomad_af'},
           {'pipeline_type': 'C',
            'category': 'F',
            'vep_custom': 'S',
            'source_field_has_custom_prefix': True,
            'variant_grid_column': 'gnomad_sv_overlap_af'}],
    'Ensembl_transcriptid': [{'genome_build_id': 'GRCh38',
                              'pipeline_type': 'S',
                              'category': 'P',
                              'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                              'vep_plugin': 'd',
                              'min_columns_version': 2,
                              'variant_grid_column': 'aloft_ensembl_transcript'},
                             {'genome_build_id': 'GRCh37',
                              'pipeline_type': 'S',
                              'category': 'P',
                              'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                              'vep_plugin': 'd',
                              'min_columns_version': 2,
                              'variant_grid_column': 'aloft_ensembl_transcript'}],
    'Aloft_Confidence': [{'genome_build_id': 'GRCh37',
                          'pipeline_type': 'S',
                          'category': 'P',
                          'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                          'vep_plugin': 'd',
                          'min_columns_version': 2,
                          'variant_grid_column': 'aloft_high_confidence'},
                         {'genome_build_id': 'GRCh38',
                          'pipeline_type': 'S',
                          'category': 'P',
                          'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                          'vep_plugin': 'd',
                          'min_columns_version': 2,
                          'variant_grid_column': 'aloft_high_confidence'}],
    'Aloft_pred': [{'genome_build_id': 'GRCh37',
                    'pipeline_type': 'S',
                    'category': 'P',
                    'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                    'vep_plugin': 'd',
                    'min_columns_version': 2,
                    'variant_grid_column': 'aloft_pred'},
                   {'genome_build_id': 'GRCh38',
                    'pipeline_type': 'S',
                    'category': 'P',
                    'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                    'vep_plugin': 'd',
                    'min_columns_version': 2,
                    'variant_grid_column': 'aloft_pred'}],
    'Aloft_prob_Dominant': [{'genome_build_id': 'GRCh37',
                             'pipeline_type': 'S',
                             'category': 'P',
                             'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                             'vep_plugin': 'd',
                             'min_columns_version': 2,
                             'variant_grid_column': 'aloft_prob_dominant'},
                            {'genome_build_id': 'GRCh38',
                             'pipeline_type': 'S',
                             'category': 'P',
                             'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                             'vep_plugin': 'd',
                             'min_columns_version': 2,
                             'variant_grid_column': 'aloft_prob_dominant'}],
    'Aloft_prob_Recessive': [{'genome_build_id': 'GRCh37',
                              'pipeline_type': 'S',
                              'category': 'P',
                              'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                              'vep_plugin': 'd',
                              'min_columns_version': 2,
                              'variant_grid_column': 'aloft_prob_recessive'},
                             {'genome_build_id': 'GRCh38',
                              'pipeline_type': 'S',
                              'category': 'P',
                              'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                              'vep_plugin': 'd',
                              'min_columns_version': 2,
                              'variant_grid_column': 'aloft_prob_recessive'}],
    'Aloft_prob_Tolerant': [{'genome_build_id': 'GRCh37',
                             'pipeline_type': 'S',
                             'category': 'P',
                             'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                             'vep_plugin': 'd',
                             'min_columns_version': 2,
                             'variant_grid_column': 'aloft_prob_tolerant'},
                            {'genome_build_id': 'GRCh38',
                             'pipeline_type': 'S',
                             'category': 'P',
                             'source_field_processing_description': 'Most damaging transcript prediction chosen, and Ensembl transcript stored.',
                             'vep_plugin': 'd',
                             'min_columns_version': 2,
                             'variant_grid_column': 'aloft_prob_tolerant'}],
    'AlphaMissense_rankscore': [{'genome_build_id': 'GRCh37',
                                 'pipeline_type': 'S',
                                 'category': 'P',
                                 'vep_plugin': 'd',
                                 'min_columns_version': 3,
                                 'variant_grid_column': 'alphamissense_rankscore'},
                                {'genome_build_id': 'GRCh38',
                                 'pipeline_type': 'S',
                                 'category': 'P',
                                 'vep_plugin': 'd',
                                 'min_columns_version': 3,
                                 'variant_grid_column': 'alphamissense_rankscore'}],
    'Amino_acids': [{'category': 'G',
                     'variant_grid_column': 'amino_acids'}],
    'BayesDel_noAF_rankscore': [{'genome_build_id': 'GRCh37',
                                 'pipeline_type': 'S',
                                 'category': 'P',
                                 'vep_plugin': 'd',
                                 'min_columns_version': 2,
                                 'variant_grid_column': 'bayesdel_noaf_rankscore'},
                                {'genome_build_id': 'GRCh38',
                                 'pipeline_type': 'S',
                                 'category': 'P',
                                 'vep_plugin': 'd',
                                 'min_columns_version': 2,
                                 'variant_grid_column': 'bayesdel_noaf_rankscore'}],
    'CADD_phred': [{'pipeline_type': 'S',
                    'category': 'P',
                    'vep_plugin': 'd',
                    'max_columns_version': 1,
                    'variant_grid_column': 'cadd_phred'}],
    'CADD_raw_rankscore': [{'genome_build_id': 'GRCh38',
                            'pipeline_type': 'S',
                            'category': 'P',
                            'vep_plugin': 'd',
                            'min_columns_version': 2,
                            'variant_grid_column': 'cadd_raw_rankscore'},
                           {'genome_build_id': 'GRCh37',
                            'pipeline_type': 'S',
                            'category': 'P',
                            'vep_plugin': 'd',
                            'min_columns_version': 2,
                            'variant_grid_column': 'cadd_raw_rankscore'}],
    'CANONICAL': [{'category': 'G',
                   'variant_grid_column': 'canonical'}],
    'ClinPred_rankscore': [{'genome_build_id': 'GRCh38',
                            'pipeline_type': 'S',
                            'category': 'P',
                            'vep_plugin': 'd',
                            'min_columns_version': 2,
                            'variant_grid_column': 'clinpred_rankscore'},
                           {'genome_build_id': 'GRCh37',
                            'pipeline_type': 'S',
                            'category': 'P',
                            'vep_plugin': 'd',
                            'min_columns_version': 2,
                            'variant_grid_column': 'clinpred_rankscore'}],
    'Codons': [{'category': 'G', 'variant_grid_column': 'codons'}],
    'Consequence': [{'category': 'G',
                     'variant_grid_column': 'consequence'}],
    'CNT': [{'pipeline_type': 'S',
             'category': 'F',
             'vep_custom': 'c',
             'source_field_has_custom_prefix': True,
             'variant_grid_column': 'cosmic_count'}],
    'Existing_variation': [{'category': 'E',
                            'source_field_processing_description': 'Extract COSMIC IDs',
                            'variant_grid_column': 'cosmic_id'},
                           {'category': 'E',
                            'source_field_processing_description': 'Extract rsIDs',
                            'variant_grid_column': 'dbsnp_rs_id'}],
    'LEGACY_ID': [{'pipeline_type': 'S',
                   'category': 'E',
                   'vep_custom': 'c',
                   'source_field_has_custom_prefix': True,
                   'variant_grid_column': 'cosmic_legacy_id'}],
    'ada_score': [{'genome_build_id': 'GRCh38',
                   'pipeline_type': 'S',
                   'category': 'S',
                   'vep_plugin': 'v',
                   'variant_grid_column': 'dbscsnv_ada_score'},
                  {'genome_build_id': 'GRCh37',
                   'pipeline_type': 'S',
                   'category': 'S',
                   'vep_plugin': 'v',
                   'variant_grid_column': 'dbscsnv_ada_score'}],
    'rf_score': [{'genome_build_id': 'GRCh37',
                  'pipeline_type': 'S',
                  'category': 'S',
                  'vep_plugin': 'v',
                  'variant_grid_column': 'dbscsnv_rf_score'},
                 {'genome_build_id': 'GRCh38',
                  'pipeline_type': 'S',
                  'category': 'S',
                  'vep_plugin': 'v',
                  'variant_grid_column': 'dbscsnv_rf_score'}],
    'DISTANCE': [{'category': 'N',
                  'variant_grid_column': 'distance'}],
    'DOMAINS': [{'category': 'D', 'variant_grid_column': 'domains'}],
    'ENSP': [{'category': 'E',
              'variant_grid_column': 'ensembl_protein'}],
    'EXON': [{'category': 'G', 'variant_grid_column': 'exon'}],
    'FATHMM_pred': [{'pipeline_type': 'S',
                     'category': 'P',
                     'source_field_processing_description': 'Most damaging',
                     'vep_plugin': 'd',
                     'max_columns_version': 1,
                     'variant_grid_column': 'fathmm_pred_most_damaging'}],
    'FLAGS': [{'category': 'G', 'variant_grid_column': 'flags'}],
    'GERP++_RS': [{'genome_build_id': 'GRCh38',
                   'pipeline_type': 'S',
                   'category': 'C',
                   'vep_plugin': 'd',
                   'variant_grid_column': 'gerp_pp_rs'},
                  {'genome_build_id': 'GRCh37',
                   'pipeline_type': 'S',
                   'category': 'C',
                   'vep_plugin': 'd',
                   'variant_grid_column': 'gerp_pp_rs'}],
    'AC': [{'genome_build_id': 'GRCh38',
            'pipeline_type': 'S',
            'category': 'F',
            'vep_custom': 'n',
            'source_field_has_custom_prefix': True,
            'max_columns_version': 2,
            'variant_grid_column': 'gnomad_ac'},
           {'pipeline_type': 'C',
            'category': 'F',
            'vep_custom': 'S',
            'source_field_has_custom_prefix': True,
            'variant_grid_column': 'gnomad_ac'},
           {'genome_build_id': 'GRCh38',
            'pipeline_type': 'S',
            'category': 'F',
            'vep_custom': 'o',
            'source_field_has_custom_prefix': True,
            'min_columns_version': 3,
            'variant_grid_column': 'gnomad_ac'},
           {'genome_build_id': 'GRCh37',
            'pipeline_type': 'S',
            'category': 'F',
            'source_field_processing_description': 'Sum of exome AC + genome AC',
            'vep_custom': 'g',
            'source_field_has_custom_prefix': True,
            'variant_grid_column': 'gnomad_ac'}],
    'afr_AF': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_afr_af'}],
    'AF-afr': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'n',
                'source_field_has_custom_prefix': True,
                'max_columns_version': 2,
                'variant_grid_column': 'gnomad_afr_af'}],
    'AF_afr': [{'genome_build_id': 'GRCh37',
                'pipeline_type': 'S',
                'category': 'F',
                'source_field_processing_description': '(exome_AC+genome_AC)/(exome_AN+genome_AN)',
                'vep_custom': 'g',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_afr_af'},
               {'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'o',
                'source_field_has_custom_prefix': True,
                'min_columns_version': 3,
                'variant_grid_column': 'gnomad_afr_af'}],
    'AFR_AF': [{'genome_build_id': 'GRCh37',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_afr_af'}],
    'AMR_AF': [{'genome_build_id': 'GRCh37',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_amr_af'}],
    'AF_amr': [{'genome_build_id': 'GRCh37',
                'pipeline_type': 'S',
                'category': 'F',
                'source_field_processing_description': '(exome_AC+genome_AC)/(exome_AN+genome_AN)',
                'vep_custom': 'g',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_amr_af'},
               {'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'o',
                'source_field_has_custom_prefix': True,
                'min_columns_version': 3,
                'variant_grid_column': 'gnomad_amr_af'}],
    'AF-amr': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'n',
                'source_field_has_custom_prefix': True,
                'max_columns_version': 2,
                'variant_grid_column': 'gnomad_amr_af'}],
    'amr_AF': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_amr_af'}],
    'AN': [{'pipeline_type': 'C',
            'category': 'F',
            'vep_custom': 'S',
            'source_field_has_custom_prefix': True,
            'variant_grid_column': 'gnomad_an'},
           {'genome_build_id': 'GRCh38',
            'pipeline_type': 'S',
            'category': 'F',
            'vep_custom': 'o',
            'source_field_has_custom_prefix': True,
            'min_columns_version': 3,
            'variant_grid_column': 'gnomad_an'},
           {'genome_build_id': 'GRCh37',
            'pipeline_type': 'S',
            'category': 'F',
            'source_field_processing_description': 'Sum of exome AN + genome AN',
            'vep_custom': 'g',
            'source_field_has_custom_prefix': True,
            'variant_grid_column': 'gnomad_an'},
           {'genome_build_id': 'GRCh38',
            'pipeline_type': 'S',
            'category': 'F',
            'vep_custom': 'n',
            'source_field_has_custom_prefix': True,
            'max_columns_version': 2,
            'variant_grid_column': 'gnomad_an'}],
    'AF_asj': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'o',
                'source_field_has_custom_prefix': True,
                'min_columns_version': 3,
                'variant_grid_column': 'gnomad_asj_af'},
               {'genome_build_id': 'GRCh37',
                'pipeline_type': 'S',
                'category': 'F',
                'source_field_processing_description': '(exome_AC+genome_AC)/(exome_AN+genome_AN)',
                'vep_custom': 'g',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_asj_af'}],
    'asj_AF': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_asj_af'}],
    'AF-asj': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'n',
                'source_field_has_custom_prefix': True,
                'max_columns_version': 2,
                'variant_grid_column': 'gnomad_asj_af'}],
    'AF-eas': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'n',
                'source_field_has_custom_prefix': True,
                'max_columns_version': 2,
                'variant_grid_column': 'gnomad_eas_af'}],
    'EAS_AF': [{'genome_build_id': 'GRCh37',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_eas_af'}],
    'AF_eas': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'o',
                'source_field_has_custom_prefix': True,
                'min_columns_version': 3,
                'variant_grid_column': 'gnomad_eas_af'},
               {'genome_build_id': 'GRCh37',
                'pipeline_type': 'S',
                'category': 'F',
                'source_field_processing_description': '(exome_AC+genome_AC)/(exome_AN+genome_AN)',
                'vep_custom': 'g',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_eas_af'}],
    'eas_AF': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_eas_af'}],
    'faf95': [{'genome_build_id': 'GRCh38',
               'pipeline_type': 'S',
               'category': 'F',
               'vep_custom': 'o',
               'source_field_has_custom_prefix': True,
               'min_columns_version': 3,
               'variant_grid_column': 'gnomad_faf95'}],
    'faf99': [{'genome_build_id': 'GRCh38',
               'pipeline_type': 'S',
               'category': 'F',
               'vep_custom': 'o',
               'source_field_has_custom_prefix': True,
               'min_columns_version': 3,
               'variant_grid_column': 'gnomad_faf99'}],
    'fafmax_faf95_max': [{'genome_build_id': 'GRCh38',
                          'pipeline_type': 'S',
                          'category': 'F',
                          'vep_custom': 'o',
                          'source_field_has_custom_prefix': True,
                          'min_columns_version': 3,
                          'variant_grid_column': 'gnomad_fafmax_faf95_max'}],
    'fafmax_faf99_max': [{'genome_build_id': 'GRCh38',
                          'pipeline_type': 'S',
                          'category': 'F',
                          'vep_custom': 'o',
                          'source_field_has_custom_prefix': True,
                          'min_columns_version': 3,
                          'variant_grid_column': 'gnomad_fafmax_faf99_max'}],
    'gnomad_filtered': [{'genome_build_id': 'GRCh38',
                         'pipeline_type': 'S',
                         'category': 'F',
                         'vep_custom': 'o',
                         'source_field_has_custom_prefix': True,
                         'min_columns_version': 3,
                         'variant_grid_column': 'gnomad_filtered'},
                        {'genome_build_id': 'GRCh37',
                         'pipeline_type': 'S',
                         'category': 'F',
                         'source_field_processing_description': 'Filtered in either exome or genomes VCF',
                         'vep_custom': 'g',
                         'source_field_has_custom_prefix': True,
                         'variant_grid_column': 'gnomad_filtered'}],
    'FILTER': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'n',
                'source_field_has_custom_prefix': True,
                'max_columns_version': 2,
                'variant_grid_column': 'gnomad_filtered'}],
    'AF_fin': [{'genome_build_id': 'GRCh37',
                'pipeline_type': 'S',
                'category': 'F',
                'source_field_processing_description': '(exome_AC+genome_AC)/(exome_AN+genome_AN)',
                'vep_custom': 'g',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_fin_af'},
               {'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'o',
                'source_field_has_custom_prefix': True,
                'min_columns_version': 3,
                'variant_grid_column': 'gnomad_fin_af'}],
    'AF-fin': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'n',
                'source_field_has_custom_prefix': True,
                'max_columns_version': 2,
                'variant_grid_column': 'gnomad_fin_af'}],
    'fin_AF': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_fin_af'}],
    'N_HOMALT': [{'pipeline_type': 'C',
                  'category': 'F',
                  'vep_custom': 'S',
                  'source_field_has_custom_prefix': True,
                  'variant_grid_column': 'gnomad_hom_alt'}],
    'nhomalt': [{'genome_build_id': 'GRCh37',
                 'pipeline_type': 'S',
                 'category': 'F',
                 'source_field_processing_description': 'exome_nhomalt + genome_nhomalt',
                 'vep_custom': 'g',
                 'source_field_has_custom_prefix': True,
                 'variant_grid_column': 'gnomad_hom_alt'},
                {'genome_build_id': 'GRCh38',
                 'pipeline_type': 'S',
                 'category': 'F',
                 'vep_custom': 'o',
                 'source_field_has_custom_prefix': True,
                 'min_columns_version': 3,
                 'variant_grid_column': 'gnomad_hom_alt'},
                {'genome_build_id': 'GRCh38',
                 'pipeline_type': 'S',
                 'category': 'F',
                 'vep_custom': 'n',
                 'source_field_has_custom_prefix': True,
                 'max_columns_version': 2,
                 'variant_grid_column': 'gnomad_hom_alt'}],
    'mid_AF': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_mid_af'}],
    'AF_mid': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'o',
                'source_field_has_custom_prefix': True,
                'min_columns_version': 3,
                'variant_grid_column': 'gnomad_mid_af'}],
    'AF-nfe': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'n',
                'source_field_has_custom_prefix': True,
                'max_columns_version': 2,
                'variant_grid_column': 'gnomad_nfe_af'}],
    'AF_nfe': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'o',
                'source_field_has_custom_prefix': True,
                'min_columns_version': 3,
                'variant_grid_column': 'gnomad_nfe_af'},
               {'genome_build_id': 'GRCh37',
                'pipeline_type': 'S',
                'category': 'F',
                'source_field_processing_description': '(exome_AC+genome_AC)/(exome_AN+genome_AN)',
                'vep_custom': 'g',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_nfe_af'}],
    'nfe_AF': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_nfe_af'}],
    'EUR_AF': [{'genome_build_id': 'GRCh37',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_nfe_af'}],
    'nonpar': [{'genome_build_id': 'GRCh37',
                'pipeline_type': 'S',
                'category': 'F',
                'source_field_processing_description': 'nonpar from genomes',
                'vep_custom': 'g',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_non_par'}],
    'non_par': [{'genome_build_id': 'GRCh38',
                 'pipeline_type': 'S',
                 'category': 'F',
                 'source_field_processing_description': 'nonpar from genomes',
                 'vep_custom': 'o',
                 'source_field_has_custom_prefix': True,
                 'min_columns_version': 3,
                 'variant_grid_column': 'gnomad_non_par'}],
    'OTH_AF': [{'genome_build_id': 'GRCh37',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_oth_af'}],
    'AF_remaining': [{'genome_build_id': 'GRCh38',
                      'pipeline_type': 'S',
                      'category': 'F',
                      'vep_custom': 'o',
                      'source_field_has_custom_prefix': True,
                      'min_columns_version': 3,
                      'variant_grid_column': 'gnomad_oth_af'}],
    'AF_oth': [{'genome_build_id': 'GRCh37',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'g',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_oth_af'}],
    'oth_AF': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_oth_af'}],
    'AF-oth': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'n',
                'source_field_has_custom_prefix': True,
                'max_columns_version': 2,
                'variant_grid_column': 'gnomad_oth_af'}],
    'grpmax': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'o',
                'source_field_has_custom_prefix': True,
                'min_columns_version': 3,
                'variant_grid_column': 'gnomad_popmax'}],
    'popmax': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'n',
                'source_field_has_custom_prefix': True,
                'max_columns_version': 2,
                'variant_grid_column': 'gnomad_popmax'},
               {'genome_build_id': 'GRCh37',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'g',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_popmax'}],
    'AC_popmax': [{'genome_build_id': 'GRCh37',
                   'pipeline_type': 'S',
                   'category': 'F',
                   'source_field_processing_description': 'Sum of exome AC_popmax + genome AC_popmax',
                   'vep_custom': 'g',
                   'source_field_has_custom_prefix': True,
                   'variant_grid_column': 'gnomad_popmax_ac'},
                  {'genome_build_id': 'GRCh38',
                   'pipeline_type': 'S',
                   'category': 'F',
                   'vep_custom': 'n',
                   'source_field_has_custom_prefix': True,
                   'max_columns_version': 2,
                   'variant_grid_column': 'gnomad_popmax_ac'}],
    'AC_grpmax': [{'genome_build_id': 'GRCh38',
                   'pipeline_type': 'S',
                   'category': 'F',
                   'vep_custom': 'o',
                   'source_field_has_custom_prefix': True,
                   'min_columns_version': 3,
                   'variant_grid_column': 'gnomad_popmax_ac'}],
    'POPMAX_AF': [{'pipeline_type': 'C',
                   'category': 'F',
                   'vep_custom': 'S',
                   'source_field_has_custom_prefix': True,
                   'variant_grid_column': 'gnomad_popmax_af'}],
    'AF_popmax': [{'genome_build_id': 'GRCh37',
                   'pipeline_type': 'S',
                   'category': 'F',
                   'source_field_processing_description': 'Re-calculated from max (exome_AC+genome_AC)/(exome_AN+genome_AN)',
                   'vep_custom': 'g',
                   'source_field_has_custom_prefix': True,
                   'variant_grid_column': 'gnomad_popmax_af'},
                  {'genome_build_id': 'GRCh38',
                   'pipeline_type': 'S',
                   'category': 'F',
                   'vep_custom': 'n',
                   'source_field_has_custom_prefix': True,
                   'max_columns_version': 2,
                   'variant_grid_column': 'gnomad_popmax_af'}],
    'AF_grpmax': [{'genome_build_id': 'GRCh38',
                   'pipeline_type': 'S',
                   'category': 'F',
                   'vep_custom': 'o',
                   'source_field_has_custom_prefix': True,
                   'min_columns_version': 3,
                   'variant_grid_column': 'gnomad_popmax_af'}],
    'AN_popmax': [{'genome_build_id': 'GRCh38',
                   'pipeline_type': 'S',
                   'category': 'F',
                   'vep_custom': 'n',
                   'source_field_has_custom_prefix': True,
                   'max_columns_version': 2,
                   'variant_grid_column': 'gnomad_popmax_an'},
                  {'genome_build_id': 'GRCh37',
                   'pipeline_type': 'S',
                   'category': 'F',
                   'source_field_processing_description': 'Sum of exome AN_popmax + genome AN_popmax',
                   'vep_custom': 'g',
                   'source_field_has_custom_prefix': True,
                   'variant_grid_column': 'gnomad_popmax_an'}],
    'AN_grpmax': [{'genome_build_id': 'GRCh38',
                   'pipeline_type': 'S',
                   'category': 'F',
                   'vep_custom': 'o',
                   'source_field_has_custom_prefix': True,
                   'min_columns_version': 3,
                   'variant_grid_column': 'gnomad_popmax_an'}],
    'nhomalt_popmax': [{'genome_build_id': 'GRCh38',
                        'pipeline_type': 'S',
                        'category': 'F',
                        'vep_custom': 'n',
                        'source_field_has_custom_prefix': True,
                        'max_columns_version': 2,
                        'variant_grid_column': 'gnomad_popmax_hom_alt'}],
    'AF-sas': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'n',
                'source_field_has_custom_prefix': True,
                'max_columns_version': 2,
                'variant_grid_column': 'gnomad_sas_af'}],
    'sas_AF': [{'genome_build_id': 'GRCh38',
                'pipeline_type': 'C',
                'category': 'F',
                'vep_custom': 'S',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_sas_af'}],
    'AF_sas': [{'genome_build_id': 'GRCh37',
                'pipeline_type': 'S',
                'category': 'F',
                'source_field_processing_description': '(exome_AC+genome_AC)/(exome_AN+genome_AN)',
                'vep_custom': 'g',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'gnomad_sas_af'},
               {'genome_build_id': 'GRCh38',
                'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 'o',
                'source_field_has_custom_prefix': True,
                'min_columns_version': 3,
                'variant_grid_column': 'gnomad_sas_af'}],
    '': [{'pipeline_type': 'C',
          'category': 'F',
          'vep_custom': 'S',
          'source_field_has_custom_prefix': True,
          'variant_grid_column': 'gnomad_sv_overlap_coords'},
         {'pipeline_type': 'C',
          'category': 'F',
          'vep_custom': 'S',
          'source_field_has_custom_prefix': True,
          'variant_grid_column': 'gnomad_sv_overlap_percent'}],
    'gnomAD_SV_name': [{'pipeline_type': 'C',
                        'category': 'F',
                        'vep_custom': 'N',
                        'variant_grid_column': 'gnomad_sv_overlap_name'}],
    'AC_male': [{'genome_build_id': 'GRCh37',
                 'pipeline_type': 'S',
                 'category': 'F',
                 'vep_custom': 'g',
                 'source_field_has_custom_prefix': True,
                 'min_columns_version': 3,
                 'variant_grid_column': 'gnomad_xy_ac'}],
    'AC_XY': [{'genome_build_id': 'GRCh38',
               'pipeline_type': 'S',
               'category': 'F',
               'vep_custom': 'o',
               'source_field_has_custom_prefix': True,
               'min_columns_version': 3,
               'variant_grid_column': 'gnomad_xy_ac'}],
    'AF_XY': [{'genome_build_id': 'GRCh38',
               'pipeline_type': 'S',
               'category': 'F',
               'vep_custom': 'o',
               'source_field_has_custom_prefix': True,
               'min_columns_version': 3,
               'variant_grid_column': 'gnomad_xy_af'}],
    'AF_male': [{'genome_build_id': 'GRCh37',
                 'pipeline_type': 'S',
                 'category': 'F',
                 'vep_custom': 'g',
                 'source_field_has_custom_prefix': True,
                 'min_columns_version': 3,
                 'variant_grid_column': 'gnomad_xy_af'}],
    'AN_male': [{'genome_build_id': 'GRCh37',
                 'pipeline_type': 'S',
                 'category': 'F',
                 'vep_custom': 'g',
                 'source_field_has_custom_prefix': True,
                 'min_columns_version': 3,
                 'variant_grid_column': 'gnomad_xy_an'}],
    'AN_XY': [{'genome_build_id': 'GRCh38',
               'pipeline_type': 'S',
               'category': 'F',
               'vep_custom': 'o',
               'source_field_has_custom_prefix': True,
               'min_columns_version': 3,
               'variant_grid_column': 'gnomad_xy_an'}],
    'Grantham': [{'pipeline_type': 'S',
                  'category': 'P',
                  'vep_plugin': 'g',
                  'variant_grid_column': 'grantham'}],
    'HGNC_ID': [{'category': 'E', 'variant_grid_column': 'hgnc_id'}],
    'HGVSc': [{'category': 'H', 'variant_grid_column': 'hgvs_c'}],
    'HGVSp': [{'category': 'H', 'variant_grid_column': 'hgvs_p'}],
    'IMPACT': [{'category': 'P', 'variant_grid_column': 'impact'}],
    'Interpro_domain': [{'genome_build_id': 'GRCh38',
                         'pipeline_type': 'S',
                         'category': 'D',
                         'vep_plugin': 'd',
                         'variant_grid_column': 'interpro_domain'},
                        {'genome_build_id': 'GRCh37',
                         'pipeline_type': 'S',
                         'category': 'D',
                         'vep_plugin': 'd',
                         'variant_grid_column': 'interpro_domain'}],
    'INTRON': [{'category': 'G', 'variant_grid_column': 'intron'}],
    'Mastermind_counts': [{'genome_build_id': 'GRCh38',
                           'pipeline_type': 'S',
                           'category': 'L',
                           'source_field_processing_description': 'MMCNT1',
                           'vep_plugin': 'n',
                           'variant_grid_column': 'mastermind_count_1_cdna'},
                          {'genome_build_id': 'GRCh37',
                           'pipeline_type': 'S',
                           'category': 'L',
                           'source_field_processing_description': 'MMCNT1',
                           'vep_plugin': 'n',
                           'variant_grid_column': 'mastermind_count_1_cdna'},
                          {'genome_build_id': 'GRCh37',
                           'pipeline_type': 'S',
                           'category': 'L',
                           'source_field_processing_description': 'MMCNT2',
                           'vep_plugin': 'n',
                           'variant_grid_column': 'mastermind_count_2_cdna_prot'},
                          {'genome_build_id': 'GRCh38',
                           'pipeline_type': 'S',
                           'category': 'L',
                           'source_field_processing_description': 'MMCNT2',
                           'vep_plugin': 'n',
                           'variant_grid_column': 'mastermind_count_2_cdna_prot'},
                          {'genome_build_id': 'GRCh37',
                           'pipeline_type': 'S',
                           'category': 'L',
                           'source_field_processing_description': 'MMCNT3',
                           'vep_plugin': 'n',
                           'variant_grid_column': 'mastermind_count_3_aa_change'},
                          {'genome_build_id': 'GRCh38',
                           'pipeline_type': 'S',
                           'category': 'L',
                           'source_field_processing_description': 'MMCNT3',
                           'vep_plugin': 'n',
                           'variant_grid_column': 'mastermind_count_3_aa_change'}],
    'Mastermind_MMID3': [{'genome_build_id': 'GRCh38',
                          'pipeline_type': 'S',
                          'category': 'L',
                          'vep_plugin': 'n',
                          'variant_grid_column': 'mastermind_mmid3'},
                         {'genome_build_id': 'GRCh37',
                          'pipeline_type': 'S',
                          'category': 'L',
                          'vep_plugin': 'n',
                          'variant_grid_column': 'mastermind_mmid3'}],
    'MaveDB_score': [{'genome_build_id': 'GRCh38',
                      'pipeline_type': 'S',
                      'category': 'f',
                      'vep_plugin': 'V',
                      'min_columns_version': 3,
                      'variant_grid_column': 'mavedb_score'}],
    'MaveDB_urn': [{'genome_build_id': 'GRCh38',
                    'pipeline_type': 'S',
                    'category': 'f',
                    'vep_plugin': 'V',
                    'min_columns_version': 3,
                    'variant_grid_column': 'mavedb_urn'}],
    'MaxEntScan_alt': [{'pipeline_type': 'S',
                        'category': 'S',
                        'vep_plugin': 'm',
                        'variant_grid_column': 'maxentscan_alt'}],
    'MaxEntScan_diff': [{'pipeline_type': 'S',
                         'category': 'S',
                         'vep_plugin': 'm',
                         'variant_grid_column': 'maxentscan_diff'}],
    'MaxEntScan_ref': [{'pipeline_type': 'S',
                        'category': 'S',
                        'vep_plugin': 'm',
                        'variant_grid_column': 'maxentscan_ref'}],
    'MetaLR_rankscore': [{'genome_build_id': 'GRCh37',
                          'pipeline_type': 'S',
                          'category': 'P',
                          'vep_plugin': 'd',
                          'min_columns_version': 2,
                          'variant_grid_column': 'metalr_rankscore'},
                         {'genome_build_id': 'GRCh38',
                          'pipeline_type': 'S',
                          'category': 'P',
                          'vep_plugin': 'd',
                          'min_columns_version': 2,
                          'variant_grid_column': 'metalr_rankscore'}],
    'MutationAssessor_pred': [{'pipeline_type': 'S',
                               'category': 'P',
                               'source_field_processing_description': 'Most damaging',
                               'vep_plugin': 'd',
                               'max_columns_version': 1,
                               'variant_grid_column': 'mutation_assessor_pred_most_damaging'}],
    'MutationTaster_pred': [{'pipeline_type': 'S',
                             'category': 'P',
                             'source_field_processing_description': 'Most damaging',
                             'vep_plugin': 'd',
                             'max_columns_version': 1,
                             'variant_grid_column': 'mutation_taster_pred_most_damaging'}],
    'NMD': [{'pipeline_type': 'S',
             'category': 'P',
             'vep_plugin': 'N',
             'min_columns_version': 2,
             'variant_grid_column': 'nmd_escaping_variant'}],
    'max': [{'category': 'C',
             'source_field_processing_description': 'max() for indels',
             'vep_custom': '1',
             'source_field_has_custom_prefix': True,
             'min_vep_version': 112,
             'summary_stats': 'max',
             'variant_grid_column': 'phastcons_100_way_vertebrate'},
            {'genome_build_id': 'GRCh38',
             'category': 'C',
             'source_field_processing_description': 'max() for indels',
             'vep_custom': '2',
             'source_field_has_custom_prefix': True,
             'min_vep_version': 112,
             'summary_stats': 'max',
             'variant_grid_column': 'phastcons_30_way_mammalian'},
            {'genome_build_id': 'GRCh37',
             'category': 'C',
             'source_field_processing_description': 'max() for indels',
             'vep_custom': '3',
             'source_field_has_custom_prefix': True,
             'min_vep_version': 112,
             'summary_stats': 'max',
             'variant_grid_column': 'phastcons_46_way_mammalian'},
            {'category': 'C',
             'source_field_processing_description': 'max() for indels',
             'vep_custom': '4',
             'source_field_has_custom_prefix': True,
             'min_vep_version': 112,
             'summary_stats': 'max',
             'variant_grid_column': 'phylop_100_way_vertebrate'},
            {'genome_build_id': 'GRCh38',
             'category': 'C',
             'source_field_processing_description': 'max() for indels',
             'vep_custom': '5',
             'source_field_has_custom_prefix': True,
             'min_vep_version': 112,
             'summary_stats': 'max',
             'variant_grid_column': 'phylop_30_way_mammalian'},
            {'genome_build_id': 'GRCh37',
             'category': 'C',
             'source_field_processing_description': 'max() for indels',
             'vep_custom': '6',
             'source_field_has_custom_prefix': True,
             'min_vep_version': 112,
             'summary_stats': 'max',
             'variant_grid_column': 'phylop_46_way_mammalian'}],
    'phastCons100way_vertebrate': [{'pipeline_type': 'S',
                                    'category': 'C',
                                    'source_field_processing_description': 'max() for indels',
                                    'vep_custom': '1',
                                    'max_vep_version': 111,
                                    'variant_grid_column': 'phastcons_100_way_vertebrate'}],
    'phastCons30way_mammalian': [{'genome_build_id': 'GRCh38',
                                  'pipeline_type': 'S',
                                  'category': 'C',
                                  'source_field_processing_description': 'max() for indels',
                                  'vep_custom': '2',
                                  'max_vep_version': 111,
                                  'variant_grid_column': 'phastcons_30_way_mammalian'}],
    'phastCons46way_mammalian': [{'genome_build_id': 'GRCh37',
                                  'pipeline_type': 'S',
                                  'category': 'C',
                                  'source_field_processing_description': 'max() for indels',
                                  'vep_custom': '3',
                                  'max_vep_version': 111,
                                  'variant_grid_column': 'phastcons_46_way_mammalian'}],
    'phyloP100way_vertebrate': [{'pipeline_type': 'S',
                                 'category': 'C',
                                 'source_field_processing_description': 'max() for indels',
                                 'vep_custom': '4',
                                 'max_vep_version': 111,
                                 'variant_grid_column': 'phylop_100_way_vertebrate'}],
    'phyloP30way_mammalian': [{'genome_build_id': 'GRCh38',
                               'pipeline_type': 'S',
                               'category': 'C',
                               'source_field_processing_description': 'max() for indels',
                               'vep_custom': '5',
                               'max_vep_version': 111,
                               'variant_grid_column': 'phylop_30_way_mammalian'}],
    'phyloP46way_mammalian': [{'genome_build_id': 'GRCh37',
                               'pipeline_type': 'S',
                               'category': 'C',
                               'source_field_processing_description': 'max() for indels',
                               'vep_custom': '6',
                               'max_vep_version': 111,
                               'variant_grid_column': 'phylop_46_way_mammalian'}],
    'Polyphen2_HVAR_pred': [{'pipeline_type': 'S',
                             'category': 'P',
                             'source_field_processing_description': 'Most damaging',
                             'vep_plugin': 'd',
                             'max_columns_version': 1,
                             'variant_grid_column': 'polyphen2_hvar_pred_most_damaging'}],
    'Protein_position': [{'category': 'G',
                          'variant_grid_column': 'protein_position'}],
    'PUBMED': [{'category': 'L', 'variant_grid_column': 'pubmed'}],
    'REPEAT_MASKER': [{'category': 'Q',
                       'vep_custom': 'r',
                       'variant_grid_column': 'repeat_masker'}],
    'REVEL_rankscore': [{'genome_build_id': 'GRCh37',
                         'pipeline_type': 'S',
                         'category': 'P',
                         'vep_plugin': 'd',
                         'min_columns_version': 2,
                         'variant_grid_column': 'revel_rankscore'},
                        {'genome_build_id': 'GRCh38',
                         'pipeline_type': 'S',
                         'category': 'P',
                         'vep_plugin': 'd',
                         'min_columns_version': 2,
                         'variant_grid_column': 'revel_rankscore'}],
    'REVEL_score': [{'pipeline_type': 'S',
                     'category': 'P',
                     'vep_plugin': 'd',
                     'max_columns_version': 1,
                     'variant_grid_column': 'revel_score'}],
    'SIFT': [{'genome_build_id': 'GRCh37',
              'category': 'P',
              'variant_grid_column': 'sift'},
             {'genome_build_id': 'GRCh38',
              'category': 'P',
              'variant_grid_column': 'sift'}],
    'SOMATIC': [{'category': 'E',
                 'source_field_processing_description': 'Any values present',
                 'variant_grid_column': 'somatic'}],
    'SpliceAI_pred_SYMBOL': [{'genome_build_id': 'GRCh37',
                              'pipeline_type': 'S',
                              'category': 'S',
                              'vep_plugin': 'a',
                              'variant_grid_column': 'spliceai_gene_symbol'},
                             {'genome_build_id': 'GRCh38',
                              'pipeline_type': 'S',
                              'category': 'S',
                              'vep_plugin': 'a',
                              'variant_grid_column': 'spliceai_gene_symbol'}],
    'SpliceAI_pred_DP_AG': [{'genome_build_id': 'GRCh37',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_dp_ag'},
                            {'genome_build_id': 'GRCh38',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_dp_ag'}],
    'SpliceAI_pred_DP_AL': [{'genome_build_id': 'GRCh37',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_dp_al'},
                            {'genome_build_id': 'GRCh38',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_dp_al'}],
    'SpliceAI_pred_DP_DG': [{'genome_build_id': 'GRCh38',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_dp_dg'},
                            {'genome_build_id': 'GRCh37',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_dp_dg'}],
    'SpliceAI_pred_DP_DL': [{'genome_build_id': 'GRCh38',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_dp_dl'},
                            {'genome_build_id': 'GRCh37',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_dp_dl'}],
    'SpliceAI_pred_DS_AG': [{'genome_build_id': 'GRCh38',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_ds_ag'},
                            {'genome_build_id': 'GRCh37',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_ds_ag'}],
    'SpliceAI_pred_DS_AL': [{'genome_build_id': 'GRCh38',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_ds_al'},
                            {'genome_build_id': 'GRCh37',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_ds_al'}],
    'SpliceAI_pred_DS_DG': [{'genome_build_id': 'GRCh37',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_ds_dg'},
                            {'genome_build_id': 'GRCh38',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_ds_dg'}],
    'SpliceAI_pred_DS_DL': [{'genome_build_id': 'GRCh38',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_ds_dl'},
                            {'genome_build_id': 'GRCh37',
                             'pipeline_type': 'S',
                             'category': 'S',
                             'vep_plugin': 'a',
                             'variant_grid_column': 'spliceai_pred_ds_dl'}],
    'SpliceRegion': [{'pipeline_type': 'S',
                      'category': 'S',
                      'vep_plugin': 's',
                      'variant_grid_column': 'splice_region'}],
    'SYMBOL': [{'category': 'G', 'variant_grid_column': 'symbol'}],
    'TOPMED': [{'pipeline_type': 'S',
                'category': 'F',
                'vep_custom': 't',
                'source_field_has_custom_prefix': True,
                'variant_grid_column': 'topmed_af'}],
    'VARIANT_CLASS': [{'category': 'G',
                       'variant_grid_column': 'variant_class'}],
    'VEST4_rankscore': [{'genome_build_id': 'GRCh37',
                         'pipeline_type': 'S',
                         'category': 'P',
                         'vep_plugin': 'd',
                         'min_columns_version': 2,
                         'variant_grid_column': 'vest4_rankscore'},
                        {'genome_build_id': 'GRCh38',
                         'pipeline_type': 'S',
                         'category': 'P',
                         'vep_plugin': 'd',
                         'min_columns_version': 2,
                         'variant_grid_column': 'vest4_rankscore'}]
}
