# Generated by Django 6.0.6 on 2026-07-22 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0166_reminder_legacy_somatic_forwardport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MMEInboundQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_json', models.JSONField()),
                ('num_results', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MMESubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64)),
                ('external_patient_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('S', 'Submitted'), ('E', 'Error')], default='D', max_length=1)),
                ('request_json', models.JSONField(null=True)),
                ('response_json', models.JSONField(null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted', models.DateTimeField(blank=True, null=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.classification')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('classification', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='MMEMatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('matched_patient_id', models.CharField(max_length=255)),
                ('contact_name', models.TextField(null=True)),
                ('contact_href', models.TextField(null=True)),
                ('patient_json', models.JSONField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mme.mmesubmission')),
            ],
        ),
    ]
